src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Customer_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Customer Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_Xero_Accounting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Xero Accounting</label>
        <type>Checkbox</type>
    </fields>    
    <label>General Configurations</label>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountingCustomerBatchSchedulerTest.cls
/**
 * Author: Nikhil Kumar Srivastava
 * Since: April 16, 2019
 * Name: AccountingCustomerBatchSchedulerTest
 * Description: test Class for AccountingCustomerBatchScheduler.
**/

@isTest
public without sharing class AccountingCustomerBatchSchedulerTest {
    
    @testSetup
    private static void setupTestData() { 
        TestDataFactory.disableFLSChecks();
        TestUtil.createIFWConfigForXero();
        insert new General_Configurations__c(Enable_Xero_Accounting__c = true);
        List<IFW_IntegrationConfig__c> IFWConfigObj = [Select Id from IFW_IntegrationConfig__c];
        IFW_IntegrationConfigItem__c IFWConfigItemObj = TestUtil.createIFWConfigItemForXero('Contacts', IFWConfigObj[0].Id);
        //Disable Trigger to stop syncing the record
        Trigger_Soft_Disable__c triggerToDisable = new Trigger_Soft_Disable__c();
        triggerToDisable.Name = 'CustomerTrigger';
        triggerToDisable.Disable_Delete__c = triggerToDisable.Disable_Insert__c = triggerToDisable.Disable_Undelete__c = true;
        triggerToDisable.Disable_Update__c = true;
        insert triggerToDisable;
        Account testCustomer = TestUtil.createCustomer(false, 'customerName', 'abc@abc.com', 'Agra', '1111111112', null, null, false, true,'Individual','firstname1', 'lastname', '9999999999', 'BillingStreet'); 
        testCustomer.Available_For_Xero_Customer_Sync__c = true;
        insert testCustomer;
        delete triggerToDisable;
        system.assertEquals(true, String.isNotBlank(testCustomer.Id));
    }
    
    
    static testmethod void AccountingCustomerBatchSchedulerTest() { 
        List<Account> accList = [Select Id,Is_Customer__c from Account where Is_Customer__c = true Limit 1];
        system.assertEquals(1,accList.size());
        system.assertEquals(true,accList[0].Is_Customer__c);
        Test.setMock(HttpCalloutMock.class, new Xero_MockHttpResponseGenerator());
        Test.startTest();
        XeroScriptUtil.syncCustomers(25,120,25);
        Test.stopTest();
     } 
}