src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Type</label>
        <referenceTo>Account_Type__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Average_Spend_per_Order__c</fullName>
        <label>Average Spend per Order</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <label>Customer Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drivers_License__c</fullName>
        <label>Drivers License#</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Home_number__c</fullName>
        <formula>IF(Home_Number__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Home_Number__c) , 
8 , MID(Home_Number__c, 0, 4) + &quot; &quot; +MID(Home_Number__c, 5, 4) , 
10 , IF(BEGINS(Home_Number__c, &apos;04&apos;) || BEGINS(Home_Number__c, &apos;05&apos;) , 
MID(Home_Number__c, 0, 4) + &quot; &quot; +MID(Home_Number__c, 5, 3)+ &quot; &quot; +MID(Home_Number__c, 8, 3), 
MID(Home_Number__c, 0, 2) + &quot; &quot; +MID(Home_Number__c, 3, 4)+ &quot; &quot; +MID(Home_Number__c, 7, 4)) 
, Home_Number__c ), 


CASE( LEN(Home_Number__c) , 10, &quot;(&quot; + MID(Home_Number__c, 0, 3) + &quot;) &quot; +MID(Home_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Home_Number__c, 7, 4) , Home_Number__c)) 
, 
CASE( LEN(Home_Number__c) , 8 , MID(Home_Number__c, 0, 4) + &quot; &quot; +MID(Home_Number__c, 4, 4) , 
10, &quot;(&quot; + MID(Home_Number__c, 0, 3) + &quot;) &quot; +MID(Home_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Home_Number__c, 7, 4) , Home_Number__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Home number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Mobile_Number__c</fullName>
        <formula>IF(Mobile__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Mobile__c) , 
8 , MID(Mobile__c, 0, 4) + &quot; &quot; +MID(Mobile__c, 5, 4) , 
10 , IF(BEGINS(Mobile__c, &apos;04&apos;) || BEGINS(Mobile__c, &apos;05&apos;) , 
MID(Mobile__c, 0, 4) + &quot; &quot; +MID(Mobile__c, 5, 3)+ &quot; &quot; +MID(Mobile__c, 8, 3), 
MID(Mobile__c, 0, 2) + &quot; &quot; +MID(Mobile__c, 3, 4)+ &quot; &quot; +MID(Mobile__c, 7, 4)) 
, Mobile__c ), 


CASE( LEN(Mobile__c) , 10, &quot;(&quot; + MID(Mobile__c, 0, 3) + &quot;) &quot; +MID(Mobile__c, 4, 3) 
+ &quot;-&quot; +MID(Mobile__c, 7, 4) , Mobile__c)) 
, 
CASE( LEN(Mobile__c) , 8 , MID(Mobile__c, 0, 4) + &quot; &quot; +MID(Mobile__c, 4, 4) , 
10, &quot;(&quot; + MID(Mobile__c, 0, 3) + &quot;) &quot; +MID(Mobile__c, 4, 3) 
+ &quot;-&quot; +MID(Mobile__c, 7, 4) , Mobile__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Work_Number__c</fullName>
        <formula>IF(Work_Number__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Work_Number__c) , 
8 , MID(Work_Number__c, 0, 4) + &quot; &quot; +MID(Work_Number__c, 5, 4) , 
10 , IF(BEGINS(Work_Number__c, &apos;04&apos;) || BEGINS(Work_Number__c, &apos;05&apos;) , 
MID(Work_Number__c, 0, 4) + &quot; &quot; +MID(Work_Number__c, 5, 3)+ &quot; &quot; +MID(Work_Number__c, 8, 3), 
MID(Work_Number__c, 0, 2) + &quot; &quot; +MID(Work_Number__c, 3, 4)+ &quot; &quot; +MID(Work_Number__c, 7, 4)) 
, Work_Number__c ), 


CASE( LEN(Work_Number__c) , 10, &quot;(&quot; + MID(Work_Number__c, 0, 3) + &quot;) &quot; +MID(Work_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Work_Number__c, 7, 4) , Work_Number__c)) 
, 
CASE( LEN(Work_Number__c) , 8 , MID(Work_Number__c, 0, 4) + &quot; &quot; +MID(Work_Number__c, 4, 4) , 
10, &quot;(&quot; + MID(Work_Number__c, 0, 3) + &quot;) &quot; +MID(Work_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Work_Number__c, 7, 4) , Work_Number__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Work Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Number_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Number SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Number__c</fullName>
        <label>Home Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedIn__c</fullName>
        <label>LinkedIn</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mobile_Number_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Number SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Other Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <description>Nick Name of Customer</description>
        <label>Nickname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General customer notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Open_Orders__c</fullName>
        <label>Open Orders</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Orders_Lifetime__c</fullName>
        <label>Orders Lifetime</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Email__c</fullName>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Email__c</fullName>
        <label>Preferred Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Phone__c</fullName>
        <label>Preferred Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Preferred_SMS__c</fullName>
        <label>Preferred SMS</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Price_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Level</label>
        <referenceTo>Price_Level__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts (Purchase Tax)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SA_same_as_BA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shipping Address same as Billing Address</description>
        <label>SA same as BA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shopify_ID__c</fullName>
        <description>This field is used to store the Shopify ID of the customer.</description>
        <label>Shopify ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shopify_URL__c</fullName>
        <formula>$Setup.Shopify_Configuration__c.Customer_Base_URL__c + Shopify_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shopify URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Store_Credit__c</fullName>
        <label>Total Store Credit</label>
        <summarizedField>Store_Credit__c.Amount__c</summarizedField>
        <summaryForeignKey>Store_Credit__c.Customer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Twitter__c</fullName>
        <label>Twitter</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Email__c</fullName>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Work_Number_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Number SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Number__c</fullName>
        <label>Work Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Type__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Level__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Price Level</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Customer.cls
/**
 * Author: Tarun Khandelwal
 * Since: May 15, 2015
 * Name: Customer
 * Description: Apex class to handle JSON related oprations of Customer object.
**/
public without sharing class Customer {
    
    // Customer Name
    public String BusinessName {get; set;}
    
    // Customer First Name
    public String FirstName {get; set;}
    
    // Customer Last Name
    public String LastName {get; set;} 
    
    // Active Customer
    public Boolean Active {get; set;}
    
    // Birth Date
    public Date Birthdate {get; set;}
    
    // Birth Month
    public Integer BirthMonth {get; set;}
    
    // Birth Date
    public Integer BirthDay {get; set;}
    
    // Birth Year
    public Integer BirthYear {get; set;}
    
    // Company Name
    public String Company {get; set;}
    
    // FaceBook Link
    public String FacebookLink {get; set;}
    
    // Twitter Link 
    public String TwitterLink {get; set;}
    
    // Linkedin Link
    public String LinkedInLink {get; set;}
    
    // Home Eamil Address
    public String HomeEmail {get; set;}
    
    // Work Email Address
    public String WorkEmail {get; set;}
    
    // Other Email Address
    public String OtherEmail {get; set;}
    
    // Home Number
    public String HomeNumber {get; set;}
    // Home Number
    public String FormattedHomeNumber {get; set;}
    
    // Mobile Number
    public String OtherPhone {get; set;}
    
    // Work Number
    public String WorkNumber {get; set;}
    
    // Mobile Number
    public String FormattedOtherPhone {get; set;}
    
    // Work Number
    public String FormattedWorkNumber {get; set;}
    
    // Is Home Number is treated as SMS ?
    public Boolean HomeNumberSMS {get; set;}
    
    // Is Mobile Number is treated as SMS ?
    public Boolean MobileNumberSMS {get; set;}
    
    // Is Work Number is treated as SMS ?
    public Boolean WorkNumberSMS {get; set;}
    
    // Is Customer
    public Boolean IsCustomer {get; set;}
    
    // Is vendor
    public Boolean IsVendor {get; set;}
    
    // Job Title
    public String JobTitle {get; set;}
    
    // Nick Name
    public String Nickname {get; set;}
    
    // Preferred Email
    public String PreferredEmail {get; set;}
    
    // Preferred Phone
    public String PreferredPhone {get; set;}
    
    // Preferred SMS
    public String PreferredSMS {get; set;}
    
    // Preferred Phone
    public String FormattedPreferredPhone {get; set;}
    
    // Preferred SMS
    public String FormattedPreferredSMS {get; set;}
    
    // Is Both Address Same - Shipping Address and Billing Address?
    public Boolean IsBothAddressSame {get; set;}
    
    // Type__c
    public String Type {get; set;}
    
    public String TaxExemptions {get; set;}
    
    // Billing Address Fields
    public String BillingStreet1 {get; set;}
    public String BillingStreet2 {get; set;}
    public String BillingCity {get; set;}
    public String BillingState {get; set;}
    public String BillingCountry {get; set;}
    public String BillingPostalCode {get; set;}
    
    // Shipping Address Fields
    public String ShippingStreet1 {get; set;}
    public String ShippingStreet2 {get; set;}
    public String ShippingCity {get; set;}
    public String ShippingState {get; set;}
    public String ShippingCountry {get; set;}
    public String ShippingPostalCode {get; set;}
    
    // Id
    public String Id {get; set;}
    
    // Price Level ID
    public String PriceLevelId {get; set;}
    
    // Price Leel Name
    public String PriceLevelName {get; set;}
    
    // SalesTax ID
    public String SalesTaxId {get; set;}
    
    // Price Leel Name
    public String SalesTaxName {get; set;}
    
    // SalesTax ID
    public String PurchaseTaxId {get; set;}
    
    // Price Leel Name
    public String PurchaseTaxName {get; set;}
    
    // Customer Number
    public String CustomerNumber {get; set;}
    
    public Decimal TotalStoreCredit;
    
    //Account type
    public String AccountTypeName;
    public String AccountTypeId;
    
    public String Notes;
    public String DriversLicense;
    public String ShopifyId;
    public String ShopifyUrl;
    // Constructor
    public Customer(Account customerRec) { 
        populateCustomerRec(customerRec);
    }
    
    public Customer(Account customerRec,String taxExmptionList) { 
        populateCustomerRec(customerRec);
        this.TaxExemptions = taxExmptionList;
    }
    
    public Customer(String Id, String customerName) {
    	this.Id = Id;
    	this.BusinessName = customerName;
    }
    
    private void populateCustomerRec(Account customerRec) {
    	this.BusinessName = customerRec.Name;
        this.FirstName = customerRec.FirstName__c;
        this.LastName = customerRec.LastName__c;
        
        this.HomeEmail = (customerRec.Email__c == null) ? '' : customerRec.Email__c;
        this.HomeNumber = (customerRec.Home_Number__c == null ) ? '' : customerRec.Home_Number__c;
        this.FormattedHomeNumber = (customerRec.Formatted_Home_number__c == null ) ? '' : customerRec.Formatted_Home_number__c;
        this.AccountTypeName = customerRec.Account_type__r.Name;
        this.AccountTypeId = customerRec.Account_type__r.Id;
        // Address fields
        String billingStreet = (customerRec.BillingStreet == null ) ? '' : customerRec.BillingStreet;
        List<String> bsList = billingStreet.split('\n');
        this.BillingStreet1 = (bsList.size() > 0) ? bsList[0] : '';
        this.BillingStreet2 = (bsList.size() > 1) ? bsList[1] : '';
        this.BillingCity = (customerRec.BillingCity == null) ? '' : customerRec.BillingCity;
        this.BillingState = (customerRec.BillingState == null) ? '' : customerRec.BillingState;
        this.BillingCountry = (customerRec.BillingCountry == null) ? '' : customerRec.BillingCountry;
        this.BillingPostalCode = (customerRec.BillingPostalCode == null) ? '' : customerRec.BillingPostalCode;
        
        String shippingStreet = (customerRec.ShippingStreet == null ) ? '' : customerRec.ShippingStreet;
        List<String> ssList = shippingStreet.split('\n');
        this.ShippingStreet1 = (ssList.size() > 0) ? ssList[0] : '';
        this.ShippingStreet2 = (ssList.size() > 1) ? ssList[1] : '';
        this.ShippingCity = (customerRec.ShippingCity == null) ? '' : customerRec.ShippingCity;
        this.ShippingState = (customerRec.ShippingState == null) ? '' : customerRec.ShippingState;
        this.ShippingCountry = (customerRec.ShippingCountry == null) ? '' : customerRec.ShippingCountry;
        this.ShippingPostalCode = (customerRec.ShippingPostalCode == null) ? '' : customerRec.ShippingPostalCode;
        this.IsBothAddressSame = customerRec.SA_same_as_BA__c;
        
        // Addtional Fields
        this.Birthdate = customerRec.Birth_Date__c;
        if(customerRec.Birth_Date__c != null) {
            this.BirthDay = customerRec.Birth_Date__c.day();
            this.BirthMonth = customerRec.Birth_Date__c.month();
            this.BirthYear = customerRec.Birth_Date__c.year();
        }
         
        this.Active = customerRec.Active__c;
        this.Company = (customerRec.Company_Name__c == null) ? '' : customerRec.Company_Name__c;
        this.JobTitle = (customerRec.Job_Title__c == null) ? '' : customerRec.Job_Title__c;
        
        // Phone And Email
        this.WorkEmail = (customerRec.Work_Email__c == null) ? '' : customerRec.Work_Email__c;
        this.OtherEmail = (customerRec.Other_Email__c == null) ? '' : customerRec.Other_Email__c;
        this.OtherPhone = (customerRec.Mobile__c == null) ? '' : customerRec.Mobile__c;
        this.FormattedOtherPhone = (customerRec.Formatted_Mobile_Number__c == null) ? '' : customerRec.Formatted_Mobile_Number__c;
        this.WorkNumber = (customerRec.Work_Number__c == null) ? '' : customerRec.Work_Number__c;
        this.FormattedWorkNumber = (customerRec.Formatted_Work_Number__c == null) ? '' : customerRec.Formatted_Work_Number__c;
        this.HomeNumberSMS = customerRec.Home_Number_SMS__c;
        this.MobileNumberSMS = customerRec.Mobile_Number_SMS__c;
        this.WorkNumberSMS = customerRec.Work_Number_SMS__c;
        
        if(customerRec.Preferred_Email__c != null) {
            if(customerRec.Preferred_Email__c == customerRec.Email__c) {
                this.PreferredEmail = 'HomeEmail';
            } else if(customerRec.Preferred_Email__c == customerRec.Work_Email__c) {
                this.PreferredEmail = 'WorkEmail';
            } else if(customerRec.Preferred_Email__c == customerRec.Other_Email__c) {
                this.PreferredEmail = 'OtherEmail';
            }
        } else {
            this.PreferredEmail = '';
        }
        
        if(customerRec.Preferred_Phone__c != null) {
            if(customerRec.Preferred_Phone__c == customerRec.Home_Number__c) {
                this.PreferredPhone = 'HomeNumber';
                this.FormattedPreferredPhone = 'FormattedHomeNumber';
            } else if(customerRec.Preferred_Phone__c == customerRec.Mobile__c) {
                this.PreferredPhone = 'OtherPhone';
                this.FormattedPreferredPhone = 'FormattedOtherPhone';
            } else if(customerRec.Preferred_Phone__c == customerRec.Work_Number__c) {
                this.PreferredPhone = 'WorkNumber';
                this.FormattedPreferredPhone = 'FormattedWorkNumber';
            }
        } else {
            this.PreferredPhone = '';
            this.FormattedPreferredPhone = '';
        }
        
        if(customerRec.Preferred_SMS__c != null) {
            if(customerRec.Preferred_SMS__c == customerRec.Home_Number__c) {
                this.PreferredSMS = 'HomeNumber';
                this.FormattedPreferredSMS = 'FormattedHomeNumber';
            } else if(customerRec.Preferred_SMS__c == customerRec.Mobile__c) {
                this.PreferredSMS = 'OtherPhone';
                this.FormattedPreferredSMS = 'FormattedOtherPhone';
            } else if(customerRec.Preferred_SMS__c == customerRec.Work_Number__c) {
                this.PreferredSMS = 'WorkNumber';
                this.FormattedPreferredSMS = 'FormattedOtherPhone';
            }
        } else {
            this.PreferredSMS = '';
            this.FormattedPreferredSMS = '';
        }
        
        this.IsCustomer = customerRec.Is_Customer__c;
        this.IsVendor = customerRec.Is_Vendor__c;
        this.Nickname = (customerRec.Nickname__c == null) ? '' : customerRec.Nickname__c;
        this.Type = customerRec.Type__c;
        this.FacebookLink = (customerRec.Facebook__c == null) ? '' : customerRec.Facebook__c;
        this.TwitterLink = (customerRec.Twitter__c == null) ? '' : customerRec.Twitter__c;
        this.LinkedInLink = (customerRec.LinkedIn__c == null) ? '' : customerRec.LinkedIn__c;
        
        this.Id = (customerRec.Id == null) ? '' : customerRec.Id; 
        
        this.PriceLevelId = customerRec.Price_Level__c;
        this.PriceLevelName = (customerRec.Price_Level__c == null) ? '' : customerRec.Price_Level__r.Name__c;
        this.SalesTaxId = customerRec.Sales_Tax__c;
        this.SalesTaxName = (customerRec.Sales_Tax__c == null) ? '' : customerRec.Sales_Tax__r.Name__c;
        this.PurchaseTaxId = customerRec.Purchase_Tax__c;
        this.PurchaseTaxName = (customerRec.Purchase_Tax__c == null) ? '' : customerRec.Purchase_Tax__r.Name__c;
        this.CustomerNumber = customerRec.Customer_Number__c;
        this.TotalStoreCredit = customerRec.Total_Store_Credit__c;
        this.Notes = customerRec.Notes__c;
        this.DriversLicense = customerRec.Drivers_License__c;
        if(GeneralConfiguration.isShopifyIntegrationEnabled() && String.isNotBlank(customerRec.Shopify_ID__c)) {
            this.ShopifyId = customerRec.Shopify_ID__c;
            this.ShopifyUrl = customerRec.Shopify_URL__c;
        }
    }
    /**
     * Name: parse
     * Desc: Method to Parse JSON String to class instance
     * @param:  (1) JSONString - String - JSON String 
     * @return: COLineItem - Class Object
    **/
    public static Customer parse(String json) {
        return (Customer) System.JSON.deserialize(json, Customer.class);
    }
    
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> customerFields = new List<String>{ 'Id',
                                                        'Name',
                                                        'FirstName__c',
                                                        'LastName__c',
                                                        'Active__c',
                                                        'Birth_Date__c',
                                                        'Company_Name__c',
                                                        'Facebook__c',
                                                        'Email__c',
                                                        'Home_Number__c',
                                                        'Home_Number_SMS__c',
                                                        'Is_Customer__c',
                                                        'Is_Vendor__c',
                                                        'Job_Title__c',
                                                        'LinkedIn__c',
                                                        'Mobile__c',
                                                        'Mobile_Number_SMS__c', 
                                                        'Nickname__c',
                                                        'Other_Email__c',
                                                        'Preferred_Email__c',
                                                        'Preferred_Phone__c',
                                                        'Preferred_SMS__c',
                                                        'Twitter__c',
                                                        'Type__c',
                                                        'Work_Email__c',
                                                        'Work_Number__c',
                                                        'Work_Number_SMS__c',
                                                        'SA_same_as_BA__c',
                                                        'BillingStreet',
                                                        'BillingCity',
                                                        'BillingState',
                                                        'BillingCountry',
                                                        'BillingPostalCode',
                                                        'ShippingStreet',
                                                        'ShippingCity',
                                                        'ShippingState',
                                                        'ShippingCountry',
                                                        'ShippingPostalCode',
                                                        'LastModifiedDate',
                                                        'Sales_Tax__c',
                                                        'Sales_Tax__r.Name__c',
                                                        'Price_Level__c',
                                                        'Price_Level__r.Name__c',
                                                        'Purchase_Tax__c',
                                                        'Purchase_Tax__r.Name__c',
                                                        'Orders_Lifetime__c',
                                                        'Open_Orders__c',
                                                        'Average_Spend_per_Order__c',
                                                        'Customer_Number__c',
                                                        'Formatted_Home_number__c',
                                                        'Formatted_Work_Number__c',
                                                        'Formatted_Mobile_Number__c',
                                                        'Total_Store_Credit__c',
                                                        'Account_type__r.Id',
                                                        'Account_type__r.Name',
                                                        'Notes__c',
                                                        'Drivers_License__c',
                                                        'Shopify_ID__c',
                                                        'Shopify_URL__c'
                                                };
        return customerFields;
    }
    
}