src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Formatted_Home_number__c</fullName>
        <formula>IF(Home_Number__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Home_Number__c) , 
8 , MID(Home_Number__c, 0, 4) + &quot; &quot; +MID(Home_Number__c, 5, 4) , 
10 , IF(BEGINS(Home_Number__c, &apos;04&apos;) || BEGINS(Home_Number__c, &apos;05&apos;) , 
MID(Home_Number__c, 0, 4) + &quot; &quot; +MID(Home_Number__c, 5, 3)+ &quot; &quot; +MID(Home_Number__c, 8, 3), 
MID(Home_Number__c, 0, 2) + &quot; &quot; +MID(Home_Number__c, 3, 4)+ &quot; &quot; +MID(Home_Number__c, 7, 4)) 
, Home_Number__c ), 


CASE( LEN(Home_Number__c) , 10, &quot;(&quot; + MID(Home_Number__c, 0, 3) + &quot;) &quot; +MID(Home_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Home_Number__c, 7, 4) , Home_Number__c)) 
, 
CASE( LEN(Home_Number__c) , 8 , MID(Home_Number__c, 0, 4) + &quot; &quot; +MID(Home_Number__c, 4, 4) , 
10, &quot;(&quot; + MID(Home_Number__c, 0, 3) + &quot;) &quot; +MID(Home_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Home_Number__c, 7, 4) , Home_Number__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Home number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Mobile_Number__c</fullName>
        <formula>IF(Mobile__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Mobile__c) , 
8 , MID(Mobile__c, 0, 4) + &quot; &quot; +MID(Mobile__c, 5, 4) , 
10 , IF(BEGINS(Mobile__c, &apos;04&apos;) || BEGINS(Mobile__c, &apos;05&apos;) , 
MID(Mobile__c, 0, 4) + &quot; &quot; +MID(Mobile__c, 5, 3)+ &quot; &quot; +MID(Mobile__c, 8, 3), 
MID(Mobile__c, 0, 2) + &quot; &quot; +MID(Mobile__c, 3, 4)+ &quot; &quot; +MID(Mobile__c, 7, 4)) 
, Mobile__c ), 


CASE( LEN(Mobile__c) , 10, &quot;(&quot; + MID(Mobile__c, 0, 3) + &quot;) &quot; +MID(Mobile__c, 4, 3) 
+ &quot;-&quot; +MID(Mobile__c, 7, 4) , Mobile__c)) 
, 
CASE( LEN(Mobile__c) , 8 , MID(Mobile__c, 0, 4) + &quot; &quot; +MID(Mobile__c, 4, 4) , 
10, &quot;(&quot; + MID(Mobile__c, 0, 3) + &quot;) &quot; +MID(Mobile__c, 4, 3) 
+ &quot;-&quot; +MID(Mobile__c, 7, 4) , Mobile__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Preferred_Phone__c</fullName>
        <formula>IF(Preferred_Phone__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Preferred_Phone__c) , 
8 , MID(Preferred_Phone__c, 0, 4) + &quot; &quot; +MID(Preferred_Phone__c, 5, 4) , 
10 , IF(BEGINS(Preferred_Phone__c, &apos;04&apos;) || BEGINS(Preferred_Phone__c, &apos;05&apos;) , 
MID(Preferred_Phone__c, 0, 4) + &quot; &quot; +MID(Preferred_Phone__c, 5, 3)+ &quot; &quot; +MID(Preferred_Phone__c, 8, 3), 
MID(Preferred_Phone__c, 0, 2) + &quot; &quot; +MID(Preferred_Phone__c, 3, 4)+ &quot; &quot; +MID(Preferred_Phone__c, 7, 4)) 
, Preferred_Phone__c ), 


CASE( LEN(Preferred_Phone__c) , 10, &quot;(&quot; + MID(Preferred_Phone__c, 0, 3) + &quot;) &quot; +MID(Preferred_Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Preferred_Phone__c, 7, 4) , Preferred_Phone__c)) 
, 
CASE( LEN(Preferred_Phone__c) , 8 , MID(Preferred_Phone__c, 0, 4) + &quot; &quot; +MID(Preferred_Phone__c, 4, 4) , 
10, &quot;(&quot; + MID(Preferred_Phone__c, 0, 3) + &quot;) &quot; +MID(Preferred_Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Preferred_Phone__c, 7, 4) , Preferred_Phone__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Preferred Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Work_Number__c</fullName>
        <formula>IF(Work_Number__c != null, 
IF( BillingCountry != null , 
IF(BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Work_Number__c) , 
8 , MID(Work_Number__c, 0, 4) + &quot; &quot; +MID(Work_Number__c, 5, 4) , 
10 , IF(BEGINS(Work_Number__c, &apos;04&apos;) || BEGINS(Work_Number__c, &apos;05&apos;) , 
MID(Work_Number__c, 0, 4) + &quot; &quot; +MID(Work_Number__c, 5, 3)+ &quot; &quot; +MID(Work_Number__c, 8, 3), 
MID(Work_Number__c, 0, 2) + &quot; &quot; +MID(Work_Number__c, 3, 4)+ &quot; &quot; +MID(Work_Number__c, 7, 4)) 
, Work_Number__c ), 


CASE( LEN(Work_Number__c) , 10, &quot;(&quot; + MID(Work_Number__c, 0, 3) + &quot;) &quot; +MID(Work_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Work_Number__c, 7, 4) , Work_Number__c)) 
, 
CASE( LEN(Work_Number__c) , 8 , MID(Work_Number__c, 0, 4) + &quot; &quot; +MID(Work_Number__c, 4, 4) , 
10, &quot;(&quot; + MID(Work_Number__c, 0, 3) + &quot;) &quot; +MID(Work_Number__c, 4, 3) 
+ &quot;-&quot; +MID(Work_Number__c, 7, 4) , Work_Number__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Work Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Number__c</fullName>
        <label>Home Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Other Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Other_Email__c</fullName>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Email__c</fullName>
        <label>Preferred Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Phone__c</fullName>
        <label>Preferred Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Email__c</fullName>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Work_Number__c</fullName>
        <label>Work Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Colour__c</fullName>
        <description>Exterior Colour of unit</description>
        <label>Exterior Colour</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORDU_Stock_Id__c</fullName>
        <label>ORDU Stock Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Id__c</fullName>
        <description>This will contain the stock id</description>
        <label>Stock Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Model</label>
        <referenceTo>Unit_Sub_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Id__c</fullName>
        <description>This will be used for Generating unit Id</description>
        <label>Unit Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Make of unit</description>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Types of units</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COU</fullName>
                </value>
                <value>
                    <fullName>STOCK</fullName>
                </value>
                <value>
                    <fullName>ORDU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Model year of the unit</description>
        <label>Unit Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Model</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <label>Sub-Model</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>unit model description</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit lookup with Customer Owned Unit</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Customer_Owned_Unit__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Model_Name__c</fullName>
        <label>Sub Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Unit sub model description</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrintUnitOrderCtrl.cls
public without sharing class PrintUnitOrderCtrl {

    public String companyLogoURL { get{return GeneralConfiguration.getCompanyLogoUrl();} private set;}
    public UnitOrderDetail unitWrapper {get; private set;}
    
    public PrintUnitOrderCtrl() {
        String vendorId = ApexPages.currentPage().getParameters().get('id');
        String unitIds = BPUtility.getDecodedString(ApexPages.currentPage().getParameters().get('unitIds'));
        
        List<Customer_Owned_Unit__c> unitList = getUnits(unitIds);
        BrandingLocationWrapper brandingLocationObj = getBrandingLocation();
        List<Account> vendorList = SOQLUtil.getVendorDetailRecord('Id', vendorId);
        
        unitWrapper = new UnitOrderDetail(brandingLocationObj, vendorList[0], unitList);
    }
    
    private List<Customer_Owned_Unit__c> getUnits(String unitIds) {
        List<String> unitIdList = unitIds.split(',');
        Set<Id> unitIdSet = new Set<Id>();
        for(String unitId : unitIdList) {
            unitIdSet.add(Id.valueOf(unitId));
        } 
        return SOQLUtil.getUnitDetails(unitIdSet);
    }
    
    private BrandingLocationWrapper getBrandingLocation() {
        List<Business_Profile__c> businessProfileList = SOQLUtil.getBusinessProfileData(new List<Id>());
        BrandingLocationWrapper brandingLocationObj = new BrandingLocationWrapper();
        brandingLocationObj.setDefaultBrandingLocation((businessProfileList.size() > 0 ? businessProfileList[0] : new Business_Profile__c()));
        return brandingLocationObj;
    }

    public class UnitOrderDetail {
        public CustomerDetail.Company CompanyInfo {get; set;}
        public Vendor vendor {get; set;}
        public List<UnitWrapper> unitList {get; set;}

        public UnitOrderDetail(BrandingLocationWrapper brandingLocationObj, Account vendorRec, List<Customer_Owned_Unit__c> units) {
            this.CompanyInfo = new CustomerDetail.Company(brandingLocationObj);
            this.vendor = new Vendor(vendorRec);
            
            this.unitList = new List<UnitWrapper>();
            for(Customer_Owned_Unit__c unitRec : units) {
                unitList.add(new UnitWrapper(unitRec));
            }
        }
    }
    
    public class Vendor {
        public String Name {get; private set;}
        public String AccountNumber {get; private set;}
        public String Address1 {get; private set;}
        public String Address2 {get; private set;}
        public String CityProv {get; private set;}
        public String Postal {get; private set;}
        public String State {get; private set;}
        public String Email {get; private set;}
        public String Phone {get; private set;}
        public Date CurrentDate {get; private set;} 
        
        public Vendor(Account vendorRec) {
            this.CurrentDate = system.today();
            this.Name = vendorRec.Name;
            
            String billingStreet = (vendorRec.BillingStreet == null ) ? '' : vendorRec.BillingStreet;
            List<String> bsList = billingStreet.split('\n');
            this.Address1 = (bsList.size() > 0) ? bsList[0].replace(',', ' ') : '';
            this.Address2 = (bsList.size() > 1) ? bsList[1].replace(',', ' ') : '';
            this.CityProv = vendorRec.BillingCity;
            this.Postal = vendorRec.BillingPostalCode;
            this.State = vendorRec.BillingState;
            
            if(vendorRec.Preferred_Email__c == null) {
                if(vendorRec.Email__c != null) {
                    this.Email = vendorRec.Email__c;
                } else if(vendorRec.Work_Email__c != null) {
                    this.Email = vendorRec.Work_Email__c;
                } else if(vendorRec.Other_Email__c != null) {
                    this.Email = vendorRec.Other_Email__c;
                }
            } else {
                this.Email = vendorRec.Preferred_Email__c;
            }

            if(vendorRec.Preferred_Phone__c == null) {
                if(vendorRec.Home_Number__c != null) {
                    this.Phone = vendorRec.Formatted_Home_number__c;
                } else if(vendorRec.Mobile__c != null) {
                    this.Phone = vendorRec.Formatted_Mobile_Number__c;
                } else if(vendorRec.Work_Number__c != null) {
                    this.Phone = vendorRec.Formatted_Work_Number__c;
                }
            } else {
                this.Phone = vendorRec.Formatted_Preferred_Phone__c;
            }
            this.AccountNumber = vendorRec.AccountNumber;
        }
    }
    
    public class UnitWrapper {  
        public String Id {get; private set;}
        public String Name {get; private set;}
        public String UnitType {get; private set;}
        public String UnitId {get; private set;}
        public String StockNumber {get; private set;}
        public Decimal Year {get; private set;}
        public String MakeModelDescription {get; private set;}
        public String Make {get; private set;}
        public String MakeName {get; private set;}
        public String Model {get; private set;}
        public String ModelName {get; private set;}
        public String SubModel {get; private set;}
        public String SubModelName {get; private set;}
        public String ExteriorColour {get; private set;}
        public String InteriorColour {get; private set;}
        public Decimal Cylinders {get; private set;}
        public Decimal Displacement {get; private set;}
        public Decimal TotalPrice {get; private set;}
        public Decimal TotalCost {get; private set;}
        public String Unit {get; private set;}
        public String OrderedBy {get;set;}
        public List<UnitExtraFields> unitExtraFieldList {get; set;}
        public List<UnitCostingWrapper> unitCostingList {get; private set;}
		
        public UnitWrapper(Customer_Owned_Unit__c unitRec) {
            this.Id = unitRec.Id;
            this.Name = unitRec.Name != null ? unitRec.Name : '';
            this.UnitType = (unitRec.Unit_Type__c != null) ? unitRec.Unit_Type__c : '';
            if(unitRec.Unit_Type__c == 'Stock'){
                this.UnitId = unitRec.Stock_Id__c;
            }else if(unitRec.Unit_Type__c == 'COU' || unitRec.Unit_Type__c == 'ORDU'){
                this.UnitId = unitRec.Unit_Id__c;
            }
            if(unitRec.Status__c == 'Received') {
                this.StockNumber = unitRec.ORDU_Stock_Id__c;
            } else {
                this.StockNumber = unitRec.Stock_Id__c;
            }
    		
            this.Year = unitRec.Year__c;
            this.Make = unitRec.Unit_Make__c;
            this.MakeName = (unitRec.Unit_Make__c != null) ? unitRec.Unit_Make__r.Name : '';
            this.Model = unitRec.Unit_Model__c;
            this.ModelName = (unitRec.Unit_Model__c != null) ? unitRec.Unit_Model__r.Name__c : '';        
            this.SubModel = unitRec.Sub_Model__c;
            this.SubModelName = (unitRec.Sub_Model__c != null) ? unitRec.Sub_Model__r.Sub_Model_Name__c : '';
            this.MakeModelDescription = (unitRec.Sub_Model__c != null) ? unitRec.Sub_Model__r.Description__c : '';
            
            Unit = '';
            if(unitRec.Year__c != null){
                Unit += unitRec.Year__c;
            }
            if(unitRec.Unit_Make__c != null && String.isNotBlank(unitRec.Unit_Make__r.Name)) {
                Unit += ' ' + unitRec.Unit_Make__r.Name;
            }
            if(unitRec.Unit_Model__c != null && String.isNotBlank(unitRec.Unit_Model__r.Name__c)) {
                Unit += ','+ ' ' + unitRec.Unit_Model__r.Name__c;
            }
            if(unitRec.Sub_Model__r.Sub_Model_Name__c != null && String.isNotBlank(unitRec.Sub_Model__r.Sub_Model_Name__c)) { 
                Unit += ','+ ' ' + unitRec.Sub_Model__r.Sub_Model_Name__c;
            }
            
            this.ExteriorColour = unitRec.Colour__c;
            this.InteriorColour = unitRec.Interior_Colour__c;
	    	this.Cylinders = unitRec.Cylinders__c;
            this.Displacement = unitRec.Displacement__c;
            this.TotalPrice = (unitRec.Total_Price__c != null) ? unitRec.Total_Price__c : 0;
            this.TotalCost = (unitRec.Total_Cost__c != null) ? unitRec.Total_Cost__c : 0;
            
            this.unitExtraFieldList = new List<UnitExtraFields>();
            for(GeneralConfiguration.UnitDataFieldConfigWrapper config : GeneralConfiguration.getUnitDataFieldsConfig()) {
                String fieldValue = this.getUnitGenericFieldValue(unitRec, config.FieldName);
                if(String.isNotBlank(fieldValue)) {
                    this.unitExtraFieldList.add(new UnitExtraFields(config.DisplayLabel, fieldValue));
                }
            }
            
            this.unitCostingList = new List<UnitCostingWrapper>();
            for(Unit_Price_Cost__c unitPriceCost : unitRec.Unit_Prices_Costs__r) {
                this.unitCostingList.add(new UnitCostingWrapper(unitPriceCost));
            }
            this.OrderedBy = unitRec.CreatedBy.Name;
        }
        
        public String getUnitGenericFieldValue(Customer_Owned_Unit__c unitRec, String genericFieldLabel) {
	        String fieldAPIName = genericFieldLabel.replace(' ', '_') + '__c';
	        try {
	            return (unitRec.get(fieldAPIName) != null ? String.valueOf(unitRec.get(fieldAPIName)) : '');
	        } catch(Exception e) {
	        }
	        return '';
	    }
    }
    
    public class UnitCostingWrapper {
        public String Description {get; private set;}
        public Decimal Cost {get; private set;}
        
        public UnitCostingWrapper(Unit_Price_Cost__c unitPriceCostRec) {
            this.description = unitPriceCostRec.Item_Description__c;
            this.cost = unitPriceCostRec.Total_Cost__c;
        }
    }
    
    public class UnitExtraFields {
        public String Label {get; private set;}
        public String Value {get; private set;}
        
        public UnitExtraFields(String label, String value) {
            this.Label = label;
            this.Value = value;
        }
    }
}