src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>Customer AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <label>Customer AccountingResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <label>Customer SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>availForQBSync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer availForQBSync</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Type__c</fullName>
        <description>Customer order types</description>
        <label>CO Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cash Sale</fullName>
                </value>
                <value>
                    <fullName>Internal Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>IF( !ISBLANK(Customer__r.Name) , Customer__r.Name, 
    IF( ISPICKVAL(CO_Type__c , &apos;Cash Sale&apos;)  , &apos;CASH SALE&apos;, 
       IF(ISPICKVAL(CO_Type__c , &apos;Internal Service&apos;), &apos;UNIT INVENTORY&apos;, &apos;&apos;) ) )</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Payment__c</fullName>
        <label>Total Payment</label>
        <summarizedField>CO_Invoice_Header__c.Total_Payment__c</summarizedField>
        <summaryFilterItems>
            <field>CO_Invoice_Header__c.Invoice_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>CO_Invoice_Header__c.CO_Header__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponseForJournalEntry__c</fullName>
        <description>AccountingResponse For JournalEntry</description>
        <label>AccountingResponseForJournalEntry</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <label>AccountingResponse</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
    	<fullName>Customer_Name__c</fullName>
	    <formula>CO_Header__r.Customer_Name__c</formula>
	    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
	    <label>Customer Name</label>
	    <type>Text</type>
    </fields>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>AutoNumberHolder__r.Name</formula>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SyncTokenForJournalEntry__c</fullName>
        <description>SyncToken For JournalEntry</description>
        <label>SyncTokenForJournalEntry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <label>SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Payment__c</fullName>
        <label>Total Payment</label>
        <summarizedField>CO_Invoice_Payment__c.Amount__c</summarizedField>
        <summaryForeignKey>CO_Invoice_Payment__c.CO_Invoice_Header__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>availForQBJournalEntrySync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>availForQBJournalEntrySync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>availForQBSync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>availForQBSync</label>
        <type>Checkbox</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>AccountingIdForJournalEntry__c</fullName>
        <label>AccountingIdForJournalEntry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponseForJournalEntry__c</fullName>
        <label>AccountingResponseForJournalEntry</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <formula>CO_Invoice_Header__r.CO_Header__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CO Header</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Reverse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Reverse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Cash Rounding</fullName>
                </value>
                <value>
                    <fullName>Charge Account</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Financing</fullName>
                </value>
                <value>
                    <fullName>Gift Card</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Use Deposit</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>EFTPOS</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Afterpay</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Payment Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reverse_Link__c</fullName>
        <label>Reverse Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncTokenForJournalEntry__c</fullName>
        <label>SyncTokenForJournalEntry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>availForQBJournalEntrySync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>availForQBJournalEntrySync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Invoice Payment</label>
    <nameField>
        <displayFormat>COIP-{00000000}</displayFormat>
        <label>CO Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Method</label>
</CustomObject>

src/classes/AccountingCOInvoicePayment.cls
/**
 * Author: Richa Mittal
 * Since: Dec 26, 2016
 * Name: AccountingCOInvoicePayment
 * Description: Apex class to handle JSON related oprations of paymrnt of CO Invoice for Accounting.
**/
public without sharing class AccountingCOInvoicePayment {
    
    // CO Invoice Header Id
    public String COInvoiceHeaderId {get; set;}
    
    // Customer Id
    public String CustomerId {get; set;}
    
    // Amount
    public Decimal Amount {get; set;}
    
    // CO Invoice Payment Number
    public String COInvoicePaymentNumber {get; set;}
    
    // CO Invoice Payment Id
    public String COInvoicePaymentId {get; set;}
    
    // Reverse Link
    public String ReverseLink {get; set;}
    
    // Payment Method
    public String PaymentMethod {get; set;}
    
    // Created Date
    public String CreatedDate {get; set;} 
    
    // Is Reverse Payment
    public Boolean IsReverse {get; set;} // 05/11/2016
    
    // Customer AccountingId
    public String AccountingId;
    
    // Customer Name
    public String SyncToken;
    
    public String accountingResponse;
    
    // Customer payment Journal Entry AccountingId
	public String JournalEntryAccountingId;
	    
    // Customer payment Journal Entry SyncToken
    public String JournalEntrySyncToken;
    
    public String JournalEntryAccountingResponse;
    
    public CustomerWrapper customer {get; set;}
    
    public COInvoiceHeaderWrapper COInvoiceHeaderRec {get; set;}
    
    public String CustomerOrderNumber;
    
    public String COType;
    
    public Date PaymentDate;
    
    public String XeroAccountingId;
    
    public String CustomerOrderId;
    
    public String Id;
    
    // Constructor
    public AccountingCOInvoicePayment(CO_Invoice_Payment__c  coInvoicePaymentRec) { 
        this.COInvoiceHeaderId = coInvoicePaymentRec.CO_Invoice_Header__c;
        this.CustomerId = coInvoicePaymentRec.Customer_Name__c;
        this.COInvoicePaymentId = coInvoicePaymentRec.Id;
        this.Amount = (coInvoicePaymentRec.Amount__c != null) ? coInvoicePaymentRec.Amount__c.setScale(2, RoundingMode.HALF_UP) : 0.00;
        this.COInvoicePaymentNumber = coInvoicePaymentRec.Name;
        this.ReverseLink = coInvoicePaymentRec.Reverse_Link__c;
        this.PaymentMethod = coInvoicePaymentRec.Payment_Method__c;
        this.PaymentDate = coInvoicePaymentRec.Payment_Date__c;
        this.CreatedDate = DateTimeUtility.getFormttedDateFromDateTime(coInvoicePaymentRec.CreatedDate, 'dd/MM/yyyy');
        this.IsReverse = (coInvoicePaymentRec.Is_Reverse__c != null) ? coInvoicePaymentRec.Is_Reverse__c : false; // 05/11/2016 
        
        /*
        this.AccountingId = coInvoicePaymentRec.AccountingId__c;
        this.SyncToken = coInvoicePaymentRec.SyncToken__c;
        this.accountingResponse = coInvoicePaymentRec.AccountingResponse__c;
        */
        
        this.JournalEntryAccountingId = coInvoicePaymentRec.AccountingIdForJournalEntry__c;
        this.JournalEntrySyncToken = coInvoicePaymentRec.SyncTokenForJournalEntry__c;
        this.JournalEntryAccountingResponse = coInvoicePaymentRec.AccountingResponseForJournalEntry__c;
        
        this.customer = new CustomerWrapper(coInvoicePaymentRec.Customer_Name__r.AccountingId__c, coInvoicePaymentRec.Customer_Name__r.Name);
        
        this.COInvoiceHeaderRec = new COInvoiceHeaderWrapper(coInvoicePaymentRec.CO_Invoice_Header__r.AccountingId__c);
        
        this.CustomerOrderNumber = coInvoicePaymentRec.CO_Invoice_Header__r.CO_Header__r.Name;
        this.COType = coInvoicePaymentRec.CO_Invoice_Header__r.CO_Header__r.CO_Type__c;
        
        this.XeroAccountingId = coInvoicePaymentRec.Xero_Accounting_Id__c;
        this.CustomerOrderId = coInvoicePaymentRec.CO_Invoice_Header__r.CO_Header__c;
        this.Id = coInvoicePaymentRec.Id;
    }
    
    /**
     * Name: parse
     * Desc: Method to Parse JSON String to class instance
     * @param:  (1) JSONString - String - JSON String 
     * @return: COLineItem - Class Object
    **/ 
    public static List<COInvoicePayment> parse(String json) {
        return (List<COInvoicePayment>) System.JSON.deserialize(json, List<COInvoicePayment>.class);
    }
    
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> coInvoiceItemFields = new List<String>{ 'Id',
                                                        'Name', 
                                                        'CO_Invoice_Header__c',
                                                        'Payment_Method__c',
                                                        'Amount__c',
                                                        'Reverse_Link__c',
                                                        'CreatedDate',
                                                        'Is_Reverse__c', // 05/11/2016
            											'availForQBJournalEntrySync__c',
                                                        'AccountingResponseForJournalEntry__c',
                                                        'AccountingIdForJournalEntry__c',
                                                        'Xero_Accounting_Id__c',
                                                        'Available_For_Xero_Sync__c',
                                                        'SyncTokenForJournalEntry__c',
                                                        'CO_Invoice_Header__r.Id',
				                                        'CO_Invoice_Header__r.Name', 
				                                        'CO_Invoice_Header__r.CO_Header__c',
				                                        'CO_Invoice_Header__r.Invoice_Date__c',
				                                        'CO_Invoice_Header__r.Invoice_Status__c',
				                                        'CO_Invoice_Header__r.Invoice_Number__c',
				                                        'CO_Invoice_Header__r.AccountingId__c',
				                                        'CO_Invoice_Header__r.Total_Payment__c',
				                                        'CO_Invoice_Header__r.SyncToken__c',
				                                        'CO_Invoice_Header__r.AccountingResponse__c',
            											'CO_Invoice_Header__r.CO_Header__r.Name',
            											'CO_Invoice_Header__r.CO_Header__r.CO_Type__c',
            											'Payment_Date__c',
				                                        'CO_Invoice_Header__r.CO_Header__r.Customer__r.availForQBSync__c',
                                                        'CO_Invoice_Header__r.CO_Header__r.Customer__c',
                                                        'CO_Invoice_Header__r.CO_Header__r.Customer__r.AccountingId__c',
                                                        'CO_Invoice_Header__r.CO_Header__r.Customer__r.Name',
                                                        'Customer_Name__c',
                                                        'Customer_Name__r.AccountingId__c',
                                                        'Customer_Name__r.Name',
                                                        'Customer_Name__r.availForQBSync__c'
                                               		 };
        return coInvoiceItemFields;
    }
    
    
    /*public static Map<String, Set<String>> objectToFieldMap = new Map<String, Set<String>>{
    	'COInvoicePayment'		=> new Set<String>{ 'Id',
                                                'Name', 
                                                'CO_Invoice_Header__c',
                                                'Payment_Method__c',
                                                'Amount__c',
                                                'Reverse_Link__c',
                                                'CreatedDate',
                                                'Is_Reverse__c', // 05/11/2016
                                                'AccountingId__c',
                                                'SyncToken__c',
                                                'AccountingResponse__c'
                                       		 },
    	'COInvoiceHeader'		=> new Set<String>{	'Id',
	                                        'Name', 
	                                        'CO_Header__c',
	                                        'Invoice_Date__c',
	                                        'Invoice_Status__c',
	                                        'Invoice_Number__c',
	                                        'AccountingId__c',
	                                        'Total_Payment__c',
	                                        'SyncToken__c',
	                                        'AccountingResponse__c',
	                                        'CO_Header__r.Customer__r.AccountingId__c',
	                                        'CO_Header__r.Customer__r.Name'
            								}
    };*/
    
    
    public class CustomerWrapper{
    	
    	public String AccountingId {get; set;}
    	public String Name {get; set;} 
    	
    	public CustomerWrapper(String AccountingId, String Name) {
    		this.AccountingId = AccountingId;
    		this.Name = Name;
    		
    	}
    }
    
    public class COInvoiceHeaderWrapper{
    	
    	public String AccountingId {get; set;}
    	
    	public COInvoiceHeaderWrapper(String AccountingId) {
    		this.AccountingId = AccountingId;
    		
    	}
    }
}