src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Sales Tax Items</relationshipLabel>
        <relationshipName>Sales_Tax_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_Exemption__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Tax Exemptions</relationshipLabel>
        <relationshipName>Tax_Exemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tax Exemption</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Tax Exemption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Exemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaxExemptionsTest.cls
/**
 * Author: Gourav Goyal
 * Since: July 26, 2017
 * Name: TaxExemptions test
 * Description: Controller test Class of taxExemptions class.
**/
@isTest
private class TaxExemptionsTest {
     /**
     * Name: fetchSalesTaxItemTest
     * Desc: Testing to fetch sales tax item in TaxExemptions constructor.
     * @param: 
     * @return: 
    **/
    static testmethod void fetchSalesTaxItemTest(){
        Account customer = testUtil.createCustomer(true,'test customer','abc@abc.com','jaipur','1111122222');
        Category__c categoryObj = testUtil.createCategory(true,'category one');
        Sales_Tax__c salesTax2 = TestUtil.createSalesTax(true, 'Testing Sales Tax 2', true, false, true);
        Sales_Tax_Item__c salesTaxItem1 = TestUtil.createSalesTaxItem(true, 'Test Sales Tax Item 1', 20, 'Testing Form Label 1', true, categoryObj.id);
        Tax_Exemption__c taxExemptionObj = TestUtil.createTaxExemption(true,customer.id,salesTaxItem1.id);
        List<String> appliesToList = new List<String>();
        appliesToList.add('test data');
        appliesToList.add('test data second');
        
        test.startTest();
        TaxExemptions taxExemptionsObj = new TaxExemptions(salesTaxItem1,appliesToList);
        TaxExemptions taxExemptionsObj1 = new TaxExemptions(taxExemptionObj,appliesToList);
        test.stopTest();
        system.assert(true,true);
    }
    
    /**
     * Name: fetchTaxExemptionsDataTest
     * Desc: Testing to fetch sales tax fields in TaxExemptions fieldsList method.
     * @param: 
     * @return: 
    **/
    static testmethod void fetchTaxExemptionsDataTest(){
        
        test.startTest();
        TaxExemptions.fieldsList();
        test.stopTest();
        system.assert(true,true);
    }
}