src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Checkout_Type__c</fullName>
        <label>Checkout Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Third-Party</fullName>
                </value>
                <value>
                    <fullName>Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PopulateCostsOnUnitBatchTest.cls
@isTest
private class PopulateCostsOnUnitBatchTest {
    
    @testsetup
    private static void setup(){
    	Account customer = TestDataFactory.createCustomer('Test001', 'Individual', 'Fname', 'Lname');
    	CO_Header__c coHeader = TestDataFactory.createCoHeader(customer.Id);
    	List<CO_Invoice_Header__c> coInvoiceHeaderList = new List<CO_Invoice_Header__c>();
    	for(Integer i = 0; i < 20; i++){
    		CO_Invoice_Header__c coInvoiceHeader = TestDataFactory.sampleCOInvoiceHeader(coHeader.Id, 'Closed');
    		coInvoiceHeader.Checkout_Type__c = 'Deal';
    		coInvoiceHeaderList.add(coInvoiceHeader);
    	}
    	insert coInvoiceHeaderList;
    }
    
    @isTest
    private static void test(){
    	Account customer = [SELECT FirstName__c FROM Account WHERE Is_Customer__c = true LIMIT 1];
    	Test.startTest();
    	PopulateCostsOnUnitBatch populateCostsOnUnitBatch = new PopulateCostsOnUnitBatch();
    	Id batchId = Database.executeBatch(populateCostsOnUnitBatch);
    	Test.stopTest();
    	system.assertEquals(customer.FirstName__c, 'Fname');
    }
}