src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Formatted_Name__c</fullName>
        <formula>IF( Is_Generic_Unit__c , &apos;Service job without a unit&apos;, IF( NOT(ISBLANK(Unit_Make__c)), Unit_Make__r.Name, &apos;&apos;) &amp; 
IF( NOT(ISBLANK(Unit_Model__c)), &apos; &apos; &amp; Unit_Model__r.Name__c, &apos;&apos;) &amp; 
IF( NOT(ISBLANK(Sub_Model__r.Sub_Model_Name__c)), &apos; &apos; &amp; Sub_Model__r.Sub_Model_Name__c, &apos;&apos;) &amp; 
IF( NOT(ISNULL(Year__c)), &apos; &apos; &amp; TEXT(Year__c), &apos;&apos;) &amp; 
IF( NOT(ISBLANK(Colour__c)), &apos;, &apos; &amp; Colour__c, &apos;&apos;))</formula>
        <label>Formatted Name</label>
        <type>Text</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Concern__c</fullName>
        <label>Appointment Concern</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Appointment_Day_Segment__c</fullName>
        <label>Appointment Day Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Morning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afternoon</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_DateTime__c</fullName>
        <label>End DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Scheduling_Count__c</fullName>
        <label>Event Scheduling Count</label>
        <summaryForeignKey>Event_Scheduling__c.Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Is_MultiDay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MultiDay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Technician__c.Type__c</field>
                <operation>equals</operation>
                <value>Technician</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Technician__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_In_DateTime__c</fullName>
        <label>Due In DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Due_In_Time__c</fullName>
        <label>Due In Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promised_By_DateTime__c</fullName>
        <label>Promised By DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Promised_By_Time__c</fullName>
        <label>Promised By Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminder</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Arrived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unit Arrived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Location__c</fullName>
        <description>This field is used to hold the location of the unit on the store property</description>
        <label>Unit Location</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Scheduling__c.object
<CustomObject>
    <description>Ticket - 12652</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Schedulings</relationshipLabel>
        <relationshipName>Event_Schedulings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician</label>
        <referenceTo>Technician__c</referenceTo>
        <relationshipLabel>Event Schedulings</relationshipLabel>
        <relationshipName>Event_Schedulings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Scheduling</label>
    <nameField>
        <displayFormat>ESCH-{00000000}</displayFormat>
        <label>Event Scheduling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Schedulings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Unique name field</description>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technician_Name__c</fullName>
        <label>Technician Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_In_DateTime__c</fullName>
        <label>Due In DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Due_In_Time__c</fullName>
        <label>Due In Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promised_By_DateTime__c</fullName>
        <label>Promised By DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Promised_By_Time__c</fullName>
        <label>Promised By Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Type</label>
        <referenceTo>Transaction_Type__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Arrived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unit Arrived</label>
        <type>Checkbox</type>
    </fields>  
    <fields>
        <fullName>Unit_Location__c</fullName>
        <description>This field is use to hold the location of the unit on the store property</description>
        <label>Unit Location</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Technician__c.object
<CustomObject>
    <fields>
        <fullName>Technician_Name__c</fullName>
        <label>Technician Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Technician</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Technician Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Type__c.object
<CustomObject>
    <description>Object used in SO related functionlaity</description>
    <fields>
        <fullName>Code_Label__c</fullName>
        <label>Code Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is what controls the behavior of a service section and who is being billed for the service work.  There are only three possible settings for this</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Third-Party</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Deal Service</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Stock Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Type</label>
    <nameField>
        <displayFormat>TTN-{00000000}</displayFormat>
        <label>Transaction Type Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppointmentWrapper.cls
/** 
* Author: Rajat Jain <rajat.jain@metacube.com>
* Since: May 17, 2018 
* Name: AppointmentWrapper
* Description: Apex class which contains all Appointment Data Wrapper
**/
public without sharing class AppointmentWrapper {
    public String Id;
    public String CustomerId;
    public String COUId;
    public List<String> Concern;
    public List<String> SOKitConcern;
    public Decimal EstimatedHours;
    public String TransactionTypeLabel;
    public String TransactionTypeId;
    public String TransactionType;
    public String Title;
    
    public Boolean isConflictExists;
    public String EventId;
    
    public String StartDate;
    public String EndDate;
    public String StartTime;
    public String EndTime;
    public String FormattedStartDate;
    
    public String ActualStartDate;
    public String ActualEndDate;
    public String ActualStartTime;
    public String ActualEndTime;
    
    public String DueInTime;
    public String DueInDate;
    public String PromiseByTime;
    public String PromisedByDate;
    public Boolean IsUnitArrived;
    public String UnitLocation;

    public Boolean IsMultiday;
    public Boolean IsSelectedDayIsStartDay;
    public Boolean IsSelectedDayIsEndDay;
    public Boolean IsSameSOTypeAppointmentOverlapped;
    public Boolean IsAppointmentOverlapped;
    
    public String CustomerName;
    public String COId;
    public String CONumber;
    public String UnitFormattedName;
    public String AppointmentDaySegment;
    public String TechnicianId;
    public String TechnicianName;
    public String SOHeaderId;
    public Boolean IsWorkLate;
    public String ServiceJobStatus;
    public Boolean IsMultiTechnicianAssigned;
    public Decimal AppointmentEstimatedHours;
    
	public List<EventSchedulingWrapper> EventSchedulingList;
    
    public AppointmentWrapper(Event__c eventRec) {
    	this.Id = eventRec.Id;
        populateDefaultFields(eventRec);
    }
    
    public AppointmentWrapper(Event__c eventRec, Boolean needUnitDetail) {
    	this.Id = this.EventId = eventRec.Id;
        populateDefaultFields(eventRec);
        populateOtherFields(eventRec);
        populateEventScheduling(eventRec.Event_Schedulings__r);
        populateDateTimeFields(eventRec);
        if(eventRec.Technician__c != null) {
            this.TechnicianId = (eventRec.Technician__c != null) ? eventRec.Technician__c : null;
            this.TechnicianName = (eventRec.Technician__c != null) ? eventRec.Technician__r.Technician_Name__c : null;
        } else if(IsMultiTechnicianAssigned) {
            this.TechnicianName = 'Multiple technicians';
        }
    }
    
    public AppointmentWrapper(Event__c eventRec, Boolean needUnitDetail, DateTime selectedDateTime) {
    	this.Id = this.EventId = eventRec.Id;
        populateDefaultFields(eventRec);
        populateOtherFields(eventRec);
        populateDateTimeFields(eventRec);
        if(eventRec.Technician__c != null) {
            this.TechnicianId = (eventRec.Technician__c != null) ? eventRec.Technician__c : null;
            this.TechnicianName = (eventRec.Technician__c != null) ? eventRec.Technician__r.Technician_Name__c : null;
        } else if(IsMultiTechnicianAssigned) {
            this.TechnicianName = 'Multiple technicians';
        }
        
        ShopSettingWrapper seletedDayShopSettingRec;
        this.IsSelectedDayIsStartDay = selectedDateTime.isSameDay(eventRec.Start_DateTime__c);
        //system.assert(eventRec.Id != '00U2M00000NmRNz', selectedDateTime + '\n' + eventRec.StartDateTime + 'isSameDay' + '\n' + selectedDateTime.isSameDay(eventRec.StartDateTime));
        this.IsSelectedDayIsEndDay = selectedDateTime.isSameDay(eventRec.End_DateTime__c);
        
        if(!this.IsSelectedDayIsStartDay || !this.IsSelectedDayIsEndDay) {
            String selectedDayName = AccountSettingService.getDayNameFromDate(Date.newinstance(selectedDateTime.year(), selectedDateTime.month(), selectedDateTime.day()));
            List<ShopSettingWrapper> shopSettingList = AccountSettingService.getShopSettingDataForParticularDay(selectedDayName);
            if(shopSettingList.size() > 0) {
                seletedDayShopSettingRec = shopSettingList[0];
            } else {
                throw new BlackPurlException(BlackPurlException.getErrorMessage('Shop setting config is not defined for ' + selectedDayName, 'Error'));
            }
        }
        
        this.StartDate = (eventRec.Start_DateTime__c != null) ? (this.IsSelectedDayIsStartDay ? 
                            BPUtility.getFormatedDateTime(eventRec.Start_DateTime__c) : BPUtility.getFormatedDateTime(selectedDateTime)) : null;
        this.EndDate = (eventRec.End_DateTime__c != null) ? (this.IsSelectedDayIsEndDay ? 
                            BPUtility.getFormatedDateTime(eventRec.End_DateTime__c) : BPUtility.getFormatedDateTime(selectedDateTime)) : null;
        this.StartTime = (eventRec.Start_DateTime__c != null) ? (this.IsSelectedDayIsStartDay ? 
                            eventRec.Start_DateTime__c.format('h:mma') : seletedDayShopSettingRec.FromTime) : null;
        this.EndTime = (eventRec.End_DateTime__c != null) ? (this.IsSelectedDayIsEndDay ? 
                            eventRec.End_DateTime__c.format('h:mma') : seletedDayShopSettingRec.ToTime) : null;
                            
        this.IsSameSOTypeAppointmentOverlapped = this.IsSameSOTypeAppointmentOverlapped != null ? this.IsSameSOTypeAppointmentOverlapped : false;
        this.IsAppointmentOverlapped = this.IsAppointmentOverlapped != null ? this.IsAppointmentOverlapped : false;
    }
    
    public AppointmentWrapper(Event_Scheduling__c schedulingRec, Boolean needUnitDetail, DateTime selectedDateTime) {
    	this.Id = schedulingRec.Id;
    	this.EventId = schedulingRec.Event__c;
        populateDefaultFields(schedulingRec.Event__r);
        populateOtherFields(schedulingRec.Event__r);
        populateDateTimeFields(schedulingRec);
        if(schedulingRec.Technician__c != null) {
            this.TechnicianId = (schedulingRec.Technician__c != null) ? schedulingRec.Technician__c : null;
            this.TechnicianName = (schedulingRec.Technician__c != null) ? schedulingRec.Technician__r.Technician_Name__c : null;
        } else if(IsMultiTechnicianAssigned) {
            this.TechnicianName = 'Multiple technicians';
        }
        
        ShopSettingWrapper seletedDayShopSettingRec;
        this.IsSelectedDayIsStartDay = selectedDateTime.isSameDay(schedulingRec.Start_Date_Time__c);
        //system.assert(schedulingRec.Id != '00U2M00000NmRNz', selectedDateTime + '\n' + schedulingRec.StartDateTime + 'isSameDay' + '\n' + selectedDateTime.isSameDay(schedulingRec.StartDateTime));
        this.IsSelectedDayIsEndDay = selectedDateTime.isSameDay(schedulingRec.End_Date_Time__c);
        
        if(!this.IsSelectedDayIsStartDay || !this.IsSelectedDayIsEndDay) {
            String selectedDayName = AccountSettingService.getDayNameFromDate(Date.newinstance(selectedDateTime.year(), selectedDateTime.month(), selectedDateTime.day()));
            List<ShopSettingWrapper> shopSettingList = AccountSettingService.getShopSettingDataForParticularDay(selectedDayName);
            if(shopSettingList.size() > 0) {
                seletedDayShopSettingRec = shopSettingList[0];
            } else {
                throw new BlackPurlException(BlackPurlException.getErrorMessage('Shop setting config is not defined for ' + selectedDayName, 'Error'));
            }
        }
        
        this.StartDate = (schedulingRec.Start_Date_Time__c != null) ? (this.IsSelectedDayIsStartDay ? 
                            BPUtility.getFormatedDateTime(schedulingRec.Start_Date_Time__c) : BPUtility.getFormatedDateTime(selectedDateTime)) : null;
        this.EndDate = (schedulingRec.End_Date_Time__c != null) ? (this.IsSelectedDayIsEndDay ? 
                            BPUtility.getFormatedDateTime(schedulingRec.End_Date_Time__c) : BPUtility.getFormatedDateTime(selectedDateTime)) : null;
        this.StartTime = (schedulingRec.Start_Date_Time__c != null) ? (this.IsSelectedDayIsStartDay ? 
                            schedulingRec.Start_Date_Time__c.format('h:mma') : seletedDayShopSettingRec.FromTime) : null;
        this.EndTime = (schedulingRec.End_Date_Time__c != null) ? (this.IsSelectedDayIsEndDay ? 
                            schedulingRec.End_Date_Time__c.format('h:mma') : seletedDayShopSettingRec.ToTime) : null;
                            
        this.IsSameSOTypeAppointmentOverlapped = this.IsSameSOTypeAppointmentOverlapped != null ? this.IsSameSOTypeAppointmentOverlapped : false;
        this.IsAppointmentOverlapped = this.IsAppointmentOverlapped != null ? this.IsAppointmentOverlapped : false;
    }
    
    private void populateDefaultFields(Event__c eventRec) {
    	this.CustomerId = eventRec.Customer__c;
        this.Concern = (eventRec.Appointment_Concern__c != null) ? eventRec.Appointment_Concern__c.split('\n') : new List<String>();
        this.SOKitConcern = new List<String>();
        this.COUId = eventRec.Customer_Owned_Unit__c;
        this.TransactionTypeLabel = eventRec.Transaction_Type__r.Code_Label__c;
        this.TransactionTypeId = eventRec.Transaction_Type__c;
        this.TransactionType = eventRec.Transaction_Type__r.Type__c;
        this.Title = eventRec.Name__c;
        //this.IsWorkLate = eventRec.Is_Work_Late__c;
        this.IsMultiday = eventRec.Is_MultiDay__c;

        this.DueInTime = (String.isNotBlank(eventRec.Due_In_Time__c) && eventRec.Due_In_DateTime__c != null) ? 
        				eventRec.Due_In_DateTime__c.format('h:mm a') : '';
        this.PromiseByTime = (String.isNotBlank(eventRec.Promised_By_Time__c) && eventRec.Promised_By_DateTime__c != null) ? 
        				eventRec.Promised_By_DateTime__c.format('h:mm a') : '';
        				
        this.DueInDate = eventRec.Due_In_DateTime__c != null ?
            eventRec.Due_In_DateTime__c.format(Constants.localeToDateTimeFmtMap.get(UserInfo.getLocale())) : '';
        this.PromisedByDate = eventRec.Promised_By_DateTime__c != null ?
            eventRec.Promised_By_DateTime__c.format(Constants.localeToDateTimeFmtMap.get(UserInfo.getLocale())) : '';
        this.IsUnitArrived = eventRec.Unit_Arrived__c != null ? eventRec.Unit_Arrived__c : false;
        this.UnitLocation = eventRec.Unit_Location__c != null ? eventRec.Unit_Location__c : '';
        this.IsMultiTechnicianAssigned = eventRec.Event_Scheduling_Count__c > 1 ? true : false;
    }
    
    private void populateOtherFields(Event__c eventRec) {
        this.CustomerName = (eventRec.Customer__r.Name != null) ? eventRec.Customer__r.Name : null;
        this.UnitFormattedName = eventRec.Customer_Owned_Unit__r.Formatted_Name__c;
        this.AppointmentDaySegment = eventRec.Appointment_Day_Segment__c;
        this.CONumber = (eventRec.CO_Header__r.Name != null) ? eventRec.CO_Header__r.Name : null;
        this.COId = (eventRec.CO_Header__c != null) ? eventRec.CO_Header__c : null;
        this.SOHeaderId = (eventRec.Service_Order_Header__c != null) ? eventRec.Service_Order_Header__c : null;
        this.ServiceJobStatus = (eventRec.Service_Order_Header__c != null) ? eventRec.Service_Order_Header__r.Work_Status__c : null;
    }

    private void populateDateTimeFields(Event__c eventRec) {
        this.AppointmentEstimatedHours = eventRec.Estimated_Hours__c;
        this.EstimatedHours= eventRec.Estimated_Hours__c;
        this.ActualStartDate = (eventRec.Start_DateTime__c != null) ? BPUtility.getFormatedDateTime(eventRec.Start_DateTime__c) : null;
        this.ActualEndDate = (eventRec.End_DateTime__c != null) ? BPUtility.getFormatedDateTime(eventRec.End_DateTime__c) : null;
        this.ActualStartTime = (eventRec.Start_DateTime__c != null) ? eventRec.Start_DateTime__c.format('h:mma') : null;
        this.ActualEndTime = (eventRec.End_DateTime__c != null) ? eventRec.End_DateTime__c.format('h:mma') : null;
        this.FormattedStartDate = null;
        if(eventRec.Start_DateTime__c != null) {
            this.FormattedStartDate = eventRec.Start_DateTime__c.format('MMMM dd, yyyy');
        }
    }

    private void populateDateTimeFields(Event_Scheduling__c schedulingRec) {
    	this.EventId = schedulingRec.Event__c;
        this.EstimatedHours= schedulingRec.Hours__c;
        this.AppointmentEstimatedHours = schedulingRec.Event__r.Estimated_Hours__c;
        this.ActualStartDate = (schedulingRec.Start_Date_Time__c != null) ? BPUtility.getFormatedDateTime(schedulingRec.Start_Date_Time__c) : null;
        this.ActualEndDate = (schedulingRec.End_Date_Time__c != null) ? BPUtility.getFormatedDateTime(schedulingRec.End_Date_Time__c) : null;
        this.ActualStartTime = (schedulingRec.Start_Date_Time__c != null) ? schedulingRec.Start_Date_Time__c.format('h:mma') : null;
        this.ActualEndTime = (schedulingRec.End_Date_Time__c != null) ? schedulingRec.End_Date_Time__c.format('h:mma') : null;
        this.FormattedStartDate = null;
        if(schedulingRec.Start_Date_Time__c != null) {
            this.FormattedStartDate = schedulingRec.Start_Date_Time__c.format('MMMM dd, yyyy');
        }
    }

    private void populateEventScheduling(List<Event_Scheduling__c> eventSchedulingList) {
    	this.EventSchedulingList = new List<EventSchedulingWrapper>();
    	for(Event_Scheduling__c schedulingRec : eventSchedulingList) {
    		this.EventSchedulingList.add(new EventSchedulingWrapper(schedulingRec));
        }
    }

    public static List<String> getAppointmentFieldsList() {
       return new List<String>{'Technician__c', 
       							'Technician__r.Technician_Name__c',
                                'Name__c', 
                                'Appointment_Day_Segment__c',
                                'Transaction_Type__c',
                                'Transaction_Type__r.Code_Label__c',
                                'Transaction_Type__r.Type__c',
                                'Estimated_Hours__c', 
                                'Start_DateTime__c',
                                'End_DateTime__c', 
                                'Customer_Owned_Unit__c',
                                'Customer__c',
                                'CO_Header__c',
                                'CO_Header__r.Name',
                                'Appointment_Concern__c',
                                'Customer__r.Name',
                                'Customer_Owned_Unit__r.Formatted_Name__c',
                                'Service_Order_Header__c',
                                //'Is_Work_Late__c',
                                'Is_MultiDay__c',
                                'Promised_By_Time__c',
                                'Due_In_Time__c',
                                'Promised_By_DateTime__c',
                                'Due_In_DateTime__c',
                                'Unit_Arrived__c',
                                'Service_Order_Header__r.Work_Status__c',
                                'Unit_Location__c',
                                'Event_Scheduling_Count__c'
                            };
    }
}