src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Active__c , &apos;Active&apos;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Qty_On_Order__c &gt; 0,&apos;On Order&apos;,  IF( OR((Qty_In_Stock__c &lt; Auto_reorder_Min__c),( AND((Qty_In_Stock__c = Auto_reorder_Min__c),( Auto_reorder_Min__c !=  Auto_reorder_Max__c )))), &apos;Required&apos;, IF(Qty_In_Stock__c &gt; 0, &apos;In Stock&apos;,&apos;Out of Stock&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Header__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Partially Received</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vendor Order Header</label>
    <nameField>
        <displayFormat>VO-{00000000}</displayFormat>
        <label>Vendor Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Line_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Order Line Item Groups</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Order Header</label>
        <referenceTo>Vendor_Order_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Line Item Groups</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Line Item Group</label>
    <nameField>
        <displayFormat>VOG-{00000000}</displayFormat>
        <label>Vendor Order Line Item Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Line Item Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Yamaha_Australia_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used for Yamaha Australia vendor order export file.</description>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>Dealer’s Account Number with Yamaha. Max length is 6 characters.</description>
        <inlineHelpText>Dealer’s Account Number with Yamaha. Max length is 6 characters.</inlineHelpText>
        <label>Dealer Code</label> 
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Person_Code__c</fullName>
        <description>Dealer Sales Representative. Max length is 3 characters.</description>
        <inlineHelpText>Dealer Sales Representative. Max length is 3 characters.</inlineHelpText>
        <label>Sales Person Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <description>User Id is used to log on to YDC system. Max length is 10 characters.</description>
        <inlineHelpText>User Id is used to log on to YDC system. Max length is 10 characters.</inlineHelpText>
        <label>User ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Yamaha Australia Config</label>
</CustomObject>

src/classes/VendorOrderExportCtrlTest.cls
@isTest 
public class VendorOrderExportCtrlTest {
	
	@testSetup
    private static void setupTestData() {
        TestDataFactory.disableFLSChecks();
    	IFW_IntegrationConfig__c ifwIntegration = TestUtil.createIFWConfigForXero(); 
		IFW_IntegrationConfigItem__c ifwConfigItem = TestUtil.createIFWConfigItemForXero('Journal Entry', ifwIntegration.Id);
        Account vendorRec = TestDataFactory.createVendor('Test Vendor');
        Vendor_Order_Header__c vOHeaderRec = TestDataFactory.createVendorOrderHeader(vendorRec.Id);
        Category__c categoryRec = TestDataFactory.createCategory('Test category');
        
        Part__c partRec = TestDataFactory.createPart(vendorRec.Id, 10, 10, 10, 10, 2, categoryRec.Id);
        Vendor_Order_Line_Item_Group__c vendorOrderLineItemGroupRec = TestDataFactory.createVendorOrderLineItemGroup(vOHeaderRec.Id, partRec.Id);
    }
      
    @isTest
    private static void genericVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
        VendorOrderExportCtrl.VOExportParams paramObj = new VendorOrderExportCtrl.VOExportParams();
        paramObj.VOHeaderId = vOHeaderRec.Id;
        paramObj.ExportType = 'Generic (.csv)';
  		pageRef.getParameters().put('params', BPUtility.getEncodedString(System.JSON.serialize(paramObj)));
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/csv#Vendor Order.csv');
    }
    
    @isTest
    private static void partsCanadaVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
        VendorOrderExportCtrl.VOExportParams paramObj = new VendorOrderExportCtrl.VOExportParams();
        paramObj.VOHeaderId = vOHeaderRec.Id;
        paramObj.ExportType = 'Parts Canada (.csv)';
  		pageRef.getParameters().put('params', BPUtility.getEncodedString(System.JSON.serialize(paramObj)));
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/csv#Vendor Order.csv');
    }
    
    @isTest
    private static void hondaEBizVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
        VendorOrderExportCtrl.VOExportParams paramObj = new VendorOrderExportCtrl.VOExportParams();
        paramObj.VOHeaderId = vOHeaderRec.Id;
        paramObj.ExportType = 'Honda eBiz';
  		pageRef.getParameters().put('params', BPUtility.getEncodedString(System.JSON.serialize(paramObj)));
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/plain/#HNVENDOR.DAT');
    }
    
    @isTest
    private static void hDnetAustraliaVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id, Name from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
        VendorOrderExportCtrl.VOExportParams paramObj = new VendorOrderExportCtrl.VOExportParams();
        paramObj.VOHeaderId = vOHeaderRec.Id;
        paramObj.ExportType = 'HDnet Australia';
  		pageRef.getParameters().put('params', BPUtility.getEncodedString(System.JSON.serialize(paramObj)));
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType, 'text/plain/#' + vOHeaderRec.Name + '.txt');
    }
    
    @isTest
    private static void bossWebVendorOrderExportCtrlTest() {
    	Vendor_Order_Header__c vOHeaderRec = [SELECT Id, Name from Vendor_Order_Header__c LIMIT 1];
    	PageReference pageRef = Page.VendorOrderExport;
        VendorOrderExportCtrl.VOExportParams paramObj = new VendorOrderExportCtrl.VOExportParams();
        paramObj.VOHeaderId = vOHeaderRec.Id;
        paramObj.ExportType = 'BossWeb';
  		pageRef.getParameters().put('params', BPUtility.getEncodedString(System.JSON.serialize(paramObj)));
  		Test.setCurrentPage(pageRef);
  		VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
  		system.assertEquals(vendorOrderExportCtrl.contentType.contains('.txt'), true);
    }
    
    @isTest
    private static void yamahaAustraliaVendorOrderExportCtrlTest() {
        Yamaha_Australia_Config__c yamahaRec = new Yamaha_Australia_Config__c();
        yamahaRec.Dealer_Code__c = '123';
        yamahaRec.Sales_Person_Code__c = '123';
        yamahaRec.User_ID__c = '123';
        insert yamahaRec;
        
        Vendor_Order_Header__c vOHeaderRec = [SELECT Id, Name, Status__c from Vendor_Order_Header__c LIMIT 1];
        vOHeaderRec.Status__c = 'Open';
        update vOHeaderRec;
        
        PageReference pageRef = Page.VendorOrderExport;
        VendorOrderExportCtrl.VOExportParams paramObj = new VendorOrderExportCtrl.VOExportParams();
        paramObj.VOHeaderId = vOHeaderRec.Id;
        paramObj.ExportType = 'Yamaha Australia';
  		pageRef.getParameters().put('params', BPUtility.getEncodedString(System.JSON.serialize(paramObj)));
        Test.setCurrentPage(pageRef);
        VendorOrderExportCtrl vendorOrderExportCtrl = new VendorOrderExportCtrl();
        system.assertEquals(vendorOrderExportCtrl.contentType.contains('.txt'), false);
    }
}