src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Price_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Level</label>
        <referenceTo>Price_Level__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BRP_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Dealer_Id__c</fullName>
        <description>Holds the BRP Dealer ID of the BP Dealer</description>
        <label>Dealer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radius_Measure__c</fullName>
        <description>Mile or Kilometer</description>
        <label>Radius Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radius__c</fullName>
        <description>Radius for searching for parts</description>
        <label>Radius</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BRP Settings</label>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>URL of the resource you will access</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Auto_reorder_Max__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Auto Reorder To</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_reorder_Min__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Auto Reorder At</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Counted__c</fullName>
        <label>Last Counted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Sold__c</fullName>
        <label>Last Sold</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Stocked__c</fullName>
        <label>Last Stocked</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Packaged_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packaged Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qty_In_Stock__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Qty In Stock</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty_On_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Qty On Order</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRP_Part_Index__c</fullName>
        <defaultValue>1</defaultValue>
        <label>BRP Part Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Included_In_BRP_Inventory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Included In BRP Inventory</label>
        <type>Checkbox</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price_Level__c.object
<CustomObject>
    <label>Price Level</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BRPPartsIntegrationTest.cls
@isTest
private class BRPPartsIntegrationTest {
    @TestSetup
    private static void setup(){
        TestDataFactory.disableFLSChecks();
        IFW_IntegrationConfig__c IFWConfigObj = TestDataFactory.createIFWConfigForBRP();
        List<IFW_IntegrationConfig__c> IFWConfigObjList = [Select Id from IFW_IntegrationConfig__c];
        IFW_IntegrationConfigItem__c IFWConfigItemObj = TestUtil.createIFWConfigItemBRP('GetPartLocator', IFWConfigObjList[0].Id);
        IFWConfigItemObj.Endpoint_URL__c = 'http://services.motiveintegrator.com/PDS/services/PartsLocator/Get';
        update IFWConfigItemObj;
        insert new BRP_Settings__c(Dealer_Id__c = '0000691784', Radius_Measure__c = 'mile', Radius__c = 100);
        Account vendor = TestUtil.createVendor(true, 'Test Vendor');
        Category__c testCategory = TestUtil.createCategory(true, 'Test Category');
        
        Price_Level__c defaultPriceLevel = TestUtil.createPriceLevel(true, 'Default Price Level', 'MSRP', 10 , true, true);
        Sales_Tax__c defaultSalesTax = TestUtil.createSalesTax(true, 'Test Sales Tax', true, true, true);
        Account customer = TestUtil.createCustomer(true, 'customerName', 'abc@abc.com', 'jaipur', '1111111111', null, null, false, true,'Individual');
        
        CO_Header__c coHeader = TestUtil.createCOHeader(true, customer.Id);
        Part__c part = TestUtil.createPart(false, 'partNumberP01', vendor.Id, 'Test Part', testCategory.Id, 10, 20, 50, 100, 100);
        part.Packaged_Part__c = false;
        part.Qty_On_Order__c = 0;
        part.Auto_reorder_Min__c = 1;
        part.Last_Sold__c = System.today();
        part.Auto_reorder_Max__c = 4;
        part.Last_Stocked__c = System.today();
        part.Last_Counted__c = System.today();
        part.Qty_In_Stock__c = 5;
        part.BRP_Part_Index__c = 1;
        part.Is_Included_In_BRP_Inventory__c =  false;
        insert part;

        Part__c part1 = TestUtil.createPart(false, 'partNumberP011', vendor.Id, 'Test Part1', testCategory.Id, 10, 220, 530, 100, 100);
        part1.Packaged_Part__c = false;
        part1.Qty_On_Order__c = 0;
        part.Qty_In_Stock__c = 5;
        part1.Auto_reorder_Min__c = 1;
        part1.Last_Sold__c = System.today();
        part1.Auto_reorder_Max__c = 4;
        part1.Last_Stocked__c = System.today();
        part1.Last_Counted__c = System.today();
        part1.BRP_Part_Index__c = 1;
        part1.Is_Included_In_BRP_Inventory__c =  false;
        insert part1;
    }
    @isTest
    private static void testBRPPartsIntegration() {
        Test.setMock(HttpCalloutMock.class, new BRPPartsIntegrationMockTest('Supplier'));
        Test.startTest();
        Part__c part = [Select Id, Qty_In_Stock__c from Part__c Limit 1][0];
        String res = BRPPartsIntegration.getPartsLocator(string.valueOf(part.id), 10, 'Supplier');
        Account testVendor = [Select Id, name from Account where Name = 'Test Vendor'];
        system.assertEquals('Test Vendor', testVendor.name);
        Test.stopTest();
    }
    @isTest
    private static void testBRPPartsIntegration1() {
        Test.setMock(HttpCalloutMock.class, new BRPPartsIntegrationMockTest('Dealer Radius'));
        Test.startTest();
        Part__c part = [Select Id, Qty_In_Stock__c from Part__c Limit 1][0];
        String res = BRPPartsIntegration.getPartsLocator(string.valueOf(part.id), 10, 'Dealer Radius');
        Account testVendor = [Select Id, name from Account where Name = 'Test Vendor'];
        system.assertEquals('Test Vendor', testVendor.name);
        Test.stopTest();
    }
}