src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Purchase_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts (Purchase Tax)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales tax to apply on unit</description>
        <label>Applicable Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Taxable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is unit taxable or not</description>
        <label>Taxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Base_Unit_Price__c</fullName>
        <description>Price total of all Base Units related to this unit.</description>
        <label>Total Base Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Base_Units_Cost__c</fullName>
        <description>Total Base unit cost</description>
        <label>Total Base Units Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total Cost</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Dealer_Options_Cost__c</fullName>
        <description>Total Dealer Options Cost</description>
        <label>Total Dealer Options Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Dealer_Options_Price__c</fullName>
        <description>Price Total of all Dealer Options related to this unit.</description>
        <label>Total Dealer Options Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Factory_Options_Cost__c</fullName>
        <description>Total Factory Options Cost</description>
        <label>Total Factory Options Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Factory_Options_Price__c</fullName>
        <description>Total Factory Options Price</description>
        <label>Total Factory Options Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total Price</description>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Id__c</fullName>
        <description>This will be used for Generating unit Id</description>
        <label>Unit Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Make of unit</description>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Types of units</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COU</fullName>
                </value>
                <value>
                    <fullName>STOCK</fullName>
                </value>
                <value>
                    <fullName>ORDU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Owned Units (Vendor)</relationshipLabel>
        <relationshipName>Customer_Owned_Units1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Active__c , &apos;Active&apos;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <description>Cost of unit</description>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit lookup with Customer Owned Unit</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Description of unit</description>
        <label>Item/Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of unit</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <description>Quantity of unit</description>
        <label>Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Ordered_Unit_Price_Cost__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Ordered Unit Price Cost</label>
        <referenceTo>Unit_Price_Cost__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taxable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Taxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total cost of unit</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total price of unit</description>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Base unit, Factory options, Dealer installed options</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Factory</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Customer_Owned_Unit__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicable_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicable Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnitPriceAndCostTriggerTest.cls
/**
**/ 
@isTest
private class UnitPriceAndCostTriggerTest {

    static testMethod void insertUnitPriceAndCostTriggerTest() {
    	Account customer = TestUtil.createCustomer(true, 'customerName', 'abc@abc.com', 'Agra', '1111111112', null, null, false, true,'Individual','firstname1', 'lastname', '9999999999', 'BillingStreet');
       	Unit_Make__c unitmake = TestUtil.createUnitMake(true, 'unitMakeName', '12A', true);
        Unit_Model__c unitmodel = TestUtil.createUnitModel(true, 'unitModelName', '12A', true, unitMake.Id);
        List<Customer_Owned_Unit__c> customerOwnedUnitRecList = new List<Customer_Owned_Unit__c>();
        Customer_Owned_Unit__c customerOwnedUnitStockRec1 = TestUtil.createCustomerOwnedUnit(false,customer.id, unitmake.id,unitmodel.id,null,'123');
        customerOwnedUnitStockRec1.Unit_Type__c = 'STOCK';
        customerOwnedUnitStockRec1.Status__c = 'Available';
        customerOwnedUnitStockRec1.Unit_Id__c = '';
        
    	Customer_Owned_Unit__c customerOwnedUnitStockRec2 = TestUtil.createCustomerOwnedUnit(false,customer.id, unitmake.id,unitmodel.id,null,'1213');
        customerOwnedUnitStockRec2.Unit_Type__c = 'STOCK';
        customerOwnedUnitStockRec2.Status__c = 'Available';
        customerOwnedUnitStockRec2.Unit_Id__c = '';
    	
    	Test.startTest();
        customerOwnedUnitRecList.add(customerOwnedUnitStockRec1);
        customerOwnedUnitRecList.add(customerOwnedUnitStockRec2);
        insert customerOwnedUnitRecList;
    	Test.stopTest();
        
        Unit_Price_Cost__c unitPriceAndCost1COU1 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnitStockRec1.Id, Type__c = 'Factory', Cost__c = 100, Price__c = 150, Qty__c = 2);
        Unit_Price_Cost__c unitPriceAndCost2COU1 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnitStockRec2.Id, Type__c = 'Dealer', Cost__c = 200, Price__c = 300, Qty__c = 2);
        
        Unit_Price_Cost__c unitPriceAndCost1COU2 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnitStockRec1.Id, Type__c = 'Base', Cost__c = 50, Price__c = 20, Qty__c =1);
        Unit_Price_Cost__c unitPriceAndCost2COU2 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnitStockRec2.Id, Type__c = 'Dealer', Cost__c = 60, Price__c = 100, Qty__c = 5);
        insert new List<Unit_Price_Cost__c>{unitPriceAndCost1COU1, unitPriceAndCost2COU1, unitPriceAndCost1COU2, unitPriceAndCost2COU2};
		
		validateTriggerUpdate();
		
		unitPriceAndCost1COU2.Customer_Owned_Unit__c = customerOwnedUnitStockRec1.Id;
		update unitPriceAndCost1COU2;
		delete unitPriceAndCost1COU1;
		validateTriggerUpdate();
	}
	
	private static void validateTriggerUpdate() {
		List<Customer_Owned_Unit__c> customerOwnedUnitRecList = [Select Id, Total_Base_Unit_Price__c, Total_Base_Units_Cost__c, Total_Dealer_Options_Cost__c, Total_Dealer_Options_Price__c, Total_Factory_Options_Cost__c,
					Total_Factory_Options_Price__c, Total_Cost__c, Total_Price__c, (Select Type__c, Total_Cost__c, Total_Price__c from Unit_Prices_Costs__r) from Customer_Owned_Unit__c];
				
		for(Customer_Owned_Unit__c couRec : customerOwnedUnitRecList) {
			Decimal baseUnitsCost = 0;
			Decimal baseUnitsPrice = 0;
			Decimal factoryOptionsCost = 0;
			Decimal factoryOptionsPrice = 0;
			Decimal dealerOptionsCost = 0;
			Decimal dealerOptionsPrice = 0;
			Decimal totalCost = 0;
			Decimal totalPrice = 0;
			for(Unit_Price_Cost__c unitPriceAndCostRec : couRec.Unit_Prices_Costs__r) {
				if(unitPriceAndCostRec.Type__c != null && unitPriceAndCostRec.Type__c == UnitPriceAndCostTriggerHelper.TYPE_BASE) {
					baseUnitsCost += (unitPriceAndCostRec.Total_Cost__c == null) ? 0 : unitPriceAndCostRec.Total_Cost__c;
					baseUnitsPrice += (unitPriceAndCostRec.Total_Price__c == null) ? 0 : unitPriceAndCostRec.Total_Price__c;
				} else if(unitPriceAndCostRec.Type__c != null && unitPriceAndCostRec.Type__c == UnitPriceAndCostTriggerHelper.TYPE_DEALER) {
					dealerOptionsCost += (unitPriceAndCostRec.Total_Cost__c == null) ? 0 : unitPriceAndCostRec.Total_Cost__c;
					dealerOptionsPrice += (unitPriceAndCostRec.Total_Price__c == null) ? 0 : unitPriceAndCostRec.Total_Price__c;
				} else if(unitPriceAndCostRec.Type__c != null && unitPriceAndCostRec.Type__c == UnitPriceAndCostTriggerHelper.TYPE_FACTORY) {
					factoryOptionsCost += (unitPriceAndCostRec.Total_Cost__c == null) ? 0 : unitPriceAndCostRec.Total_Cost__c;
					factoryOptionsPrice += (unitPriceAndCostRec.Total_Price__c == null) ? 0 : unitPriceAndCostRec.Total_Price__c;
				} 
			}
			
			system.assertEquals(baseUnitsCost, couRec.Total_Base_Units_Cost__c);
			system.assertEquals(baseUnitsPrice, couRec.Total_Base_Unit_Price__c);
			system.assertEquals(factoryOptionsCost, couRec.Total_Factory_Options_Cost__c);
			system.assertEquals(factoryOptionsPrice, couRec.Total_Factory_Options_Price__c);
			system.assertEquals(dealerOptionsCost, couRec.Total_Dealer_Options_Cost__c);
			system.assertEquals(dealerOptionsPrice, couRec.Total_Dealer_Options_Price__c);
			system.assertEquals(totalCost, couRec.Total_Cost__c);
			system.assertEquals(totalPrice, couRec.Total_Price__c);
			
		}
	}
    
    static testMethod void upcEnhancedTaxCalculationTest() {
		TestUtil.createEnhancedTaxSettingInGeneralConfig();
        
        Sales_Tax__c standardSalestax = TestUtil.createMixedPurchaseTaxForEnhancedTaxCalculation();
       
		Account vendor = TestUtil.createVendor(false, 'Test Vendor');   
		vendor.Purchase_Tax__c = standardSalestax.ID;
		insert vendor;
		
		Unit_Make__c unitmake = TestUtil.createUnitMake(true, 'unitMakeName', '12A', true);
        Unit_Model__c unitmodel = TestUtil.createUnitModel(true, 'unitModelName', '12A', true, unitMake.Id);
        Customer_Owned_Unit__c customerOwnedUnit = TestUtil.createCustomerOwnedUnit(false, null, UnitMake.Id, UnitModel.Id, null);
        customerOwnedUnit.Taxable__c = true;
		customerOwnedUnit.Applicable_Tax__c = standardSalestax.Id;
		customerOwnedUnit.Unit_Type__c = 'ORDU';
        customerOwnedUnit.Status__c = 'On Order';
		customerOwnedUnit.Unit_Id__c = '';
		customerOwnedUnit.Vendor__c = vendor.Id ;
        insert customerOwnedUnit;
        
        Unit_Price_Cost__c unitPriceAndCostBase = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnit.Id, Type__c = 'Base', 
        	Item_Description__c ='Test',Total_Price__c = 2000, Cost__c = 2500, Total_Cost__c = 2500, Qty__c = 1, Price__c = 2000);
        Unit_Price_Cost__c unitPriceAndCostBase1 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnit.Id, Type__c = 'Base', 
        	Item_Description__c ='Test',Total_Price__c = 2000, Cost__c = 2500, Total_Cost__c = 300, Qty__c = 1, Price__c = 2000);
        Unit_Price_Cost__c unitPriceAndCostBaseFact = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnit.Id, Type__c = 'Factory', 
        	Item_Description__c ='Test',Total_Price__c = 2000, Cost__c = 800, Total_Cost__c = 800, Qty__c = 1, Price__c = 2000);
        Unit_Price_Cost__c unitPriceAndCostBaseFact1 = new Unit_Price_Cost__c(Customer_Owned_Unit__c = customerOwnedUnit.Id, Type__c = 'Factory', 
        	Item_Description__c ='Test',Total_Price__c = 2000, Cost__c = 2500, Total_Cost__c = 300, Qty__c = 1, Price__c = 2000);
        	
        insert new List<Unit_Price_Cost__c>{unitPriceAndCostBase, unitPriceAndCostBase1, unitPriceAndCostBaseFact, unitPriceAndCostBaseFact1};
        
        List<Customer_Owned_Unit__c> unitList = [Select Id, Total_Cost__c, Tax_Amount__c from Customer_Owned_Unit__c where Id=: customerOwnedUnit.Id];
        system.assertEquals(1, unitList.size());
        system.assertEquals(3900, unitList[0].Total_Cost__c);
        system.assertEquals(773.5, unitList[0].Tax_Amount__c);
    }
}