src/objects/Accounting_Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Blackpurl_Balance__c</fullName>
	    <inlineHelpText>Balance in blackpurl</inlineHelpText>
	    <label>Blackpurl Balance</label>
	    <precision>18</precision>
	    <scale>2</scale>
	    <type>Currency</type>
    </fields>
    <fields>
	    <fullName>GL_Account_Name__c</fullName>
	    <label>GL Account Name</label>
	    <length>255</length>
	    <type>Text</type>
    </fields>
    <fields>
        <fullName>GL_Balance__c</fullName>
	    <inlineHelpText>Balance in GL</inlineHelpText>
	    <label>GL Balance</label>
	    <precision>18</precision>
	    <scale>2</scale>
	    <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_BP_records__c</fullName>
	    <label>Number of BP records</label>
	    <precision>18</precision>
	    <scale>0</scale>
	    <type>Number</type>
    </fields>
    <fields>
        <fullName>Reconciliation_Date__c</fullName>
	    <label>Reconciliation Date</label>
	    <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
	    <inlineHelpText>Reconciliation account type</inlineHelpText>
	    <label>Type</label>
	    <type>Picklist</type>
	    <valueSet>
	        <valueSetDefinition>
	            <value>
	                <fullName>Parts</fullName>
	            </value>
	            <value>
	                <fullName>Units</fullName>
	            </value>
	            <value>
	                <fullName>Deposits</fullName>
	            </value>
	            <value>
	                <fullName>WIP Labor</fullName>
	            </value>
	            <value>
	                <fullName>AP Inventory</fullName>
	            </value>
	            <value>
	                <fullName>Store credit</fullName>
	            </value>
	            <value>
	                <fullName>Stocked Trade</fullName>
	            </value>
	            <value>
	                <fullName>Deal Option</fullName>
	            </value>
	            <value>
	                <fullName>Deductible</fullName>
	            </value>
	        </valueSetDefinition>
	    </valueSet>
    </fields>
    <fields>
	    <fullName>Variance__c</fullName>
	    <formula>Blackpurl_Balance__c - GL_Balance__c</formula>
	    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
	    <label>Variance</label>
	    <precision>18</precision>
	    <scale>2</scale>
	    <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variance_Change__c</fullName>
        <description>Variance for current date minus variance from previous date.</description>
        <inlineHelpText>Variance for current date minus variance from previous date.</inlineHelpText>
        <label>Variance Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Accounting Reconciliation</label>
    <nameField>
        <displayFormat>AREC-{00000000}</displayFormat>
        <label>Accounting Reconciliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountingReconciliationWrapper.cls
/**
 * Author: Nidhi Sharma
 * Since: August 24, 2022
 * Name: AccountingReconciliationWrapper
**/
public class AccountingReconciliationWrapper {
    
    public String ReconciliationDateTime;
    public String RecordLink;
    public String Type;
    public String GLName;
    public Decimal BPRecords;
    public Decimal BPBalance;
    public Decimal GLBalance;
    public Decimal Variance;
    public Decimal VarianceChange;

    public AccountingReconciliationWrapper(Accounting_Reconciliation__c accReconcilicationRec) {
        if(accReconcilicationRec != null) {
            this.RecordLink = System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + accReconcilicationRec.Id;
            this.ReconciliationDateTime = accReconcilicationRec.Reconciliation_Date__c != null ? BPUtility.getFormatedDateAndTime(accReconcilicationRec.Reconciliation_Date__c) : '';
            this.Type = accReconcilicationRec.Type__c != null ? accReconcilicationRec.Type__c : '';
            this.GLName = accReconcilicationRec.GL_Account_Name__c != null ? accReconcilicationRec.GL_Account_Name__c : '';
            this.BPRecords = accReconcilicationRec.Number_of_BP_records__c;
            this.BPBalance = accReconcilicationRec.Blackpurl_Balance__c;
            this.GLBalance = accReconcilicationRec.GL_Balance__c;
            this.Variance = accReconcilicationRec.Variance__c;
            this.VarianceChange = accReconcilicationRec.Variance_Change__c != null ? accReconcilicationRec.Variance_Change__c : 0;
        }
    }
}