src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Active__c , &apos;Active&apos;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
				<value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Internal Expense</fullName>
                </value>
                <value>
                    <fullName>Labour</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Part</fullName>
                </value>
                <value>
                    <fullName>Vendor Product</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Trade-in</fullName>
                </value>
                <value>
                    <fullName>Stamp Duty</fullName>
                </value>
                <value>
                    <fullName>Deductible</fullName>
                </value>
                <value>
                    <fullName>Stocked Trade</fullName>
                </value>
                <value>
                    <fullName>Lien Payout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_Shopify_Integration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enabling will expose elements on the front end side for setup purposes while leaving the actual integration inactive.</description>
        <inlineHelpText>Enabling will expose elements on the front end side for setup purposes while leaving the actual integration inactive.</inlineHelpText>
        <label>Enable Shopify Integration</label>
        <type>Checkbox</type>
	</fields>
    <label>General Configurations</label>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Part</description>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Qty_On_Order__c &gt; 0,&apos;On Order&apos;,  IF( OR((Qty_In_Stock__c &lt; Auto_reorder_Min__c),( AND((Qty_In_Stock__c = Auto_reorder_Min__c),( Auto_reorder_Min__c !=  Auto_reorder_Max__c )))), &apos;Required&apos;, IF(Qty_In_Stock__c &gt; 0, &apos;In Stock&apos;,&apos;Out of Stock&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shopify_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Shopify integration related info</description>
    <fields>
        <fullName>Website_Title__c</fullName>
        <label>Website Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Shopify Configuration</label>
</CustomObject>

src/objects/Tag__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tag</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Tag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Website_Product__c.object
<CustomObject>
    <fields>
        <fullName>Delete_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to inform that related Website product is not deleted but user did delete product action from Blackpurl</description>
        <inlineHelpText>Checkbox to inform that related Website product is not deleted but user did delete product action from Blackpurl</inlineHelpText>
        <label>Delete Pending?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Option_Value_1__c</fullName>
        <description>Variant Option Value 1</description>
        <inlineHelpText>Variant Option Value 1</inlineHelpText>
        <label>Option Value 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linked Blackpurl Part</description>
        <inlineHelpText>Linked Blackpurl Part</inlineHelpText>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Website Products</relationshipLabel>
        <relationshipName>Website_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <description>Website product Id</description>
        <inlineHelpText>Website product Id</inlineHelpText>
        <label>Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Vendor__c</fullName>
        <description>Website product vendor name</description>
        <inlineHelpText>Website product vendor name</inlineHelpText>
        <label>Product Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Product status</description>
        <inlineHelpText>Product status</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Linked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ignored</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syncing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Product title. All variants should have same product title.</description>
        <inlineHelpText>Product title. All variants should have same product title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Website Product</label>
    <nameField>
        <displayFormat>WP-{00000000}</displayFormat>
        <label>Website Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Website Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WebsiteProductManagementTest.cls
@isTest
public without sharing class WebsiteProductManagementTest {
    
    @TestSetup
    private static void createSampleData() {
        TestDataFactory.disableFLSChecks();
        
        General_Configurations__c generalConfig = General_Configurations__c.getOrgDefaults();
    	generalConfig.Enable_Shopify_Integration__c = true;
    	upsert generalConfig;
        
        TestUtil.activateShopifyIntegration();
        TestUtil.createShopifyConfiguration();
        
        IFW_IntegrationConfig__c IFWConfigObj = TestUtil.createIFWConfigsForShopify();
        List<IFW_IntegrationConfig__c> IFWConfigObjList = [SELECT Id FROM IFW_IntegrationConfig__c];
        TestUtil.createIFWConfigItemForShopify('Token' , IFWConfigObjList[0].Id, 'POST');
        TestUtil.createIFWConfigItemForShopify('Product' , IFWConfigObjList[0].Id, 'GET');
        
        Account vendor = TestUtil.createVendor(true, 'Vendor');
        Tag__c tag = TestDataFactory.createTag('New Tag');
        Category__c testCategory = TestUtil.createCategory(false, 'Test Category');
        testCategory.Type__c = 'Part';
        insert testCategory;
        
        Part__c part = TestUtil.createPart(true, '123', vendor.Id, 'Part', testCategory.Id, 10, 20, 50, 100, 100);
        Website_Product__c websiteProduct = TestUtil.createWebsiteProduct(true, part.Id, vendor.Name);
    }

    @isTest
    public static void getAllProductsTest() {
        Website_Product__c websiteProductRec = [SELECT Id, Title__c, Product_Vendor__c, Status__c FROM Website_Product__c Order BY Title__c ASC LIMIT 1];
        Datetime dateTimeWhenSearch = Datetime.now().addDays(12);
        Test.startTest();
        String productJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.getAllProducts(BPUtility.getEncodedString('{"StartIndex":0,"RecordCount":10,"SearchKeyword":"'+ websiteProductRec.Title__c +'","ProductVendorList":["'+ websiteProductRec.Product_Vendor__c +'"],"StatusList":["'+ websiteProductRec.Status__c +'"],"DateTimeWhenSearchExecuted":"'+ dateTimeWhenSearch +'"}')));
        Test.stopTest();
        List<WebsiteProductWrapper> productList = (List<WebsiteProductWrapper>) System.JSON.deserialize(productJSON, List<WebsiteProductWrapper>.class);
        system.assertEquals(1, productList.size());
    }

    @isTest
    public static void getProductStaticsTest() {
        Website_Product__c websiteProductRec = [SELECT Id, Title__c, Product_Vendor__c, Status__c FROM Website_Product__c Order BY Title__c ASC LIMIT 1];
        Test.startTest();
        String productStaticsJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.getProductStatics(BPUtility.getEncodedString('{"SearchKeyword":"'+ websiteProductRec.Title__c +'","ProductVendorList":["'+ websiteProductRec.Product_Vendor__c +'"],"StatusList":["'+ websiteProductRec.Status__c +'"]}')));
        Test.stopTest();
        Map<String, String> productStaticsMap = (Map<String, String>) JSON.deserialize(productStaticsJSON, Map<String, String>.class);
        String ProductCount = productStaticsMap.get('ProductCount');
        system.assertEquals('1', ProductCount);
    }

    @isTest
    public static void getWebsiteInfoTest() {
        Test.startTest();
        String websiteInfoJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.getWebsiteInfo());
        WebsiteInfoWrapper WebsiteInfoObj = (WebsiteInfoWrapper) System.JSON.deserialize(websiteInfoJSON, WebsiteInfoWrapper.class);
        Test.stopTest();
        System.assertEquals(Shopify_Configuration__c.getOrgDefaults().Website_Title__c, WebsiteInfoObj.Title);
    }

    @isTest
    public static void searchPartWithFiltersTest() {
        Test.startTest();
        String searchPartJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.searchPartWithFilters(BPUtility.getEncodedString('{"SearchText":"test","SearchableObjects":"Part__c","FilterValues":[]}')));
        Test.stopTest();
        List<SearchSuggestionJSON.ResultJSON> searchPartList = (List<SearchSuggestionJSON.ResultJSON>) System.JSON.deserialize(searchPartJSON, List<SearchSuggestionJSON.ResultJSON>.class);
        system.assertEquals(0, searchPartList.size());
    }

    @isTest
    public static void saveProductAndVariantsTest() { 
        Website_Product__c websiteProductRec = [SELECT Id FROM Website_Product__c ORDER BY Title__c ASC LIMIT 1];
        Part__c partRec = [SELECT Id, Part_Number__c, Description__c FROM Part__c ORDER BY Part_Number__c ASC LIMIT 1];
        Test.startTest();
        WebsiteProductManagementCtrl.saveProductAndVariants(BPUtility.getEncodedString('{"Title":"Test Title 1","ProductId":"112","VariantOptionList":[{"Label1":"Color","Label2":"Size","Label3":"Gender","Value1":"Red","Value2":"M","Value3":"Female"}]}'));
        Test.stopTest();
        List<Website_Product__c> websiteProductList = [SELECT Id FROM Website_Product__c ORDER BY Title__c ASC];
        System.assertEquals(2, websiteProductList.size());
    }

    @isTest
    public static void deleteProductVariantTest() {
        Test.setMock(HttpCalloutMock.class, new WebsiteProductMockResponseGenerator());
        Website_Product__c websiteProductRec = [SELECT Id FROM Website_Product__c ORDER BY Title__c ASC LIMIT 1];
        Test.startTest();
        WebsiteProductManagementCtrl.deleteProductVariant(BPUtility.getEncodedString(websiteProductRec.Id));
        Test.stopTest();
        List<Website_Product__c> websiteProductList = [SELECT Id, Delete_Pending__c FROM Website_Product__c Where Id =: websiteProductRec.Id ORDER BY Title__c ASC];
        if(websiteProductList.size() != 0) {
            System.assertEquals(true, websiteProductList[0].Delete_Pending__c);
        }
    }

    @isTest
    public static void getProductVendorTest() {
        Test.startTest();
        String productVendorJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.getProductVendor(BPUtility.getEncodedString('Vend')));
        Test.stopTest();
        List<String> productVendorList = (List<String>) System.JSON.deserialize(productVendorJSON, List<String>.class);
        system.assertEquals(1, productVendorList.size());
    }

    @isTest
    public static void pollProductsFromWebsiteTest() {
        Test.setMock(HttpCalloutMock.class, new WebsiteProductMockResponseGenerator());
        Test.startTest();
        WebsiteProductManagementCtrl.pollProductsFromWebsite();
        Test.stopTest();
        List<Website_Product__c> websiteProductList = [SELECT Id FROM Website_Product__c ORDER BY Title__c ASC];
        System.assertEquals(2, websiteProductList.size());
    }

    @isTest
    public static void isPollingInProgressTest() {
        Test.startTest();
        Boolean isPollingInProgress = WebsiteProductManagementCtrl.isPollingInProgress();
        Test.stopTest();
        System.assertEquals(false, isPollingInProgress);
    }

    @isTest
    public static void getProductVariantsByProductIdTest() {
        Website_Product__c websiteProductRec = [SELECT Id, Product_Id__c, Option_Value_1__c FROM Website_Product__c ORDER BY Title__c ASC LIMIT 1];
        Test.startTest();
        String productVariantJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.getProductVariantsByProductId(BPUtility.getEncodedString(websiteProductRec.Product_Id__c)));
        Test.stopTest();
        WebsiteProductVariantWrapper productVariant = (WebsiteProductVariantWrapper) System.JSON.deserialize(productVariantJSON, WebsiteProductVariantWrapper.Class);
        System.assertEquals(websiteProductRec.Option_Value_1__c, productVariant.VariantOptionList[0].Value1);
    }

    @isTest
    public static void searchBPVendorsTest() {
        Account Vendor = [SELECT Id, Name FROM Account LIMIT 1];
        Test.startTest();
        String BPVendorsJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.searchBPVendors(BPUtility.getEncodedString(Vendor.Name)));
        Test.stopTest();
        List<Vendor> BPVendorList = (List<Vendor>) System.JSON.deserialize(BPVendorsJSON, List<Vendor>.Class);
        system.assertEquals(1, BPVendorList.size());
    }

    @isTest
    public static void searchTagsTest() {
        Tag__c tag = [SELECT Id, Name__c FROM Tag__c LIMIT 1];
        Test.startTest();
        String tagJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.searchTags(BPUtility.getEncodedString(tag.Name__c)));
        Test.stopTest();
        List<TagWrapper> tagList = (List<TagWrapper>) System.JSON.deserialize(tagJSON, List<TagWrapper>.Class);
        system.assertEquals(1, tagList.size());
    }

    @isTest
    public static void searchCategoriesTest() {
        Category__c category = [SELECT Id, Name FROM Category__c LIMIT 1];
        Test.startTest();
        String categoryJSON = BPUtility.getDecodedString(WebsiteProductManagementCtrl.searchCategories(BPUtility.getEncodedString(category.Name)));
        Test.stopTest();
        List<CategoryService.CategoryWrapper> categoryList = (List<CategoryService.CategoryWrapper>) System.JSON.deserialize(categoryJSON, List<CategoryService.CategoryWrapper>.Class);
        system.assertEquals(1, categoryList.size());
    }

    @isTest
    public static void saveProductsTest() {
        Website_Product__c websiteProductRec = [SELECT Id FROM Website_Product__c ORDER BY Title__c ASC LIMIT 1];
        Part__c partRec = [SELECT Id, Part_Number__c, Description__c FROM Part__c ORDER BY Part_Number__c ASC LIMIT 1];
        Test.startTest();
        WebsiteProductManagementCtrl.saveProducts(BPUtility.getEncodedString('[{"Title":"Test Title 1","ProductId":"112","Status":"New","IsIgnored":true,"VariantOptions":"Red,M,Female","ProductVendor":"Hero","PartId":"'+ partRec.Id +'","PartCodeDesc":"'+ partRec.Part_Number__c + ' - ' + partRec.Description__c +'","OptionLabel1":"Color","OptionLabel2":"Size","OptionLabel3":"Gender","OptionValue1":"Red","OptionValue2":"M","OptionValue3":"Female"}]'));
        Test.stopTest();
        List<Website_Product__c> websiteProductList = [SELECT Id FROM Website_Product__c ORDER BY Title__c ASC];
        System.assertEquals(2, websiteProductList.size());
    }
}