src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General customer notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Return_CR_Header__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Memo__c</fullName>
        <label>Credit Memo#</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credited_Date__c</fullName>
        <label>Credited Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item_Total__c</fullName>
        <label>Item Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Charges_Total__c</fullName>
        <label>Other Charges Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Credited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Return CR Headers</relationshipLabel>
        <relationshipName>Return_CR_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Return CR Header</label>
    <nameField>
        <displayFormat>RTNCR-{00000000}</displayFormat>
        <label>Return CR Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return CR Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Return_CR_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Return_CR_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Return CR Header</label>
        <referenceTo>Return_CR_Header__c</referenceTo>
        <relationshipLabel>Return CR Line Items</relationshipLabel>
        <relationshipName>Return_CR_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Return CR Line Item</label>
    <nameField>
        <displayFormat>RTNCRLI-{00000000}</displayFormat>
        <label>Return CR Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return CR Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Return_VO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Memo__c</fullName>
        <label>Credit Memo#</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credited_Date__c</fullName>
        <label>Credited Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA#</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Total__c</fullName>
        <formula>SubTotal__c +  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Return Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Field to indicate why they are returning the parts.</description>
        <inlineHelpText>Field to indicate why they are returning the parts.</inlineHelpText>
        <label>Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Returned_Date__c</fullName>
        <label>Returned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Credited</fullName>
                </value>
                <value>
                    <fullName>Partially Credited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <description>Indicates a tracking number.</description>
        <inlineHelpText>Indicates a tracking number.</inlineHelpText>
        <label>Tracking#</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Return VO Headers</relationshipLabel>
        <relationshipName>Return_VO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Return VO Header</label>
    <nameField>
        <displayFormat>RTN-{00000000}</displayFormat>
        <label>Return VO Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return VO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Return_VO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Return_CR_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Return CR Line Item</label>
        <referenceTo>Return_CR_Line_Item__c</referenceTo>
        <relationshipLabel>Return VO Line Items</relationshipLabel>
        <relationshipName>Return_VO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Return_VO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Return VO Header</label>
        <referenceTo>Return_VO_Header__c</referenceTo>
        <relationshipLabel>Return VO Line Items</relationshipLabel>
        <relationshipName>Return_VO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Return VO Line Item</label>
    <nameField>
        <displayFormat>RVOLI-{00000000}</displayFormat>
        <label>Return VO Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return VO Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReturnVOService.cls
/** 
 * Author: Richa Mittal
 * Since: Nov 08, 2023
 * Name: ReturnVOService 
 * Description: service class which contains all methods related to Return VO Ctrl.
**/
public without sharing class ReturnVOService {
    
    public static String getActiveRVOCountByVendorId(String vendorId) {
    	String query = 'SELECT Count(Id) RVOCount FROM Return_VO_Header__c WHERE Vendor__c = \''+ BPUtility.escapeSingleQuotes(vendorId) + '\' AND Status__c = \'In Progress\'';
    	List<AggregateResult> aggList = SOQLUtility.getQueryResults('Return_VO_Header__c', query);
    	return String.valueOf((aggList.size() > 0) ? (Integer) aggList[0].get('RVOCount') : 0);
    }

    public static GlobalSearchResultsWrapper getActiveReturnVendorOrdersByVendorId(String filterJson) {
        GlobalSearchResultsWrapper.COOpenOrderFilterJSON filterObj = (GlobalSearchResultsWrapper.COOpenOrderFilterJSON) System.JSON.deserialize(filterJson, 
                                                                        GlobalSearchResultsWrapper.COOpenOrderFilterJSON.class);
        
        String query = 'SELECT Name, Vendor__r.Name, Reason__c, Return_Total__c, LastModifiedDate, RMA__c, Status__c FROM Return_VO_Header__c WHERE Vendor__c = \'' + BPUtility.escapeSingleQuotes(filterObj.VendorId) + 
            			'\' AND Status__c = \'In Progress\' ORDER BY Name Desc ' + 
            			SOQLUtility.getLimitClause(filterObj.StartIndex, filterObj.RecordCount);

        if(AccessControl.ifObjectFieldIsAccessible('Return_VO_Header__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<Return_VO_Header__c> rvoHeaderList = Database.query(query);
        return new GlobalSearchResultsWrapper(rvoHeaderList.size(), rvoHeaderList);
    }

    public static List<ReturnVOHeaderWrapper.ReturnCreditHistoryWrapper> getCreditHistory(String rvoId) {
        Set<String> rcrIdList = new Set<String>();
        for(Return_VO_Line_Item__c rvoliRec: [SELECT Return_CR_Line_Item__r.Return_CR_Header__c FROM Return_VO_Line_Item__c WHERE Return_VO_Header__c = :rvoId]) {
            rcrIdList.add(rvoliRec.Return_CR_Line_Item__r.Return_CR_Header__c);
        }
        List<ReturnVOHeaderWrapper.ReturnCreditHistoryWrapper> historyObjList = new List<ReturnVOHeaderWrapper.ReturnCreditHistoryWrapper>();
        List<Return_CR_Header__c> rcrHeaderList = [SELECT Status__c, Credited_Date__c, Credit_Memo__c, Owner.Name, Item_Total__c, Name, 
                                                    Other_Charges_Total__c, (SELECT Id FROM Return_CR_Line_Items__r) FROM Return_CR_Header__c 
                                                    WHERE Id IN :rcrIdList];

        for(Return_CR_Header__c rcrRec: rcrHeaderList) {
            historyObjList.add(new ReturnVOHeaderWrapper.ReturnCreditHistoryWrapper(rcrRec));
        }
        return historyObjList;
    }

    public static Map<String, String> rvoWrapperKeyToAPINameMap = new Map<String, String>{
                                                                                          'ReturnedDate' => 'Returned_Date__c',
                                                                                          'Reason' => 'Reason__c',
                                                                                          'TrackingNumber' => 'Tracking_Number__c',
                                                                                          'RMANumber' => 'RMA__c',
                                                                                          'Notes' => 'Notes__c'
                                                                                        };
}