src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>Customer AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Store_Credit__c.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Customer__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Credits</relationshipLabel>
        <relationshipName>Store_Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Store Credit</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Store Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccSync_StoreCreditJE_Batch_SchTest.cls
/**
 * Author: Rajat Jain
 * Since: June 5, 2018
 * Name: AccSync_StoreCreditJE_Batch_SchTest
 * Description: test Class for AccSync_StoreCreditJE_Batch_SchTest.
**/

@isTest
public without sharing class AccSync_StoreCreditJE_Batch_SchTest {
    static String CRON_EXP = '0 0 0 * * ? *';
    
    @testSetup
    static void setup() {
        TestUtil.setQuickBooksConfigurations(true);
        Account testCustomer = TestUtil.createCustomer(false, 'Test Customer', 'a.b@gmail.com', 'Jaipur', '987456123');
    	testCustomer.Is_Customer__c = true;
    	insert testCustomer;
    	Store_Credit__c storeCreditObj = new Store_Credit__c();
		storeCreditObj.Customer__c = testCustomer.Id;
		storeCreditObj.Amount__c = 100;
		storeCreditObj.Reference__c = 'Ref1';
        insert storeCreditObj;
        system.assertEquals(true, String.isNotBlank(testCustomer.Id));
    }
   
    static testmethod void accSync_ItemCategoryTest() {
        Test.startTest();
        TestUtil.setQuickBooksConfigurations(false);
        Map<Id, Store_Credit__c> storeCreditIdToRecMap = new Map<Id, Store_Credit__c>([Select Id, AccountingId__c FROM Store_Credit__c]);
        
        AccSync_StoreCreditJE_Batch_Scheduler storeCreditSchObj = new AccSync_StoreCreditJE_Batch_Scheduler(storeCreditIdToRecMap.keySet(), 10);
        //system.schedule('AccSync_StoreCreditJE_Batch_Scheduler', CRON_EXP, storeCreditSchObj);
        storeCreditSchObj.execute(null);
        Test.stopTest();
        system.assertEquals('675',[Select AccountingId__c From Store_Credit__c][0].AccountingId__c ); 
    }
}