src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Vendor_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Vendor Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_Xero_Accounting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Xero Accounting</label>
        <type>Checkbox</type>
    </fields>    
    <label>General Configurations</label>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountingVendorBatchSchedulerTest.cls
/**
 * Author: Nikhil Kumar Srivastava
 * Since: April 16, 2019
 * Name: AccountingVendorBatchSchedulerTest
 * Description: test Class for AccountingVendorBatchScheduler.
**/

@isTest
public without sharing  class AccountingVendorBatchSchedulerTest {

    @testSetup
    private static void setupTestData() { 
        TestDataFactory.disableFLSChecks();
        TestUtil.createIFWConfigForXero();
        insert new General_Configurations__c(Enable_Xero_Accounting__c = true);
        List<IFW_IntegrationConfig__c> IFWConfigObj = [Select Id from IFW_IntegrationConfig__c];
        IFW_IntegrationConfigItem__c IFWConfigItemObj = TestUtil.createIFWConfigItemForXero('Contacts' , IFWConfigObj[0].Id);
        //Disable Trigger to stop syncing the record
        Trigger_Soft_Disable__c triggerToDisable = new Trigger_Soft_Disable__c();
        triggerToDisable.Name = 'CustomerTrigger';
        triggerToDisable.Disable_Delete__c = triggerToDisable.Disable_Insert__c = triggerToDisable.Disable_Undelete__c = true;
        triggerToDisable.Disable_Update__c = true;
        insert triggerToDisable;
        Account vendorObj = TestUtil.createVendor(false, 'Xero Vendor');
        vendorObj.Available_For_Xero_Vendor_Sync__c = true;
        insert vendorObj;
        delete triggerToDisable;
        system.assertEquals(true, String.isNotBlank(vendorObj.Id));
    }
    
    static testmethod void AccountingCustomerBatchSchedulerTest() { 
        List<Account> accList = [Select Id,Is_Vendor__c from Account where Is_Vendor__c = true Limit 1];
        system.assertEquals(1,accList.size());
        system.assertEquals(true,accList[0].Is_Vendor__c);
        Test.setMock(HttpCalloutMock.class, new Xero_MockHttpResponseGenerator());
        test.startTest();
        XeroScriptUtil.syncVendors(25,120,25);
        test.stopTest();
     }
}