src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>availForQBSync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer availForQBSync</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QB_SyncCustomerBatchTest.cls
@isTest
global without sharing class QB_SyncCustomerBatchTest {
    @testSetup
    private static void setupTestData() {
        TestDataFactory.disableFLSChecks();
        TestUtil.setQuickBooksConfigurations(false);
        List<customHttpHeaderWrapper> headerList = new List<customHttpHeaderWrapper>();
        customHttpHeaderWrapper header = new customHttpHeaderWrapper('Content-Type', 'applications/json');
        headerList.add(header);
    }

    static testMethod void customerPayload(){
        Test.startTest();
        List<IFW_IntegrationConfig__c> IFWConfigObj = [Select Id from IFW_IntegrationConfig__c];
		IFW_IntegrationConfigItem__c IFWConfigItemObj = TestUtil.createIFWConfigItemForQB('Customer' , IFWConfigObj[0].Id);
        Account customer =  TestDataFactory.createCustomer('Test Customer', 'Individual', 'Test', 'Customer');
        Account customerRec = [Select FirstName__c From Account];
        customerRec.FirstName__c = 'Namarta';
        update customerRec;
        Test.setMock(HttpCalloutMock.class, new QB_MockHttpResponseGenerator());
   		Test.stopTest();
        String query = 'SELECT availForQBSync__c FROM Account'; 
        Account cust = Database.query(query);
        System.assertEquals(cust.availForQBSync__c, false);   
    }

}