src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Calculate_Part_Retail_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Calculate Part Retail Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retail_Base_Value__c</fullName>
        <defaultValue>&quot;MSRP&quot;</defaultValue>
        <label>Retail Base Value</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSRP</fullName>
                </value>
                <value>
                    <fullName>Item Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retail_Round_To__c</fullName>
        <defaultValue>95</defaultValue>
        <label>Retail Round To</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retail_Rounding__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retail Rounding</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Escalator__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MSRP</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Escalators</relationshipLabel>
        <relationshipName>Escalators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Escalator</label>
    <nameField>
        <displayFormat>ESC-{00000000}</displayFormat>
        <label>Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EscalatorSOQLUtil.cls
/**
 * Author: Richa Mittal
 * Since: May 10, 2022
 * Name: EscalatorSOQLUtil
 * Description: EscalatorSOQLUtil class.
**/
public without sharing class EscalatorSOQLUtil {
    
    public static List<Escalator__c> getEscalatorsForVendors(Set<String> vendorIdSet) {
        String query = 'SELECT ' + String.join(Escalator.getFieldList(), ',');
        query += ' FROM Escalator__c WHERE Vendor__c IN :vendorIdSet AND Type__c = \'' + EscalatorUtil.TYPE_RETAIL + '\'';
        if(!AccessControl.ifObjectFieldIsAccessible('Escalator__c')) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query);
    }

    public static Map<Id, Account> getVendorWithEscalators(Set<Id> vendorIdSet) {
        String query = 'SELECT Id, Retail_Base_Value__c, Retail_Rounding__c, Retail_Round_To__c,';
        query += ' (SELECT ' + String.join(Escalator.getFieldList(), ',');
        query += ' FROM Escalators__r WHERE Type__c = \'' + EscalatorUtil.TYPE_RETAIL + '\')';
        query += ' FROM Account WHERE Id IN :vendorIdSet AND Is_Calculate_Part_Retail_Price__c = true';
        if(!AccessControl.ifObjectFieldIsAccessible('Escalator__c')) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        if(!AccessControl.ifObjectFieldIsAccessible('Account')) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return new Map<Id, Account>((List<Account>)Database.query(query));
    }
}