src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Price_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Level</label>
        <referenceTo>Price_Level__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fee__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Category__c.Type__c</field>
                <operation>equals</operation>
                <value>Labour</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Linked_Fee__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Fee</description>
        <label>Fee</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Linked Fees</relationshipLabel>
        <relationshipName>Linked_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Linked Fee</label>
    <nameField>
        <displayFormat>LF-{00000000}</displayFormat>
        <label>Linked Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Linked Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price_Level__c.object
<CustomObject>
    <label>Price Level</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Group__c.object
<CustomObject>
    <description>This object have children -user ( all  user govern by groups on them )</description>
    <fields>
        <fullName>Service_job__c</fullName>
        <label>Service job</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Group</label>
    <nameField>
        <label>User group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_To_Group__c.object
<CustomObject>
    <fields>
        <fullName>User_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Group</label>
        <referenceTo>User_Group__c</referenceTo>
        <relationshipLabel>User To Groups</relationshipLabel>
        <relationshipName>User_To_Groups1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_To_Groups1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User To Group</label>
    <nameField>
        <displayFormat>UG - {0000}</displayFormat>
        <label>User To Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User To Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LinkedFeeControllerTest.cls
@isTest
private class LinkedFeeControllerTest {

    private static void setupTestData() {
        TestUtil.createNameSpaceInGeneralConfig();
    }
    
    
    static testMethod void getLinkedFeeListTest() {
        Account vendor = TestUtil.createVendor(true, 'Test Vendor');
        Category__c testCategory = TestUtil.createCategory(true, 'Test Category');
        Price_Level__c defaultPriceLevel = TestUtil.createPriceLevel(true, 'Default Price Level', 'MSRP', 10 , true, true);
        Sales_Tax__c defaultSalesTax = TestUtil.createSalesTax(true, 'Test Sales Tax', true, true, true);
        Part__c part = TestUtil.createPart(true, 'TestPart', vendor.Id, 'TestPart', testCategory.Id, 10, 20, 50, 100, 100);
        Account customer = TestUtil.createCustomer(true, 'customerName', 'abc@abc.com', 'Agra', '1111111112', null, null, false, true,'Individual','firstname1', 'lastname', '9999999999', 'BillingStreet');
        CO_Header__c coHeader = TestUtil.createCOHeader(true, customer.Id);
        Fee__c fee = TestUtil.createFee(True, True, testCategory.Id, 'FeeCode', CoHeader.Id, 'Description', 100, True);
        Linked_Fee__c Linkedfee = TestUtil.createLinkedFee(True, 'Description', Fee.Id, 'Service Job', 200);
        
        
        Test.startTest();
        String LinkedFeeJSON = BPUtility.getDecodedString(LinkedFeeController.getLinkedFeeList(BPUtility.getEncodedString('Service Job')));
        List<LinkedFeeWrapper> linkedFeeDetails = (List<LinkedFeeWrapper>) System.JSON.deserialize(LinkedFeeJSON, List<LinkedFeeWrapper>.class);
        system.assertEquals(linkedFeeDetails[0].RelatedTo, 'Service Job');
        LinkedFeeController.getOverViewDetails();
        String jsonStr = System.Json.serialize(linkedFeeDetails[0]);
        BPUtility.getDecodedString(LinkedFeeController.saveLinkedFee(BPUtility.getEncodedString(jsonStr)));
        String LinkedFeeJSON1 = BPUtility.getDecodedString(LinkedFeeController.getLinkedFeeList(BPUtility.getEncodedString('Service Job')));
        List<LinkedFeeWrapper> linkedFeeDetails1 = (List<LinkedFeeWrapper>) System.JSON.deserialize(LinkedFeeJSON1, List<LinkedFeeWrapper>.class);
    	system.assertEquals(linkedFeeDetails1[0].Price, 200);
    	Test.stopTest();
    	
    	String soHeader = BPUtility.getDecodedString(CustomerOrderCtrl.createSOHeader(BPUtility.getEncodedString(coHeader.Id)));
    	String SOHeaderDetails1 = BPUtility.getDecodedString(CustomerOrderCtrl.getSOHeaderDetails(BPUtility.getEncodedString(coHeader.Id), BPUtility.getEncodedString(null)));
        SOHeaderWrapper soHeaderDetailsObj1 = (SOHeaderWrapper) System.JSON.deserialize(SOHeaderDetails1, SOHeaderWrapper.class);
        system.assertEquals(soHeaderDetailsObj1.SOList[0].SOGridItems[0].SOKH.SOLIList.size(), 1) ;
        BPUtility.getDecodedString(LinkedFeeController.getFeeList());
        
        BPUtility.getDecodedString(LinkedFeeController.deleteLinkedFee(BPUtility.getEncodedString(linkedFee.Id), BPUtility.getEncodedString('Service Job')));
        String LinkedFeeJSON2 = BPUtility.getDecodedString(LinkedFeeController.getLinkedFeeList(BPUtility.getEncodedString('Service Job')));
        List<LinkedFeeWrapper> linkedFeeDetails2 = (List<LinkedFeeWrapper>) System.JSON.deserialize(LinkedFeeJSON2, List<LinkedFeeWrapper>.class);
    	system.assertEquals(linkedFeeDetails2.size(), 0);
    }
    
     static testMethod void permissionUserTest() {
        Account vendor = TestUtil.createVendor(true, 'Test Vendor');
        Category__c testCategory = TestUtil.createCategory(true, 'Test Category');
        Price_Level__c defaultPriceLevel = TestUtil.createPriceLevel(true, 'Default Price Level', 'MSRP', 10 , true, true);
        Sales_Tax__c defaultSalesTax = TestUtil.createSalesTax(true, 'Test Sales Tax', true, true, true);
        Part__c part = TestUtil.createPart(true, 'TestPart', vendor.Id, 'TestPart', testCategory.Id, 10, 20, 50, 100, 100);
        Account customer = TestUtil.createCustomer(true, 'customerName', 'abc@abc.com', 'Agra', '1111111112', null, null, false, true,'Individual','firstname1', 'lastname', '9999999999', 'BillingStreet');
        CO_Header__c coHeader = TestUtil.createCOHeader(true, customer.Id);
        Fee__c fee = TestUtil.createFee(True, True, testCategory.Id, 'FeeCode', CoHeader.Id, 'Description', 100, True);
        Linked_Fee__c Linkedfee = TestUtil.createLinkedFee(True, 'Description', Fee.Id, 'Service Job', 200);
        
        User Defaultuser = TestUtil.createUser(true, 'a@b.com', 'Testing ', 'en_US', 'testUse123r@force.com', 'Test U');
         User_Group__c usergrp = new User_Group__c(); 
         usergrp.Service_job__c = 'Primary'; 
         insert usergrp;
         User_To_Group__c UserAssign = new User_To_Group__c(); 
         UserAssign.User__c = Defaultuser.id;
         UserAssign.User_Group__c = usergrp.Id;
        	Insert UserAssign ;
        	system.runas(DefaultUser)   {

    	String soHeader = BPUtility.getDecodedString(CustomerOrderCtrl.createSOHeader(BPUtility.getEncodedString(coHeader.Id)));
    	String SOHeaderDetails1 = BPUtility.getDecodedString(CustomerOrderCtrl.getSOHeaderDetails(BPUtility.getEncodedString(coHeader.Id), BPUtility.getEncodedString(null)));
        SOHeaderWrapper soHeaderDetailsObj1 = (SOHeaderWrapper) System.JSON.deserialize(SOHeaderDetails1, SOHeaderWrapper.class);
        system.assertEquals(soHeaderDetailsObj1.SOList[0].SOGridItems[0].SOKH.SOLIList.size(), 1) ;
        	}
    	
    }
}