src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>Customer AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <label>Customer AccountingResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <label>Customer SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_AccountingId__c</fullName>
        <label>Vendor AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <description>AccountingId</description>
        <label>QB Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <description>AccountingResponse</description>
        <label>AccountingResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>COGS_GL__c</fullName>
        <label>COGS GL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_GL__c</fullName>
        <label>Income GL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_GL__c</fullName>
        <label>Inventory GL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <description>SyncToken</description>
        <label>SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <label>AccountingResponse</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>AutoNumberHolder__r.Name</formula>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <label>SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Part</description>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_ID__c</fullName>
        <description>Merge of Part Number and Vendor Code</description>
        <formula>Part_Number__c  &amp; Vendor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Merge of Part Number and Vendor Code</inlineHelpText>
        <label>Part ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <description>Used for part category change</description>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part_FIFO_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <label>AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <label>AccountingResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Return__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Return</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_FIFO_Bucket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is FIFO Bucket</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_In__c</fullName>
        <label>Qty In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty_Out__c</fullName>
        <label>Qty Out</label>
        <summarizedField>Part_FIFO_Bucket_Activity_Line_Item__c.Qty_Out__c</summarizedField>
        <summaryForeignKey>Part_FIFO_Bucket_Activity_Line_Item__c.Part_FIFO_Bucket__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <label>SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Cost__c  *  Remaining_Qty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <formula>if(LEN(TEXT(Part_Adjust_Number__c)) == 5, &apos;PA-&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 4, &apos;PA-0&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 3, &apos;PA-00&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 2, &apos;PA-000&apos; &amp;  TEXT(Part_Adjust_Number__c),
  if(LEN(TEXT(Part_Adjust_Number__c)) == 1, &apos;PA-0000&apos; &amp;  TEXT(Part_Adjust_Number__c),&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VRCost__c</fullName>
        <label>VRCost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <formula>if(!ISBLANK(Cost__c)&amp;&amp; !ISBLANK(VRCost__c), VRCost__c - Cost__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoicing_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoicing Header</label>
        <referenceTo>Vendor_Invoicing_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Receiving_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Receiving Header</label>
        <referenceTo>Vendor_Receiving_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Part FIFO Bucket</label>
    <nameField>
        <displayFormat>PBN-{00000000}</displayFormat>
        <label>Part FIFO Bucket  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoicing_Header__c.object
<CustomObject>
    <fields>
        <fullName>AccountingId__c</fullName>
        <description>Accounting Id</description>
        <label>AccountingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountingResponse__c</fullName>
        <description>Accounting Response</description>
        <label>AccountingResponse</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice#</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncToken__c</fullName>
        <description>SyncToken</description>
        <label>SyncToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Number__c</fullName>
        <formula>IF( ISNULL( Invoice_Number__c ) || ISBLANK( Invoice_Number__c ) , Name , Invoice_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Invoice Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoicing Headers</relationshipLabel>
        <relationshipName>Vendor_Invoicing_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vendor Invoicing Header</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Vendor Invoicing Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoicing Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Receiving_Header__c.object
<CustomObject>
    <fields>
        <fullName>Packing_Slip_Number__c</fullName>
        <label>Packing Slip#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Receiving Headers</relationshipLabel>
        <relationshipName>Vendor_Receiving_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <description>Used for Vendor receiving header</description>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vendor Receiving Header</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Receiving Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountingFIFOBucket.cls
/**
 * Author: Richa Mittal
 * Since: Dec 26, 2016
 * Name: AccountingCOInvoicePayment
 * Description: Apex class to handle JSON related oprations of paymrnt of CO Invoice for Accounting.
**/
public without sharing class AccountingFIFOBucket {
    
     public String Id {get; set;}
        
    // SourceName
    public String SourceName {get; set;}
    
    // Reference
    public String Reference {get; set;}
    
    // QtyIn
    public Decimal QtyIn {get; set;}
    
    // QtyOut
    public Decimal QtyOut {get; set;}
    
    // Variance
    public Decimal Variance {get; set;}
    
    // Cost
    public Decimal Cost {get; set;}
    
    // Total
    public Decimal Total {get; set;}
    
    // VRCost
    public Decimal VRCost {get; set;}
    
    // Is FIFO Bucket
    public Boolean IsFIFOBucket {get; set;}
    
    // PartId
    public String PartId;
    
    public String ItemDesc;
    
    public String PartNumber;
    
    // Name
    public String Name;
    
    // Name
    public Date CreatedDate;
    
    public String VendorName;
    
    //EntityRefWrapper
    public EntityRefWrapper EntityRef;
    
    public String COGS_GL;
        
    public String Income_GL;
    
    public String Inventory_GL;
    
    // AccountingId
    public String AccountingId;
    public String XeroAccountingId;
    
    // SyncToken
    public String SyncToken;
    
    public String accountingResponse;
    
    public String UniqueId;
    
    // Constructor
    public AccountingFIFOBucket(Part_FIFO_Bucket__c  partFIFOBucketRec) { 
        this.Id = partFIFOBucketRec.Id;
        this.SourceName = partFIFOBucketRec.Source_Name__c != null ? partFIFOBucketRec.Source_Name__c : '';
        String ref = partFIFOBucketRec.Reference__c != null ? partFIFOBucketRec.Reference__c : '';
        if(!ref.equalsIgnoreCase('Count Adjustment') && !ref.equalsIgnoreCase('Cost Adjustment') && this.SourceName.equalsIgnoreCase('Cost Adjust')) {
        	ref = 'Cost Adjustment';
        }
        this.Reference = ref;
        this.QtyIn = partFIFOBucketRec.Qty_In__c;
        this.QtyOut = partFIFOBucketRec.Qty_Out__c;
        this.Variance = partFIFOBucketRec.Variance__c;
        this.Cost = partFIFOBucketRec.Cost__c;
        this.Total = partFIFOBucketRec.Total__c;
        this.VRCost = partFIFOBucketRec.VRCost__c;
        this.IsFIFOBucket = partFIFOBucketRec.Is_FIFO_Bucket__c;
        this.PartId = partFIFOBucketRec.Part__c;
        this.Name = partFIFOBucketRec.Name;
        this.VendorName = partFIFOBucketRec.Part__r.Vendor__r.Name;
        this.ItemDesc = partFIFOBucketRec.Part__r.Part_Number__c + ' - ' + partFIFOBucketRec.Part__r.Description__c;
        this.PartNumber = partFIFOBucketRec.Part__r.Part_Number__c;
        this.CreatedDate = DateTimeUtility.getDateFromFormattedDateStr(DateTimeUtility.getFormttedDateFromDateTime(partFIFOBucketRec.CreatedDate, 'dd/MM/yyyy'));
        
        this.EntityRef = new EntityRefWrapper(partFIFOBucketRec.Part__r.Vendor__r.Vendor_AccountingId__c, partFIFOBucketRec.Part__r.Vendor__r.Name);
        
        this.COGS_GL = partFIFOBucketRec.Part__r.Category__r.COGS_GL__c;
        this.Income_GL = partFIFOBucketRec.Part__r.Category__r.Income_GL__c;
        this.Inventory_GL = partFIFOBucketRec.Part__r.Category__r.Inventory_GL__c;
        
        this.AccountingId = partFIFOBucketRec.AccountingId__c;
        this.XeroAccountingId = partFIFOBucketRec.Xero_Accounting_Id__c;
        this.SyncToken = partFIFOBucketRec.SyncToken__c;
        this.accountingResponse = partFIFOBucketRec.AccountingResponse__c; 
        
        if(partFIFOBucketRec.Vendor_Invoicing_Header__c!= null){
			this.UniqueId =  partFIFOBucketRec.Vendor_Invoicing_Header__c!= null?partFIFOBucketRec.Vendor_Invoicing_Header__r.Vendor_Invoice_Number__c : null;
		}else if(partFIFOBucketRec.Vendor_Receiving_Header__c != null){
			this.UniqueId =  partFIFOBucketRec.Vendor_Receiving_Header__c!= null?partFIFOBucketRec.Vendor_Receiving_Header__r.Packing_Slip_Number__c : null;
		}else if(partFIFOBucketRec.Customer_Return__c != null){
			this.UniqueId =  (partFIFOBucketRec.Customer_Return__c != null) ? partFIFOBucketRec.Customer_Return__r.Invoice_Number__c : null;
		}else if(partFIFOBucketRec.Source_Name__c.equalsIgnoreCase('Cost Adjust') || partFIFOBucketRec.Source_Name__c.equalsIgnoreCase('Oversold') || partFIFOBucketRec.Source_Name__c.equalsIgnoreCase('Count Adjust') || partFIFOBucketRec.Source_Name__c.equalsIgnoreCase('Stock Count') ){
			this.UniqueId = partFIFOBucketRec.Unique_Id__c;
		}else{
			this.UniqueId = 'Add Part';
		}
    }
    
    
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> partFIFOBucketFields = new List<String>{ 'Id',
                                                        'Name', 
                                                        'Source_Name__c',
                                                        'Reference__c',
                                                        'Qty_In__c',
            											'Qty_Out__c',
            											'Variance__c',
                                                        'Cost__c',
            											'Total__c',
                                                        'VRCost__c',
                                                        'Is_FIFO_Bucket__c',
                                                        'Part__c',
            											'Part__r.Part_Id__c',
            											'Part__r.Part_Number__c',
            											'Part__r.Description__c',
                                                        'Part__r.Vendor__r.Vendor_AccountingId__c',
                                                        'Part__r.Vendor__r.Name',
            											'Part__r.Category__r.COGS_GL__c',
            											'Part__r.Category__r.Income_GL__c',
            											'Part__r.Category__r.Inventory_GL__c',
                                                        'AccountingId__c',
                                                        'SyncToken__c',
                                                        'AccountingResponse__c',
                                                        'CreatedDate',
                                                        'Vendor_Invoicing_Header__c',
                                                        'Vendor_Invoicing_Header__r.Vendor_Invoice_Number__c',
                                                        'Vendor_Receiving_Header__c',
                                                        'Vendor_Receiving_Header__r.Packing_Slip_Number__c',
                                                        'Customer_Return__c',
                                                        'Customer_Return__r.Invoice_Number__c',
                                                        'Unique_Id__c',
                                                        'Xero_Accounting_Id__c'
                                                     };
        return partFIFOBucketFields;
    }
    
    public class AccountRefWrapper{
        public String Id;
        public String Name;
        
        public AccountRefWrapper(String Id, String Name) {
            this.Id = Id;
            this.Name = Name;
        }
    } 
    
    public class EntityRefWrapper{
        public String AccountingId;
        public String Name;
        
        public EntityRefWrapper(String AccountingId, String Name) {
            this.AccountingId = AccountingId;
            this.Name = Name;
        }
    }
}