src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part_Category_Default__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Category Default</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
				<value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Internal Expense</fullName>
                </value>
                <value>
                    <fullName>Labour</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>Part</fullName>
                </value>
                <value>
                    <fullName>Vendor Product</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Trade-in</fullName>
                </value>
                <value>
                    <fullName>Stamp Duty</fullName>
                </value>
                <value>
                    <fullName>Deductible</fullName>
                </value>
                <value>
                    <fullName>Stocked Trade</fullName>
                </value>
                <value>
                    <fullName>Lien Payout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateFieldsOnVendorBatchTest.cls
@isTest
private class PopulateFieldsOnVendorBatchTest {
     @testsetup
     private static void setup(){
     	Category__c categoryRec = TestDataFactory.createCategory('category001');
     	categoryRec.Type__c = 'Part';
     	categoryRec.Default__c = true;
     	update categoryRec;
     	
     	List<Account> vendorList = new List<Account>();
     	for(Integer i = 0; i < 20; i++){
     		vendorList.add(TestDataFactory.sampleVendor('vendor001'));
     	}
     	insert vendorList;
     }
     
     @isTest
     private static void test(){
     	Test.startTest();
     	Id batchId = Database.executeBatch(new PopulateFieldsOnVendorBatch());
     	Test.stopTest();
     	
     	Account vendor = [SELECT Id, Part_Category_Default__c FROM Account WHERE Is_vendor__c = true LIMIT 1];
     	Category__c categoryRec = [SELECT Id FROM Category__c LIMIT 1];
     	system.assertEquals(vendor.Part_Category_Default__c, categoryRec.ID);
     }
}