src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part_Purchases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Part Purchases</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_Type__c</fullName>
        <label>Part Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Part</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Merchandise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PopulatePartTypeFieldOnPartBatchTest.cls
@isTest
private class PopulatePartTypeFieldOnPartBatchTest {
    @testsetup
    private static void setup(){
    	Account vendor = TestDataFactory.createVendor('Test Vendor');
    	Category__c categoryRec = TestDataFactory.createCategory('category001');
    	Part__c part = TestDataFactory.createPart(vendor.Id,  10, 20, 50, 100, 100, categoryRec.Id);
    	part.Part_Type__c = null;
    	update part;
    }
    
    @isTest
    private static void test(){
    	Test.startTest();
    	Id batchId = Database.executeBatch(new PopulatePartTypeFieldOnPartBatch());
    	Test.stopTest();
    	Account vendor = [SELECT Id, Part_Purchases__c FROM Account WHERE Is_Vendor__c = true LIMIT 1];
		system.assertEquals(vendor.Part_Purchases__c, true);	
    }
}