src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Customer_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Customer Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_For_Xero_Vendor_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Vendor Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AR_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>AR Payments</relationshipLabel>
        <relationshipName>AR_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AR Payment</label>
    <nameField>
        <displayFormat>ARP-{00000000}</displayFormat>
        <label>AR Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for CO Deposit</description>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Deposit</label>
    <nameField>
        <displayFormat>CODN-{00000000}</displayFormat>
        <label>CO Deposits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_CO_Invoice_JE_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero CO Invoice JE Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_For_Xero_Invoice_Payment_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Invoice Payment Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Invoice_Status__c )</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CO Invoice Payment</label>
    <nameField>
        <displayFormat>COIP-{00000000}</displayFormat>
        <label>CO Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Count_Session__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>

    <label>Count Session</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Count Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Count Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_For_Xero_Unit_Invoice_JE_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Unit Invoice JE Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hours_Logged__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Hours Logged</label>
    <nameField>
        <displayFormat>HN-{00000000}</displayFormat>
        <label>Hours Logged Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hours Logged</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Part_FIFO_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Return__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Return</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_FIFO_Bucket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is FIFO Bucket</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Name__c</fullName>
        <label>Source Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Receiving_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Receiving Header</label>
        <referenceTo>Vendor_Receiving_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Part FIFO Bucket</label>
    <nameField>
        <displayFormat>PBN-{00000000}</displayFormat>
        <label>Part FIFO Bucket  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Part_FIFO_Bucket_Activity_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_FIFO_Bucket__c</fullName>
        <label>Part FIFO Bucket</label>
        <referenceTo>Part_FIFO_Bucket__c</referenceTo>
        <relationshipLabel>Part FIFO Bucket Activity Line Items</relationshipLabel>
        <relationshipName>Part_FIFO_Bucket_Activity_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part FIFO Bucket Activity Line Item</label>
    <nameField>
        <displayFormat>PBNLI-{00000000}</displayFormat>
        <label>Part FIFO Bucket Activity Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Bucket Activity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Return_VO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <description>Not in use</description>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Not in use</inlineHelpText>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Return VO Header</label>
    <nameField>
        <displayFormat>RTN-{00000000}</displayFormat>
        <label>Return VO Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return VO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Store_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Store Credits</relationshipLabel>
        <relationshipName>Store_Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Store Credit</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Store Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Co Invoice Header</description>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit lookup with Customer Owned Unit</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoicing_Header__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Invoicing Header</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Vendor Invoicing Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoicing Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Receiving_Header__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_Xero_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for Vendor Receiving</description>
        <label>Available For Xero Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Receiving Header</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Receiving Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XeroScriptUtil.cls
/**
 * Author: Nikhil Kumar Srivastava
 * Since: April 04, 2019
 * Name: XeroScriptUtil
 * Description: Apex class for all scripts related to Xero
**/
global class XeroScriptUtil {
	
	public static Map<String, String> entityNameToSyncingEntityNameMap = new Map<String, String> {
	    'CO Invoice' => IntegrationUtility.INVOICE,
	    'FIFO Buckets' => IntegrationUtility.PART_FIFO,
	    'FIFO Buckets Line Items' => IntegrationUtility.PART_FIFO_BUCKET_ACTIVITY_LINE_ITEM,
	    'VR JE' => IntegrationUtility.VENDOR_RECEIVING,
	    'Vendor Return' => IntegrationUtility.VO_RETURN,
	    'Vendor Invoice' => IntegrationUtility.VO_INVOICE,
        'Store Credit' => IntegrationUtility.STORE_CREDIT,
        'Hours Logged' => IntegrationUtility.HOURS_LOGGED,
        'Unit NITC JE' => IntegrationUtility.UNIT_NITC_JE,
        'Unit Consignment' => IntegrationUtility.UNIT_CONSIGNMENT
    };
    
	public static void scheduleJobs(List<sObject> recordList, Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec, Integer batchSize,
                                            String entityType) { 
        scheduleJobs(recordList, maxNumberOfRecord, timeIntervalForJobsInSec, batchSize, entityType, 0);
    }

    public static void scheduleJobs(List<sObject> recordList, Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec, Integer batchSize,
                                            String entityType, Integer schedulerInterval) {
        for(Integer i = 0; i < Math.ceil(recordList.size() / Decimal.valueOf(maxNumberOfRecord)) && i < 99; i++) {
            String cronExp = QBUtil.getCronExpForGivenTime(schedulerInterval + 10 + (i * timeIntervalForJobsInSec));
            Set<Id> recordIdSet = new Set<Id>();
            for(Integer j = (i * maxNumberOfRecord); (j < ((i + 1) * maxNumberOfRecord) && j < recordList.size()); j++) {
                recordIdSet.add(recordList[j].Id);
            }
            system.debug('Record Id Set for Scheduling ' + (i + 1) + '  ' + recordIdSet);
            
            if(entityType == IntegrationUtility.CUSTOMER) {
                QBUtil.abortAlreadyScheduleJobs('Xero Customer Sync ' + i);
                system.schedule('Xero Customer Sync ' + i, cronExp, new AccountingCustomerBatchScheduler(recordIdSet, batchSize));
            } else if(entityType == IntegrationUtility.VENDOR) {
                QBUtil.abortAlreadyScheduleJobs('Xero Vendor Sync ' + i);
                system.schedule('Xero Vendor Sync ' + i, cronExp, new AccountingVendorBatchScheduler(recordIdSet, batchSize));
            } else if(entityType == IntegrationUtility.UNIT_INVOICE) {
                QBUtil.abortAlreadyScheduleJobs('Xero Unit Invoice Sync ' + i);
                system.schedule('Xero Unit Invoice Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.UNIT_INVOICE));
            } else if(entityType == IntegrationUtility.CO_DEPOSIT) {
                QBUtil.abortAlreadyScheduleJobs('Xero CO Deposit Sync ' + i);
                system.schedule('Xero CO Deposit Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.CO_DEPOSIT));
            } else if(entityType == IntegrationUtility.CO_INVOICE_PAYMENT) {
                QBUtil.abortAlreadyScheduleJobs('Xero CO Payment JE Sync ' + i);
                system.schedule('Xero CO Payment JE Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.CO_INVOICE_PAYMENT));
            } else if(entityType == IntegrationUtility.CO_INVOICE_JE) {
                QBUtil.abortAlreadyScheduleJobs('Xero CO Invoice JE Sync ' + i);
                system.schedule('Xero CO Invoice JE Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.CO_INVOICE_JE));
            } else if(entityType == IntegrationUtility.UNIT_INVOICE_JE) {
                QBUtil.abortAlreadyScheduleJobs('Xero Unit Invoice JE Sync ' + i);
                system.schedule('Xero Unit Invoice JE Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.UNIT_INVOICE_JE));
            } else if(entityType == IntegrationUtility.COUNT_SESSION_JE) {
                QBUtil.abortAlreadyScheduleJobs('Xero Count Session JE Sync ' + i);
                system.schedule('Xero Count Session JE Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.COUNT_SESSION_JE));
            } else if(entityType == IntegrationUtility.AR_Payment) {
                QBUtil.abortAlreadyScheduleJobs('AR Payment Sync ' + i);
                system.schedule('AR Payment Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.AR_Payment));
            } else if(entityType == IntegrationUtility.UNIT_PRICE_COST) {
                QBUtil.abortAlreadyScheduleJobs('Xero Unit Adjustment Sync ' + i);
                system.schedule('Xero Unit Adjustment Sync ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.UNIT_PRICE_COST));
            } else if(entityType == 'CO Invoice JE Update') {
                QBUtil.abortAlreadyScheduleJobs('Xero CO Invoice JE Update ' + i);
                system.schedule('Xero CO Invoice JE Update ' + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, IntegrationUtility.CO_INVOICE_JE, true));       
            } else {
                String scheduleJobName = 'Xero ' + entityType + ' Sync ';
                QBUtil.abortAlreadyScheduleJobs(scheduleJobName + i);
                if(entityType == IntegrationUtility.INVOICE) {
                    system.schedule(scheduleJobName + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, 
                        entityType, new List<String>{IntegrationUtility.INVOICE, IntegrationUtility.CO_INVOICE_JE, IntegrationUtility.INVOICE_PAYMENT}));                    
                } else {
                    system.schedule(scheduleJobName + i, cronExp, new AccountingBatchScheduler(recordIdSet, batchSize, entityType));
                }
            }
        }
   }             
            
    global static void syncCustomers(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec, Integer batchSize) {
        List<Account> customerList = [Select Id from Account where Is_Customer__c = true AND Available_For_Xero_Customer_Sync__c = true
                                            Order by CreatedDate DESC];
        scheduleJobs(customerList, maxNumberOfRecord, timeIntervalForJobsInSec, batchSize, IntegrationUtility.CUSTOMER, 0);
    }       
    
    global static void syncVendors(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec, Integer batchSize) {
        List<Account> vendorList = [Select Id from Account where Is_Vendor__c = true AND Available_For_Xero_Vendor_Sync__c = true 
                                            Order by CreatedDate ASC];
        scheduleJobs(vendorList, maxNumberOfRecord, timeIntervalForJobsInSec, batchSize, IntegrationUtility.VENDOR, 0);
    } 
    
    global static void syncUnitInvoice(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Customer_Owned_Unit__c> unitList = 
            [SELECT Id FROM Customer_Owned_Unit__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(unitList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.UNIT_INVOICE, 0);
    }
    
    global static void syncCODeposit(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<CO_Deposit__c> coDepositList = 
            [SELECT Id FROM CO_Deposit__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(coDepositList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.CO_DEPOSIT, 0);
    }
    
    global static void syncCOInvoicePaymentJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<CO_Invoice_Payment__c> coInvoicePaymentList = 
            [SELECT Id FROM CO_Invoice_Payment__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(coInvoicePaymentList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.CO_INVOICE_PAYMENT, 0);
    }
    
    global static void syncCOInvoiceJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<CO_Invoice_Header__c> coInvoiceHeaderList = 
            [SELECT Id FROM CO_Invoice_Header__c where Available_For_Xero_CO_Invoice_JE_Sync__c = true Order by CreatedDate ASC];
        system.debug('RecOrds' + coInvoiceHeaderList);
        scheduleJobs(coInvoiceHeaderList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.CO_INVOICE_JE, 0);
    }
    global static void updateCOInvoiceJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<CO_Invoice_Header__c> coInvoiceHeaderList = 
            [SELECT Id FROM CO_Invoice_Header__c where Available_For_Xero_CO_Invoice_JE_Sync__c = true Order by CreatedDate ASC ];
            scheduleJobs(coInvoiceHeaderList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, 'CO Invoice JE Update', 0);
    }
    global static void syncUnitInvoiceJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Customer_Owned_Unit__c> unitList = 
            [SELECT Id FROM Customer_Owned_Unit__c where Available_For_Xero_Unit_Invoice_JE_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(unitList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.UNIT_INVOICE_JE, 0);
    }
    
    global static void syncCountSessionJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Count_Session__c> countSessionList = 
            [SELECT Id FROM Count_Session__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC]; 
        scheduleJobs(countSessionList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.COUNT_SESSION_JE, 0);
    }
    
    global static void syncARPayments(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<AR_Payment__c> arPaymentList = 
            [SELECT Id FROM AR_Payment__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC]; 
        scheduleJobs(arPaymentList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.AR_Payment, 0);
    }
    
    global static void syncUnitAdjustments(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Unit_Price_Cost__c> unitPriceAndCostList = 
            [SELECT Id FROM Unit_Price_Cost__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(unitPriceAndCostList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.UNIT_PRICE_COST, 0);
    }
    
    global static void syncCOInvoice(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<CO_Invoice_Header__c> coInvoiceHeaderList = 
            [SELECT Id FROM CO_Invoice_Header__c WHERE Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(coInvoiceHeaderList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.INVOICE, 0);
    }
    
    global static void syncCOInvoicePayment(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<CO_Invoice_Header__c> coInvoiceHeaderList = 
            [SELECT Id FROM CO_Invoice_Header__c WHERE Available_For_Xero_Invoice_Payment_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(coInvoiceHeaderList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.INVOICE_PAYMENT, 0);
    }
    
    global static void syncFIFOBuckets(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Part_FIFO_Bucket__c> FIFOBucketsList = 
            [SELECT Id FROM Part_FIFO_Bucket__c WHERE Available_For_Xero_Sync__c = true AND Is_FIFO_Bucket__c = true AND Vendor_Receiving_Header__c = null 
                    AND Customer_Return__c = null AND Source_Name__c != 'Oversold' Order by CreatedDate ASC];
        scheduleJobs(FIFOBucketsList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.PART_FIFO, 0);
    }
    
    global static void syncFIFOBucketLineItems(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Part_FIFO_Bucket_Activity_Line_Item__c> FIFOBucketLineItemsList = 
            [SELECT Id FROM Part_FIFO_Bucket_Activity_Line_Item__c where Available_For_Xero_Sync__c = true AND 
                    Part_FIFO_Bucket__r.Is_FIFO_Bucket__c = true AND CO_Invoice_Header__c = null Order by CreatedDate ASC];
        scheduleJobs(FIFOBucketLineItemsList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.PART_FIFO_BUCKET_ACTIVITY_LINE_ITEM, 0);
    }
    
    global static void syncVRJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Vendor_Receiving_Header__c> vrhList = 
            [SELECT Id FROM Vendor_Receiving_Header__c where Available_For_Xero_Sync__c = true AND 
                (Status__c = 'Stocked' OR Status__c = 'Invoiced') Order by CreatedDate ASC];
        scheduleJobs(vrhList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.VENDOR_RECEIVING, 0);
    }
    
    global static void syncVendorReturn(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Return_VO_Header__c> vendorReturnList = [SELECT Id FROM Return_VO_Header__c where Available_For_Xero_Sync__c = true 
                                                        AND Status__c = 'Credited' Order by CreatedDate ASC];
        scheduleJobs(vendorReturnList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.VO_RETURN, 0);
    }
    
    global static void syncVendorInvoices(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Vendor_Invoicing_Header__c> vendorInvoiceList = 
                        [SELECT Id FROM Vendor_Invoicing_Header__c WHERE Status__c = 'Invoiced' AND Available_For_Xero_Sync__c = true 
                            Order by CreatedDate ASC];
        scheduleJobs(vendorInvoiceList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.VO_INVOICE, 0);
    }
    
    global static void syncStoreCredits(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Store_Credit__c> storeCreditList = [SELECT Id FROM Store_Credit__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(storeCreditList, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.STORE_CREDIT, 0);
    }
    
    global static void syncHoursLogged(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Hours_Logged__c> hoursLogged = [SELECT Id FROM Hours_Logged__c where Available_For_Xero_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(hoursLogged, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.HOURS_LOGGED, 0);
    }
    
    global static void syncUnitNITCJE(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Customer_Owned_Unit__c> hoursLogged = [SELECT Id FROM Customer_Owned_Unit__c where Available_For_Xero_NITC_JE_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(hoursLogged, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, IntegrationUtility.UNIT_NITC_JE, 0);
    }
    
    global static void syncConsignmentUnit(Integer maxNumberOfRecord, Integer timeIntervalForJobsInSec) {
        List<Customer_Owned_Unit__c> hoursLogged = [SELECT Id FROM Customer_Owned_Unit__c where Available_For_Xero_Consignment_Sync__c = true Order by CreatedDate ASC];
        scheduleJobs(hoursLogged, maxNumberOfRecord, timeIntervalForJobsInSec, maxNumberOfRecord, 'Unit Consignment');
    }
}