src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Email__c</fullName>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Work_Email__c</fullName>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Xero_Customer_Accounting_Id__c</fullName>
        <label>Xero Customer Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Vendor_Accounting_Id__c</fullName>
        <label>Xero Vendor Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <fields>
        <fullName>Accounting_Enabled__c</fullName>
        <formula>IF(
	Integration_Name__c == &apos;Xero&apos;,
	$Setup.General_Configurations__c.Enable_Xero_Accounting__c,
	IF(
		Integration_Name__c == &apos;QuickBooks Online&apos;,
		 $Setup.QuickBooks_Configurations__c.Enable_QuickBooks__c,
		Enabled__c
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accounting Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auth_Scheme__c</fullName>
        <label>Auth Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bearer_Token__c</fullName>
        <label>Bearer Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certifcate_Password__c</fullName>
        <label>Certifcate Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <label>Certificate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Id__c</fullName>
        <label>Company Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <label>Integration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Timeout value in Ms</description>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Token_Expiry__c</fullName>
        <description>Token lifetime in seconds</description>
        <label>Token Expiry</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Token_Type__c</fullName>
        <label>Token Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>URL of the resource you will access</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Item</fullName>
                </value>
                <value>
                    <fullName>Journal Entry</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Organisation</fullName>
                </value>
				<value>
                    <fullName>Tax Rate</fullName>
                </value>
                <value>
                    <fullName>GetPartLocator</fullName>
                </value>
				<value>
                    <fullName>GetVehicleSpecification</fullName>
                </value>
                <value>
                    <fullName>GetDealer</fullName>
                </value>
                <value>
                    <fullName>Honda Part Inventory</fullName>
                </value>
                <value>
                    <fullName>Honda All Vendor Invoices</fullName>
                </value>
                <value>
                    <fullName>Honda Vendor Invoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartsInvoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartInventory</fullName>
                </value>
                <value>
                    <fullName>BRPRepairOrder</fullName>
                </value>
                <value>
                    <fullName>BRPRetailDeliveryReporting</fullName>
                </value>
                <value>
                    <fullName>Upsert Product</fullName>
                </value>
                <value>
                    <fullName>Payment Terminal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HTTP_Method__c</fullName>
        <label>HTTP Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Override parent Timeout if set</description>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MapCustomesAndVendorsFromBPToXero.cls
/** 
* Author: Richa Mittal
* Since: Feb 22, 2021
* Name: MapCustomesAndVendorsFromBPToXero 
* Description: Batch class for fetching contacts from xero and map to BP customer/vendor if exists and set accounting Id
**/
global without sharing class MapCustomesAndVendorsFromBPToXero implements Database.Batchable<Integer>, Database.AllowsCallouts, Database.Stateful {
    
    public Integer APICounter = 1;
    public Boolean recordFound = false;
    public IFW_IntegrationConfig__c ifwRec;
    
    global MapCustomesAndVendorsFromBPToXero() {
    
    }
    
    global MapCustomesAndVendorsFromBPToXero(Integer APICounter) {
        this.APICounter = APICounter;
    }
    
    global Iterable<Integer> start(Database.BatchableContext bc) {
        return new List<Integer>{APICounter};
    }
    
    global void execute(Database.batchableContext bc, List<Integer> apiCountList) {
    	if(ifwRec == null) {
    		List<IFW_IntegrationConfig__c> ifwConfigRec = [SELECT Id, Access_Token__c, Auth_Scheme__c, Bearer_Token__c, Certificate_Name__c, Certifcate_Password__c, Consumer_Key__c, 
											                  Consumer_Secret__c, Accounting_Enabled__c, Integration_Name__c, Grant_Type__c, Password__c, Username__c, Refresh_Token__c, Timeout__c, 
											                  Token_Expiry__c, Token_Type__c, Integration_Type__c, Client_Id__c, Client_Secret__c, Company_Id__c, 
	    													(Select IFW_IntegrationConfig__c, Endpoint_URL__c, HTTP_Method__c, Timeout__c FROM IFW_IntegrationConfigItems__r WHERE 
	    														HTTP_Method__c = 'GET' AND Entity_Name__c = 'Contacts') 
	    													FROM IFW_IntegrationConfig__c WHERE Integration_Name__c = 'Xero' AND Accounting_Enabled__c = true];
			
			if(ifwConfigRec.size() > 0 && ifwConfigRec[0].IFW_IntegrationConfigItems__r.size() > 0) {
				ifwRec = ifwConfigRec[0];
			}
    	}
    	if(ifwRec == null) {
    		new LogService().createErrorLog('MapCustomesAndVendorsFromBPToXero', 'execute()', 'Xero config not defined', '', null, 
                                          null, LogService.XERO);
            return;
    	}
        
        XeroResponseWrapper responseWrapper = getContactsFromXero(APICounter);
        if(responseWrapper != null && responseWrapper.Contacts != null && responseWrapper.Contacts.size() > 0) {
        	recordFound = true;
        	updateXeroAccIdInBP(responseWrapper);
        }
    }
    
    global void finish(Database.batchableContext bc) {
        APICounter++;
        if(recordFound) {
            Database.executeBatch(new MapCustomesAndVendorsFromBPToXero(APICounter));
        }
    }
    
    private XeroResponseWrapper getContactsFromXero(Integer APICounter) {
    	XeroResponseWrapper responseWrapper;
        Map<String, String> urlParamMap = new Map<String, String>{'page' => String.valueOf(APICounter)};
        HttpResponse response = BaseIntegration.performCallout(ifwRec, ifwRec.IFW_IntegrationConfigItems__r[0], null, new List<CustomHttpHeaderWrapper>(), urlParamMap);
        
        update ifwRec;
        
        if(response.getStatusCode() == 200 || response.getStatusCode() == 201) {
            responseWrapper = (XeroResponseWrapper)System.JSON.deserialize(response.getBody(), XeroResponseWrapper.class);
        } else {
        	new LogService().createErrorLog('MapCustomesAndVendorsFromBPToXero', 'getContactsFromXero()', response.getBody(), response.getStatusCode(), null, 
                                      null, LogService.XERO);
        }
        return responseWrapper;
    }
    
    private void updateXeroAccIdInBP(XeroResponseWrapper responseWrapper) {
    	Map<String, XeroContactDTO> contactNameToXeroContactRecMap = new Map<String, XeroContactDTO>();
        for(XeroContactDTO xeroContactRec : responseWrapper.Contacts) {
            contactNameToXeroContactRecMap.put((xeroContactRec.Name).toLowerCase(), xeroContactRec);
        }
        
        if(contactNameToXeroContactRecMap.size() > 0) {
        	List<Account> accList = [SELECT Id, Name, Email__c, Other_Email__c, Work_Email__c, Is_Customer__c, Is_Vendor__c FROM Account 
        								WHERE ((Is_Customer__c = true AND Xero_Customer_Accounting_Id__c = null) OR 
        								(Is_Vendor__c = true AND Xero_Vendor_Accounting_Id__c = null)) AND (Name IN :contactNameToXeroContactRecMap.keySet())];
        	
        	Map<String, List<Account>> fullNameToListOfCustomers = new Map<String, List<Account>>();
        	Map<String, List<Account>> fullNameToListOfVendors = new Map<String, List<Account>>();
        	for(Account accRec: accList) {
        		String accName = (accRec.Name).toLowerCase();
        		if(accRec.Is_Customer__c) {
        			if(!fullNameToListOfCustomers.containsKey(accName)) {
        				fullNameToListOfCustomers.put(accName, new List<Account>());
        			}
        			fullNameToListOfCustomers.get(accName).add(accRec);
        		} else if(accRec.Is_Vendor__c) {
        			if(!fullNameToListOfVendors.containsKey(accName)) {
        				fullNameToListOfVendors.put(accName, new List<Account>());
        			}
        			fullNameToListOfVendors.get(accName).add(accRec);
        		}
        	}
        	
        	List<Account> accListToUpdate = new List<Account>();
    		accListToUpdate.addAll(mapContactFromXero('Customer', fullNameToListOfCustomers, contactNameToXeroContactRecMap));
    		accListToUpdate.addAll(mapContactFromXero('Vendor', fullNameToListOfVendors, contactNameToXeroContactRecMap));
    		if(accListToUpdate.size() > 0) {
	    		update accListToUpdate;
	    	}
        }
    }
    
    private List<Account> mapContactFromXero(String accType, Map<String, List<Account>> nameToListOfAccRecs, Map<String, XeroContactDTO> contactNameToXeroContactRecMap) {
    	List<Account> accListToUpdate = new List<Account>();
    	for(String name: nameToListOfAccRecs.keySet()) {
    		if(contactNameToXeroContactRecMap.containsKey(name)) {
    			XeroContactDTO xeroContactRec = contactNameToXeroContactRecMap.get(name);
    			if((accType == 'Customer' && (xeroContactRec.IsCustomer || !xeroContactRec.IsSupplier)) 
    				|| (accType == 'Vendor' && (xeroContactRec.IsSupplier || !xeroContactRec.IsCustomer))) {
    				if(nameToListOfAccRecs.get(name).size() == 1) {
    					if(accType == 'Customer') {
    						accListToUpdate.add(new Account(Id = nameToListOfAccRecs.get(name)[0].Id,
    													Xero_Customer_Accounting_Id__c = xeroContactRec.ContactID));
    					} else if(accType == 'Vendor') {
    						accListToUpdate.add(new Account(Id = nameToListOfAccRecs.get(name)[0].Id,
        													Xero_Vendor_Accounting_Id__c = xeroContactRec.ContactID));
    					}
	    			} else {
	    				List<String> matchedAccIdList = new List<String>();
	    				for(Account accRec: nameToListOfAccRecs.get(name)) {
	    					Set<String> emailStrSet = new Set<String>();
        					if(accType == 'Customer' && String.isNotBlank(nameToListOfAccRecs.get(name)[0].Email__c)) {
        						emailStrSet.add(nameToListOfAccRecs.get(name)[0].Email__c);	
        					}
        					if(String.isNotBlank(nameToListOfAccRecs.get(name)[0].Other_Email__c)) {
        						emailStrSet.add(nameToListOfAccRecs.get(name)[0].Other_Email__c);	
        					}
        					if(String.isNotBlank(nameToListOfAccRecs.get(name)[0].Work_Email__c)) {
        						emailStrSet.add(nameToListOfAccRecs.get(name)[0].Work_Email__c);	
        					}
        					
        					if(String.isBlank(xeroContactRec.EmailAddress) && emailStrSet.size() == 0) {
        						matchedAccIdList.add(accRec.Id);
        					} else if(String.isNotBlank(xeroContactRec.EmailAddress) && emailStrSet.contains(xeroContactRec.EmailAddress)) {
        						matchedAccIdList.add(accRec.Id);
        					}
	    				}
	    				if(matchedAccIdList.size() == 1) {
	    					if(accType == 'Customer') {
	    						accListToUpdate.add(new Account(Id = matchedAccIdList[0],
    													Xero_Customer_Accounting_Id__c = xeroContactRec.ContactID));
	    					} else if(accType == 'Vendor') {
	    						accListToUpdate.add(new Account(Id = matchedAccIdList[0],
    													Xero_Vendor_Accounting_Id__c = xeroContactRec.ContactID));
	    					}
	    				}
    				}
    			}
    		}
    	}
    	return accListToUpdate;
    }
    
    public class XeroResponseWrapper {
        public List<XeroContactDTO>  Contacts;
    }
    
    public class XeroContactDTO {
        public String Name;
	    public String ContactID;
	    public String EmailAddress;
	    public Boolean IsCustomer;
	    public Boolean IsSupplier;
    }
}