src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General customer notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Active__c = TRUE, &apos;Active&apos; , &apos;InActive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Related_List_Page_Size__c</fullName>
        <defaultValue>10</defaultValue>
        <inlineHelpText>Number of records to be displayed in related list at a time</inlineHelpText>
        <label>Related List Page Size</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>General Configurations</label>
</CustomObject>

src/objects/In_Progress_VR__c.object
<CustomObject>
    <fields>
        <fullName>Vendor_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Order Header</label>
        <referenceTo>Vendor_Order_Header__c</referenceTo>
        <relationshipLabel>In Progress VRs</relationshipLabel>
        <relationshipName>In_Progress_VRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Receiving_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Receiving Header</label>
        <referenceTo>Vendor_Receiving_Header__c</referenceTo>
        <relationshipLabel>In Progress VRs</relationshipLabel>
        <relationshipName>In_Progress_VRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>In_Progress_VRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <label>In Progress VR</label>
    <nameField>
        <displayFormat>IPVR-{00000000}</displayFormat>
        <label>In Progress VR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>In Progress VRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PO_Type__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Current_Cost__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update Current Cost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PO_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PO_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <label>Purchase Order Type</label>
    <nameField>
        <displayFormat>POT-{0000000}</displayFormat>
        <label>PO Type Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Header__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Date_Formula__c</fullName>
        <formula>IF(  ISBLANK(Expected_Date__c) ,   TODAY() +  Purchase_Order_Type__r.Lead_Time__c  ,  IF( AND(ISPICKVAL(Status__c, &apos;Open&apos;), (Expected_Date__c - TODAY()) &lt; 0) , TODAY() +  Purchase_Order_Type__r.Lead_Time__c, Expected_Date__c) )</formula>
        <label>Expected Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Date__c</fullName>
        <label>Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Progress_VR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Vendor Order Receiving which is using the record</inlineHelpText>
        <label>In Progress VR</label>
        <referenceTo>Vendor_Receiving_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Headers</relationshipLabel>
        <relationshipName>Vendor_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vendor_Order_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General unit notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ordered_Date__c</fullName>
        <label>Ordered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vendor_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order Type</label>
        <referenceTo>PO_Type__c</referenceTo>
        <relationshipLabel>Vendor Order Headers</relationshipLabel>
        <relationshipName>Vendor_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Partially Received</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Recieved__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Recieved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Order Headers</relationshipLabel>
        <relationshipName>Vendor_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Header</label>
    <nameField>
        <displayFormat>VO-{00000000}</displayFormat>
        <label>Vendor Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Line_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vendor_Order_Line_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Received_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Received Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unreceived_Qty__c</fullName>
        <formula>Need__c - Received_Qty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unreceived Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Order Header</label>
        <referenceTo>Vendor_Order_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Line Item Groups</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Line Item Group</label>
    <nameField>
        <displayFormat>VOG-{00000000}</displayFormat>
        <label>Vendor Order Line Item Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Line Item Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Receiving_Header__c.object
<CustomObject>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vendor_Receiving_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <label>Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Vendor Receiving Header Owners</relationshipLabel>
        <relationshipName>Vendor_Receiving_Header_Owners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Stocked</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Receiving Headers</relationshipLabel>
        <relationshipName>Vendor_Receiving_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Receiving Header</label>
    <nameField>
        <displayFormat>VR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Receiving Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VendorOrderHeader.cls
/**
 * Author: Tarun Khandelwal
 * Since: July 22, 2015
 * Name: VendorOrderHeader
 * Description: Apex class to handle JSON related oprations of VO Header object.
**/
public without sharing class VendorOrderHeader implements Comparable{
    public String VOName;
    
    public String VendorName;
    
    public String VendorId;
    
    public String OwnerId;
    
    public String OwnerName;
    
    public String Status;
    
    public String Notes;
    
    public OrderTypeWrapper OrderType;
    
    public String OrderedDate;
    
    public String ExpectedDate;
    
    public String ReceivedDate;
    
    public String CreatedDate;
    
    // Variables required in Vendor Order Receiving page
    public String InProgressVR;
    public String InProgressVRId;
    public decimal QtyUnreceived;
    public List<VendorOrderLineItemGroup> VOLIGroups;
    public String Id;
    
    public Decimal PercentRecieved;
    public Decimal QtyReceived;
    public Decimal QtyNeeded;
    public String HondaDealerNumber;
    public Boolean IsVOAssociatedWithBRPVendor;
	public String BRPStatus;
    
	public String LastModifiedDate;
	public String CreatedBy;
	public String LastModifiedBy;
	public Decimal TotalReceived;

    // Constructor
    public VendorOrderHeader(Id voHeaderId) {
    	List<Vendor_Order_Header__c> voHeaders = SOQLUtil.getVendorOrderHeaderRecords('Id', voHeaderId, null, false);
		if(voHeaders.size() > 0){
			this.populateVendorOrder(voHeaders[0]);
			this.IsVOAssociatedWithBRPVendor = BRPUtility.isPartsMasterVendor(voHeaders[0].Vendor__c);
		}
    }
    
    // Constructor
    public VendorOrderHeader(Vendor_Order_Header__c voHeader) {
		this.populateVendorOrder(voHeader);
    }
    
    private void populateVendorOrder(Vendor_Order_Header__c voHeader){
    	this.Id = voHeader.Id;
    	VOName = voHeader.Name;
		VendorName = voHeader.Vendor__r.Name;
		VendorId = voHeader.Vendor__c;
		OwnerName = voHeader.Owner.Name;
		OwnerId = voHeader.OwnerId;
		Status = voHeader.Status__c;
		OrderType = new OrderTypeWrapper(voHeader.Purchase_Order_Type__c, voHeader.Purchase_Order_Type__r.Code__c, voHeader.Purchase_Order_Type__r.Lead_Time__c, voHeader.Purchase_Order_Type__r.Update_Current_Cost__c);
		Notes = voHeader.Notes__c;
		if(voHeader.Ordered_Date__c != null) {
			OrderedDate = BPUtility.getFormatedDateTime(datetime.newInstance(voHeader.Ordered_Date__c.year(), voHeader.Ordered_Date__c.month(),voHeader.Ordered_Date__c.day()));
		}
		if(voHeader.Expected_Date_Formula__c != null) {
			ExpectedDate = BPUtility.getFormatedDateTime(datetime.newInstance(voHeader.Expected_Date_Formula__c.year(), voHeader.Expected_Date_Formula__c.month(),voHeader.Expected_Date_Formula__c.day()));
		}
		if(voHeader.Received_Date__c != null) {
			ReceivedDate = BPUtility.getFormatedDateTime(datetime.newInstance(voHeader.Received_Date__c.year(), voHeader.Received_Date__c.month(),voHeader.Received_Date__c.day()));
		}
		CreatedDate = BPUtility.getFormatedDateTime(voHeader.CreatedDate);
		LastModifiedDate = BPUtility.getLastModifiedDateStr(voHeader);
		CreatedBy = voHeader.CreatedBy.Name != null ? voHeader.CreatedBy.Name : '';
		LastModifiedBy = BPUtility.getLastModifiedBy(voHeader);
		
		// Variables required in Vendor Order Receiving page
		for(In_Progress_VR__c inProgressVRRec : voHeader.In_Progress_VRs__r) {
			//system.assert(false, inProgressVRRec);
			InProgressVR = inProgressVRRec.Vendor_Receiving_Header__r.Name;
			InProgressVRId = inProgressVRRec.Vendor_Receiving_Header__c;
		}
		this.HondaDealerNumber = HondaUtility.getDealerNumber();
		this.TotalReceived = voHeader.Total_Recieved__c;
    }
    
    /**
     * Name: populateVendorOrderGroups
     * Desc: Method to populate vendor order groups records for this vendor header
     * @param:  (1) voHeader - Vendor_Order_Header__c 
     * @return: 
    **/
    public void populateVendorOrderGroups(Vendor_Order_Header__c voHeader){
    	QtyUnreceived = 0;
    	QtyReceived = 0;
    	VOLIGroups = new List<VendorOrderLineItemGroup>();
    	for(Vendor_Order_Line_Item_Group__c voliG : voHeader.Vendor_Order_Line_Item_Groups__r){
    		VendorOrderLineItemGroup voliGroup = new VendorOrderLineItemGroup(voliG, this);
    		QtyUnreceived += voliG.Unreceived_Qty__c;
    		QtyReceived += voliG.Received_Qty__c;
    		VOLIGroups.add(voliGroup);
    	}
    	if(QtyUnreceived < 0) {
    		QtyUnreceived = 0;
    		PercentRecieved =100;
    	} else {
    		PercentRecieved = (QtyReceived == 0) 
    						  ? 0
    						  : (QtyReceived / (QtyReceived + QtyUnreceived)) * 100;
    	}
    	
    	system.debug('QtyReceived  ' + QtyReceived  + '\nQtyUnreceived' + QtyUnreceived + '\nPercentRecieved ' + PercentRecieved);
    }
    
    /**
     * Name: parse
     * Desc: Method to Parse JSON String to class instance
     * @param:  (1) JSONString - String - JSON String 
     * @return: VendorOrderHeader - Class Object
    **/
    public static VendorOrderHeader parse(String json) {
        return (VendorOrderHeader) System.JSON.deserialize(json, VendorOrderHeader.class);
    }
    
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> voHeaderFieldsList = new List<String>{	'Id', 
        													'Vendor__c',
        													'Vendor__r.Name', 
        													'Status__c',
        													'Notes__c',
        													'Received_Date__c', 
        													'Purchase_Order_Type__c',
        													'Purchase_Order_Type__r.Code__c',
        													'Purchase_Order_Type__r.Lead_Time__c',
															'Purchase_Order_Type__r.Update_Current_Cost__c', 
        													'Owner__c', 
        													'Ordered_Date__c', 
        													'Expected_Date__c', 
        													'Expected_Date_Formula__c', 
        													'CreatedDate',
        													'Name',
        													'Owner.Name',
        													'Owner.Id',
        													'In_Progress_VR__c',
        													'In_Progress_VR__r.Name',
															'LastModifiedDate',
															'Last_Modified_Date__c',
															'CreatedBy.Name',
															'LastModifiedBy.Name',
															'Last_Modified_By__r.Name',
															'Total_Recieved__c'
        												};
        return voHeaderFieldsList;
    }
    
    /**
     * Name: getPaginatedRecords
     * Desc: Method to paginate entity records list
     * @param:  
     * @return:
    **/
    public static List<VendorOrderHeader> getPaginatedRecords(List<VendorOrderHeader> allrecords, Integer currentPage, integer pageSize) {
    	List<VendorOrderHeader> objRecords = new List<VendorOrderHeader>();
    	if(currentPage == null || currentPage == 0){
    		currentPage = 1;
    	}
    	if(pageSize == null || pageSize == 0){
    		pageSize = (Integer) General_Configurations__c.getInstance().Related_List_Page_Size__c;
    	}
    	
    	for(Integer i = (currentPage * pageSize - pageSize); i < (currentPage * pageSize); i++){
    		if(allrecords.size() > i){
    			objRecords.add(allrecords.get(i));
    		}
    	}
    	return objRecords;
    }
    
    /**
     * Name: compareTo
     * Desc: Overrided Method to sort the collection to move all those vendor orders in last which are already part of any other vendor receiving records
     * @param:  
     * @return:
    **/
    public Integer compareTo(object compareTo){
        VendorOrderHeader compareToObj = ((VendorOrderHeader)compareTo);
        Integer returnVal = 0;
        					
		if(this.InProgressVRId == compareToObj.InProgressVRId && (this.InProgressVRId != null && compareToObj.InProgressVRId != null)){
			returnVal = (this.VOName == compareToObj.VOName)
						? 0
						:(
							(VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'ASC')
							?	((this.VOName < compareToObj.VOName) ? -1 : 1)
							:	(VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'DESC')
								?	((this.VOName < compareToObj.VOName) ? 1 : -1)
								:	0
						);
        } else if(this.InProgressVRId == null && compareToObj.InProgressVRId == null) {
			DateTime todayDate = Datetime.now();
            DateTime currentExpDate = this.ExpectedDate == null ? null : HomeSearchFilterInterface.getDateFromString(this.ExpectedDate).date();
			DateTime compExpDate = compareToObj.ExpectedDate == null ? null : HomeSearchFilterInterface.getDateFromString(compareToObj.ExpectedDate).date();
			Integer ascSort = VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'ASC' ? -1 : 1;
			Integer descSort = VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'ASC' ? 1 : -1;
			boolean isAsc = VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'ASC';

            returnVal = (currentExpDate == compExpDate || currentExpDate == null || compExpDate == null)
                		?(this.VOName == compareToObj.VOName)
                            ? 0
                            :(
                                (VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'ASC')
                                ?	((this.VOName < compareToObj.VOName) ? -1 : 1)
                                :	(VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'DESC')
                                    ?	((this.VOName < compareToObj.VOName) ? 1 : -1)
                                    :	0
                            )
						:(currentExpDate == todayDate) ? isAsc ? ascSort :	(compExpDate < currentExpDate) ? 1 : -1 
														: (compExpDate == todayDate) ? isAsc ? descSort : (currentExpDate < compExpDate) ? -1 : 1
							:(currentExpDate < todayDate && compExpDate < todayDate)
            					?(currentExpDate > compExpDate) ? ascSort : descSort
                                : (currentExpDate > todayDate && compExpDate > todayDate)
            						?(currentExpDate < compExpDate) ? ascSort : descSort
                                	:(currentExpDate < todayDate) ? -1 : 1;
        } else if(this.InProgressVRId == null) {
			returnVal = (compareToObj.InProgressVRId == VendorOrderReceivingCtrl.Vendor_Order_Receiving_Id)
						?	1
						:	-1;
		} else if(compareToObj.InProgressVRId == null) {
			returnVal = (this.InProgressVRId == VendorOrderReceivingCtrl.Vendor_Order_Receiving_Id)
						?	-1
						:	1;
		} else {
			returnVal = (this.InProgressVRId == VendorOrderReceivingCtrl.Vendor_Order_Receiving_Id)
						?	-1
						:(
							(compareToObj.InProgressVRId == VendorOrderReceivingCtrl.Vendor_Order_Receiving_Id)
							?	1
							:(
								(VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'ASC')
								?	((this.VOName < compareToObj.VOName) ? -1 : 1)
								:	(VendorOrderReceivingCtrl.VO_Sort_Order.toUpperCase() == 'DESC')
									?	((this.VOName < compareToObj.VOName) ? 1 : -1)
									:	0
							)
						);
		}
        //System.debug('@@@\n' + this.InProgressVRId + '  ' + this.VOName + '\n' + compareToObj.InProgressVRId + '  ' + compareToObj.VOName + '\n' + returnVal + '\n' + VendorOrderReceivingCtrl.Vendor_Order_Receiving_Id);
        return returnVal;
    }
    
    // Order Type wrapper
    public class OrderTypeWrapper {
    	public String Id;
    	public String Name;
    	public Integer LeadTime;
		public Boolean UpdateCurrentCost;
    	
    	public OrderTypeWrapper(String Id, String Name, decimal LeadTime, Boolean updateCurrentCost){
    		this.Id = Id;
    		this.Name = Name;
    		this.LeadTime = (LeadTime == null) ? 0 : Integer.valueOf(LeadTime);
			this.UpdateCurrentCost = updateCurrentCost;
    	}
    }
}