src/objects/Applicable_Taxes__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicable Taxes</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Applicable Taxes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Individual_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_Tax__c</fullName>
        <formula>IF( 
            CO_Line_Item__c != null,  
            CO_Line_Item__r.Applicable_Tax__r.Name__c,
            IF(
                Service_Order_Line_Item__c != null,
                Service_Order_Line_Item__r.Applicable_Tax__r.Name__c,
                IF(
                    Option_Fee__c != null,
                    Option_Fee__r.Applicable_Tax__r.Name__c,
                    IF(
                        Deal_Unit_Price_Cost__c != null,
                        Deal_Unit_Price_Cost__r.Applicable_Tax__r.Name__c,
                        IF(
                            Deal_Item__c != null,
                            Deal_Item__r.Applicable_Tax__r.Name__c,
                            IF(
                                F_I_Product__c != null,
                                F_I_Product__r.Applicable_Tax_Name__c,
                                null
                        )
                    )
                )
            )
            )
        )</formula>
        <label>Applicable Tax</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enhanced_Tax_Amount__c</fullName>
        <label>Enhanced Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Item_Name__c</fullName>
        <label>Sales Tax Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Individual Taxes</relationshipLabel>
        <relationshipName>Individual_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taxable_Amount_for_Section_Header__c</fullName>
        <label>Taxable Amount for Section Header</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price_Cost__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Price Cost</label>
        <referenceTo>Unit_Price_Cost__c</referenceTo>
        <relationshipLabel>Individual Taxes</relationshipLabel>
        <relationshipName>Individual_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Individual Tax</label>
    <nameField>
        <displayFormat>ITN-{00000000}</displayFormat>
        <label>Individual Tax Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <description>Rate Type</description>
        <label>Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalating rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tiered rate</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total cost of unit</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Customer_Owned_Unit__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Customer__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs (Customer)</relationshipLabel>
        <relationshipName>Unit_Prices_Costs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicable_Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicable Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateIndividualTaxesUnderUPCBatch.cls
/**
 * Author: Nidhi Sharma
 * Since: August 2, 2024
 * Name: CreateIndividualTaxesUnderUPCBatch
 * Description: 
**/
global without sharing class CreateIndividualTaxesUnderUPCBatch extends PostInstallScriptBaseBatch {

    global CreateIndividualTaxesUnderUPCBatch() {
        this.scriptName = 'executeCreateIndividualTaxesUnderUPCBatch()';
    }
    
    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id FROM Unit_Price_Cost__c WHERE Applicable_Tax__c != null AND (Customer__c != null OR Vendor__c != null) AND Unit_Type__c = \'STOCK\'';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> upcList) {
        List<Unit_Price_Cost__c> upcListToProcess = new List<Unit_Price_Cost__c>();
        for(Unit_Price_Cost__c upcRec : [SELECT Total_Cost__c, Applicable_Tax__c, Customer__c, (Select Id FROM Individual_Taxes__r LIMIT 1) FROM Unit_Price_Cost__c WHERE Id IN: upcList]) {
            if(upcRec.Individual_Taxes__r.isEmpty()) upcListToProcess.add(upcRec);
        }
        createIndividualTaxes(upcListToProcess);
    }
    
    global override void finishScript(Database.BatchableContext bc) {}

    private void createIndividualTaxes(List<Unit_Price_Cost__c> upcList) {
        Set<Id> salesTaxIds = new Set<Id>();
        for(Unit_Price_Cost__c upcRec : upcList) {
            if(upcRec.Applicable_Tax__c != null) salesTaxIds.add(upcRec.Applicable_Tax__c);
        }
        if(!salesTaxIds.isEmpty()) {
            Map<Id, List<Applicable_Taxes__c>> salesTaxIdToAppTaxRecordsMap = new Map<Id, List<Applicable_Taxes__c>>();
            List<Applicable_Taxes__c> applicableTaxList = TaxManagementSOQLUtil.getApplicableTaxListBySalesTaxIdList(new List<Id>(salesTaxIds));
            for(Applicable_Taxes__c appTax : applicableTaxList) {
                if(!salesTaxIdToAppTaxRecordsMap.containsKey(appTax.Sales_Tax__c)) {
                    salesTaxIdToAppTaxRecordsMap.put(appTax.Sales_Tax__c, new List<Applicable_Taxes__c>());
                } 
                salesTaxIdToAppTaxRecordsMap.get(appTax.Sales_Tax__c).add(appTax);
            }
            List<Individual_Tax__c> individualTaxInsertList = new List<Individual_Tax__c>();
            List<Unit_Price_Cost__c> upcUpdateList = new List<Unit_Price_Cost__c>();
            for(Unit_Price_Cost__c upcRec : upcList) {
                Decimal taxRate = 0;
                if(upcRec.Individual_Taxes__r.isEmpty() && upcRec.Applicable_Tax__c != null && salesTaxIdToAppTaxRecordsMap.get(upcRec.Applicable_Tax__c) != null) {
                    for(Applicable_Taxes__c appTax : salesTaxIdToAppTaxRecordsMap.get(upcRec.Applicable_Tax__c)) {
                        Sales_Tax_Item__c stiRec = appTax.Sales_Tax_Item__r;
                        Individual_Tax__c individualTaxRec = new Individual_Tax__c();
                        individualTaxRec.Unit_Price_Cost__c = upcRec.Id;
                        individualTaxRec.Sales_Tax_Item__c = stiRec.Id;
                        individualTaxRec.Sales_Tax_Item_Name__c = stiRec.Name__c;
                        individualTaxRec.Taxable_Amount_for_Section_Header__c = upcRec.Total_Cost__c;
                        if(stiRec.Rate_Type__c == TaxManagementService.FIXED_RATE) {
                            individualTaxRec.Tax_Rate__c = stiRec.Rate__c;
                        } else {
                            individualTaxRec.Enhanced_Tax_Amount__c = TaxEngine.getEnhancedTaxAmount(individualTaxRec.Taxable_Amount_for_Section_Header__c, stiRec);
                        }
                        if((stiRec.Rate__c != null && stiRec.Rate__c != 0) || (individualTaxRec.Enhanced_Tax_Amount__c != null && individualTaxRec.Enhanced_Tax_Amount__c != 0)) {
                            individualTaxInsertList.add(individualTaxRec);
                        }
                        if(stiRec.Rate__c != null) taxRate += stiRec.Rate__c;
                    }
                    
                }
                if(GeneralConfiguration.getTaxIncludingPricing()) {
                    upcRec.Tax__c = taxRate;
                    upcUpdateList.add(upcRec);
                }
            }
            DMLUtility.insertSobjectList('Individual_Tax__c', individualTaxInsertList);
            if(!upcUpdateList.isEmpty()) {
                UnitPriceAndCostTriggerHelper.isForceStopTrigger = true;
                DMLUtility.updateSobjectList('Unit_Price_Cost__c', upcUpdateList);
            }
        }
    }
}