src/objects/Applicable_Taxes__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Tax_Item__c</fullName>
        <label>Sales Tax Item</label>
        <referenceTo>Sales_Tax_Item__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <referenceTo>Sales_Tax__c</referenceTo>
        <relationshipLabel>Applicable Taxes</relationshipLabel>
        <relationshipName>Applicable_Taxes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Applicable Taxes</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Applicable Taxes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicable Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Tax__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Is_Removed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Removed</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Is_Removed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Removed</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicableTaxTriggerHelper.cls
/**
 * Author: Tarun Khandelwal
 * Since: Oct. 11, 2014
 * Name: ApplicableTaxTriggerHelper
 * Description: Helper class for triggers on Applicable Tax object (Used In Kendo)
**/
public without sharing class ApplicableTaxTriggerHelper {
    
     // List to store trigger new list
    public static List<Applicable_Taxes__c> applicableTaxNewList = new List<Applicable_Taxes__c>();
    
    // List to store trigger old list
    public static List<Applicable_Taxes__c> applicableTaxOldList = new List<Applicable_Taxes__c>();
    
    // Map to store new Trigger Map
    public static Map<Id, Applicable_Taxes__c> applicableTaxNewMap = new Map<Id, Applicable_Taxes__c>();
    
    // Map to store Old Trigger Map
    public static Map<Id, Applicable_Taxes__c> applicableTaxOldMap = new Map<Id, Applicable_Taxes__c>();
    
    /**
     * Name: updateRateFieldOnSalesTax
     * Desc: Update Rate field of Sales Tax object to the sum of corresponding Sales Tax Item Rate 
     * @param: 
     * @return: 
    **/
    public static void  updateRateFieldOnSalesTax() {
        Set<Id> salesTaxSet = new Set<Id>();
        List<Applicable_Taxes__c> appTaxList = (trigger.isInsert ? applicableTaxNewList : (trigger.isDelete ? applicableTaxOldList : new List<Applicable_Taxes__c>()));
        for(Applicable_Taxes__c appTax : appTaxList){
            salesTaxSet.add(appTax.Sales_Tax__c);
        }
        salesTaxSet.remove(null);
        if(!salesTaxSet.isEmpty()) {
            if(AccessControl.ifObjectFieldIsAccessible('Sales_Tax__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
            if(AccessControl.ifObjectFieldIsAccessible('Applicable_Taxes__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
            
            List<Sales_Tax__c> stUpdateList = [Select Id, (SELECT Sales_Tax_Item__r.Rate__c from Applicable_Taxes__r WHERE Sales_Tax_Item__r.Rate__c != null) From Sales_Tax__c WHERE Id IN: salesTaxSet AND Is_Removed__c = false];
            for(Sales_Tax__c tax : stUpdateList) {
                tax.Rate__c = 0;
                for( Applicable_Taxes__c app : tax.Applicable_Taxes__r) {
                    tax.Rate__c += app.Sales_Tax_Item__r.Rate__c;      
                }
            }
            DMLUtility.updateSobjectList('Sales_Tax__c', stUpdateList);
        }
    }
}