src/objects/AR_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Payment_on_Account__c</fullName>
        <label>Payment on Account</label>
        <referenceTo>Payment_on_Account__c</referenceTo>
        <relationshipLabel>AR Payments</relationshipLabel>
        <relationshipName>AR_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AR Payment</label>
    <nameField>
        <displayFormat>ARP-{00000000}</displayFormat>
        <label>AR Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Method</label>
</CustomObject>

src/objects/Payment_on_Account__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments on Account</relationshipLabel>
        <relationshipName>Payments_on_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>EFTPOS</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Afterpay</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Payment Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment on Account</label>
    <nameField>
        <displayFormat>POA-{00000000}</displayFormat>
        <label>Payment on Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments on Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ARPaymentTriggerHelperTest.cls
@isTest
private class ARPaymentTriggerHelperTest {
    
    static testMethod void testARPaymentInsert() {
        Account testCustomer = TestUtil.createCustomer(true, 'Test Customer', 'a.b@gmail.com', 'Jaipur', '987456123');
        Payment_on_Account__c poaRec = new Payment_on_Account__c(Payment_Date__c = system.today(), Payment_Method__c = 'Debit', Customer__c = testCustomer.Id);
        insert poaRec;
        insert new AR_Payment__c(Payment_on_Account__c = poaRec.Id);
        system.assertEquals(1, [Select Id from AR_Payment__c].size());
    }   
}