src/objects/BP_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Bypass_FLS_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass FLS Check</label>
        <type>Checkbox</type>
    </fields>
    <label>BP Configurations</label>
</CustomObject>

src/objects/File_Storage__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>TextArea</type>
    </fields>
    <label>File Storage</label>
    <nameField>
        <displayFormat>FS-{00000000}</displayFormat>
        <label>File Storage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Storage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SOM_Integration__c.object
<CustomObject>
    <label>SOM Integration</label>
    <nameField>
        <displayFormat>SOM-{00000000}</displayFormat>
        <label>SOM Integration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOM Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OutdatedDataCleanupBatchSchTest.cls
@isTest
private class OutdatedDataCleanupBatchSchTest {

    @TestSetup
    static void makeData(){
        //Skip FLS check
        BP_Configurations__c config = BP_Configurations__c.getOrgDefaults();
        config.Bypass_FLS_Check__c = true;
        upsert config;

        SOM_Integration__c somStorageRec = new SOM_Integration__c();
        insert somStorageRec;
        insert new Attachment(ParentId = somStorageRec.Id, Name = 'Test', Body = Blob.valueOf('test'));

        File_Storage__c ftpFSRec = new File_Storage__c(Name__c = 'FTP');
        insert ftpFSRec;
        insert new Attachment(ParentId = ftpFSRec.Id, Name = 'Test', Body = Blob.valueOf('test'));

        insert new Log__c();
    }

    @isTest
    static void batchTest() {
        system.assertEquals(1, [Select Id from Attachment WHERE ParentId IN (Select Id From SOM_Integration__c)].size());
        system.assertEquals(1, [Select Id from Attachment WHERE ParentId IN (Select Id From File_Storage__c)].size());
        Test.startTest();
        String cronExpression = QBUtil.getCronExpForGivenTime(2);
        System.schedule('OutdatedDataCleanupBatchSchTest', cronExpression, new OutdatedDataCleanupBatchSch('File'));
        Database.executeBatch(new OutdatedDataCleanupBatchSch('File'));
        Test.stopTest();
        system.assertEquals(0, [Select Id from Attachment WHERE ParentId IN (Select Id From SOM_Integration__c)].size());
        system.assertEquals(0, [Select Id from Attachment WHERE ParentId IN (Select Id From File_Storage__c)].size());
    }
}