src/objects/BRP_Dealer_Product_Line__c.object
<CustomObject>
    <fields>
        <fullName>BRP_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BRP Dealer</label>
        <referenceTo>BRP_Dealers__c</referenceTo>
        <relationshipLabel>BRP Dealer Product Lines</relationshipLabel>
        <relationshipName>BRP_Dealer_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Party_Id__c</fullName>
        <label>Party Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BRP Dealer Product Line</label>
    <nameField>
        <label>BRP Dealer Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRP Dealer Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BRP_Dealers__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Two__c</fullName>
        <label>Line Two</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <label>Telephone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BRP Dealers</label>
    <nameField>
        <label>BRP Dealers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRP Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>URL of the resource you will access</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTTP_Method__c</fullName>
        <label>HTTP Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>State/Province</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BRPDealersControllerTest.cls
@isTest
private class BRPDealersControllerTest {
	
	@testSetup
    private static void setupTestData() {
		TestDataFactory.disableFLSChecks();

		IFW_IntegrationConfig__c IFWConfigObj = TestDataFactory.createIFWConfigForBRP();
        List<IFW_IntegrationConfig__c> IFWConfigObjList = [Select Id from IFW_IntegrationConfig__c];
        IFW_IntegrationConfigItem__c IFWConfigItemObj = TestUtil.createIFWConfigItemBRP('GetCampaigns', IFWConfigObjList[0].Id);
        IFWConfigItemObj.Endpoint_URL__c = 'https://qa-cloud-api.brp.com/dealer_connect_program/service_history/v1/vin/{vin}/campaigns';
        IFWConfigItemObj.HTTP_Method__c = 'GET';
        upsert IFWConfigItemObj;

		IFW_IntegrationConfigItem__c IFWConfigItemObj1 = TestUtil.createIFWConfigItemBRP('GetArticle', IFWConfigObjList[0].Id);
        IFWConfigItemObj1.Endpoint_URL__c = 'https://qa-cloud-api.brp.com/dealer_connect_program/service_history/v1/article/{article-no}';
        IFWConfigItemObj1.HTTP_Method__c = 'GET';
        upsert IFWConfigItemObj1;

    	BRP_Dealers__c brpDealerRec = new BRP_Dealers__c();
    	brpDealerRec.Party_ID__c = '123';
    	brpDealerRec.Telephone__c = '36253673';
    	brpDealerRec.Fax__c = 'testFax';
    	brpDealerRec.Website__c = 'test website';
    	brpDealerRec.Email__c = 'test@gmail.com';
    	brpDealerRec.Street__c = 'test street';
    	brpDealerRec.Line_Two__c = 'test address2';
    	brpDealerRec.City__c = 'test city';
    	brpDealerRec.Postcode__c = '356253';
    	brpDealerRec.State__c = 'test state';
    	brpDealerRec.Country__c = 'test country';
    	brpDealerRec.Company_Name__c = 'test company';
    	insert brpDealerRec;
    	
    	List<BRP_Dealer_Product_Line__c> brpDealerProductLineList = new List<BRP_Dealer_Product_Line__c>();
    	brpDealerProductLineList.add(new BRP_Dealer_Product_Line__c(Name = 'Test product 1', BRP_Dealer__c = brpDealerRec.Id));
    	brpDealerProductLineList.add(new BRP_Dealer_Product_Line__c(Name = 'Test product 2', BRP_Dealer__c = brpDealerRec.Id));
    	brpDealerProductLineList.add(new BRP_Dealer_Product_Line__c(Name = 'Test product 3', BRP_Dealer__c = brpDealerRec.Id));
    	insert brpDealerProductLineList;
    }

	@isTest
    private static void getDealerTest() {
    	BRPDealersController brpDealersControllerObj = new BRPDealersController();
    	BRPDealersController brpDealersControllerWithHomePageObj = new BRPDealersController(new NewHomePageCtrl());
    	
    	Test.startTest();
    	String result = BPUtility.getDecodedString(BRPDealersController.getDealer());
    	List<BRPDealerWrapper> brpDealerWrapperList = (List<BRPDealerWrapper>)system.JSON.deserialize(result, List<BRPDealerWrapper>.class);
    	System.assertEquals(brpDealerWrapperList[0].PartyId, '123');
    	Test.stopTest();
    }

    @isTest
    private static void getArticleByArticleNoTest() {
        Test.setMock(HttpCalloutMock.class, new BRPVehicleIntegrationMockTest(null));
        Test.startTest();
		String articleNo = '000137651';
        String res = BPUtility.getDecodedString(BRPDealersController.getArticleByArticleNo(BPUtility.getEncodedString(articleNo)));
        BRPArticleResponseWrapper responseWrapper = (BRPArticleResponseWrapper)system.JSON.deserialize(res, BRPArticleResponseWrapper.class);
        system.assertEquals(200, responseWrapper.StatusCode);
		system.assertEquals(articleNo, responseWrapper.SuccessResponse.article_no);
        Test.stopTest();
    }

    @isTest
    private static void getCampaignsByVINTest() {
        Test.setMock(HttpCalloutMock.class, new BRPVehicleIntegrationMockTest(null));
        Test.startTest();
		String vinNo = '2BPSCEKCXKV000009';
        String res = BPUtility.getDecodedString(BRPDealersController.getCampaignsByVIN(BPUtility.getEncodedString(vinNo)));
        BRPCampaignResponseWrapper responseWrapper = (BRPCampaignResponseWrapper)system.JSON.deserialize(res, BRPCampaignResponseWrapper.class);
        system.assertEquals(200, responseWrapper.StatusCode);
		system.assertEquals(vinNo, responseWrapper.SuccessResponse.vin);
        Test.stopTest();
    }
}