src/objects/Business_Profile__c.object
<CustomObject>
    <label>Business Profile</label>
    <nameField>
        <displayFormat>BPN-{000000}</displayFormat>
        <label>Business Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>IF( !ISBLANK(Customer__r.Name) , Customer__r.Name, 
    IF( ISPICKVAL(CO_Type__c , &apos;Cash Sale&apos;)  , &apos;CASH SALE&apos;, 
       IF(ISPICKVAL(CO_Type__c , &apos;Internal Service&apos;), &apos;UNIT INVENTORY&apos;, &apos;&apos;) ) )</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrintCOProfitabilityCtrl.cls
global without sharing class PrintCOProfitabilityCtrl {
	
    public PrintCOProfitabilityCtrl() {
        Application = GlobalController.GetResourceURL('Application');
        Application_Images = GlobalController.GetResourceURL('Application_Images');
        Assests = GlobalController.GetResourceURL('Assests');
    }
    
    public static String Application{get;}
    public static String Assests{get;}
    public static String Application_Images{get;}
    
    @RemoteAction
    global static String getCOProfitability(String coId) {
        coId = BPUtility.getDecodedString(coId);
        try {
        	ProfitabilityWrapper profitabilityWrapperObj = COService.getCOProfitability(coId); 
        	List<Business_Profile__c> businessProfileList = SOQLUtil.getBusinessProfileData(new List<Id>());
        	List<CO_Header__c> coHeaderList = [SELECT Customer_Name__c, Name FROM CO_Header__c WHERE Id =: coId];
        	COProfitabilityDetail profitabilityObj = new COProfitabilityDetail(businessProfileList, profitabilityWrapperObj, coHeaderList);
            return BPUtility.getEncodedString(system.JSON.serialize(profitabilityObj));
        } catch(Exception e) {
            throw new BlackPurlException(BlackPurlException.getErrorMessage(e.getMessage(), e.getStackTraceString()));
        }
    }
    
    public class COProfitabilityDetail {
     	public CustomerDetail.Company CompanyInfo {get; set;}
     	public String CustomerName;
     	public String CustomerOrderName;
     	public ProfitabilityWrapper ProfitabilityObj{get; private set;}
     	
     	public COProfitabilityDetail(List<Business_Profile__c> businessProfileList, ProfitabilityWrapper profitabilityWrapperObj, List<CO_Header__c> coHeaderList) {
     		if(businessProfileList.size() > 0) {
                this.CompanyInfo = new CustomerDetail.Company(businessProfileList[0]);
            } else {
                this.CompanyInfo = new CustomerDetail.Company(new Business_Profile__c());
            }
            this.CompanyInfo.BusinessPhone = this.CompanyInfo.FormattedBusinessPhone != null ? this.CompanyInfo.FormattedBusinessPhone: '';
            this.ProfitabilityObj = profitabilityWrapperObj;
            if(coHeaderList.size() > 0) {
             	this.CustomerName = coHeaderList[0].Customer_Name__c;
        		this.CustomerOrderName = coHeaderList[0].Name;
            } 
     	}
     }
}