src/objects/Cash_Drawer__c.object
<CustomObject>
    <label>Cash Drawer</label>
    <nameField>
        <label>Cash Drawer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Drawers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Drawer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer</label>
        <referenceTo>Cash_Drawer__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Charge on Account</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>Giftcard</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Rewards</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>EFTPOS</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Afterpay</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Payment Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Terminal__c</fullName>
	    <deleteConstraint>SetNull</deleteConstraint>
	    <label>Payment Terminal</label>
	    <referenceTo>Payment_Terminal__c</referenceTo>
	    <relationshipLabel>CO Deposits</relationshipLabel>
	    <relationshipName>CO_Deposits</relationshipName>
	    <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recorded_From__c</fullName>
        <label>Recorded From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Reference number from Preferred Payment Processor or user entered check/cheque or other reference number for other payment methods</description>
	    <inlineHelpText>Reference number from Preferred Payment Processor or user entered check/cheque or other reference number for other payment methods</inlineHelpText>
	    <label>Reference #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Deposit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Deposit</label>
        <referenceTo>CO_Deposit__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reverse_Link__c</fullName>
        <label>Reverse Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CO Deposit</label>
    <nameField>
        <displayFormat>CODN-{00000000}</displayFormat>
        <label>CO Deposits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>AutoNumberHolder__r.Name</formula>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Order</description>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Method</label>
</CustomObject>

src/objects/Payment_Terminal__c.object
<CustomObject>
    <label>Payment Terminal</label>
    <nameField>
        <displayFormat>PT-{00000000}</displayFormat>
        <label>Payment Terminal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Terminals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CODeposit.cls
/**
 * Author: Tarun Khandelwal
 * Since: April 22, 2014
 * Name: CODeposit
 * Description: Used to convert CODeposit JSON serialize and deserialize operations
**/
public without sharing class CODeposit {
    
     // Deposit Name
    public String DepositName{get; set;}
    
    // COHeader Id
    public String COHeaderId{get; set;}
    
    // Assignee
    public String PaymentMethod{get; set;}
    
    // Assignee Name
    public Decimal Amount{get; set;}
    
    // Created Date
    public String CreatedDate {get; set;}
    public String CreatedDate_Formatted;	//For new Co
    
    // CO Deposit Id
    public String CODepositId {get; set;}
    
    // CO invoice Number
    public String COInvoiceNumber {get; set;}
    
    public String Deal {get; set;}
    
    public String RecordedFrom {get;set;}
    
    public String ReverseLink {get; set;}
    
    public String CashDrawerId {get;set;}
    
    public String PaymentDate {get;set;}
    
    public String PaymentDate_Formatted {get;set;}

    public String ARCRInvoiceAccId;
    public String ARCreditAccId;
    public String ARCreditNumber;
    public String UnappliedPaymentType;
    
    public String CustomerId;
    public String ReferenceNumber;
    public String PaymentTerminalId;
    public String PreferredPaymentTerminalId;
    public String PaymentProcessorToken;
    public String RelatedDepositId;

    // Constructor 
    public CODeposit(CO_Deposit__c coDepositObj) { 
        this.DepositName = coDepositObj.Name; 
        this.COHeaderId = coDepositObj.CO_Header__c;
        this.PaymentMethod = coDepositObj.Payment_Method__c;
        this.Amount = (coDepositObj.Amount__c != null) ? coDepositObj.Amount__c.setScale(2, RoundingMode.HALF_UP) : 0.00;
        if(coDepositObj.Id != null) {
            this.CODepositId = coDepositObj.Id;
            this.CreatedDate = BPUtility.getExtendedMonthFormat(DateTime.valueOf(coDepositObj.CreatedDate)); 
        	this.CreatedDate_Formatted = (coDepositObj.CreatedDate != null) ? 
								BPUtility.getFormatedDateTime(datetime.newInstance(coDepositObj.CreatedDate.year(), coDepositObj.CreatedDate.month(), coDepositObj.CreatedDate.day())) : '' ;
        } else {
            this.CreatedDate = '';
            this.CreatedDate_Formatted = '';
        }
        if(coDepositObj.CO_Invoice_Header__c != null) {
        	this.COInvoiceNumber = coDepositObj.CO_Invoice_Header__r.Invoice_Number__c;
        } else {
        	this.COInvoiceNumber = '';
        }  
        this.Deal = coDepositObj.Deal__c;
        this.RecordedFrom = coDepositObj.Recorded_From__c;  
        this.ReverseLink = coDepositObj.Reverse_Link__c;
        this.CashDrawerId = coDepositObj.Cash_Drawer__c;
    	this.PaymentDate = (coDepositObj.Payment_Date__c != null) ? BPUtility.getFormatedDateTime(Date.valueOf(coDepositObj.Payment_Date__c)) : BPUtility.getFormatedDateTime(date.today());
    	this.PaymentDate_Formatted = (coDepositObj.Payment_Date__c != null) ? BPUtility.getFormatedDateTimewithSeparator(coDepositObj.Payment_Date__c, '-'): BPUtility.getFormatedDateTime(date.today());
        this.ReferenceNumber = coDepositObj.Reference__c != null ? coDepositObj.Reference__c : '';
        this.PaymentTerminalId = coDepositObj.Payment_Terminal__c;
        this.RelatedDepositId = coDepositObj.Related_Deposit__c;
    }     
    
    /**
     * Name: parse
     * Desc: Method to Parse JSON String to class instance
     * @param:  (1) JSONString - String - JSON String 
     * @return: CODeposit - Class Object
    **/
      public static List<CODeposit> parse(String json) {
        return (List<CODeposit>) System.JSON.deserialize(json, List<CODeposit>.class);
      }
  
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        List<String> CODepositFields = new List<String>{ 'Id',
                            'Name', 
                            'CO_Header__c',
                            'Amount__c',
                            'Payment_Method__c',
                            'CreatedDate',
                            'CO_Invoice_Header__c',
                            'CO_Invoice_Header__r.Name',
                            'CO_Invoice_Header__r.Invoice_Number__c',
                            'Recorded_From__c',
                            'Deal__c',
                            'Reverse_Link__c',
                            'Cash_Drawer__c',
                            'Payment_Date__c',
                            'Reference__c',
                            'Payment_Terminal__c',
                            'Related_Deposit__c'
                           };
        return CODepositFields;
    }
}