src/objects/Cash_Drawer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Cash Drawer</label>
    <nameField>
        <label>Cash Drawer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Drawers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CashDrawerWrapper.cls
public without sharing class CashDrawerWrapper {
    public String Id;
    public String CashDrawerName;
    public Boolean IsActive;
    
    public CashDrawerWrapper(Cash_Drawer__c cashDrawerRec) {
        this.Id = cashDrawerRec.Id;
        this.CashDrawerName = cashDrawerRec.Name;
        this.IsActive = cashDrawerRec.Active__c;
    }
    
    public static List<String> getCashDrawerFieldsList() {
       return new List<String>{ 'Id', 'Name', 'Active__c'};
    }
}