src/objects/Cash_Drawer__c.object
<CustomObject>
    <label>Cash Drawer</label>
    <nameField>
        <label>Cash Drawer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Drawers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Drawer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer</label>
        <referenceTo>Cash_Drawer__c</referenceTo>
        <relationshipLabel>CO Deposits</relationshipLabel>
        <relationshipName>CO_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Charge on Account</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>Giftcard</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Rewards</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>EFTPOS</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Afterpay</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Payment Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Deposit</label>
    <nameField>
        <displayFormat>CODN-{00000000}</displayFormat>
        <label>CO Deposits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CO_Invoice_Header__c</fullName>
        <label>CO Invoice Header</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cash_Drawer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Drawer</label>
        <referenceTo>Cash_Drawer__c</referenceTo>
        <relationshipLabel>CO Invoice Payments</relationshipLabel>
        <relationshipName>CO_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <formula>CO_Invoice_Header__r.CO_Header__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CO Header</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Cash Rounding</fullName>
                </value>
                <value>
                    <fullName>Charge Account</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Financing</fullName>
                </value>
                <value>
                    <fullName>Gift Card</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Use Deposit</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>EFTPOS</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Afterpay</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Payment Surcharge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Invoice Payment</label>
    <nameField>
        <displayFormat>COIP-{00000000}</displayFormat>
        <label>CO Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Method</label>
</CustomObject>

src/classes/CashReconciliationCtrl_V2Test.cls
@isTest
private class CashReconciliationCtrl_V2Test {

    @testSetup
    private static void setupTestData() {
        TestDataFactory.disableFLSChecks();
    }

    static void testData() {
        List<Cash_Drawer__c> cashDrawerList = TestDataFactory_V2.createTestDataForCashDrawer(true, 'Test Cash Drawer');
        List<CO_Header__c> coHeaderList = TestDataFactory_V2.createTestDataForCOHeader(true);
        List<CO_Invoice_Header__c> coInvoiceHeaderList = TestDataFactory_V2.createTestDataForCOInvoiceHeader(coHeaderList, false);
        coInvoiceHeaderList[0].Invoice_Status__c = 'Active';
        insert coInvoiceHeaderList[0];
        List<CO_Invoice_Payment__c> coInvoicePaymentList = TestDataFactory_V2.createTestDataForCOInvoicePayment(coInvoiceHeaderList, true);
        List<CO_Deposit__c> coDepositList = TestDataFactory_V2.createTestDataForCODeposit(coHeaderList, true);
    }

    @isTest
    public static void getCashDrawerReconciliationByDrawerIdTest() {
        testData();
        List<Cash_Drawer__c> cashDrawerList = [SELECT Id FROM Cash_Drawer__c];
        List<CO_Invoice_Payment__c> coInvoicePaymentList = [SELECT Id,Payment_Method__c,Amount__c,Cash_Drawer__c FROM CO_Invoice_Payment__c];
        coInvoicePaymentList[0].Payment_Method__c = 'Cash';
        coInvoicePaymentList[0].Amount__c = 100;
        coInvoicePaymentList[0].Cash_Drawer__c = cashDrawerList[0].Id;
        update coInvoicePaymentList[0];
        
        String reconciledDateStr = '1/12/2018';
        
        // Test the getCashDrawerReconciliationByDrawerId method
        String reconciliationRecJson = CashReconciliationCtrl.getCashDrawerReconciliationByDrawerId(
            BPUtility.getEncodedString(reconciledDateStr),
            BPUtility.getEncodedString(cashDrawerList[0].Id)
        );
        reconciliationRecJson = BPUtility.getDecodedString(reconciliationRecJson);
        ReconciliationWrapper reconciliationObj = (ReconciliationWrapper) JSON.deserialize(reconciliationRecJson, ReconciliationWrapper.class);
        // Assertion
        System.assert(reconciliationObj.CashDrawerReconcilationObjList[0].DrawerId != null);
    }

    @isTest
    public static void getReconciliationListTest() {
        // Test data setup
        testData();
        TestDataFactory_V2.createTestDataForCashDrawer(true, 'Test Cash Drawer1');
        List<CO_Invoice_Header__c> coInvoiceHeaderList = [SELECT Id FROM CO_Invoice_Header__c];
        TestDataFactory_V2.createTestDataForCOInvoicePayment(coInvoiceHeaderList, true);
    
        List<Cash_Drawer__c> cashDrawerList = [SELECT Id FROM Cash_Drawer__c];
        List<CO_Invoice_Payment__c> coInvoicePaymentList = [SELECT Id, Payment_Date__c, Payment_Method__c, Cash_Drawer__c, Amount__c FROM CO_Invoice_Payment__c];
        List<CO_Deposit__c> coDepositList = [SELECT Id, Payment_Date__c, Payment_Method__c, Cash_Drawer__c FROM CO_Deposit__c];

        coInvoicePaymentList[0].Payment_Method__c = 'Cash';
        coInvoicePaymentList[0].Amount__c = 100;
        coInvoicePaymentList[0].Cash_Drawer__c = cashDrawerList[0].Id;
        coInvoicePaymentList[0].Payment_Date__c = system.today();
        update coInvoicePaymentList[0];

        coInvoicePaymentList[1].Payment_Method__c = 'Store Credit';
        coInvoicePaymentList[1].Amount__c = -100;
        coInvoicePaymentList[1].Cash_Drawer__c = cashDrawerList[1].Id;
        coInvoicePaymentList[0].Payment_Date__c = system.today();
        update coInvoicePaymentList[1];
        
        coDepositList[0].Cash_Drawer__c = cashDrawerList[0].Id;
        coDepositList[0].Payment_Date__c = system.today();
        coDepositList[0].Payment_Method__c = 'Debit';
        update coDepositList[0];

        Date todayDate = System.today();
        String reconciledDateStr = todayDate.format();
        
        // Test the getReconciliationList method for 'Drawer' view
        String reconciliationRecJson = CashReconciliationCtrl.getReconciliationList(
            BPUtility.getEncodedString(reconciledDateStr),
            BPUtility.getEncodedString('Drawer')
        );
        reconciliationRecJson = BPUtility.getDecodedString(reconciliationRecJson);
        ReconciliationWrapper reconciliationObj = (ReconciliationWrapper) JSON.deserialize(reconciliationRecJson, ReconciliationWrapper.class);
        
        // Assertion
        System.assertEquals(reconciliationObj.ReconciliationInfo.Status, 'Unreconciled');
        
        // Test the getReconciliationList method for 'Transaction Type' view
        reconciliationRecJson = CashReconciliationCtrl.getReconciliationList(
            BPUtility.getEncodedString(reconciledDateStr),
            BPUtility.getEncodedString('Transaction Type')
        );
        reconciliationRecJson = BPUtility.getDecodedString(reconciliationRecJson);
        List<CashReconciliationTTWrapper> transactionTypeList = (List<CashReconciliationTTWrapper>) JSON.deserialize(reconciliationRecJson, List<CashReconciliationTTWrapper>.class);
       // Assertions
        for (CashReconciliationTTWrapper ttRec : transactionTypeList) {
            system.assertEquals(ttRec.CashDrawerDetailObjList.size(), 2);

            if (ttRec.PaymentMethod == 'Cash') {
                System.assertEquals(ttRec.TotalProcessedAmount, 100);
            }
            if (ttRec.PaymentMethod == 'Debit') {
                System.assertEquals(ttRec.TotalProcessedAmount, 1000);
            }
        }
    }

    @isTest
    public static void getMiniCalenderDataByDrawerIdTest() {
        // Test data setup
        testData();
        List<Cash_Drawer__c> cashDrawerList = [SELECT Id FROM Cash_Drawer__c];
                
        String StartDateStr = '1/12/2018';
        String EndDateStr = '31/12/2018';
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('StartDate', StartDateStr);
        gen.writeStringField('EndDate', EndDateStr);
        gen.writeEndObject();
        String jsonString = gen.getAsString();
        
        // Test the getMiniCalenderDataByDrawerId method
        String response = CashReconciliationCtrl.getMiniCalenderDataByDrawerId(
            BPUtility.getEncodedString(jsonString),
            BPUtility.getEncodedString(null)
        );
        String getMinicalenderDataStr = BPUtility.getDecodedString(response);
        List<ReconciliationWrapper.ReconciliationInfo> reconciliationInfoObj = (List<ReconciliationWrapper.ReconciliationInfo>) JSON.deserialize(getMinicalenderDataStr, List<ReconciliationWrapper.ReconciliationInfo>.class);
        
        // Assertion
        System.assertEquals(reconciliationInfoObj.size(), 0);
    }

    @isTest
    public static void saveReconciliationTest() {
        // Test data setup
        testData();
        List<Cash_Drawer__c> cashDrawerList = [SELECT Id FROM Cash_Drawer__c];
        List<CO_Invoice_Payment__c> coInvoicePaymentList = [SELECT Id,Payment_Method__c,Amount__c,Cash_Drawer__c FROM CO_Invoice_Payment__c];
        coInvoicePaymentList[0].Payment_Method__c = 'Cash';
        coInvoicePaymentList[0].Amount__c = 100;
        coInvoicePaymentList[0].Cash_Drawer__c = cashDrawerList[0].Id;
        update coInvoicePaymentList[0];
        
        String reconciledDateStr = '1/12/2018';
        
        // Test the saveReconciliation method
        String reconciliationRecJson = CashReconciliationCtrl.getCashDrawerReconciliationByDrawerId(
            BPUtility.getEncodedString(reconciledDateStr),
            BPUtility.getEncodedString(cashDrawerList[0].Id)
        );
        reconciliationRecJson = BPUtility.getDecodedString(reconciliationRecJson);
        ReconciliationWrapper reconciliationObj = (ReconciliationWrapper) JSON.deserialize(reconciliationRecJson, ReconciliationWrapper.class);
        reconciliationObj.CashDrawerReconcilationObjList[0].Status = 'Submitted';
        
        String response = CashReconciliationCtrl.saveReconciliation(
            BPUtility.getEncodedString(system.JSON.serialize(reconciliationObj)),
            null
        );
        
        // Assertion
        System.assertEquals(response, 'Success');
    }
}