src/objects/CASSONS_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Heroku_End_Point_URL__c</fullName>
        <label>Heroku End Point URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts_Per_Request__c</fullName>
        <defaultValue>200</defaultValue>
        <label>Parts Per Request</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduler_Interval__c</fullName>
        <defaultValue>120</defaultValue>
        <description>Scheduler interval in minutes.</description>
        <label>Scheduler Interval</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CASSONS Configuration</label>
</CustomObject>

src/objects/CASSONS_Vendor_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CASSONS Vendor List</label>
</CustomObject>

src/classes/CassonsUtility.cls
public without sharing class CassonsUtility {
    public static Set<String> getAllCassonsVendorsIdSet() {
        List<CASSONS_Vendor_List__c> cassonsVendorList =  CASSONS_Vendor_List__c.getAll().values();
        Set<String> cassonsVendorIdSet = new Set<String>();
        for(CASSONS_Vendor_List__c cassonsVendorRec : cassonsVendorList) {
            if(cassonsVendorRec.Active__c) {
                cassonsVendorIdSet.add(cassonsVendorRec.Name);
            }
        }
        return cassonsVendorIdSet;
    }

    public static Integer getPartsPerRequest() {
        return CASSONS_Configuration__c.getOrgDefaults().Parts_Per_Request__c != null ? (Integer)CASSONS_Configuration__c.getOrgDefaults().Parts_Per_Request__c : 200;
    }

    public static String getHerokuEndPoint() {
        return CASSONS_Configuration__c.getOrgDefaults().Heroku_End_Point_URL__c;
    }

    public static Integer getSchedulerInterval() {
        return CASSONS_Configuration__c.getOrgDefaults().Scheduler_Interval__c != null ? (Integer)CASSONS_Configuration__c.getOrgDefaults().Scheduler_Interval__c : 120;
    }
}