src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuickBooks_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used for Integration</description>
    <fields>
        <fullName>TaxCode_Id__c</fullName>
        <label>TaxCode Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxCode_Name__c</fullName>
        <label>TaxCode Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Agency_Id__c</fullName>
        <label>Tax Agency Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Agency_Name__c</fullName>
        <label>Tax Agency Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Configurations</label>
</CustomObject>

src/objects/Sales_Tax_Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Sales Tax Items</relationshipLabel>
        <relationshipName>Sales_Tax_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Tax Item</label>
    <nameField>
        <displayFormat>STI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesTaxServiceTest.cls
@isTest 
public class SalesTaxServiceTest {
	
	@testSetup
    private static void setupTestData() {
    	List<Category__c> categoryList = new List<Category__c>();
    	List<Sales_Tax_Item__c> salesTexItemList = new List<Sales_Tax_Item__c>();
    	for(Integer i = 0; i < 10; i++) {
    		categoryList.add(TestDataFactory.sampleCategory('Test Category' + i));
    	}
    	insert categoryList;
    	for(Integer i = 0; i < 10; i++) {
    		salesTexItemList.add(TestDataFactory.sampleSalesTaxItem('Test tax' + i, 1, 'Test form' + i, categoryList[i].Id, true));
    	}
    	insert salesTexItemList;
    	
    	QuickBooks_Configurations__c qbConfig = TestDataFactory.sampleQBConfig();
    	qbConfig.Tax_Agency_Name__c = 'Test Agency';
    	qbConfig.Tax_Agency_Id__c = '123456';
    	qbConfig.TaxCode_Name__c = 'Test code';
    	qbConfig.TaxCode_Id__c = '1234';
    	insert qbConfig;  
    }
    
    @isTest
    private static void syncAccountingServerTest() {
    	Test.startTest();
    	SalesTaxService.syncAccountingServer();
    	Test.stopTest();
    	system.assertEquals([SELECT Id From Sales_Tax_Item__c].size(), 10);
    }
    
    @isTest
    private static void syncTaxAgencyFutureTest() {
    	Test.startTest();
    	SalesTaxService.syncTaxAgencyFuture();
    	Test.stopTest();
    	system.assertEquals([SELECT Id From Sales_Tax_Item__c].size(), 10);
    }
}