src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <label>General Configurations</label>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part_FIFO_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoicing_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoicing Header</label>
        <referenceTo>Vendor_Invoicing_Header__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Part FIFO Bucket</label>
    <nameField>
        <displayFormat>PBN-{00000000}</displayFormat>
        <label>Part FIFO Bucket  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoicing_Group__c.object
<CustomObject>
    <fields>
        <fullName>VI_Discount__c</fullName>
        <label>VI_Discount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoicing_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoicing Header</label>
        <referenceTo>Vendor_Invoicing_Header__c</referenceTo>
        <relationshipLabel>Vendor Invoicing Groups</relationshipLabel>
        <relationshipName>Vendor_Invoicing_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoicing Group</label>
    <nameField>
        <displayFormat>VIG-{00000000}</displayFormat>
        <label>Vendor Invoicing Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoicing Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoicing_Header__c.object
<CustomObject>
    <label>Vendor Invoicing Header</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Vendor Invoicing Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoicing Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QBvendorCreditDTOTest.cls
@isTest
private without sharing class QBvendorCreditDTOTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.disableFLSChecks();
        
        Account vendor = TestDataFactory.createVendor('vendorName');

        BPScriptUtility.disbaleTrigger('PartTrigger');
        
        General_Configurations__c genConfig = TestDataFactory.createGeneralConfig(1);
        
        Account accRec = TestDataFactory.createVendor('newacc');
        
        Category__c catRec = TestDataFactory.createCategory('categoryName');
        
        Part__c partRec = TestDataFactory.createPart(vendor.Id, 10, 12, 15, 13, 2, catRec.Id);
        
        Part_Fifo_Bucket__c partBucketRec = TestDataFactory.createPartFifoBucket(partRec.Id);
        
        Vendor_Invoicing_Header__c vendorInvoiceHeaderRec = TestDataFactory.createVIHeader(vendor.Id,'Completed');
        
    }
    
    @isTest
    private static void QBvendorCreditDTOMethodTest(){
        
        String viHeaderQueryStr = 'SELECT ';
        for(String fieldName : AccountingVendorInvoice.objectToFieldMap.get('VIHeader')){
            fieldName = BPUtility.escapeSingleQuotes(fieldName);
            viHeaderQueryStr += fieldName + ', ';
        }
        viHeaderQueryStr = viHeaderQueryStr.substring(0, viHeaderQueryStr.length()-2);
        viHeaderQueryStr += ' FROM Vendor_Invoicing_Header__c Limit 1 ';
        Vendor_Invoicing_Header__c vendorInvoiceHeaderFinalRec = Database.query(viHeaderQueryStr);
        
        Vendor_Invoicing_Group__c vendorInvoicingGroup = TestDataFactory.createVendorInvoicingGroup(vendorInvoiceHeaderFinalRec.Id);
        vendorInvoicingGroup.VI_Discount__c = 2;
        DMLUtility.updateSobjectList('Vendor_Invoicing_Group__c', vendorInvoicingGroup);
        
        String viGroupQueryStr = 'SELECT ';
        for(String fieldName : AccountingVendorInvoice.objectToFieldMap.get('VIGroup')){
            fieldName = BPUtility.escapeSingleQuotes(fieldName);
            viGroupQueryStr += fieldName + ', ';
        }
        viGroupQueryStr = viGroupQueryStr.substring(0, viGroupQueryStr.length()-2);
        viGroupQueryStr += ' FROM Vendor_Invoicing_Group__c ';
        List<Vendor_Invoicing_Group__c> VIGroupsList = Database.query(viGroupQueryStr);
        
        String query = 'SELECT ' + String.join(AccountingFIFOBucket.fieldsList(), ',') + ' FROM Part_FIFO_Bucket__c ';
        List<Part_FIFO_Bucket__c> PartFIFOBucketList = Database.query(query);
        Test.startTest();
        AccountingVendorInvoice accVendorInvoiceRec = new AccountingVendorInvoice(vendorInvoiceHeaderFinalRec, VIGroupsList,PartFIFOBucketList);

        QBVendorCreditDTO qbVendorDTOobj = new QBVendorCreditDTO(accVendorInvoiceRec);
        Test.stopTest();
        System.assertEquals(1, PartFIFOBucketList.size());
    }
}