src/objects/Claim__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Disposition__c</fullName>
        <label>Claim Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Accepted w/ Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Claim_Number__c</fullName>
        <label>Claim Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Claim_Number__c</fullName>
        <label>Provider Claim Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Date__c</fullName>
        <label>Response Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>CL-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Claim_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_Subtotal__c</fullName>
        <formula>( Approved_Price__c *  Approved_Qty__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approved Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Claim Line Items</relationshipLabel>
        <relationshipName>Claim_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Claim Line Items</relationshipLabel>
        <relationshipName>Claim_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Claimed_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Claimed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Claimed_Qty__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Claimed Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Claimed_Subtotal__c</fullName>
        <formula>( Claimed_Price__c *  Claimed_Qty__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claimed Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Variance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Variance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SO_Payment_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SO Payment Role</label>
        <referenceTo>SO_Payment_Role__c</referenceTo>
        <relationshipLabel>Claim Line Items</relationshipLabel>
        <relationshipName>Claim_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Line Item</label>
        <referenceTo>Service_Order_Line_Item__c</referenceTo>
        <relationshipLabel>Claim Line Items</relationshipLabel>
        <relationshipName>Claim_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <formula>IF( $Setup.Configurations__c.Tax_Included_Pricing__c ,  Service_Order_Line_Item__r.Kit_Price__c * Tax__c *  Approved_Qty__c , Approved_Subtotal__c * Tax__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Variance_Amount__c</fullName>
        <label>Variance Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Variance_Qty__c</fullName>
        <label>Variance Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <formula>( Approved_Subtotal__c -  Claimed_Subtotal__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Claim Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000000}</displayFormat>
        <label>Claim Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Kit_Header_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Kit Header Line Item</label>
    <nameField>
        <displayFormat>KHLI-{00000000}</displayFormat>
        <label>Kit Header Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit Header Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Labour_Code__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - A lookup of defined categories with a Type = Labour</description>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Category__c.Type__c</field>
                <operation>equals</operation>
                <value>Labour</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Labour Codes</relationshipLabel>
        <relationshipName>Labour_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Hours__c * Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Labour Code</label>
    <nameField>
        <displayFormat>LC-{00000000}</displayFormat>
        <label>Labour Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labour Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <formula>(Qty_Needed__c * Kit_Price__c * Tax_Percent__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <formula>CO_Line_Item__r.Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Service Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{00000000}</displayFormat>
        <label>Service Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SO_Payment_Role__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>SO Payment Roles</relationshipLabel>
        <relationshipName>SO_Payment_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>SO Payment Roles</relationshipLabel>
        <relationshipName>SO_Payment_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>SO Payment Roles</relationshipLabel>
        <relationshipName>SO_Payment_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variance__c</fullName>
        <label>Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SO Payment Role</label>
    <nameField>
        <displayFormat>SOPR-{0000000}</displayFormat>
        <label>SO Payment Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SO Payment Roles</pluralLabel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>Internal</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClaimWizard.cls
/**
 * Author: Tarun Khandelwal
 * Since: May 16, 2016
 * Name: ClaimWizard
 * Description: Apex class to handle JSON related oprations of Claim Wizard Screen.
**/
public without sharing class ClaimWizard {
    
    public String ClaimId;
    public String ClaimNumber;
    public String ResponseDate;
    public String Notes;
    public String ClaimDisposition;
    public String SOHeaderId;
    public Decimal Total;
    public String ProviderClaimNumber;
    public Decimal DeductibleAmount;
    public Decimal DeductibleTaxAmount;
    public Boolean IsTaxIncludingPricing;
    public List<ClaimLineItem> VarianceLineItemList;
    public List<ClaimLineItem> NonVarianceLineItemList;
    public List<CategoryItem>  InternalCategoryList;
    public String SubmittedDate;
    
    public ClaimWizard(Claim__c claimRec, List<SO_Payment_Role__c> deductibelRecordList, List<Category__c> InternalCategoryList) {
        this.ClaimId = claimRec.Id;
        this.ClaimNumber = (claimRec.Claim_Number__c != null) ? claimRec.Claim_Number__c : claimRec.Name;
        this.ResponseDate = (claimRec.Response_Date__c != null) ? 
                                BPUtility.getFormatedDateTime(datetime.newInstance(claimRec.Response_Date__c.year(), claimRec.Response_Date__c.month(),claimRec.Response_Date__c.day())) 
                                : null;
                                
        this.Notes = claimRec.Notes__c;
        this.ClaimDisposition = claimRec.Claim_Disposition__c;
        this.SOHeaderId = claimRec.Service_Order_Header__c; 
        
        this.VarianceLineItemList = new List<ClaimLineItem>();
        this.NonVarianceLineItemList = new List<ClaimLineItem>();
        this.ProviderClaimNumber = claimRec.Provider_Claim_Number__c;
        for(Claim_Line_Item__c claimLineItemRec : claimRec.Claim_Line_Items__r) {
            if(claimLineItemRec.Is_Variance__c) {
                this.VarianceLineItemList.add(new ClaimLineItem(claimLineItemRec));
            } else {
                this.NonVarianceLineItemList.add(new ClaimLineItem(claimLineItemRec));
            }
        }   
        
        this.IsTaxIncludingPricing = GeneralConfiguration.getTaxIncludingPricing();
        this.InternalCategoryList = new List<CategoryItem>();
        for(Category__c categoryItem  :  InternalCategoryList){
            this.InternalCategoryList.add(new CategoryItem(categoryItem) );
        
        }
        
        this.DeductibleAmount = 0;
        this.DeductibleTaxAmount = 0;
        for(SO_Payment_Role__c deductibleRec : deductibelRecordList) {
            this.DeductibleAmount += deductibleRec.Total_Amount__c;
            this.DeductibleTaxAmount += (deductibleRec.Tax_Amount__c != null ? deductibleRec.Tax_Amount__c : 0);
        }
        this.SubmittedDate = (claimRec.CreatedDate != null) ? 
                                BPUtility.getFormatedDateTime(datetime.newInstance(claimRec.CreatedDate.year(), claimRec.CreatedDate.month(),claimRec.CreatedDate.day())) 
                                : BPUtility.getFormatedDateTime(system.now());
          
    }
    
    public class CategoryItem{
        public String Id;
        public String CategoryName; 
        public CategoryItem(Category__c Internalcategory){
            this.Id = Internalcategory.Id;
            this.CategoryName = Internalcategory.Name;
        
        }
    }
    
    public class ClaimLineItem {
        
        public String Id;
        public Decimal ApprovedPrice;
        public Decimal ApprovedQty;
        public Decimal ApprovedSubTotal;
        public Decimal ClaimedPrice;
        public Decimal ClaimedQty;
        public Decimal ClaimedSubtotal;
        public String  ServiceOrderLineItem ;
        public String  SOPaymentRole;
        public String  BillTo;
        public Decimal DeductibleAmount;  
        public Decimal Tax;  
        public Decimal TaxAmount;
        public Decimal Variance;  
        
        /* START: Added By Tarun - #170 - 09/24/2016 */
        public String ItemCode {get; set;}
        public String ItemDescription {get; set;}
      
        public String Itemdesc; 
        public String Total;
        public String Claim;
        public Decimal VarianceQuantity;
        public Decimal VarianceAmount;
        public Boolean IsVariance;
        public String PaymentStatus;
        public Decimal TotalVariance;
        public String Category;
        public String CategoryName;
        public Boolean IsKitLI;
        public String SOLIType;
        public Boolean IsCalculateSupplies;
          
        public ClaimLineItem(Claim_Line_Item__c claimLineItemRec){
            this.Id = claimLineItemRec.Id;
            this.ApprovedPrice = claimLineItemRec.Approved_Price__c !=null ? (claimLineItemRec.Approved_Price__c).setScale(2, RoundingMode.HALF_UP) : 0 ;
            this.ApprovedQty =  claimLineItemRec.Approved_Qty__c !=null ? claimLineItemRec.Approved_Qty__c : 0 ;
            this.ApprovedSubTotal =  claimLineItemRec.Approved_Subtotal__c ;
            this.ClaimedPrice = claimLineItemRec.Claimed_Price__c !=null ? (claimLineItemRec.Claimed_Price__c).setScale(2, RoundingMode.HALF_UP) : 0 ;
            this.ClaimedQty = claimLineItemRec.Claimed_Qty__c !=null ? claimLineItemRec.Claimed_Qty__c : 0 ;
            this.ClaimedSubtotal = claimLineItemRec.Claimed_Subtotal__c;
            
            /* START: Added By Tarun - #170 - 09/24/2016 */
            this.ItemCode = claimLineItemRec.Item_Code__c;
            this.ItemDescription = claimLineItemRec.Item_Description__c;
            this.Itemdesc = this.ItemCode + ' - ' + this.ItemDescription;
            
            //need to update from Parent Soli parts records
            this.ServiceOrderLineItem  = claimLineItemRec.Service_Order_Line_Item__c !=null ? claimLineItemRec.Service_Order_Line_Item__c : null ;
            this.SOPaymentRole  = claimLineItemRec.SO_Payment_Role__c;
            this.Tax = claimLineItemRec.Tax__c;
            this.TaxAmount = claimLineItemRec.Tax_Amount__c != null ? (claimLineItemRec.Tax_Amount__c).setScale(2, RoundingMode.HALF_UP) : 0;
            this.Variance = claimLineItemRec.Variance__c;
            this.Claim = claimLineItemRec.Claim__c;
            this.DeductibleAmount = ((claimLineItemRec.SO_Payment_Role__c != null && claimLineItemRec.SO_Payment_Role__r.Total_Amount__c != null) ? 
                                        (claimLineItemRec.SO_Payment_Role__r.Total_Amount__c).setScale(2, RoundingMode.HALF_UP) : null);
            this.VarianceQuantity = claimLineItemRec.Variance_Qty__c;
            this.VarianceAmount = claimLineItemRec.Variance_Amount__c;
            this.IsVariance = claimLineItemRec.Is_Variance__c; 
            this.BillTo = (String.isNotBlank(claimLineItemRec.Bill_To__c) ? claimLineItemRec.Bill_To__c : ((claimLineItemRec.SO_Payment_Role__c !=null) ? 
                        claimLineItemRec.SO_Payment_Role__r.RecordType.DeveloperName : ((claimLineItemRec.Variance_Qty__c == 0 ) ? Constants.Internal : 'Customer')));
            this.PaymentStatus =( claimLineItemRec.SO_Payment_Role__c !=null ) ? claimLineItemRec.SO_Payment_Role__r.Status__c : null;
            this.TotalVariance = claimLineItemRec.Total_Variance_Amount__c != null ? (claimLineItemRec.Total_Variance_Amount__c).setScale(2, RoundingMode.HALF_UP) : 0;
            this.Category =  claimLineItemRec.Category__c;
            this.CategoryName = claimLineItemRec.Category__r.Name;
            this.IsKitLI = claimLineItemRec.Service_Order_Line_Item__c != null ? (claimLineItemRec.Service_Order_Line_Item__r.Kit_Header_Line_Item__c != null ? true : false) : false;
            this.SOLIType = claimLineItemRec.Service_Order_Line_Item__c != null ? claimLineItemRec.Service_Order_Line_Item__r.Type__c : '';
            if(claimLineItemRec.Service_Order_Line_Item__c != null && claimLineItemRec.Service_Order_Line_Item__r.Labour_Code__c != null) {
                this.IsCalculateSupplies = claimLineItemRec.Service_Order_Line_Item__r.Labour_Code__r.Calculate_Supplies__c;
            }
        }
    }
    
    public static List<String> getClaimFieldsList(){
        List<String> claimsFields = new List<String>{ 'Id',
                                                    'Name',
                                                    'Claim_Number__c',
                                                    'Notes__c',
                                                    'Claim_Disposition__c',
                                                    'Response_Date__c',
                                                    'Service_Order_Header__c',
                                                    'Provider_Claim_Number__c',
                                                    'CreatedDate'
                                                };  
        return claimsFields;
    }
    
    
    public static List<String> getClaimLineItemFieldsList(){
        List<String> claimLineItemFieldList = new List<String>{ 'Id',
                                                            'Approved_Price__c',
                                                            'Approved_Qty__c',
                                                            'Approved_Subtotal__c',
                                                            'Claimed_Price__c',
                                                            'Claimed_Qty__c',
                                                            'Claimed_Subtotal__c',
                                                            'Item_Desc__c',
                                                            'Service_Order_Line_Item__c',
                                                            'SO_Payment_Role__c',
                                                            'Tax__c ',
                                                            'Tax_Amount__c',
                                                            'Variance__c ',
                                                            'Claim__c ',
                                                            'SO_Payment_Role__r.Total_Amount__c',
                                                            'Variance_Qty__c',
                                                            'Variance_Amount__c',
                                                            'Is_Variance__c',
                                                            'SO_Payment_Role__r.RecordType.DeveloperName',
                                                            'SO_Payment_Role__r.Status__c',
                                                            'Total_Variance_Amount__c',
                                                            'Category__c',
                                                            'Category__r.Name',
                                                            'Item_Code__c',
                                                            'Item_Description__c',
                                                            'Service_Order_Line_Item__r.Kit_Header_Line_Item__c',
                                                            'Bill_To__c',
                                                            'Service_Order_Line_Item__r.Type__c',
                                                            'Service_Order_Line_Item__r.Labour_Code__r.Calculate_Supplies__c'
                                                };  
        return claimLineItemFieldList;
    }
}