src/objects/CO_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CO Deposit</label>
    <nameField>
        <displayFormat>CODN-{00000000}</displayFormat>
        <label>CO Deposits Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CO Invoice Payment</label>
    <nameField>
        <displayFormat>COIP-{00000000}</displayFormat>
        <label>CO Invoice Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_on_Account__c.object
<CustomObject>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>IF( ISBLANK(Amount_Paid__c) , Total_Payment__c ,  Amount_Paid__c )</formula>
        <label>Total Amount (Formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment on Account</label>
    <nameField>
        <displayFormat>POA-{00000000}</displayFormat>
        <label>Payment on Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments on Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CashReconciliationTTWrapper.cls
public without sharing class CashReconciliationTTWrapper {
    public String PaymentMethod;
    public String Icon;
    public Decimal TotalProcessedAmount;
    public Decimal TotalActualAmount;
    public Decimal TotalVarianceAmount;
    public List<CashDrawerDetailWrapper> CashDrawerDetailObjList;
    
    public CashReconciliationTTWrapper(Reconciliation_Payment__mdt paymentTypeRec, Map<String, List<Sobject>> drawerNameToCOPaymentListMap, Set<String> cashDrawerNameSet, Map<String, Decimal> drawerNameToActualAmountMap) {
        GlobalController obj = new GlobalController();
        this.PaymentMethod = paymentTypeRec.Label;
        this.Icon = paymentTypeRec.Icon_Link__c;
        this.TotalProcessedAmount = 0;
        this.TotalActualAmount = 0;
        this.TotalVarianceAmount = 0;
        CashDrawerDetailObjList = new List<CashDrawerDetailWrapper>();
        for(String drawerName: cashDrawerNameSet) {
            List<sObject> sObjectList = drawerNameToCOPaymentListMap != null && drawerNameToCOPaymentListMap.containsKey(drawerName) ? drawerNameToCOPaymentListMap.get(drawerName) : new List<sObject>();
            Decimal actualAmount = drawerNameToActualAmountMap != null && drawerNameToActualAmountMap.containsKey(drawerName) && drawerNameToActualAmountMap.get(drawerName) != null ? drawerNameToActualAmountMap.get(drawerName) : 0;
            CashDrawerDetailWrapper cashDrawerDetailObj = new CashDrawerDetailWrapper(drawerName, sObjectList, actualAmount);
            CashDrawerDetailObjList.add(cashDrawerDetailObj);
            this.TotalProcessedAmount += cashDrawerDetailObj.ProcessedAmount;
            this.TotalActualAmount += cashDrawerDetailObj.ActualAmount;
        }
        this.TotalProcessedAmount = this.TotalProcessedAmount.setScale(2, RoundingMode.HALF_UP);
        this.TotalActualAmount = this.TotalActualAmount.setScale(2, RoundingMode.HALF_UP);
        this.TotalVarianceAmount = this.TotalActualAmount - this.TotalProcessedAmount;
    }
    
    public class CashDrawerDetailWrapper {
        public String CashDrawerName;
        public Decimal ProcessedAmount;
        public Decimal ActualAmount;
        
        public CashDrawerDetailWrapper(String drawerName, List<sObject> sobjectList, Decimal actualAmount) {
            this.CashDrawerName = drawerName;
            this.ProcessedAmount = 0;
            this.ActualAmount = actualAmount;
            if(sobjectList == null) {
                sobjectList = new List<sObject>();
            }
            for(sObject sObjectRec : sobjectList) {
                Id sobjectId = String.valueOf(sobjectRec.get('Id'));
                if(sobjectId.getSObjectType().getDescribe().getName() == Constants.NAMESPACE + 'CO_Invoice_Payment__c') {
                    CO_Invoice_Payment__c coInvoicePaymentRec = (CO_Invoice_Payment__c)sobjectRec;
                    this.ProcessedAmount += (coInvoicePaymentRec.Amount__c != null ? coInvoicePaymentRec.Amount__c : 0.00);
                } else if(sobjectId.getSObjectType().getDescribe().getName() == Constants.NAMESPACE + 'CO_Deposit__c') {
                    CO_Deposit__c coDepositRec = (CO_Deposit__c)sobjectRec;
                    this.ProcessedAmount += (coDepositRec.Amount__c != null ? coDepositRec.Amount__c : 0.00);
                } else if(sobjectId.getSObjectType().getDescribe().getName() == Constants.NAMESPACE + 'Payment_on_Account__c') {
                    Payment_on_Account__c paymentOnAccountRec = (Payment_on_Account__c)sobjectRec;
                    this.ProcessedAmount += (paymentOnAccountRec.Total_Amount__c != null ? paymentOnAccountRec.Total_Amount__c : 0.00);
                }
            }
        }
    }

    public class JournalEntryInfoWrapper {
        public String GLAccountName;
        public String Description;
        public Decimal CreditAmount;
        public Decimal DebitAmount;
    
        public JournalEntryInfoWrapper(String GLAccountName, String Description, Decimal CreditAmount, Decimal DebitAmount) {
            this.GLAccountName = GLAccountName;
            this.Description = Description;
            this.CreditAmount = CreditAmount;
            this.DebitAmount = DebitAmount;
        }
    }
}