src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_status__c</fullName>
        <label>Order status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecalculateCOTaxesBatch.cls
/** 
* Author: Manoj Sharma
* Since: Oct 25, 2024
* Name: RecalculateCOTaxesBatch 
* Description: Apex class to recalculate open CO taxes.
**/
global without sharing class RecalculateCOTaxesBatch implements Database.Batchable<sObject>, Database.AllowsCallouts  {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id, Customer__c FROM CO_Header__c WHERE Order_status__c = \'Open\' ';
        return Database.getQueryLocator(strQuery); 
    }

    global void execute(Database.batchableContext bc, List<CO_Header__c> coHeaderList) {
        CORecalculationWrapper recalculationObj = new CORecalculationWrapper();
        recalculationObj.SOHeaderId = null;
        recalculationObj.IsRecalculateTaxes = true;
        recalculationObj.IsResetPricing = false;

        for(CO_Header__c coHeaderRec : coHeaderList) {
            recalculationObj.COHeaderId = coHeaderRec.Id;
            recalculationObj.CustomerId = coHeaderRec.Customer__c;
            COService.refreshCOPricingAndTax(System.JSON.serialize(recalculationObj));
            COService.addInternalCommentToCO(recalculationObj.COHeaderId, 'BP Admin recalculated the taxes on this CO.');
        }
    }

    global void finish(Database.batchableContext bc) {
        Database.executeBatch(new RecalculateKitTaxesBatch(), 1);
    }
}