src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CO Headers</relationshipLabel>
        <relationshipName>CO_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_Header_Total__c</fullName>
        <formula>Deal_Subtotal__c +  Deal_Tax_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deal Header Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Merchandise_Total__c</fullName>
        <formula>IF( $Setup.Configurations__c.Tax_Included_Pricing__c,  Merchandise_Subtotal_When_Tax_Included__c,  Merchandise_Sub_Total__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Merchandise Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberOfDeals__c</fullName>
        <label>NumberOfDeals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Group__c</fullName>
        <label>Selling Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CO_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Part Sale</fullName>
                </value>
                <value>
                    <fullName>Service Order</fullName>
                </value>
                <value>
                    <fullName>Unit Deal</fullName>
                </value>
                <value>
                    <fullName>Cash Sale</fullName>
                </value>
                <value>
                    <fullName>Internal Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Order_Subtotal__c</fullName>
        <label>Service Order Subtotal</label>
        <summarizedField>Service_Order_Header__c.Total__c</summarizedField>
        <summaryForeignKey>Service_Order_Header__c.CO_Header__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalNumberOfCOLI__c</fullName>
        <label>TotalNumberOfCOLI</label>
        <summaryFilterItems>
            <field>CO_Line_Item__c.Is_In_Service_Order__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CO_Line_Item__c.Is_Unresolved_Fulfillment_Exists__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>CO_Line_Item__c.Related_Option_And_Fees__c</field>
            <operation>equals</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>CO_Line_Item__c.CO_Header__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalNumberOfSOHeader__c</fullName>
        <label>TotalNumberOfSOHeader</label>
        <summaryFilterItems>
            <field>Service_Order_Header__c.Is_Unresolved_Fulfillment_Exists__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Service_Order_Header__c.SO_Type__c</field>
            <operation>notEqual</operation>
            <value>Deal</value>
        </summaryFilterItems>
        <summaryForeignKey>Service_Order_Header__c.CO_Header__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message_History__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Messages History</relationshipLabel>
        <relationshipName>Messages_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Formatted_Phone__c</fullName>
        <formula>IF(Phone__c != null, 
IF(Sent_To__c != null &amp;&amp; Sent_To__r.BillingCountry != null , 
IF(Sent_To__r.BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Phone__c) , 
8 , MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 5, 4) , 
10 , IF(BEGINS(Phone__c, &apos;04&apos;) || BEGINS(Phone__c, &apos;05&apos;) , 
MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 5, 3)+ &quot; &quot; +MID(Phone__c, 8, 3), 
MID(Phone__c, 0, 2) + &quot; &quot; +MID(Phone__c, 3, 4)+ &quot; &quot; +MID(Phone__c, 7, 4)) 
, Phone__c ), 


CASE( LEN(Phone__c) , 10, &quot;(&quot; + MID(Phone__c, 0, 3) + &quot;) &quot; +MID(Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Phone__c, 7, 4) , Phone__c)) 
, 
CASE( LEN(Phone__c) , 8 , MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 4, 4) , 
10, &quot;(&quot; + MID(Phone__c, 0, 3) + &quot;) &quot; +MID(Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Phone__c, 7, 4) , Phone__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMS_Body__c</fullName>
        <label>SMS Body</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incoming_SMS_Time__c</fullName>
        <label>Incoming SMS Time</label>
        <type>DateTime</type>
    </fields>

    <label>Message History</label>
    <nameField>
        <displayFormat>MSG-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message_Read_By__c.object
<CustomObject>
    <fields>
        <fullName>Message_Status__c</fullName>
        <label>Message Status</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <referenceTo>Message_History__c</referenceTo>
        <relationshipLabel>Messages Read By</relationshipLabel>
        <relationshipName>Messages_Read_By</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Message Read By</label>
    <nameField>
        <displayFormat>MRB-{00000000}</displayFormat>
        <label>Message Read By Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages Read By</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IncomingMessageWrapper.cls
/** 
* Author: Nidhi Sharma
* Since: Nov 19, 2020
* Name: IncomingMessageWrapper 
* Description: Apex wrapper which contains Incoming message fields.
**/
public without sharing class IncomingMessageWrapper {
    public List<IncomingMessage> UnreadMessageList;
    public List<IncomingMessage> ReadMessageList;
    public Map<String, List<COWrapper>> CustomerIdToRelatedCOInfoListMap;
    
    public IncomingMessageWrapper(List<IncomingMessage> unreadMsgList, List<IncomingMessage> readMsgList, List<CO_Header__c> coList) {
    	this.UnreadMessageList = unreadMsgList;
    	this.ReadMessageList = readMsgList;
    	
    	this.CustomerIdToRelatedCOInfoListMap = new Map<String, List<COWrapper>>();
    	for(CO_Header__c coRec : coList) {
    		if(!this.CustomerIdToRelatedCOInfoListMap.containsKey(coRec.Customer__c)) {
    			this.CustomerIdToRelatedCOInfoListMap.put(coRec.Customer__c, new List<COWrapper>());
    		}
    		this.CustomerIdToRelatedCOInfoListMap.get(coRec.Customer__c).add(new COWrapper(coRec));
    	}
    }
    
    public class COWrapper {
    	public String Id;
    	public String Name;
    	public String SectionTotalStr;
    	
    	public COWrapper(CO_Header__c coRec) {
    		this.Id = coRec.Id;
    		this.Name = coRec.Name;
    		this.SectionTotalStr = '';
    		if(coRec.TotalNumberOfCOLI__c > 0 && (coRec.Selling_Group__c == 'Part Sale' || coRec.Selling_Group__c == 'Cash Sale' || 
    																							coRec.Selling_Group__c == 'Internal Service')) {
    			this.SectionTotalStr += 'Parts & accessories $' + BPUtility.formatToDecimal(coRec.Merchandise_Total__c);
    		}
    		if(coRec.TotalNumberOfSOHeader__c > 0) {
    			this.SectionTotalStr += (this.SectionTotalStr.length() > 0 ? ', ' : '');
    			this.SectionTotalStr += 'Service $' + BPUtility.formatToDecimal(coRec.Service_Order_Subtotal__c);
    		}
    		if(coRec.NumberOfDeals__c > 0) {
    			this.SectionTotalStr += (this.SectionTotalStr.length() > 0 ? ', ' : '');
    			this.SectionTotalStr += 'Deal $' + BPUtility.formatToDecimal(coRec.Deal_Header_Total__c);
    		}
    	}	
    }
    
    public class IncomingMessage {
    	public String MessageReadById;
    	public String Text;
    	public String CustomerName;
    	public String TimeReceived;
    	public String CustomerId;
    	public String CustomerPhone;
    	
    	public IncomingMessage(Message_Read_By__c msgReadByRec) {
    		this.MessageReadById = msgReadByRec.Id;
    		this.Text = msgReadByRec.Message__r.SMS_Body__c;
    		if(msgReadByRec.Message__r.Incoming_SMS_Time__c != null) {
    			this.TimeReceived = BPUtility.getFormatedDateAndTimeWithHypen(msgReadByRec.Message__r.Incoming_SMS_Time__c);
    		}
    		
    		if(msgReadByRec.Message__r.Sent_To__c != null) {
    			this.CustomerId = msgReadByRec.Message__r.Sent_To__c;
    			this.CustomerName = msgReadByRec.Message__r.Sent_To__r.Name;
    		}
    		this.CustomerPhone = msgReadByRec.Message__r.Formatted_Phone__c;
    	}	
    }
    
    public static List<String> getMsgReadByFieldList() {
    	return new List<String>{'Id', 
    							'Message_Status__c',
    							'Message__r.SMS_Body__c',
    							'Message__r.Sent_To__r.Name', 
    							'Message__r.Incoming_SMS_Time__c', 
    							'Message__r.Formatted_Phone__c'
    							};
    }
    
    public static List<String> getCOFieldList() {
    	return new List<String>{'Id', 
    							'Name',
    							'Merchandise_Total__c',
    							'Service_Order_Subtotal__c', 
    							'Deal_Header_Total__c', 
    							'Customer__c',
    							'TotalNumberOfCOLI__c',
    							'TotalNumberOfSOHeader__c',
    							'NumberOfDeals__c',
    							'Selling_Group__c'
    							};
    }
}