src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Invoice_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Invoice Headers</relationshipLabel>
        <relationshipName>CO_Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>AutoNumberHolder__r.Name</formula>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Kit_Header__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Kit Headers</relationshipLabel>
        <relationshipName>CO_Kit_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CO Kit Header</label>
    <nameField>
        <displayFormat>COKH-{00000000}</displayFormat>
        <label>CO Kit Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Kit Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CO_Kit_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Kit Header</label>
        <referenceTo>CO_Kit_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_When_Tax_Included__c</fullName>
        <label>Price When Tax Included</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <formula>Invoice_Number__r.Tracking_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tracking Number</label>
        <type>Text</type>
    </fields>
    <label>CO Line Item</label>
    <nameField>
        <displayFormat>COLI-{00000000}</displayFormat>
        <label>CO Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Individual_Tax__c.object
<CustomObject>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Individual Taxes</relationshipLabel>
        <relationshipName>Individual_Taxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enhanced_Tax_Amount__c</fullName>
        <label>Enhanced Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <formula>IF( 
	Service_Order_Line_Item__c != null, 
	Service_Order_Line_Item__r.Qty_Needed__c,
	IF( 
		CO_Line_Item__c != null, 
		IF(
			CO_Line_Item__r.Part__c != null &amp;&amp; !CO_Line_Item__r.Part__r.Non_Inventory_Part__c &amp;&amp; (CO_Line_Item__r.Qty__c &gt; 0), 
			CO_Line_Item__r.Qty_Committed__c, 
			CO_Line_Item__r.Qty__c 
		), 
		IF(
			Option_Fee__c != null, 
			Option_Fee__r.Qty__c, 
			IF(
				Deal_Unit_Price_Cost__c != null, 
				Deal_Unit_Price_Cost__r.Qty__c, 
				IF(
					Deal_Item__c != null, 
					1,
					IF(
						F_I_Product__c != null, 
						1,
						0
					)
				)
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Individual Tax</label>
    <nameField>
        <displayFormat>ITN-{00000000}</displayFormat>
        <label>Individual Tax Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrintOrderFulfillmentCtrl.cls
/** 
* Author: Richa Mittal
* Since: Feb 10, 2021
* Name: PrintOrderFulfillmentCtrl 
* Description: Apex class which contains print order fulfillment related methods.
**/
global without sharing class PrintOrderFulfillmentCtrl {
    
    public String coInvId {get;private set;}
    public String brandingLocationId {get;private set;}
	public OrderFulfillmentWrapper OrderFulfillmentObj {get; private set;}
	public Boolean isHidePartNumbersOnDocuments{get{return GeneralConfiguration.isHidePartNumbersOnDocuments();} private set;}
    public Boolean isIncludeMSRPAndDiscountOnPartLines{get{return GeneralConfiguration.isIncludeMSRPAndDiscountOnPartLines();} private set;}
    
    public PrintOrderFulfillmentCtrl() {
        coInvId = ApexPages.currentPage().getParameters().get('id');
        brandingLocationId = ApexPages.currentPage().getParameters().get('brandingLocationId');
        if(String.isBlank(coInvId)) {
            return;
        }
        
        List<CO_Invoice_Header__c> coInvoiceList = PrintCustomerOrderInvoiceCtrl.getCustomerOrderInvoiceHeaders(new List<Id>{coInvId});
        List<CO_Line_Item__c> coLineItems = SOQLUtil.getCOLineItemByCOHeaderId(coInvoiceList[0].CO_Header__c);
        List<CO_Kit_Header__c> coKitHeaders = SOQLUtil.getCOKHByCOHeaderId(coInvoiceList[0].CO_Header__c);
        List<COHeaderWrapper.COKitHeader> COKHList = COHeaderWrapper.getCOLineItemsList(coLineItems, coKitHeaders);
        Map<String, CO_Line_Item__c> coLiIdToRecMap = new Map<String, CO_Line_Item__c>();
        for(CO_Line_Item__c coli: coLineItems) {
        	coLiIdToRecMap.put(coli.Id, coli);
        }
        
        BrandingLocationWrapper brandingLocationObj = COService.getBrandingLocationDataForPrint(brandingLocationId);
	    OrderFulfillmentObj = new OrderFulfillmentWrapper(coInvoiceList[0], COKHList, coLiIdToRecMap, brandingLocationObj);
    }
    
    public class OrderFulfillmentWrapper {
    	public PrintCustomerOrderInvoiceCtrl.COInvoiceDetail COInvoice {get; set;}
    	public CustomerDetail.Company CompanyInfo {get; set;}
    	public List<SectionWrapper> LineItemsSectionList {get; set;}
    	public String CustomerInvoiceWarrantyText{get; set;}
    	public String COHeaderNumber {get; set;}
    	
    	public OrderFulfillmentWrapper(CO_Invoice_Header__c coInvoiceHeader, List<COHeaderWrapper.COKitHeader> COKHList, Map<String, CO_Line_Item__c> coLiIdToRecMap, 
    									BrandingLocationWrapper brandingLocationObj) {
            this.COHeaderNumber = coInvoiceHeader.CO_Header__r.Name;    
            this.COInvoice = new PrintCustomerOrderInvoiceCtrl.COInvoiceDetail(coInvoiceHeader); 
            
            if(brandingLocationObj != null) {
                this.CompanyInfo = new CustomerDetail.Company(brandingLocationObj);
                this.CustomerInvoiceWarrantyText = (brandingLocationObj.DisclaimerforCustomerInvoice != null) ? brandingLocationObj.DisclaimerforCustomerInvoice : '';
            }
            this.CompanyInfo.BusinessPhone = this.CompanyInfo.FormattedBusinessPhone != null ? this.CompanyInfo.FormattedBusinessPhone: '';
            
            SectionWrapper thisShipment = new SectionWrapper(Constants.THIS_SHIPMENT, coInvoiceHeader.Invoice_Number__c, coInvoiceHeader.Tracking_Number__c);
            SectionWrapper notYetShipped = new SectionWrapper(Constants.NOT_YET_SHIPPED, '', '');
            Map<String, SectionWrapper> previousShipmentMap = new Map<String, SectionWrapper>();
            
            this.LineItemsSectionList = new List<SectionWrapper>();
            for(COHeaderWrapper.COKitHeader cokhRec: COKHList) {
            	if(cokhRec.COLIList.size() > 0) {
            		String invoiceNumber = '';
            		String trackingNumber = '';
            		Decimal totalWithTax = 0;
            		for(COLineItem coli: cokhRec.COLIList) {
            			CO_Line_Item__c coliRec = coLiIdToRecMap.containsKey(coli.CoLineItemId) ? coLiIdToRecMap.get(coli.CoLineItemId) : null;
            			if(coliRec != null) {
            				invoiceNumber = coliRec.Invoice_Number__c != null ? coliRec.Invoice_Number__r.Invoice_Number__c : '';
        					trackingNumber = coliRec.Tracking_Number__c != null ? coliRec.Tracking_Number__c : '';
            				totalWithTax += getcoliTotalWithTax(coliRec);
            			}
            		}
            		
            		if(String.isBlank(cokhRec.COLIList[0].Invoice)) {
            			notYetShipped.SectionTotal += totalWithTax;
	            		notYetShipped.COKHList.add(cokhRec);
	            	} else if(cokhRec.COLIList[0].Invoice == coInvoiceHeader.Name) {
	            		thisShipment.SectionTotal += totalWithTax;
	            		thisShipment.COKHList.add(cokhRec);
	            	} else {
	            		if(!previousShipmentMap.containsKey(invoiceNumber)) {
	            			previousShipmentMap.put(invoiceNumber, new SectionWrapper(Constants.PREVIOUS_SHIPMENT, invoiceNumber, trackingNumber));
	            		}
	            		previousShipmentMap.get(invoiceNumber).SectionTotal += totalWithTax;
	            		previousShipmentMap.get(invoiceNumber).COKHList.add(cokhRec);
	            	}
            	}
            }
            this.LineItemsSectionList.add(thisShipment);
            if(previousShipmentMap.size() > 0) {
            	this.LineItemsSectionList.addAll(previousShipmentMap.values());
            } else {
            	this.LineItemsSectionList.add(new SectionWrapper(Constants.PREVIOUS_SHIPMENT, '', ''));
            }
            this.LineItemsSectionList.add(notYetShipped);
    	}
    }
    
    public class SectionWrapper {
    	public String SectionName {get; set;}
    	public String InvoiceNumber {get; set;}
    	public String TrackingNumber {get; set;}
    	public Decimal SectionTotal {get; set;}
    	public List<COHeaderWrapper.COKitHeader> COKHList {get; set;}
    	
    	public SectionWrapper(String sectionName, String invoiceNumber, String trackingNumber) {
    		this.SectionName = sectionName;
    		this.InvoiceNumber = invoiceNumber;
			this.TrackingNumber = trackingNumber;
			this.SectionTotal = 0;
			this.COKHList = new List<COHeaderWrapper.COKitHeader>();
    	}
    }
    
    private static Decimal getcoliTotalWithTax(CO_Line_Item__c coliRec) {
    	coliRec.Qty__c = (coliRec.Qty__c == null) ? 0 : coliRec.Qty__c;
        coliRec.Price__c = (coliRec.Price__c == null) ? 0 : coliRec.Price__c;
        
        if(GeneralConfiguration.getTaxIncludingPricing()) {
        	coliRec.Price_When_Tax_Included__c = (coliRec.Price_When_Tax_Included__c == null) ? 0 : coliRec.Price_When_Tax_Included__c;
			return (coliRec.Price_When_Tax_Included__c * coliRec.Qty__c).setScale(2, RoundingMode.HALF_UP);
		} else {
			Decimal coliTaxAmount = 0;
			for(Individual_Tax__c individualTaxRec : coliRec.Individual_Taxes__r) {
            	if(individualTaxRec.Enhanced_Tax_Amount__c != null) {
            		coliTaxAmount += individualTaxRec.Enhanced_Tax_Amount__c;
            	} else {
            		individualTaxRec.Tax_Rate__c = (individualTaxRec.Tax_Rate__c != null) ? individualTaxRec.Tax_Rate__c : 0;
            		coliTaxAmount += (individualTaxRec.Tax_Rate__c * coliRec.Qty__c * coliRec.Price__c) / 100;
            	}
            }
            return ((coliRec.Price__c * coliRec.Qty__c) + coliTaxAmount).setScale(2, RoundingMode.HALF_UP);
		}
    }
}