src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Order_Closed_Date__c</fullName>
        <formula>IF( Status__c == &apos;Closed&apos; , LastModifiedDate , NOW())</formula>
        <label>Order Closed Date</label>
        <type>DateTime</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_Two_Way_Text__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Configuration setting to enable or disable SMS reply functionality</description>
        <inlineHelpText>Configuration setting to enable or disable SMS reply functionality</inlineHelpText>
        <label>Enable Two Way Text</label>
        <type>Checkbox</type>
    </fields>
    <label>General Configurations</label>
</CustomObject>

src/objects/Message_History__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Emailed Invoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Messages History</relationshipLabel>
        <relationshipName>Messages_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealership_Phone__c</fullName>
        <label>Dealership Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Formatted_Phone__c</fullName>
        <formula>IF(Phone__c != null, 
IF(Sent_To__c != null &amp;&amp; Sent_To__r.BillingCountry != null , 
IF(Sent_To__r.BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Phone__c) , 
8 , MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 5, 4) , 
10 , IF(BEGINS(Phone__c, &apos;04&apos;) || BEGINS(Phone__c, &apos;05&apos;) , 
MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 5, 3)+ &quot; &quot; +MID(Phone__c, 8, 3), 
MID(Phone__c, 0, 2) + &quot; &quot; +MID(Phone__c, 3, 4)+ &quot; &quot; +MID(Phone__c, 7, 4)) 
, Phone__c ), 


CASE( LEN(Phone__c) , 10, &quot;(&quot; + MID(Phone__c, 0, 3) + &quot;) &quot; +MID(Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Phone__c, 7, 4) , Phone__c)) 
, 
CASE( LEN(Phone__c) , 8 , MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 4, 4) , 
10, &quot;(&quot; + MID(Phone__c, 0, 3) + &quot;) &quot; +MID(Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Phone__c, 7, 4) , Phone__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sent_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Thsi is not used now. Instead we use SMS_Body__c.</description>
        <inlineHelpText>Thsi is not used now. Instead we use SMS_Body__c.</inlineHelpText>
        <label>Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Direction__c</fullName>
        <label>SMS Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Reply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incoming_SMS_Time__c</fullName>
        <label>Incoming SMS Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SMS_Sent_From__c</fullName>
        <label>SMS Sent From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Customer Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message_UUID__c</fullName>
        <label>Message UUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>

    <label>Message History</label>
    <nameField>
        <displayFormat>MSG-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message_Read_By__c.object
<CustomObject>
    <fields>
        <fullName>Message_Status__c</fullName>
        <label>Message Status</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <referenceTo>Message_History__c</referenceTo>
        <relationshipLabel>Messages Read By</relationshipLabel>
        <relationshipName>Messages_Read_By</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Messages_Read_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message Read By</label>
    <nameField>
        <displayFormat>MRB-{00000000}</displayFormat>
        <label>Message Read By Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages Read By</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Group__c.object
<CustomObject>
    <description>This object have children -user ( all  user govern by groups on them )</description>
    <fields>
        <fullName>View_Incoming_Text_Messages__c</fullName>
        <label>View Incoming Text Messages</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Group</label>
    <nameField>
        <label>User group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_To_Group__c.object
<CustomObject>
    <fields>
        <fullName>User_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Group</label>
        <referenceTo>User_Group__c</referenceTo>
        <relationshipLabel>User To Groups</relationshipLabel>
        <relationshipName>User_To_Groups1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_To_Groups1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User To Group</label>
    <nameField>
        <displayFormat>UG - {0000}</displayFormat>
        <label>User To Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User To Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageHistoryService.cls
public without sharing class MessageHistoryService {
    
    public static void addMessageHistoryRecord(String customerId, PlivoIncomingMessageService.MessageWrapper messageObj) {
    	List<Message_History__c> msgUUIDList = [Select Id from Message_History__c where Message_UUID__c =: messageObj.MessageUUID];
    	if(msgUUIDList.size() == 0) {
	        Message_History__c messageRec = new Message_History__c();
	        messageRec.Activity__c = Constants.MESSAGE_HISTORY_ACTIVITY_TEXT_MESSAGE;
	        messageRec.Sent_To__c = customerId;
	        messageRec.Text__c = messageObj.MessageText;
	        messageRec.SMS_Direction__c = Constants.SMS_DIRECTION_REPLY;
	        messageRec.Message_UUID__c = messageObj.MessageUUID;
	        messageRec.Phone__c = messageObj.CustomerPhone;
	        messageRec.Incoming_SMS_Time__c = system.now();
	        messageRec.Dealership_Phone__c = messageObj.DealershipPhone;
	        if(AccessControl.ifObjectFieldIsCreateable('Message_History__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_CREATEABLE); }
	        insert messageRec;
	        
	        createMessageReadByRecords(messageRec.Id);
    	}
    }
    
    public static List<CustomerDetail.MessageHistory> getTextHistory(String customerId, String coHeaderId) {
    	List<CO_Header__c> coHeaderList = [SELECT CreatedDate, Order_Closed_Date__c FROM CO_Header__c WHERE Id =: coHeaderId];
    	if(coHeaderList.size() == 0) throw new BlackPurlException('Invalid CO Id');
    	
    	List<Message_History__c> messageHistoryList = [SELECT Text__c, Incoming_SMS_Time__c, CreatedDate, SMS_Direction__c, 
    													SMS_Sent_From__c, Formatted_Phone__c, CO_Header__r.Name, Sent_To__c 
    													FROM Message_History__c WHERE Activity__c = :Constants.MESSAGE_HISTORY_ACTIVITY_TEXT_MESSAGE AND Sent_To__c =: customerId 
    													AND ((SMS_Direction__c = :Constants.SMS_DIRECTION_SENT AND CreatedDate >= :coHeaderList[0].CreatedDate) 
    													OR (SMS_Direction__c = :Constants.SMS_DIRECTION_REPLY AND Incoming_SMS_Time__c >= :coHeaderList[0].CreatedDate)) 
    													AND CreatedDate <= :coHeaderList[0].Order_Closed_Date__c 
    													order by CreatedDate desc];
    													
    	List<CustomerDetail.MessageHistory> messageHistoryWrapperList = new List<CustomerDetail.MessageHistory>();
    	for(Message_History__c msgRec: messageHistoryList) {
    		messageHistoryWrapperList.add(new CustomerDetail.MessageHistory(msgRec, true));
    	}
    	
    	return messageHistoryWrapperList;
    }
    
    private static void createMessageReadByRecords(String messageRecId) {
    	if(General_Configurations__c.getInstance().Enable_Two_Way_Text__c) {
	        List<User> userList = [Select Id from User where Id IN (Select User__c from User_To_Group__c where User_Group__r.View_Incoming_Text_Messages__c = 'Primary')];
	        List<Message_Read_By__c> messageReadbyListToInsert = new List<Message_Read_By__c>();
	        
	        for(User useRec : userList) {
	        	Message_Read_By__c msgReadByRec = new Message_Read_By__c();
	        	msgReadByRec.User__c = useRec.Id;
	        	msgReadByRec.Message__c = messageRecId;
	        	msgReadByRec.Message_Status__c = Constants.MESSAGE_STATUS_UNREAD;
	        	messageReadbyListToInsert.add(msgReadByRec);
	        }
	        if(messageReadbyListToInsert.size() > 0) {
	        	if(AccessControl.ifObjectFieldIsCreateable('Message_Read_By__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_CREATEABLE); }
	        	insert messageReadbyListToInsert;
	        }
    	}
    }
}