src/objects/CO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(Order_status__c)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <label>Integration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QuickBooks Online</fullName>
                </value>
                <value>
                    <fullName>QB</fullName>
                </value>
                <value>
                    <fullName>MYOB</fullName>
                </value>
                <value>
                    <fullName>SOM</fullName>
                </value>
                <value>
                    <fullName>XERO</fullName>
                </value>
                <value>
                    <fullName>Part Count</fullName>
                </value>
                <value>
                    <fullName>HONDA</fullName>
                </value>
                <value>
                    <fullName>Automated Price File</fullName>
                </value>
                <value>
                    <fullName>FTP</fullName>
                </value>
                <value>
                    <fullName>Generic Export</fullName>
                </value>
                <value>
                    <fullName>Re-Open Deal</fullName>
                </value>
                <value>
                    <fullName>Re-Open Invoice</fullName>
                </value>
                <value>
                    <fullName>Shopify</fullName>
                </value>
                <value>
	                <fullName>Preferred Payment</fullName>
	            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Info__c</fullName>
        <label>Log Info</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Params__c</fullName>
        <label>Method Params</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Qty_On_Order__c &gt; 0,&apos;On Order&apos;,  IF( OR((Qty_In_Stock__c &lt; Auto_reorder_Min__c),( AND((Qty_In_Stock__c = Auto_reorder_Min__c),( Auto_reorder_Min__c !=  Auto_reorder_Max__c )))), &apos;Required&apos;, IF(Qty_In_Stock__c &gt; 0, &apos;In Stock&apos;,&apos;Out of Stock&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>Vendor__r.Vendor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SOM_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Org_Code__c</fullName>
        <label>Org Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOM_sftp_URL__c</fullName>
        <label>SOM sftp URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upload_Directory__c</fullName>
        <label>Upload Directory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SOM Configuration</label>
</CustomObject>

src/objects/SOM_Integration__c.object
<CustomObject>
    <label>SOM Integration</label>
    <nameField>
        <displayFormat>SOM-{00000000}</displayFormat>
        <label>SOM Integration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOM Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Header__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Date_Formula__c</fullName>
        <formula>IF(  ISBLANK(Expected_Date__c) ,   TODAY() +  Purchase_Order_Type__r.Lead_Time__c  ,  IF( AND(ISPICKVAL(Status__c, &apos;Open&apos;), (Expected_Date__c - TODAY()) &lt; 0) , TODAY() +  Purchase_Order_Type__r.Lead_Time__c, Expected_Date__c) )</formula>
        <label>Expected Date Formula</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Date__c</fullName>
        <label>Expected Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ordered_Date__c</fullName>
        <label>Ordered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Partially Received</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vendor Order Header</label>
    <nameField>
        <displayFormat>VO-{00000000}</displayFormat>
        <label>Vendor Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Received</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_Needed__c</fullName>
        <label>Qty Needed</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Partially Received</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>IF( Part__c != null, Part__r.Vendor__r.Vendor_Code__c,IF( Sublet__c != null, Sublet__r.Vendor__r.Vendor_Code__c, &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Order Header</label>
        <referenceTo>Vendor_Order_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Line Item</label>
    <nameField>
        <displayFormat>VOLI-{00000000}</displayFormat>
        <label>Vendor Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SOMPartsOnOrderBatch.cls
/**
* Author : Tarun Khandelwal
* Since : Nov 01, 2019
* Name : SOMPartsOnOrderBatch
* Description : Batch class to export data for Vendor Order line itesm for SOM Integration
**/
global without sharing class SOMPartsOnOrderBatch implements Database.Batchable<sobject>, Database.AllowsCallouts, Database.Stateful, Schedulable {
    
    public String fileData;
    public Integer totalRecords = 0;
    private DateTime dateTimeValue;
    
    private static List<Log__c> logListToInsert = new List<Log__c>();
    public static String pathURLToImport = '/api/2.1/path/data';
    public static String fileSeparator = '|';
    public static String newLineSeparator = '\r\n'; 
    public static final String PART_INVENTORY_SNAPSHOT = 'Part inventory snapshot';
    public static final String PART_SALES_TRANSACTIONS = 'Part sales transactions';
    public static final String PARTS_ON_ORDER = 'Parts on order';
    public static String contentType = 'text/csv';
    public static String csvFileExtension = '.csv';
    public static Integer POORetryCount = 0;
    
    global SOMPartsOnOrderBatch(Date dateValueToFilter) {
        this.dateTimeValue = DateTime.newInstance(dateValueToFilter.year(), dateValueToFilter.month(), dateValueToFilter.day());
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        fileData = '';
        String query = 'SELECT Vendor_Order_Header__r.Name, Part__r.Vendor_Code__c, Part__r.Part_Number__c, Qty_Needed__c, '+
                        'CO_Header__c, Vendor_Order_Header__r.Ordered_Date__c, Vendor_Order_Header__r.Expected_Date__c, Vendor_Order_Header__r.Expected_Date_Formula__c FROM Vendor_Order_Line_Item__c ' + 
                'WHERE Part__c != null AND Is_Received__c = false AND Vendor_Order_Header__r.Status__c IN (\'On Order\', \'Partially Received\')';
        query += this.dateTimeValue != null ? ' AND CreatedDate < ' + (this.dateTimeValue.addDays(1)).formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') : '';
        query += ' Order By Part__r.Part_Number__c ASC';
        return Database.getQueryLocator(query);
    }
    
    public static String getOrgCode() {
        return SOM_Configuration__c.getOrgDefaults().Org_Code__c;
    }

    global void execute(Database.batchableContext bc, List<Vendor_Order_Line_Item__c> voliList) {
        try{
            for(Vendor_Order_Line_Item__c voliRec : voliList) {
                fileData += (getOrgCode() + fileSeparator);
                fileData += (voliRec.Vendor_Order_Header__r.Name + fileSeparator);
                fileData += (voliRec.Part__r.Vendor_Code__c + fileSeparator);
                fileData += (voliRec.Part__r.Part_Number__c + fileSeparator);
                fileData += ((voliRec.Qty_Needed__c != null ? voliRec.Qty_Needed__c : 0) + fileSeparator);
                fileData += ((voliRec.CO_Header__c != null ? '1' : '0') + fileSeparator);
                
                if(voliRec.Vendor_Order_Header__r.Expected_Date_Formula__c != null && 
                    System.today().daysBetween(voliRec.Vendor_Order_Header__r.Expected_Date_Formula__c) > 30) {
                        fileData += '1' + fileSeparator;
                } else {
                    fileData += '0' + fileSeparator;
                }

                if(voliRec.Vendor_Order_Header__r.Ordered_Date__c != null) {
                    Date orderedDate = voliRec.Vendor_Order_Header__r.Ordered_Date__c;
                    String orderedString = DateTime.newInstance(orderedDate.year(), orderedDate.month(), orderedDate.day()).format('yyyy-MM-dd');
                    fileData += (orderedString + fileSeparator);
                }
                if(voliRec.Vendor_Order_Header__r.Expected_Date__c != null) {
                    Date expectedDate = voliRec.Vendor_Order_Header__r.Expected_Date__c;
                    String expectedString = DateTime.newInstance(expectedDate.year(), expectedDate.month(), expectedDate.day()).format('yyyy-MM-dd');
                    fileData += expectedString;
                }
                fileData += newLineSeparator;
                totalRecords++;
            }
        } catch (Exception e) {
            //createLog('SOMPartsOnOrderBatch', 'execute()', e, null, 'Error');
        }
    }
    
    global void finish(Database.batchableContext bc) {
        handleFinish(PARTS_ON_ORDER, fileData, totalRecords, null, dateTimeValue);
        
        Date todaysDate = Date.newInstance(dateTimeValue.year(), dateTimeValue.month(), dateTimeValue.day());
        runNextJobAt10PM(todaysDate.addDays(1));
    }
    
    public static void runNextJobAt10PM(Date dateToRun) {
        String jobName = 'SOM POO file generation';
        List<CronTrigger> existingSheduledJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name =: jobName];
        if(existingSheduledJobs.size() > 0) {
            system.abortJob(existingSheduledJobs[0].Id);
        }
        String CRON_EXP = '0 0 22 ? * * *';
        if(!Test.isRunningTest()) {
            system.schedule(jobName, CRON_EXP, new SOMPartsOnOrderBatch(dateToRun));
        }
    }
    
    global void execute(SchedulableContext sc) {
        Date todaysDate = Date.newInstance(dateTimeValue.year(), dateTimeValue.month(), dateTimeValue.day());
        Database.executeBatch(new SOMPartsOnOrderBatch(todaysDate), 500);
    }
    
    public static void handleFinish(String fileType, String fileContent, Integer totalRecords, Integer batchNumber, DateTime dateOfFileData) {
        try {
        	Attachment attch = createAttachment(fileType, fileContent, totalRecords, batchNumber, dateOfFileData);
	        
	        uploadToSFTPServer(attch.Body, attch.Name);

	        if(attch.ParentId == null) {
	            SOM_Integration__c SOMIntegrationRec = new SOM_Integration__c();
	            insert SOMIntegrationRec;
	            attch.ParentId = SOMIntegrationRec.Id;
	        }
	        insertAttachment(new List<Attachment>{attch}, fileType);
	        
        } catch(Exception e) {
    		logListToInsert.add(new Log__c(Integration_Type__c = 'SOM', Log_Info__c = e.getMessage(),
	        				Method_Params__c = 'fileType ' + fileType, Method__c = 'handleFinish()', 
							Apex_Class__c = 'SOMPartsOnOrderBatch', Type__c = 'Error'));
    	}
        if(logListToInsert.size() > 0) {
        	insert logListToInsert;
        }
    }
    
    private static void uploadToSFTPServer(Blob fileContentBlob, String fileName) {
        SOM_Configuration__c somConfig = SOM_Configuration__c.getOrgDefaults();
        
        if(String.isNotBlank(somConfig.Username__c) && String.isNotBlank(somConfig.Password__c) && 
                String.isNotBlank(somConfig.Upload_Directory__c) && String.isNotBlank(somConfig.SOM_sftp_URL__c)) {
            String endPoint = somConfig.SOM_sftp_URL__c + pathURLToImport + somConfig.Upload_Directory__c;
            String userName = somConfig.Username__c;
            String password = somConfig.Password__c;
            
            String authHeaderValue = generateToken(userName, password);
            String boundary = '----------------------------741e90d31eff';
            Blob bodyBlob = getRequestBody(fileContentBlob, fileName, boundary); 
            
            System.enqueueJob(new FilePostToSOMQueueable(endPoint, authHeaderValue, bodyBlob, fileName, 0));
        } else {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.ToAddresses = new List<String>{'blackpurl@metacube.com'};
            message.Subject = UserInfo.getOrganizationName() + ' - SOM Parts on order status failed - Check configurations ';
            message.PlainTextBody = 'Hi,\n\n'+ 
                                    'Please check som configurations \n\n' +
                                    'Thank You\nTeam Blackpurl';
            
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{message});
            logListToInsert.add(new Log__c(Integration_Type__c = 'SOM', Log_Info__c = 'Blank response', 
	                        Method_Params__c = 'File name ' + fileName, 
	                        Apex_Class__c = 'SOMPartsOnOrderBatch - Get response', Type__c = 'Error'));
            sendFinishMail(null, fileName);
        }
    }
    
    public static void sendFinishMail(HTTPResponse res, String fileName) {
        String status = res != null && (res.getStatusCode() == 200 || res.getStatusCode() == 201) ? 'Success' : 'Failed';
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.ToAddresses = new List<String>{'blackpurl@metacube.com'};
        message.Subject = UserInfo.getOrganizationName() + ' - SOM Part On Order posting ' + status + ' with status code ' + res.getStatusCode();
        message.PlainTextBody = 'Hi,\n\n'+ 
                                'SOM Part on order File - ' + fileName + ' posting ' + status + '\n\n' +
                                'Thank You\nTeam Blackpurl';
        
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{message});
    }
    
    private static String generateToken(String username, String password) {
        Blob headerValue = Blob.valueOf(username + ':' + password);
        return 'Basic ' + EncodingUtil.base64Encode(headerValue);
    }
    
    private static Blob getRequestBody(Blob fileBody, String fileName, String boundary) {
        String header = '--'+boundary+'\nContent-Disposition: form-data; name="file"; filename="'+fileName+'";\nContent-Type: application/octet-stream';
        String footer = '--'+boundary+'--';             
        String headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
        while(headerEncoded.endsWith('=')) {
            header+=' ';
            headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
        }
        String bodyEncoded = EncodingUtil.base64Encode(fileBody);
 
        Blob bodyBlob = null;
        String last4Bytes = bodyEncoded.substring(bodyEncoded.length()-4,bodyEncoded.length());
 
        if(last4Bytes.endsWith('==')) {
            last4Bytes = last4Bytes.substring(0,2) + '0K';
            bodyEncoded = bodyEncoded.substring(0,bodyEncoded.length()-4) + last4Bytes;
        } else if(last4Bytes.endsWith('=')) {
            last4Bytes = last4Bytes.substring(0,3) + 'N';
            bodyEncoded = bodyEncoded.substring(0,bodyEncoded.length()-4) + last4Bytes;
            footer = '\n' + footer;
        } else {
            footer = '\r\n' + footer;
        }
        
        String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
        return EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);  
    }
    
    private static Map<String, List<String>> fileTypeToFieldLabelListMap = new Map<String, List<String>> {
                    PART_INVENTORY_SNAPSHOT => new List<String>{'OrgCode','PartNumber','VendorCode','PartGroupID','QtyAvailable','Cost','AvgCost','Price','IsPackage',
                                                            'PackageUnit','ServiceQty','IsGM','Style','ObsoleteStatus','Inactive','NonStock','Superseded','SupersededTo',
                                                            'Seasonal','SeasonStartMonth','SeasonStartDay','SeasonEndMonth','SeasonEndDay','CreatedOn'},
                                                            
                    PART_SALES_TRANSACTIONS => new List<String>{'OrgCode','InvoiceID','CustomerID','PartNumber','VendorCode','Qty','Price','Cost','ExceptionalSale',
                                                            'IsSpecialOrder','CustomerCity','CustomerState','CustomerCountry','SoldBy','SoldOn'},
                                                            
                    PARTS_ON_ORDER => new List<String>{'OrgCode', 'PONumber', 'VendorCode', 'PartNumber', 'QtyOrderedNotReceived', 
                                                            'IsSpecialOrder', 'ExceptionalOrder', 'SubmittedOn', 'ExpectedOn'}
    };
    
    public static String getHeaderByFileType(String fileType) {
        String header = '';
        if(fileTypeToFieldLabelListMap.containsKey(fileType)) {
            header = String.join(fileTypeToFieldLabelListMap.get(fileType), fileSeparator);
        }
        return header;
    }
    
    public static Attachment createAttachment(String fileType, String fileContent, Integer totalLines, Integer batchNumber, DateTime dateOfFileData) {
        Attachment attachment = new Attachment();
        
        fileContent = getHeaderByFileType(fileType) + newLineSeparator + fileContent;
        attachment.ParentId = getSOMAttachmentParentId(); 
        attachment.ContentType = contentType;
        attachment.Description = fileType;
        
        dateOfFileData = dateOfFileData != null ? dateOfFileData : system.now();
        attachment.Name = getFileNameByFileType(fileType, dateOfFileData) + (batchNumber != null ? ('_' + batchNumber) : '') + csvFileExtension;
        attachment.Body = Blob.valueOf(fileContent);
        return attachment;
    }
    
    private static Map<String, String> fileTypeToFileNameInitialsMap = new Map<String, String> {PART_INVENTORY_SNAPSHOT => 'INV',
                                                                                                PART_SALES_TRANSACTIONS => 'PSI',
                                                                                                PARTS_ON_ORDER => 'POO'};
    
    public static String getFileNameByFileType(String fileType, DateTime dateTimeValue) {
        String fileName = '';
        if(fileTypeToFileNameInitialsMap.containsKey(fileType)) {
            fileName = fileTypeToFileNameInitialsMap.get(fileType) + '_';
        }
        fileName += getOrgCode() + '_';
        fileName += (dateTimeValue != null ? dateTimeValue.format('yyyyMMdd') : Datetime.now().format('yyyyMMdd'));
        
        return fileName;
    }
    
    public static String getSOMAttachmentParentId() {
        List<SOM_Integration__c> SOMIntegrationList = [SELECT Id FROM SOM_Integration__c LIMIT 1];
        
        SOM_Integration__c SOMIntegrationRec = new SOM_Integration__c();
        if(SOMIntegrationList.size() > 0) {
            SOMIntegrationRec = SOMIntegrationList[0];
        }
        return SOMIntegrationRec.Id;
    }
    
    private static void insertAttachment(List<Attachment> attachmentRecList, String fileType) {
        DMLUtility.insertSobjectList('Attachment', attachmentRecList);
    }
}