src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Order</description>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/F_I_Product__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>F &amp; I Products</relationshipLabel>
        <relationshipName>F_I_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Item Description</description>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Type__c</field>
                <operation>equals</operation>
                <value>Financing Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>F &amp; I Products</relationshipLabel>
        <relationshipName>F_I_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>F &amp; I Product</label>
    <nameField>
        <displayFormat>FI-{00000000}</displayFormat>
        <label>F &amp; I Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F &amp; I Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Option_Fee__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Not in use</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Options &amp; Fees</relationshipLabel>
        <relationshipName>Options_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Options &amp; Fees</relationshipLabel>
        <relationshipName>Options_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Option &amp; Fee</label>
    <nameField>
        <displayFormat>OF-{000000}</displayFormat>
        <label>Option &amp; Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options &amp; Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VendorProductTriggerHelper.cls
/**
 * Author: Nidhi Sharma
 * Since: June. 15, 2017
 * Name: VendorProductTriggerHelper
 * Description: Helper class for triggers on VendorProduct object
**/
public without sharing class VendorProductTriggerHelper {
	
	// List to store trigger new list
    public static List<Product__c> vendorProductNewList = new List<Product__c>();
    
    // List to store trigger old list
    public static List<Product__c> vendorProductOldList = new List<Product__c>();
    
    // Map to store new Trigger Map
    public static Map<Id, Product__c> vendorProductNewMap = new Map<Id, Product__c>();
    
    // Map to store Old Trigger Map
    public static Map<Id, Product__c> vendorProductOldMap = new Map<Id, Product__c>();
    
    /**
     * Name: afterUpdateOperation 
    **/
    public static void afterUpdateOperation() {
    	//List<SObject> sObjectListToUpdate = new List<SObject>();
    	List<Option_Fee__c> optionAndFeeListToUpdate = new List<Option_Fee__c>();
    	Map<Id, Product__c> productIdToProductRecMap = new Map<Id, Product__c>([Select Id, Code__c, Description__c, (Select Id, Item_Code__c, Item_Description__c from Options_Fees__r where Deal__r.CO_Header__r.Order_status__c != 'Closed'), (Select Id, Item_Description__c from F_I_Products__r where Deal__r.CO_Header__r.Order_status__c != 'Closed') from Product__c where Id IN : vendorProductNewMap.keySet()]);
    	
    	for(Product__c productRec : vendorProductNewList) {
    		if(productIdToProductRecMap.containsKey(productRec.Id)) {
    			for(Option_Fee__c optionAndFeeRec : productIdToProductRecMap.get(productRec.Id).Options_Fees__r) {
    				Boolean isUpdated = false;
    				if((String.isNotBlank(vendorProductOldMap.get(productRec.Id).Code__c) && String.isBlank(productRec.Code__c)) || 
    							(String.isBlank(vendorProductOldMap.get(productRec.Id).Code__c) && String.isNotBlank(productRec.Code__c)) || 
    							(String.isNotBlank(vendorProductOldMap.get(productRec.Id).Code__c) && String.isNotBlank(productRec.Code__c) 
    														&& vendorProductOldMap.get(productRec.Id).Code__c != productRec.Code__c)) {
    					optionAndFeeRec.Item_Code__c = productRec.Code__c;
    					isUpdated = true;
    				}
    				
    				if((String.isNotBlank(vendorProductOldMap.get(productRec.Id).Description__c) && String.isBlank(productRec.Description__c)) || 
    							(String.isBlank(vendorProductOldMap.get(productRec.Id).Description__c) && String.isNotBlank(productRec.Description__c)) || 
    							(String.isNotBlank(vendorProductOldMap.get(productRec.Id).Description__c) && String.isNotBlank(productRec.Description__c) 
    														&& vendorProductOldMap.get(productRec.Id).Description__c != productRec.Description__c)) {
    					optionAndFeeRec.Item_Description__c = productRec.Description__c;
    					isUpdated = true;
    				}
            		
            		if(isUpdated) {
            			optionAndFeeListToUpdate.add(optionAndFeeRec);
            		}
					
    			}
    			/*for(F_I_Product__c fAndIProductRec : productIdToProductRecMap.get(productRec.Id).F_I_Products__r) {
    				Boolean isUpdated = false; 
    				if((String.isNotBlank(vendorProductOldMap.get(productRec.Id).Code__c) && String.isBlank(productRec.Code__c)) || 
    							(String.isBlank(vendorProductOldMap.get(productRec.Id).Code__c) && String.isNotBlank(productRec.Code__c)) || 
    							(String.isNotBlank(vendorProductOldMap.get(productRec.Id).Code__c) && String.isNotBlank(productRec.Code__c) 
    														&& vendorProductOldMap.get(productRec.Id).Code__c != productRec.Code__c)) {
    					fAndIProductRec.Item_Description__c = productRec.Code__c + ' - ' + productRec.Description__c;
    					isUpdated = true;
    				}
    				
    				if(!isUpdated) {
	    				if((String.isNotBlank(vendorProductOldMap.get(productRec.Id).Description__c) && String.isBlank(productRec.Description__c)) || 
	    							(String.isBlank(vendorProductOldMap.get(productRec.Id).Description__c) && String.isNotBlank(productRec.Description__c)) || 
	    							(String.isNotBlank(vendorProductOldMap.get(productRec.Id).Description__c) && String.isNotBlank(productRec.Description__c) 
	    														&& vendorProductOldMap.get(productRec.Id).Description__c != productRec.Description__c)) {
	    					fAndIProductRec.Item_Description__c = productRec.Code__c + ' - ' + productRec.Description__c;
	    					isUpdated = true;
	    				}
    				}
            		if(isUpdated) {
            			sObjectListToUpdate.add(fAndIProductRec);
            		}
    			}*/
    		}
    	}
    	if(optionAndFeeListToUpdate.size() > 0) {
    		OptionAndFeeTriggerHelper.isCalculatePriceLevel = false;
    		OptionAndFeeTriggerHelper.isCalculateTotalOnDeal = false;
			DMLUtility.updateSobjectList('Option_Fee__c', optionAndFeeListToUpdate);
    	}
    }
}