src/objects/CO_Header__c.object
<CustomObject>
    <label>CO Header</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Hours_Logged__c.object
<CustomObject>
    <fields>
        <fullName>QB_Accounting_Id__c</fullName>
        <label>QB Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Accounting_Id__c</fullName>
        <label>Xero Accounting Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Accounting_Sync_Token__c</fullName>
        <label>Accounting Sync Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Removed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Removed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Old_Total_Cost__c</fullName>
        <formula>Old_Total_Hours__c *  Old_Costing_Rate__c</formula>
        <label>Old Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Old_Total_Hours__c</fullName>
        <label>Old Total Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Hours Logged</relationshipLabel>
        <relationshipName>Hours_Logged</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician</label>
        <referenceTo>Technician__c</referenceTo>
        <relationshipLabel>Hours Logged</relationshipLabel>
        <relationshipName>Hours_Logged</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Calculated_Hours__c *  Costing_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <formula>(Time_Spent_d__c * 24) + Time_Spent_h__c + Time_Spent_m__c/60</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Hours Logged</label>
    <nameField>
        <displayFormat>HN-{00000000}</displayFormat>
        <label>Hours Logged Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hours Logged</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Unique name field</description>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technician_Name__c</fullName>
        <label>Technician Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Technician__c.object
<CustomObject>
    <fields>
        <fullName>Technician_Name__c</fullName>
        <label>Technician Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Technician</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Technician Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountingHoursLogged.cls
/**
 * Author: Richa Mittal
 * Since: Jun 10, 2019
 * Name: AccountingHoursLogged
 * Description: Apex class to handle JSON related oprations of hours logged for Accounting.
**/
public without sharing class AccountingHoursLogged {
    public String Id;
    public String Name;
    public DateTime EndDate;
    public String TechnicianName;
    public String CONumber;
    public String COHeaderId;
    public String ServiceJobName;
    public Decimal TotalCost;
    public Decimal TotalHours;
    public Decimal OldTotalCost;
    public Decimal OldTotalHours;
    public String QBAccountingId;
    public String AccountingSyncToken;
    public String XeroAccountingId;
    public Boolean IsRemoved;
    public String TxnDate;
    
    public AccountingHoursLogged(Hours_Logged__c hoursLoggedRec, DateTime accPeriodCloseDate) { 
        this.Id = hoursLoggedRec.Id;
        this.Name = hoursLoggedRec.Name;
        this.EndDate = hoursLoggedRec.End_Date_Time__c;
        this.TxnDate = DateTimeUtility.getFormttedDateFromDateTime(this.EndDate, 'yyyy-MM-dd');
        if(this.EndDate != null && accPeriodCloseDate != null && (this.EndDate <= accPeriodCloseDate)) {
            this.EndDate = accPeriodCloseDate.addDays(1);
            this.TxnDate = DateTimeUtility.getGMTFormttedDateFromDateTime(this.EndDate, 'yyyy-MM-dd');
        }
        this.TechnicianName = hoursLoggedRec.Technician__c != null? hoursLoggedRec.Technician__r.Technician_Name__c : '';
        this.CONumber = hoursLoggedRec.Service_Order_Header__c != null ? hoursLoggedRec.Service_Order_Header__r.CO_Header__r.Name : '';
        this.COHeaderId = hoursLoggedRec.Service_Order_Header__c != null ? hoursLoggedRec.Service_Order_Header__r.CO_Header__c : null;
        this.ServiceJobName = hoursLoggedRec.Service_Order_Header__c != null ? hoursLoggedRec.Service_Order_Header__r.Name__c : '';
        this.TotalCost = hoursLoggedRec.Total_Cost__c != null ? hoursLoggedRec.Total_Cost__c : 0;
        this.TotalHours = hoursLoggedRec.Total_Hours__c != null ? hoursLoggedRec.Total_Hours__c : 0;
        this.OldTotalCost = hoursLoggedRec.Old_Total_Cost__c;
        this.IsRemoved = hoursLoggedRec.Is_Removed__c;
        this.OldTotalHours = hoursLoggedRec.Old_Total_Hours__c != null ? hoursLoggedRec.Old_Total_Hours__c : 0;
        this.QBAccountingId = hoursLoggedRec.QB_Accounting_Id__c;
        this.XeroAccountingId = hoursLoggedRec.Xero_Accounting_Id__c;
        this.AccountingSyncToken = hoursLoggedRec.Accounting_Sync_Token__c;
    }
    
    /**
     * Name: fieldsList
     * Desc: Method Which contains all the field list to be quried
     * @param:  
     * @return: List<String> - Fields List
    **/
    public static List<String> fieldsList(){
        return new List<String>{'Name',
                                'End_Date_Time__c',
                                'Technician__r.Technician_Name__c',
                                'Service_Order_Header__r.CO_Header__c',
                                'Service_Order_Header__r.CO_Header__r.Name',
                                'Service_Order_Header__r.Name__c',
                                'Total_Cost__c',
                                'Total_Hours__c',
                                'QB_Accounting_Id__c',
                                'Accounting_Sync_Token__c',
                                'Xero_Accounting_Id__c',
                                'Old_Total_Cost__c',
                                'Old_Total_Hours__c',
                                'Is_Removed__c'
                             };
    }
}