src/objects/CO_Invoice_Header__c.object
<CustomObject>
<fields>
        <fullName>Closed_Invoice_Date__c</fullName>
        <description>It is used to store date when invoice action has happened</description>
        <label>Closed Invoice Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <formula>AutoNumberHolder__r.Name</formula>
        <label>Invoice Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CO Invoice Header</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>CO Invoice Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Line_Item__c.object
<CustomObject>
	<fields>
        <fullName>Actual_Invoice_Date_Time__c</fullName>
        <label>Actual Invoice Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <formula>Price__c * Qty__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Line Item</label>
        <referenceTo>Service_Order_Line_Item__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Line Item</label>
    <nameField>
        <displayFormat>COLI-{00000000}</displayFormat>
        <label>CO Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option_Clearing__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Option Clearing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stocked_Trades__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stocked Trades</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>    
    <fields>
        <fullName>Total__c</fullName>
        <description>Deal total</description>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reopen_Invoice_Created_Date__c</fullName>
        <label>Reopen Invoice Created Date</label>
        <type>DateTime</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <description>Junction between deal and unit</description>
    <fields>
        <fullName>Actual_Cash_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Actual Cash Value</description>
        <label>Actual Cash Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deal_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Stocked_In__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is COU is stocked in</description>
        <label>Is Stocked In</label>
        <type>Checkbox</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Deal Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>Actual_Invoice_Date_Time__c</fullName>
        <label>Actual Invoice Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deal_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Deal Item</description>
        <label>Deal Item</label>
        <referenceTo>Deal_Item__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Deal Item</description>
        <label>Deal Item</label>
        <referenceTo>Deal_Item__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup To deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <formula>Kit_Price__c * Qty_Needed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>IF($Setup.Configurations__c.Tax_Included_Pricing__c, Price_When_Tax_Included__c * Qty_Needed__c , Kit_Price__c * Qty_Needed__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{00000000}</displayFormat>
        <label>Service Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateDealOptionClearingAndStockTrade.cls
global without sharing class PopulateDealOptionClearingAndStockTrade extends PostInstallScriptBaseBatch {
    global PopulateDealOptionClearingAndStockTrade() {
        this.scriptName = 'executePopulateDealOptionClearingAndStockTradeBatch()';
    }

    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id, Invoice_Number__c, Option_Clearing__c, Stocked_Trades__c, Reopen_Invoice_Created_Date__c, (SELECT Id, Actual_Cash_Value__c FROM Deal_Items__r WHERE Is_Stocked_In__c = true) FROM Deal__c ';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> sobjectList) {
        List<Deal__c> dealList = (List<Deal__c>) sobjectList;

        Map<Id, List<CO_Line_Item__c>> dealIdToColiMap = new Map<Id, List<CO_Line_Item__c>>();
        for(CO_Line_Item__c coliRec : [SELECT Revenue__c, Deal__c, Actual_Invoice_Date_Time__c, Invoice_Number__c, Invoice_Number__r.Closed_Invoice_Date__c FROM CO_Line_Item__c WHERE Deal__c IN :dealList AND Service_Order_Line_Item__c = null]) {
            if(!dealIdToColiMap.containsKey(coliRec.Deal__c)) {
                dealIdToColiMap.put(coliRec.Deal__c, new List<CO_Line_Item__c>());
            }
            dealIdToColiMap.get(coliRec.Deal__c).add(coliRec);
        }

        Map<Id, List<Service_Order_Header__c>> dealIdToSoMap = new Map<Id, List<Service_Order_Header__c>>();
        for(Service_Order_Header__c soRec : [SELECT Total__c, Deal__c, Actual_Invoice_Date_Time__c, Invoice_Number__c, Invoice_Number__r.Closed_Invoice_Date__c FROM Service_Order_Header__c WHERE Deal__c IN :dealList]) {
            if(!dealIdToSoMap.containsKey(soRec.Deal__c)) {
                dealIdToSoMap.put(soRec.Deal__c, new List<Service_Order_Header__c>());
            }
            dealIdToSoMap.get(soRec.Deal__c).add(soRec);
        }

        for(Deal__c dealRec : dealList) {
            if(dealRec.Invoice_Number__c != null) {
                dealRec.Stocked_Trades__c = 0;
                Decimal optionClearing = 0;
                if(dealIdToColiMap.containsKey(dealRec.Id)) {
                    for(CO_Line_Item__c coliRec : dealIdToColiMap.get(dealRec.Id)) {
                        if(coliRec.Invoice_Number__c == null) {
                            optionClearing += coliRec.Revenue__c != null ? coliRec.Revenue__c.setScale(2, RoundingMode.HALF_UP) : 0;
                        }
                    }
                }

                if(dealIdToSoMap.containsKey(dealRec.Id)) {
                    for(Service_Order_Header__c soRec : dealIdToSoMap.get(dealRec.Id)) {
                        if(soRec.Invoice_Number__c == null) {
                            optionClearing += soRec.Total__c != null ? soRec.Total__c.setScale(2, RoundingMode.HALF_UP) : 0;
                        }
                    }
                }
                dealRec.Option_Clearing__c = optionClearing;
            } else {
                Decimal optionClearing = 0;
                if(dealRec.Reopen_Invoice_Created_Date__c != null) {
                    if(dealIdToColiMap.containsKey(dealRec.Id)) {
                        for(CO_Line_Item__c coliRec : dealIdToColiMap.get(dealRec.Id)) {
                            if(coliRec.Actual_Invoice_Date_Time__c != null) {
                                if(coliRec.Actual_Invoice_Date_Time__c > dealList[0].Reopen_Invoice_Created_Date__c) {
                                    optionClearing -= coliRec.Revenue__c != null ? coliRec.Revenue__c.setScale(2, RoundingMode.HALF_UP) : 0;
                                }
                            } else if(coliRec.Invoice_Number__c != null) {
                                if(coliRec.Invoice_Number__r.Closed_Invoice_Date__c > dealList[0].Reopen_Invoice_Created_Date__c) {
                                    optionClearing -= coliRec.Revenue__c != null ? coliRec.Revenue__c.setScale(2, RoundingMode.HALF_UP) : 0;
                                }
                            }
                        }
                    }
                    
                    if(dealIdToSoMap.containsKey(dealRec.Id)) {
                        for(Service_Order_Header__c soRec : dealIdToSoMap.get(dealRec.Id)) {
                            if(soRec.Actual_Invoice_Date_Time__c != null) {
                                if(soRec.Actual_Invoice_Date_Time__c > dealRec.Reopen_Invoice_Created_Date__c) {
                                    optionClearing -= soRec.Total__c != null ? soRec.Total__c.setScale(2, RoundingMode.HALF_UP) : 0;
                                }
                            } else if(soRec.Invoice_Number__c != null) {
                                if(soRec.Invoice_Number__r.Closed_Invoice_Date__c > dealRec.Reopen_Invoice_Created_Date__c) {
                                    optionClearing -= soRec.Total__c != null ? soRec.Total__c.setScale(2, RoundingMode.HALF_UP) : 0;
                                }
                            }
                        }
                    }
                }
                dealRec.Option_Clearing__c = optionClearing;
                
                Decimal stockTrade = 0;
                for(Deal_Item__c dealItem : dealRec.Deal_Items__r) {
                    stockTrade += dealItem.Actual_Cash_Value__c.setScale(2, RoundingMode.HALF_UP);
                }
                dealRec.Stocked_Trades__c = stockTrade;
            }
        }

        DealTriggerHelper.isForceStopTrigger = true;
        DMLUtility.updateSobjectList('Deal__c', dealList);
        DealTriggerHelper.isForceStopTrigger = false;
    }
    
    global override void finishScript(Database.BatchableContext bc) {}

}