src/objects/CO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Line Item</label>
    <nameField>
        <displayFormat>COLI-{00000000}</displayFormat>
        <label>CO Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parts</relationshipLabel>
        <relationshipName>Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sublet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sublet Type Vendor Product</description>
        <label>Sublet</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Type__c</field>
                <operation>equals</operation>
                <value>Sublet</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Line Item</label>
    <nameField>
        <displayFormat>VOLI-{00000000}</displayFormat>
        <label>Vendor Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartPickListService.cls
/** 
* Author: Tarun Khandelwal
* Since: March 01, 2021
* Name: PartPickListService 
* Description: Apex service class which contains methods related to PartPickList section.
**/
public without sharing class PartPickListService {
    
    public static List<PartPickListCOLIWrapper> getPartPickListCOLIList(String coHeaderId) {
        // Get all Vendor Order Line Items related to CO
        List<Vendor_Order_Line_Item__c> specialOrderedVOLineItemList = SOQLUtil.getSpecialOrderByCOHeaderId(coHeaderId);
        
        // Get Vendor Id List from related Vendor order line item List.
        // This Vendor Id List is used to find out lead time.
        List<String> vendorIdList = getVendorIdList(specialOrderedVOLineItemList);
        
        // Find out default lead time per vendor
        Map<String, Integer> vendorIdToDefaultLeadTimeMap = CustomerOrderCtrl_V2.getVendorLeadTimeMap(vendorIdList);
        
        Map<String, List<COHeaderWrapper.SpecialOrder>> coLineItemIdToVOLIListMap = new Map<String, List<COHeaderWrapper.SpecialOrder>>();
        Set<String> specialOrderCOLIIdSet = new Set<String>();
        for(Vendor_Order_Line_Item__c specialOrderedVOLI : specialOrderedVOLineItemList) {
            if(String.isBlank(specialOrderedVOLI.CO_Line_Item__r.Invoice_Number__c)) {
                Integer leadTime = 0;
                if(specialOrderedVOLI.Part__c != null) {
                    leadTime = vendorIdToDefaultLeadTimeMap.get(specialOrderedVOLI.Part__r.Vendor__c);
                } else if(specialOrderedVOLI.Sublet__c != null) {
                    leadTime = vendorIdToDefaultLeadTimeMap.get(specialOrderedVOLI.Sublet__r.Vendor__c);
                }
                specialOrderCOLIIdSet.add(specialOrderedVOLI.CO_Line_Item__c);
                
                COHeaderWrapper.SpecialOrder specialOrderObj = new COHeaderWrapper.SpecialOrder(specialOrderedVOLI, leadTime);
                if(!coLineItemIdToVOLIListMap.containsKey(specialOrderedVOLI.CO_Line_Item__c)) {
                    coLineItemIdToVOLIListMap.put(specialOrderedVOLI.CO_Line_Item__c, new List<COHeaderWrapper.SpecialOrder>());
                }
                coLineItemIdToVOLIListMap.get(specialOrderedVOLI.CO_Line_Item__c).add(specialOrderObj);
            }
        }

        List<CO_Line_Item__c> coliList = SOQLUtil.getPartPickListCOLIByCOHeaderId(coHeaderId, specialOrderCOLIIdSet);
        List<PartPickListCOLIWrapper> partPickListCOLiWrapperList = new List<PartPickListCOLIWrapper>();
        for(CO_Line_Item__c coliRec : coliList) {
            partPickListCOLiWrapperList.add(new PartPickListCOLIWrapper(coliRec));
        }
        for(String coLineItemId : coLineItemIdToVOLIListMap.keyset()) {
            partPickListCOLiWrapperList.add(new PartPickListCOLIWrapper(coLineItemIdToVOLIListMap.get(coLineItemId)));
        }
        return partPickListCOLiWrapperList;
    }
    
    private static List<Id> getVendorIdList(List<Vendor_Order_Line_Item__c> voLineItemList) {
        List<String> vendorIdList = new List<String>();
        for(Vendor_Order_Line_Item__c voLineItem : voLineItemList) {
            if(voLineItem.Part__c != null && String.isBlank(voLineItem.CO_Line_Item__r.Invoice_Number__c)) {
                vendorIdList.add(voLineItem.Part__r.Vendor__c);
            } else if(voLineItem.Sublet__c != null) {
                vendorIdList.add(voLineItem.Sublet__r.Vendor__c);
            }
        }
        return vendorIdList;
    }
}