src/objects/CO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Type__c</fullName>
        <label>Section Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Merchandise</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Line Item</label>
        <referenceTo>Service_Order_Line_Item__c</referenceTo>
        <relationshipLabel>CO Line Items</relationshipLabel>
        <relationshipName>CO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CO Line Item</label>
    <nameField>
        <displayFormat>COLI-{00000000}</displayFormat>
        <label>CO Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CO_Section_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>CO Section Details</relationshipLabel>
        <relationshipName>CO_Section_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_Type__c</fullName>
        <label>Section Type</label>
        <picklist>
            <picklistValues>
                <fullName>Merchandise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deal Merchandise</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Special_Order_Status__c</fullName>
        <label>Special Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need to order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All in-stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CO Section Detail</label>
    <nameField>
        <displayFormat>COSection-{00000000}</displayFormat>
        <label>CO Section Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CO Section Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Order</description>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Service Order Headers</relationshipLabel>
        <relationshipName>Service_Order_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Order_Status__c</fullName>
        <label>Special Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Need to order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All in-stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup To deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Service Order Line Items</relationshipLabel>
        <relationshipName>Service_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Order Line Item</label>
    <nameField>
        <displayFormat>SOLI-{00000000}</displayFormat>
        <label>Service Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CO_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CO Line Item</label>
        <referenceTo>CO_Line_Item__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Received</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Line Item</label>
        <referenceTo>Service_Order_Line_Item__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Order_Belongs_To__c</fullName>
        <formula>IF(
	CO_Header__c != null,
	IF(
		Is_Service__c,
		IF(
			IsBlank(Service_Order_Line_Item__c),
			CO_Line_Item__r.Service_Order_Line_Item__r.Service_Order_Header__c,
			Service_Order_Line_Item__r.Service_Order_Header__c
		),
		IF(
			AND(
				Is_required_For_Customer__c,
				CO_Line_Item__r.Deal__c != null
			),
			&apos;Deal Merchandise&apos;,
			&apos;Merchandise&apos;
		)
	),
	&apos;&apos;
)</formula>
        <label>Special Order Belongs To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Order_Status__c</fullName>
        <formula>IF(
	CO_Header__c != null,
	IF(
		OR (
			CO_Line_Item__r.Service_Order_Line_Item__r.Service_Order_Header__r.Invoice_Number__c != null,
			CO_Line_Item__r.Invoice_Number__c  != null
		),
		&apos;Fulfilled&apos;,
		IF(
			AND(
                             Qty_Needed__c == Received__c,
                             Is_Received__c
                            ),
			&apos;In Stock&apos;,
			IF(
				AND(
					Vendor_Order_Header__c != null,
					NOT(ISPICKVAL(Vendor_Order_Header__r.Status__c, &apos;Open&apos;)),
					NOT(ISPICKVAL(Vendor_Order_Header__r.Status__c, &apos;Locked&apos;))
				),
				&apos;Order submitted&apos;,
				&apos;Need to order&apos;
			)
		)
	 ),
	 &apos;&apos;
)</formula>
        <label>Special Order Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sublet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sublet Type Vendor Product</description>
        <label>Sublet</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.Type__c</field>
                <operation>equals</operation>
                <value>Sublet</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Vendor Order Line Items</relationshipLabel>
        <relationshipName>Vendor_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Order Line Item</label>
    <nameField>
        <displayFormat>VOLI-{00000000}</displayFormat>
        <label>Vendor Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/COSectionDetailService.cls
public without sharing class COSectionDetailService {
    
    public static final String MERCHANDISE = 'Merchandise';
    public static final String DEAL_MERCHANDISE  = 'Deal Merchandise';
    public static final String SERVICE = 'Service';
    
    public static final String SO_STATUS_NONE = 'None';
    public static final String SO_STATUS_NEED_TO_ORDER = 'Need to order';
    public static final String SO_STATUS_ORDER_SUBMITTED = 'Order submitted';
    public static final String SO_STATUS_ALL_IN_STOCK = 'All in-stock';
    public static final String SO_STATUS_FULFILLED = 'Fulfilled';
    
    @future
    public static void createCOSection_future(String coHeaderId, String sectionType) {
        createCOSection(coHeaderId, sectionType);
    }
    
    @future
    public static void checkAndCreateCOSection_future(String coHeaderId, String sectionType) {
        List<CO_Header__c> coHeaderList = [SELECT Id, (SELECT Id FROM CO_Section_Details__r WHERE Section_Type__c =: sectionType)
                                                FROM CO_Header__c WHERE Id =: coHeaderId];
        
        if(coHeaderList.size() > 0 && coHeaderList[0].CO_Section_Details__r.size() == 0) {
            createCOSection(coHeaderId, sectionType);
        }
    }
    
    public static void createCOSection(String coHeaderId, String sectionType) {
        CO_Section_Detail__c coSectionDetailRec = setCOSectionValue(coHeaderId, sectionType);
        DMLUtility.insertSobjectList('CO_Section_Detail__c', coSectionDetailRec);
    }
    
    public static CO_Section_Detail__c setCOSectionValue(String coHeaderId, String sectionType) {
        CO_Section_Detail__c coSectionDetailRec = new CO_Section_Detail__c();
        coSectionDetailRec.CO_Header__c = coHeaderId;
        coSectionDetailRec.Section_Type__c = sectionType;
        coSectionDetailRec.Special_Order_Status__c = 'None';
        return coSectionDetailRec;
    }
    
    @future
    public static void checkAndDeleteCOSection_future(String coHeaderId, String sectionType) {
        if(sectionType == DEAL_MERCHANDISE) {
            List<CO_Line_Item__c> dealCOliList = [SELECT Id FROM CO_Line_Item__c WHERE CO_Header__c =: coHeaderId AND Deal__c != null 
                                                      AND Service_Order_Line_Item__c = null];
            if(dealCOliList.size() == 0) {
                deleteCOSection(coHeaderId, sectionType);
            }
        }
    }
    
    @future
    public static void deleteCOSection_future(String coHeaderId, String sectionType) {
        deleteCOSection(coHeaderId, sectionType);
    }
    
    public static void deleteCOSection(String coHeaderId, String sectionType) {
        List<CO_Header__c> coHeaderList = [SELECT Id, (SELECT Id FROM CO_Section_Details__r WHERE Section_Type__c =: sectionType limit 1)
                                                FROM CO_Header__c WHERE Id =: coHeaderId];
                                                
        if(coHeaderList.size() > 0 && coHeaderList[0].CO_Section_Details__r.size() > 0) {
            delete coHeaderList[0].CO_Section_Details__r;
        }
    }
    
    
    
    @future 
    public static void setSectionStatus_future(Set<Id> coHeaderIdSet) {
        setSectionStatus(coHeaderIdSet, null);
    }
    
    @future 
    public static void setSectionStatus_future(Set<Id> coHeaderIdSet, String sectionType) {
        setSectionStatus(coHeaderIdSet, sectionType);
    }
    
    public static void setSectionStatus(Set<Id> coHeaderIdSet, String sectionType) {
        List<CO_Header__c> coHeaderList = 
            [SELECT Id, (SELECT Section_Type__c, Special_Order_Status__c FROM CO_Section_Details__r),
                    (SELECT Invoice_Number__c FROM Service_Order_Headers__r),
                    (SELECT Special_Order_Belongs_To__c, Special_Order_Status__c FROM Vendor_Order_Line_Items__r Order BY Special_Order_Belongs_To__c ASC) 
                 FROM CO_Header__c WHERE Id IN: coHeaderIdSet];
        
        if(String.isBlank(sectionType)) {
            setSOStatusForMerchandise(coHeaderList);
            setSOStatusForServiceJobs(coHeaderList);
        } else if(sectionType == MERCHANDISE || sectionType == DEAL_MERCHANDISE) {
            setSOStatusForMerchandise(coHeaderList);
        } else {
            setSOStatusForServiceJobs(coHeaderList);
        }
    }
    
    public static void setSOStatusForMerchandise(List<CO_Header__c> coHeaderList) {
        
        Map<String, List<CO_Line_Item__c>> coHeaderIdToMerchListMap = new Map<String, List<CO_Line_Item__c>>();
        Map<String, List<CO_Line_Item__c>> coHeaderIdToDealMerchListMap = new Map<String, List<CO_Line_Item__c>>();
        for(CO_Header__c coHeader : coHeaderList) {
            coHeaderIdToMerchListMap.put(coHeader.Id, new List<CO_Line_Item__c>());
            coHeaderIdToDealMerchListMap.put(coHeader.Id, new List<CO_Line_Item__c>());
        }
        
        List<CO_Line_Item__c> coliList = 
            [SELECT CO_Header__c, Service_Order_Line_Item__c, Deal__c, Service_Order_Line_Item__r.Deal__c, Invoice_Number__c,
                    (SELECT Special_Order_Belongs_To__c, Special_Order_Status__c FROM Vendor_Order_Line_Items__r WHERE Is_Received__c = false) 
                FROM CO_Line_Item__c WHERE Part__c != null AND CO_Header__c IN: coHeaderList];
        
        for(CO_Line_Item__c coliRec : coliList) {
            if(coliRec.Deal__c == null && coliRec.Service_Order_Line_Item__c == null) {
                coHeaderIdToMerchListMap.get(coliRec.CO_Header__c).add(coliRec);
            } else if(coliRec.Deal__c != null && coliRec.Service_Order_Line_Item__c == null){
                coHeaderIdToDealMerchListMap.get(coliRec.CO_Header__c).add(coliRec);
            }
        }
        
        List<CO_Section_Detail__c> coSectionDetailList = new List<CO_Section_Detail__c>();
        for(CO_Header__c coHeader : coHeaderList) {
            Map<String, Id> sectionTypeToSectionIdMap = new Map<String, Id>();
            Map<String, String> sectionNameToSOStatusMap = new Map<String, String>();
            
            for(CO_Section_Detail__c sectionDetail : coHeader.CO_Section_Details__r) {
                sectionTypeToSectionIdMap.put(sectionDetail.Section_Type__c, sectionDetail.Id);
                sectionNameToSOStatusMap.put(sectionDetail.Section_Type__c, 'None');
            }
            sectionNameToSOStatusMap.put(MERCHANDISE, getSOStatusForMerchSection(coHeaderIdToMerchListMap.get(coHeader.Id)));
            sectionNameToSOStatusMap.put(DEAL_MERCHANDISE, getSOStatusForMerchSection(coHeaderIdToDealMerchListMap.get(coHeader.Id)));
            
            for(String sectionName : sectionNameToSOStatusMap.keySet()) {
                if(sectionTypeToSectionIdMap.containsKey(sectionName)) {
                    CO_Section_Detail__c sectionDetailRec = new CO_Section_Detail__c(Id = sectionTypeToSectionIdMap.get(sectionName));
                    sectionDetailRec.Special_Order_Status__c = sectionNameToSOStatusMap.get(sectionName);
                    coSectionDetailList.add(sectionDetailRec);
                }
            }
        }
        if(coSectionDetailList.size() > 0) {
            DMLUtility.updateSobjectList('CO_Section_Detail__c', coSectionDetailList);
        }
    }
    
    public static void setSOStatusForServiceJobs(List<CO_Header__c> coHeaderList) {
        
        List<Service_Order_Header__c> soHeaderList = 
            [SELECT Id, (SELECT Id, Service_Order_Header__r.Invoice_Number__c FROM Service_Order_Line_Items__r 
                            WHERE Part__c != null OR Sublet__c != null)
                   FROM Service_Order_Header__c WHERE CO_Header__c IN: coHeaderList];
        
        Map<Id, List<Service_Order_Line_Item__c>> soHeaderIdToSOLIListMap = new Map<Id, List<Service_Order_Line_Item__c>>();
        for(Service_Order_Header__c soHeader : soHeaderList) {
            soHeaderIdToSOLIListMap.put(soHeader.Id, soHeader.Service_Order_Line_Items__r);
        }
        
        
        List<Vendor_Order_Line_Item__c> voliList = 
            [SELECT Related_SOLI__c, Special_Order_Belongs_To__c, Special_Order_Status__c FROM Vendor_Order_Line_Item__c WHERE CO_Header__c IN: coHeaderList 
                    AND Related_SOLI__c != null AND Is_Received__c = false];
        
        Map<String, Map<Id, List<Vendor_Order_Line_Item__c>>> soHeaderToSoliIdToVOLIListMap = new Map<String, Map<Id, List<Vendor_Order_Line_Item__c>>>();
        for(Vendor_Order_Line_Item__c voli : voliList) {
            if(!soHeaderToSoliIdToVOLIListMap.containsKey(voli.Special_Order_Belongs_To__c)) {
                soHeaderToSoliIdToVOLIListMap.put(voli.Special_Order_Belongs_To__c, new Map<Id, List<Vendor_Order_Line_Item__c>>());
            }
            Map<Id, List<Vendor_Order_Line_Item__c>> soliIdToVOLIListMap = soHeaderToSoliIdToVOLIListMap.get(voli.Special_Order_Belongs_To__c);
            if(!soliIdToVOLIListMap.containsKey(voli.Related_SOLI__c)) {
                soliIdToVOLIListMap.put(voli.Related_SOLI__c, new List<Vendor_Order_Line_Item__c>());
            }
            soliIdToVOLIListMap.get(voli.Related_SOLI__c).add(voli);
        }
        
        List<Service_Order_Header__c> serviceJobList = new List<Service_Order_Header__c>();
        Set<String> soHeaderIdSet = new Set<String>();
        for(CO_Header__c coHeader : coHeaderList) {
            Map<String, String> sectionNameToSOStatusMap = new Map<String, String>();
            
            for(Service_Order_Header__c serviceJob : coHeader.Service_Order_Headers__r) {
                soHeaderIdSet.add(serviceJob.Id);
                
                String soId = (String.valueOf(serviceJob.Id)).subString(0, 15);
                if(soHeaderToSoliIdToVOLIListMap.containsKey(soId)) {
                    sectionNameToSOStatusMap.put(serviceJob.Id, 
                        getSOStatusForServiceSection(soHeaderIdToSOLIListMap.get(serviceJob.Id), soHeaderToSoliIdToVOLIListMap.get(soId)));
                } else {
                    sectionNameToSOStatusMap.put(serviceJob.Id, 
                        getSOStatusForServiceSection(soHeaderIdToSOLIListMap.get(serviceJob.Id), new Map<Id, List<Vendor_Order_Line_Item__c>>()));
                }
            }
            
            for(String sectionName : sectionNameToSOStatusMap.keySet()) {
                if(soHeaderIdSet.contains(sectionName)) {
                    Service_Order_Header__c soHeader = new Service_Order_Header__c(Id = sectionName);
                    soHeader.Special_Order_Status__c = sectionNameToSOStatusMap.get(sectionName);
                    serviceJobList.add(soHeader);
                }
            }
        }
        if(serviceJobList.size() > 0) {
            DMLUtility.updateSobjectList('Service_Order_Header__c', serviceJobList);
        }
    }
        
    public static String getSOStatusForServiceSection(List<Service_Order_Line_Item__c> soliList, 
                                                        Map<Id, List<Vendor_Order_Line_Item__c>> soliIdToVOLIListMap) {
        String soStatus;
        if(soliList.size() == 0) {
            soStatus = SO_STATUS_NONE;
        } else if(soliList[0].Service_Order_Header__r.Invoice_Number__c != null) {
            soStatus = SO_STATUS_FULFILLED;
        } else {
            Boolean isAllInStock = true;
            for(Service_Order_Line_Item__c soli : soliList) {
                if(soliIdToVOLIListMap.containsKey(soli.Id) && soliIdToVOLIListMap.get(soli.Id).size() > 0) {
                    isAllInStock = false;
                    break;
                }
            }
            if(isAllInStock) {
                soStatus = SO_STATUS_ALL_IN_STOCK;
            } else {
                for(Service_Order_Line_Item__c soli : soliList) {
                    if(soliIdToVOLIListMap.containsKey(soli.Id)) {
                        for(Vendor_Order_Line_Item__c voli : soliIdToVOLIListMap.get(soli.Id)) {
	                        if(voli.Special_Order_Status__c == SO_STATUS_NEED_TO_ORDER) {
	                            soStatus = SO_STATUS_NEED_TO_ORDER;
	                            break;
	                        } else if(voli.Special_Order_Status__c == SO_STATUS_ORDER_SUBMITTED) {
	                            soStatus = SO_STATUS_ORDER_SUBMITTED;
	                        } else if(voli.Special_Order_Status__c == 'In Stock' && soStatus != SO_STATUS_ORDER_SUBMITTED) {
	                            soStatus = SO_STATUS_ALL_IN_STOCK;
	                        }
	                    }
                    }
                    if(soStatus == SO_STATUS_NEED_TO_ORDER) {
                        break;
                    }
                }
            }
        }
        return soStatus;
    }
    
    
    public static String getSOStatusForMerchSection(List<CO_Line_Item__c> merchList) {
        String soStatus;
        if(merchList.size() == 0) {
            soStatus = SO_STATUS_NONE;
        } else {
            Boolean isAllFullfilled = true;
            for(CO_Line_Item__c coli : merchList) {
                if(coli.Invoice_Number__c == null) {
                    isAllFullfilled = false;
                    break;
                }
            }
            if(isAllFullfilled) {
                soStatus = SO_STATUS_FULFILLED;
            } else {
                Boolean isAllInStock = true;
                for(CO_Line_Item__c coli : merchList) {
	                if(coli.Vendor_Order_Line_Items__r.size() > 0) {
	                    isAllInStock = false;
	                    break;
	                }
	            }
	            if(isAllInStock) {
	                soStatus = SO_STATUS_ALL_IN_STOCK;
	            } else {
	                for(CO_Line_Item__c coli : merchList) {
	                    for(Vendor_Order_Line_Item__c voli : coli.Vendor_Order_Line_Items__r) {
	                        if(voli.Special_Order_Status__c == SO_STATUS_NEED_TO_ORDER) {
	                            soStatus = SO_STATUS_NEED_TO_ORDER;
	                            break;
	                        } else if(voli.Special_Order_Status__c == SO_STATUS_ORDER_SUBMITTED) {
	                            soStatus = SO_STATUS_ORDER_SUBMITTED;
	                        } else if(voli.Special_Order_Status__c == 'In Stock' && soStatus != SO_STATUS_ORDER_SUBMITTED) {
	                            soStatus = SO_STATUS_ALL_IN_STOCK;
	                        }
	                    }
	                    if(soStatus == SO_STATUS_NEED_TO_ORDER) {
	                        break;
	                    }
	                }
	            }
            }
        }
        return soStatus;
    }
}