src/objects/Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Automatic_tax_rates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatic tax rates</label>
        <type>Checkbox</type>
    </fields>
    <label>Configurations</label>
</CustomObject>

src/classes/PopulatedStoreAutomatedTaxRatesScheduler.cls
global without sharing class PopulatedStoreAutomatedTaxRatesScheduler implements Schedulable {
    global void execute(SchedulableContext sc) { 
        if(Configurations__c.getOrgDefaults().Automatic_tax_rates__c) {
            populateStoreAutomatedTaxRates();
        }
    }

    @future (callout=true)
    public static void populateStoreAutomatedTaxRates() {
        ZipTaxService.populateStoreAutomatedTaxRates();
    }
}