src/objects/Count_Session__c.object
<CustomObject>
	<fields>
        <fullName>Count_Date_Time__c</fullName>
        <label>Count Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Net_Adjustment_After_Finalize__c</fullName>
        <label>Net Adjustment After Finalize</label>
        <summarizedField>Count_Session_Line_Item__c.Total_Cost_Adjustment__c</summarizedField>
        <summaryForeignKey>Count_Session_Line_Item__c.Count_Session__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of count session</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

    <label>Count Session</label>
    <nameField>
        <displayFormat>CS-{00000000}</displayFormat>
        <label>Count Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Count Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Count_Session_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Count_Session__c</fullName>
        <label>Count Session</label>
        <referenceTo>Count_Session__c</referenceTo>
        <relationshipName>Count_Session_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Adjustment__c</fullName>
        <label>Total Cost Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Count Session Line Item</label>
    <nameField>
        <displayFormat>CSLI-{00000000}</displayFormat>
        <label>Count Session Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Count Session Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_QB_Accounting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable QB Accounting</label>
        <type>Checkbox</type>
    </fields>
    <label>General Configurations</label>
</CustomObject>

src/objects/QuickBooks_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used for Integration</description>
    <fields>
        <fullName>Company_Id__c</fullName>
        <label>Company Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_QuickBooks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable QuickBooks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Point_URL__c</fullName>
        <label>End Point URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Token_Secret__c</fullName>
        <label>OAuth Token Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OAuth_Token__c</fullName>
        <label>OAuth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Configurations</label>
</CustomObject>

src/classes/AccSync_CountSession_BatchTest.cls
@isTest
private class AccSync_CountSession_BatchTest {
    
    @testSetup
    private static void setup(){
        TestUtil.bypassValidation();
    	QuickBooks_Configurations__c qbConfig = new QuickBooks_Configurations__c();
		qbConfig.Consumer_Key__c = 'qyprdFawAAiD3SLud6d5RvREaVOoAn';
        qbConfig.End_Point_URL__c = 'https://sandbox-quickbooks.api.intuit.com/v3/company/';
        qbConfig.Consumer_Secret__c = 'q3JPBvXRxwRWldrpEQzXlByXs7joEglmCBhRPinr';
        qbConfig.OAuth_Token__c = 'qyprdAVMsASHRkSalO3JwbyPdnzistYmRRfJBFbAxL6AOlDj';
        qbConfig.OAuth_Token_Secret__c = 'TN3csfs1tTSX77SW5ysYkcVxJo1gIq8Lq3wusQKO';
        qbConfig.Company_Id__c = '123145730762509';
		qbConfig.Enable_QuickBooks__c = true;   
		insert qbConfig;
		TestUtil.setQuickBooksIFWConfigurations(qbConfig);
		insert new General_Configurations__c(Enable_QB_Accounting__c = true);
        Count_Session__c brandingLocationRec = new Count_Session__c(name__c = 'balveer', Count_Date_Time__c=date.today());
        insert brandingLocationRec;
        Count_Session_Line_Item__c CountSessionLineItem = new Count_Session_Line_Item__c(Count_Session__c = brandingLocationRec.id, Total_Cost_Adjustment__c = 123.9);
        insert CountSessionLineItem;
    }
    
    @isTest
    private static void testAccSync_CountSession_BatchMethods(){
    	Test.startTest();
        List<Count_Session__c> countSessionRec = new List<Count_Session__c>();
        List<Count_Session__c> CountSession = [select id, name__c, Status__c, Net_Adjustment_After_Finalize__c from Count_Session__c];
        CountSession[0].name__c = 'jay';
        CountSession[0].Status__c = 'Closed';
        countSessionRec.add(CountSession[0]);
        update countSessionRec;
        
    	Test.stopTest();
        
        List<Count_Session__c> result = [select id, Status__c, Net_Adjustment_After_Finalize__c from Count_Session__c];
        system.assertEquals(1, result.size());
        List<Count_Session_Line_Item__c> results = [select id, Count_Session__c from Count_Session_Line_Item__c];
        system.assertEquals(result[0].id, results[0].Count_Session__c);
    }
}