src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>State/Province</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State_Abbreviation__mdt.object
<CustomObject>
    <description>This will be used for mapping values of Abbreviation to State. For Ex. FL for state Florida.</description>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>State Abbreviation</label>
    <pluralLabel>State Abbreviations</pluralLabel>
</CustomObject>

src/classes/AbbreviationsUtil.cls
public without sharing class AbbreviationsUtil {

    public static Map<String,String> getStateAbbreviationToStateMap(){
        Map<String,String> stateAbbrToStateMap = new Map<String,String>();
        for(State_Abbreviation__mdt stateAbbrRec: State_Abbreviation__mdt.getAll().values()) {
            stateAbbrToStateMap.put(stateAbbrRec.Country__c + '^&&^' + stateAbbrRec.Abbreviation__c , stateAbbrRec.State__c);
        }
        return stateAbbrToStateMap;
    }

    public static String getStateNameByAbbreviations(String country, String abbrevaition){
        if(String.isBlank(country)) { return abbrevaition;}
        List<State_Abbreviation__mdt> stateAbbreviationList = [Select Id, State__c From State_Abbreviation__mdt where Country__c =: country And Abbreviation__c =: abbrevaition Limit 1]; 
        if(stateAbbreviationList.size() != 0){
            return stateAbbreviationList[0].State__c;
        } else {
            return abbrevaition;
        }
    }

    public static String getStateAbbreviationsByName(String country, String stateFullName){
        if(String.isBlank(country)) { return stateFullName;}
        List<State_Abbreviation__mdt> stateAbbreviationList = [Select Id, Abbreviation__c From State_Abbreviation__mdt where Country__c =: country And State__c =: stateFullName Limit 1]; 
        if(stateAbbreviationList.size() != 0) {
            return stateAbbreviationList[0].Abbreviation__c;
        } else {
            return stateFullName;
        }
    }
}