src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Agreed_Payout__c</fullName>
        <label>Agreed Payout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Types of units</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COU</fullName>
                </value>
                <value>
                    <fullName>STOCK</fullName>
                </value>
                <value>
                    <fullName>ORDU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <description>Junction between deal and unit</description>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to cou</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deals_Units_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee_Total_Included_In_Profitability__c</fullName>
        <label>Fee Total Included In Profitability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <description>Used for Customer Invoice Detail grid search</description>
        <formula>IF( ISPICKVAL(Type__c, &apos;Trade In&apos;), -1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Used for Customer Invoice Detail grid search</inlineHelpText>
        <label>Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trade In</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
    	<fullName>Unit_Type__c</fullName>
        <formula>IF(AND(ISPICKVAL(Type__c, &apos;Unit&apos;),ISBLANK(Customer_Owned_Unit__c)), &apos;Temporary unit&apos;, 
		IF(ISPICKVAL(Type__c, &apos;Trade In&apos;), &apos;Trade-in&apos;, 
		IF(Customer_Owned_Unit__r.Consignment__c, &apos;Consignment&apos;, 
		IF(ISPICKVAL(Customer_Owned_Unit__r.Unit_Type__c, &apos;STOCK&apos;), &apos;Stock unit&apos;, 
		IF(ISPICKVAL(Customer_Owned_Unit__r.Unit_Type__c, &apos;ORDU&apos;), &apos;Order unit&apos;, 
		&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Deal Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fee__c.object
<CustomObject>
    <fields>
        <fullName>Is_Include_In_Profit_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Include In Profit Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <description>A dollar value with 2 decimal places</description>
        <label>Price</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Selling</fullName>
                    <default>true</default>
                    <label>Selling</label>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Option_Fee__c.object
<CustomObject>
    <fields>
        <fullName>Deal_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal item</description>
        <label>Deal Item</label>
        <referenceTo>Deal_Item__c</referenceTo>
        <relationshipLabel>Options &amp; Fees</relationshipLabel>
        <relationshipName>Options_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Fee</description>
        <label>Fee</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Options &amp; Fees</relationshipLabel>
        <relationshipName>Options_Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of this item</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <description>Quantity</description>
        <label>Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Option &amp; Fee</label>
    <nameField>
        <displayFormat>OF-{000000}</displayFormat>
        <label>Option &amp; Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options &amp; Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CorrectDealItemReportFieldsForProfBatch.cls
/**
 * Author: Richa Mittal
 * Since: Sep 16, 2024
 * Name: CorrectDealItemReportFieldsForProfBatch
 * Description: Batch for Populating fields on deal item
**/
global without sharing class CorrectDealItemReportFieldsForProfBatch extends PostInstallScriptBaseBatch {

    global CorrectDealItemReportFieldsForProfBatch() {
        this.scriptName = 'executeCorrectDealItemReportFieldsForProfBatch()';
    }
    
    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id, Customer_Owned_Unit__r.Unit_Type__c, Customer_Owned_Unit__r.Agreed_Payout__c, ' + 
        '(SELECT Id, Qty__c, Price__c, Fee__r.Is_Include_In_Profit_Calculation__c FROM Options_Fees__r ' +
        'WHERE Price__c != null AND Price__c != 0 AND Fee__c != null) FROM Deal_Item__c WHERE Type__c = \'Unit\'';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> dealItemRecList) {
        for(Deal_Item__c dealItemRec: (List<Deal_Item__c>) dealItemRecList) {
            dealItemRec.Fee_Total_Included_In_Profitability__c = 0;
            for(Option_Fee__c ofRec : dealItemRec.Options_Fees__r) {
                ofRec.Qty__c = (ofRec.Qty__c != null) ? ofRec.Qty__c : 0;
                Decimal price = (ofRec.Qty__c * ofRec.Price__c).setScale(2, RoundingMode.HALF_UP);
                dealItemRec.Fee_Total_Included_In_Profitability__c += (ofRec.Fee__r.Is_Include_In_Profit_Calculation__c ? price : 0);
            }
            if(dealItemRec.Customer_Owned_Unit__r.Unit_Type__c != null && dealItemRec.Customer_Owned_Unit__r.Unit_Type__c.equalsIgnoreCase('COU')) {
                dealItemRec.Unit_Cost__c = dealItemRec.Customer_Owned_Unit__r.Agreed_Payout__c != null ? dealItemRec.Customer_Owned_Unit__r.Agreed_Payout__c.setScale(2, RoundingMode.HALF_UP) : null;
            }
        }
		DealItemTriggerHelper.isForceStopTrigger = true;
        DMLUtility.updateSobjectList('Deal_Item__c', dealItemRecList);
        DealItemTriggerHelper.isForceStopTrigger = false;
    }
    
    global override void finishScript(Database.BatchableContext bc) {}
}