src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Date_Stocked_In__c</fullName>
        <description>Date the unit was stocked into inventory</description>
        <label>Date Stocked In</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Types of units</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COU</fullName>
                </value>
                <value>
                    <fullName>STOCK</fullName>
                </value>
                <value>
                    <fullName>ORDU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Date__c</fullName>
        <label>Adjustment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit lookup with Customer Owned Unit</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Customer_Owned_Unit__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UPCAdjustmentDateBatch.cls
/**
 * Author: Nidhi Sharma
 * Since: 13 May, 2024
 * Name: UPCAdjustmentDateBatch
 * Description: Batch for adjustment date on UPC
**/
global without sharing class UPCAdjustmentDateBatch extends PostInstallScriptBaseBatch {

    global UPCAdjustmentDateBatch() {
        this.scriptName = 'executeUPCAdjustmentDateBatch()';
    }
    
    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'Select Customer_Owned_Unit__r.Date_Stocked_In__c, Customer_Owned_Unit__r.CreatedDate from Unit_Price_Cost__c WHERE Adjustment_Date__c = null AND Unit_Type__c = \'STOCK\'';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> upcList) {
        for(Unit_Price_Cost__c upcRec : (List<Unit_Price_Cost__c>) upcList) {
            if(upcRec.Customer_Owned_Unit__r.Date_Stocked_In__c != null) {
                Date stockedInDateTime = upcRec.Customer_Owned_Unit__r.Date_Stocked_In__c;
                upcRec.Adjustment_Date__c = DateTime.newInstance(stockedInDateTime.year(), stockedInDateTime.month(), stockedInDateTime.day(), 0, 0, 0);
            } else {
                upcRec.Adjustment_Date__c = upcRec.Customer_Owned_Unit__r.CreatedDate;
            }
        }
        DMLUtility.updateSobjectList('Unit_Price_Cost__c', upcList);
    }
    
    global override void finishScript(Database.BatchableContext bc) {}
}