src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Colour__c</fullName>
        <description>Exterior Colour of unit</description>
        <label>Exterior Colour</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Engine_Serial_No__c</fullName>
        <description>Engine Serial Number of unit</description>
        <label>Engine Serial No</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage_Value__c</fullName>
        <description>Mileage of unit</description>
        <label>Mileage Value</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if unit is new</description>
        <label>New Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>General unit notes</description>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_Id__c</fullName>
        <description>This will contain the stock id</description>
        <label>Stock Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Model</label>
        <referenceTo>Unit_Sub_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suggested_Price__c</fullName>
        <label>Suggested Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total Price</description>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Make of unit</description>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <formula>IF( Unit_Id__c != null, Unit_Id__c , Stock_Id__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN_Number__c</fullName>
        <description>This VIN number is used. Please ignore previous VIN__c.</description>
        <label>VIN Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Model year of the unit</description>
        <label>Unit Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Make__c.object
<CustomObject>
    <label>Unit Make</label>
    <nameField>
        <label>Make</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Makes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Model</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Model__c</fullName>
        <label>Sub-Model</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Model_Name__c</fullName>
        <label>Sub Model Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DP360InventoryWrapper.cls
public without sharing class DP360InventoryWrapper {
	public Integer dealer_id;
   	public String inv_id;
   	public String condition;
   	public String year;
    public String make;
    public String model;
    public Decimal price;
    
    public String vin;
    public String stocknumber;
    public String color;
    public String miles;
    public String description;
    public Boolean sold;
    
    public String engine_id;
    public String unit_status;
    public Decimal suggested_price;
    public String url;
    public Decimal sale_price;
    
    public DP360InventoryWrapper(Customer_Owned_Unit__c unitRec, Integer dealerId) {
        this.dealer_id = dealerId;
        this.inv_id = unitRec.Unit_Number__c;
        this.condition = (unitRec.New_Unit__c ? 'New' : 'Used');
        this.year = unitRec.Year__c != null ? String.valueOf(unitRec.Year__c) : null;
        this.make = (unitRec.Unit_Make__c != null) ? unitRec.Unit_Make__r.Name : null;
        this.model = (unitRec.Unit_Model__c != null) ? unitRec.Unit_Model__r.Name__c + ((unitRec.Sub_Model__c != null) ? ' ' + unitRec.Sub_Model__r.Sub_Model_Name__c : '') : null;
        this.price = unitRec.Total_Price__c != null ? unitRec.Total_Price__c : 0;
        
        this.vin = String.isNotBlank(unitRec.VIN_Number__c) ? unitRec.VIN_Number__c: unitRec.Unit_Number__c;
        this.stocknumber = unitRec.Stock_Id__c;
        this.color = unitRec.Colour__c;
        this.miles = unitRec.Mileage_Value__c != null ? String.valueOf(unitRec.Mileage_Value__c) : null;
        this.description = unitRec.Notes__c;
        this.suggested_price = this.price;
        this.sold = (String.isNotBlank(unitRec.Status__c) && dp360UnitSoldStatusSet.contains(unitRec.Status__c));
        
        this.engine_id = unitRec.Engine_Serial_No__c;
        this.unit_status = unitRec.Status__c;
        this.url = AccountingUtil.getURL(unitRec.Id, 'ViewUnit');
        this.sale_price = unitRec.Suggested_Price__c != null ? unitRec.Suggested_Price__c : 0;
    }
    
    public static Set<String> dp360UnitSoldStatusSet = new Set<String>{'Reserved', 'Sold', 'Delivered', 'Received', 'Transferred', 'Inactive'};
    
    public static List<String> unitFieldsList() {
        return new List<String>{'New_Unit__c', 'Year__c', 'Unit_Make__c', 'Unit_Make__r.Name', 'Unit_Model__c', 'Unit_Model__r.Name__c', 
                                'Unit_Number__c', 'Total_Price__c', 'VIN_Number__c', 'Stock_Id__c', 'Colour__c', 'Mileage_Value__c', 'Notes__c', 
                                'Status__c', 'Engine_Serial_No__c', 'Sub_Model__c', 'Sub_Model__r.Sub_Model_Name__c', 'Suggested_Price__c'};
    }

    public static List<String> dp360UpdateUnitFieldsList() {
        return new List<String>{'New_Unit__c', 'Year__c', 'Unit_Make__c', 'Unit_Model__c', 'Unit_Number__c', 'Total_Price__c', 'VIN_Number__c', 
                                'Stock_Id__c', 'Colour__c', 'Mileage_Value__c', 'Notes__c', 'Engine_Serial_No__c', 'Sub_Model__c', 'Suggested_Price__c', 'Status__c'};
    }
    
}