src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Customer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Account.Is_Customer__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreed_Payout__c</fullName>
        <label>Agreed Payout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Stocked_In__c</fullName>
        <description>Date the unit was stocked into inventory</description>
        <label>Date Stocked In</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referenced_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referenced Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total Cost</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Types of units</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COU</fullName>
                </value>
                <value>
                    <fullName>STOCK</fullName>
                </value>
                <value>
                    <fullName>ORDU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Owned Units (Vendor)</relationshipLabel>
        <relationshipName>Customer_Owned_Units1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>CO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Order</description>
        <label>CO Header</label>
        <referenceTo>CO_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Number</label>
        <referenceTo>CO_Invoice_Header__c</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of deal</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quotation</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of deal</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Deal</fullName>
                </value>
                <value>
                    <fullName>Financed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deal_Item__c.object
<CustomObject>
    <description>Junction between deal and unit</description>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to cou</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deals_Units_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to deal</description>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Items</relationshipLabel>
        <relationshipName>Deal_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stocked_In_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stocked In Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Deals Items (Stocked In Unit)</relationshipLabel>
        <relationshipName>Deals_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>IF(ISPICKVAL(Type__c, &apos;Trade In&apos;), (Actual_Cash_Value__c * -1),  Unit_Cost__c +  Unit_Option_Cost__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trade In</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <formula>IF( ISPICKVAL(Type__c, &apos;Trade In&apos;), (Pre_Tax_Agreed_Value__c* -1), (Base_Price__c + Factory_Option_Total__c + Dealer_Option_Total__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
    	<fullName>Unit_Type__c</fullName>
        <formula>IF(AND(ISPICKVAL(Type__c, &apos;Unit&apos;),ISBLANK(Customer_Owned_Unit__c)), &apos;Temporary unit&apos;, 
		IF(ISPICKVAL(Type__c, &apos;Trade In&apos;), &apos;Trade-in&apos;, 
		IF(Customer_Owned_Unit__r.Consignment__c, &apos;Consignment&apos;, 
		IF(ISPICKVAL(Customer_Owned_Unit__r.Unit_Type__c, &apos;STOCK&apos;), &apos;Stock unit&apos;, 
		IF(ISPICKVAL(Customer_Owned_Unit__r.Unit_Type__c, &apos;ORDU&apos;), &apos;Order unit&apos;, 
		&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Deal Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Price_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Date__c</fullName>
        <label>Adjustment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Owned_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unit lookup with Customer Owned Unit</description>
        <label>Customer Owned Unit</label>
        <referenceTo>Customer_Owned_Unit__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Ordered_Unit_Price_Cost__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Ordered Unit Price Cost</label>
        <referenceTo>Unit_Price_Cost__c</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <description>Total cost of unit</description>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Base unit, Factory options, Dealer installed options</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Factory</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Customer_Owned_Unit__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs</relationshipLabel>
        <relationshipName>Unit_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Customer__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Prices &amp; Costs (Customer)</relationshipLabel>
        <relationshipName>Unit_Prices_Costs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Price &amp; Cost</label>
    <nameField>
        <displayFormat>UNP-{00000000}</displayFormat>
        <label>Unit Price &amp; Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Prices &amp; Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateUnitRegisterReoprtFieldsBatch.cls
global without sharing class PopulateUnitRegisterReoprtFieldsBatch extends PostInstallScriptBaseBatch  {
    global PopulateUnitRegisterReoprtFieldsBatch() {
        this.scriptName = 'executePopulateUnitRegisterReoprtFieldsBatch()';
    }
    
    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id FROM Customer_Owned_Unit__c WHERE (Unit_Type__c = \'STOCK\') OR (Unit_Type__c = \'COU\' AND Consignment__c = true)';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> couList) {
        List<Customer_Owned_Unit__c> couListToUpdate = new List<Customer_Owned_Unit__c>();
        List<Customer_Owned_Unit__c> stockUnitList = [SELECT Id, Account__c, Date_Stocked_In__c, Acquisition_Cost__c, Invoice_Number__c, Vendor__c, Agreed_Payout__c, Status__c, Referenced_Unit__c, Referenced_Unit__r.Total_Cost__c, (SELECT Id, Deal__r.CO_Header__r.Name, Total_Cost__c, Deal__r.CO_Header__r.Customer__c, Unit_Price__c, Type__c FROM Deals_Items__r WHERE Type__c = 'Trade In' Limit 1), (SELECT Id, Deal__r.CO_Header__r.Name, Total_Cost__c, Deal__r.CO_Header__r.Customer__c, Unit_Price__c, Type__c FROM Deals_Units_Junction__r ), (SELECT Id, Total_Cost__c, Adjustment_Date__c FROM Unit_Prices_Costs__r) FROM Customer_Owned_Unit__c WHERE Unit_Type__c = 'STOCK' AND Id IN :couList];
        for(Customer_Owned_Unit__c stockUnit : stockUnitList) {
            stockUnit.Reference_Number__c = 'Unknown';
            stockUnit.How_Acquired__c = 'Add unit';
            if(stockUnit.Referenced_Unit__c != null) {
                stockUnit.How_Acquired__c = 'Purchase';
                stockUnit.Acquired_From__c = stockUnit.Vendor__c;
                stockUnit.Acquisition_Cost__c = stockUnit.Referenced_Unit__r.Total_Cost__c;
                stockUnit.Reference_Number__c = stockUnit.Invoice_Number__c;
            }

            for(Deal_Item__c dealItem : stockUnit.Deals_Units_Junction__r) {
                if(stockUnit.Status__c == 'Sold') {
                    stockUnit.Sale_Number__c = dealItem.Deal__r.CO_Header__r.Name;
                    stockUnit.Sold_To__c = dealItem.Deal__r.CO_Header__r.Customer__c;
                    stockUnit.Sold_Price__c = dealItem.Unit_Price__c;
                }
            }

            for(Deal_Item__c dealItem : stockUnit.Deals_Items__r) {
                if(dealItem.Type__c == 'Trade In') {
                    stockUnit.How_Acquired__c = 'Trade-in';
                    stockUnit.Acquired_From__c = dealItem.Deal__r.CO_Header__r.Customer__c;
                    stockUnit.Acquisition_Cost__c = dealItem.Total_Cost__c * -1;
                    stockUnit.Reference_Number__c = dealItem.Deal__r.CO_Header__r.Name;
                }
            }

            if(stockUnit.Acquisition_Cost__c == null || stockUnit.Acquisition_Cost__c == 0) {
                Decimal acquisitionCost = 0;
                for(Unit_Price_Cost__c upcRec : stockUnit.Unit_Prices_Costs__r) {
                    if(upcRec.Adjustment_Date__c != null && stockUnit.Date_Stocked_In__c == upcRec.Adjustment_Date__c.date()) {
                        acquisitionCost += (upcRec.Total_Cost__c == null) ? 0 : upcRec.Total_Cost__c.setScale(2, RoundingMode.HALF_UP);
                    }
                }
                stockUnit.Acquisition_Cost__c = acquisitionCost;
            }
        }
        
        
        List<Customer_Owned_Unit__c> consignmentUnitList = [SELECT Id, Account__c, Date_Stocked_In__c, Date_Stocked_Out__c, Agreed_Payout__c, Status__c, (SELECT Id, Deal__r.CO_Header__r.Name, Deal__r.CO_Header__r.Customer__c, Unit_Price__c FROM Deals_Units_Junction__r limit 1) FROM Customer_Owned_Unit__c WHERE Consignment__c = true AND Id IN :couList];
        for(Customer_Owned_Unit__c consignmentUnit : consignmentUnitList) {
            consignmentUnit.How_Acquired__c = 'Consignment';
            consignmentUnit.Acquired_From__c = consignmentUnit.Account__c;
            consignmentUnit.Acquisition_Cost__c = consignmentUnit.Agreed_Payout__c;
            consignmentUnit.Date_Stocked_In__c = consignmentUnit.Date_Stocked_Out__c;
            if(consignmentUnit.Status__c == 'Transferred' && !consignmentUnit.Deals_Units_Junction__r.isEmpty()) {
                consignmentUnit.Reference_Number__c = consignmentUnit.Deals_Units_Junction__r[0].Deal__r.CO_Header__r.Name;
                consignmentUnit.Sale_Number__c = consignmentUnit.Deals_Units_Junction__r[0].Deal__r.CO_Header__r.Name;
                consignmentUnit.Sold_To__c = consignmentUnit.Deals_Units_Junction__r[0].Deal__r.CO_Header__r.Customer__c;
                consignmentUnit.Sold_Price__c = consignmentUnit.Deals_Units_Junction__r[0].Unit_Price__c;
            }
        }
        couListToUpdate.addAll(consignmentUnitList);
        couListToUpdate.addAll(stockUnitList);
        CustomerOwnedUnitTriggerHelper.isForceStopTrigger = true;
        DMLUtility.updateSobjectList('Customer_Owned_Unit__c', couListToUpdate);
        CustomerOwnedUnitTriggerHelper.isForceStopTrigger = false;
    }
    
    global override void finishScript(Database.BatchableContext bc) {
    }
}