src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Available_For_DP360_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For DP360 Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DP360_Inventory_Id__c</fullName>
        <label>DP360 Inventory Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Types of units</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COU</fullName>
                </value>
                <value>
                    <fullName>STOCK</fullName>
                </value>
                <value>
                    <fullName>ORDU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DP360ScriptUtil.cls
global without sharing class DP360ScriptUtil {
    
    global static void syncAvailableStockUnitsToDP360() {
        setFlagForAllStockUnits();
        setFlagForAllOrderedUnits();
        Database.executeBatch(new DP360InventoryBatch(), 10);
    }
    
    global static void setFlagForAllStockUnits() {
        List<Customer_Owned_Unit__c> stockUnitList = [SELECT Id FROM Customer_Owned_Unit__c WHERE Unit_Type__c = 'STOCK' AND Status__c = 'Available'
                                                        AND DP360_Inventory_Id__c = null AND Available_For_DP360_Sync__c = false];
        for(Customer_Owned_Unit__c skuUnit : stockUnitList) {
            skuUnit.Available_For_DP360_Sync__c = true;
        }
        if(stockUnitList.size() > 0) {
            CustomerOwnedUnitTriggerHelper.isForceStopTrigger = true;
            update stockUnitList;
            CustomerOwnedUnitTriggerHelper.isForceStopTrigger = false;
        }
    }
    
    global static void setFlagForAllOrderedUnits() {
        List<Customer_Owned_Unit__c> orderedUnitList = [SELECT Id FROM Customer_Owned_Unit__c WHERE Unit_Type__c = 'ORDU' AND Status__c = 'On Order'
                                                        AND DP360_Inventory_Id__c = null AND Available_For_DP360_Sync__c = false];
        for(Customer_Owned_Unit__c orderedUnit : orderedUnitList) {
            orderedUnit.Available_For_DP360_Sync__c = true;
        }
        if(orderedUnitList.size() > 0) {
            CustomerOwnedUnitTriggerHelper.isForceStopTrigger = true;
            update orderedUnitList;
            CustomerOwnedUnitTriggerHelper.isForceStopTrigger = false;
        }
    }
}