src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>DP360_Inventory_Id__c</fullName>
        <label>DP360 Inventory Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of unit based on unit type</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Traded</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>On Order</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Id__c</fullName>
        <description>This will be used for Generating unit Id</description>
        <label>Unit Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Make of unit</description>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Make__c.object
<CustomObject>
    <label>Unit Make</label>
    <nameField>
        <label>Make</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Makes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DP360ScriptUtilTest.cls
@isTest
global without sharing class DP360ScriptUtilTest {
    
    @testSetup
    private static void setup() {
        IFW_IntegrationConfig__c ifwConfig = TestDataFactory.createIFWConfigForDP360();
        IFW_IntegrationConfigItem__c ifwConfigItem1 = TestDataFactory.createIFWConfigItemForDP360('Token', ifwConfig.Id);
        IFW_IntegrationConfigItem__c ifwConfigItem2 = TestDataFactory.createIFWConfigItemForDP360('Create Unit', ifwConfig.Id);
        
        Unit_Make__c unitMakeRec = TestDataFactory.createUnitMake('Test make', 'TES', true);
        Unit_Model__c unitModelRec = TestDataFactory.createUnitModel('Test Model', 'TES', true, unitMakeRec.Id);
        Unit_Sub_Model__c unitSubModelRec = TestDataFactory.createSubModel(unitModelRec);
    }
    
    @isTest
    private static void syncUnitsBatch() {
        Unit_Make__c unitMakeRec = [SELECT Id FROM Unit_Make__c limit 1];
        Unit_Model__c unitModelRec = [SELECT Id FROM Unit_Model__c limit 1];
        Unit_Sub_Model__c unitSubModelRec = [SELECT Id FROM Unit_Sub_Model__c limit 1];
        
        Test.setMock(HttpCalloutMock.class, new DP360UnitMockResponseGenerator());  
        Test.startTest();
        CustomerOwnedUnitTriggerHelper.isForceStopTrigger = true;
        Customer_Owned_Unit__c unitRec = TestDataFactory.sampleStockUnit(unitMakeRec.Id, unitModelRec.Id, unitSubModelRec.Id, 'VIN#123');
        unitRec.Status__c = 'Available';
        unitRec.Unit_Id__c = 'UNT-000001';
        insert unitRec;
        CustomerOwnedUnitTriggerHelper.isForceStopTrigger = false;
        
        DP360ScriptUtil.syncAvailableStockUnitsToDP360();
        Test.stopTest();
        
        system.assertEquals('UNT-000001', [SELECT DP360_Inventory_Id__c FROM Customer_Owned_Unit__c limit 1].DP360_Inventory_Id__c);
    }
    
    global class DP360UnitMockResponseGenerator implements HttpCalloutMock {
        global HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"message": "Inventory has been saved", "data": {"AddedVins": ["VIN#123"], "existingVins": []}}');
            res.setStatusCode(200);
            return res;
        }
    }
}