src/objects/Customer_Owned_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Avail_For_QB_Sync_Category__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Avail For QB Sync - Category</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Make of unit</description>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Model of unit</description>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Customer Owned Units</relationshipLabel>
        <relationshipName>Customer_Owned_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Owned Unit</label>
    <nameField>
        <displayFormat>COU-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Owned Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_QB_Accounting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable QB Accounting</label>
        <type>Checkbox</type>
    </fields>
    <label>General Configurations</label>
</CustomObject>

src/objects/QuickBooks_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used for Integration</description>
    <fields>
        <fullName>End_Point_URL__c</fullName>
        <label>End Point URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Configurations</label>
</CustomObject>

src/objects/Unit_Make__c.object
<CustomObject>
    <label>Unit Make</label>
    <nameField>
        <label>Make</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Makes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnitCategoryServiceTest.cls
@isTest 
public class UnitCategoryServiceTest {
	
	@testSetup
    private static void setupTestData() {
    	List<Account> customerList = new List<Account>();
    	List<Customer_Owned_Unit__c> customerOwnedUnitList = new List<Customer_Owned_Unit__c>();
    	for(Integer i = 0; i < 10; i++) {
            customerList.add(TestDataFactory.sampleCustomer('Test Customer' + i, 'Individual', 'Test', 'Customer' + i));
        }
        insert customerList;
        
        Unit_Make__c unitMake = TestDataFactory.createUnitMake('Unit Make', 'Te1', true);
    	Unit_Model__c unitModel = TestDataFactory.createUnitModel('Unit Model', 'Te1', true, unitMake.Id);
    	Unit_Sub_Model__c unitSubModel = TestDataFactory.createSubModel(unitModel);
    	for(Integer i = 0; i< 10; i++) {
    		Customer_Owned_Unit__c customerOwnedUnit = TestDataFactory.sampleCustomerOwnedUnit(customerList[0].Id, unitMake.Id, 
    			                                                                                     unitModel.Id, unitSubModel.Id, 'VIN1');
    		customerOwnedUnit.Avail_For_QB_Sync_Category__c = true;
    		customerOwnedUnitList.add(customerOwnedUnit);
    	}
    	insert customerOwnedUnitList; 
    	
    	General_Configurations__c genConfigRec  = TestDataFactory.sampleGeneralConfig(2);
    	genConfigRec.Enable_QB_Accounting__c = true;
    	insert genConfigRec;
    } 
    
    @isTest
    private static void syncUnitsTest() {
    	Test.startTest();
    	List<Customer_Owned_Unit__c> customerOwnedUnitList = [Select Id from Customer_Owned_Unit__c];
    	Set<Id> unitIdSet = (new Map<Id,SObject>(customerOwnedUnitList)).keySet();
    	UnitCategoryService.syncUnits(unitIdSet);
    	customerOwnedUnitList = [Select Id, Avail_For_QB_Sync_Category__c from Customer_Owned_Unit__c];
    	Test.stopTest();
    	system.assertEquals(customerOwnedUnitList[0].Avail_For_QB_Sync_Category__c, true);
    }
    
    @isTest
    private static void syncUnitsTestQuickBooks() {
    	TestDataFactory.createQBConfig();
    	Test.startTest();
    	List<Customer_Owned_Unit__c> customerOwnedUnitList = [Select Id from Customer_Owned_Unit__c];
    	Set<Id> unitIdSet = (new Map<Id,SObject>(customerOwnedUnitList)).keySet();
    	UnitCategoryService.syncUnits(unitIdSet);
    	Test.stopTest();
    	customerOwnedUnitList = [Select Id, Avail_For_QB_Sync_Category__c from Customer_Owned_Unit__c];
    	system.assertEquals(customerOwnedUnitList[0].Avail_For_QB_Sync_Category__c, false);
    }
    
    @isTest
    private static void syncUnitsTestQuickBooksStatus() {
    	TestDataFactory.createQBConfig();
    	Test.startTest();
    	List<Customer_Owned_Unit__c> customerOwnedUnitList = [Select Id from Customer_Owned_Unit__c];
    	Set<Id> unitIdSet = (new Map<Id,SObject>(customerOwnedUnitList)).keySet();
    	UnitCategoryService.syncUnits(unitIdSet);
    	Test.stopTest();
    	customerOwnedUnitList = [Select Id, Avail_For_QB_Sync_Category__c from Customer_Owned_Unit__c];
    	system.assertEquals(customerOwnedUnitList[0].Avail_For_QB_Sync_Category__c, false);
    }
    
    @isTest
    private static void syncUnitsTestQuickBooksStatusNot200() {
    	QuickBooks_Configurations__c qbConfig = TestDataFactory.sampleQBConfig();
    	qbConfig.End_Point_URL__c = '';
    	insert qbConfig;
    	Test.startTest();
    	List<Customer_Owned_Unit__c> customerOwnedUnitList = [Select Id from Customer_Owned_Unit__c];
    	Set<Id> unitIdSet = (new Map<Id,SObject>(customerOwnedUnitList)).keySet();
    	UnitCategoryService.syncUnits(unitIdSet);
    	Test.stopTest();
    	customerOwnedUnitList = [Select Id, Avail_For_QB_Sync_Category__c from Customer_Owned_Unit__c];
    	system.assertEquals(customerOwnedUnitList[0].Avail_For_QB_Sync_Category__c, true);
    }
}