src/objects/Deal_Item__c.object
<CustomObject>
    <description>Junction between deal and unit</description>
    <fields>
        <fullName>Override_Tax_For_All_Line_Items__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It can be checked only if Taxable flag is checked. If this flag is checked then ALL line items are taxed using tax selected for Applicable_Tax__c field (of course only if the item is taxable).</description>
        <inlineHelpText>It can be checked only if Taxable flag is checked. If this flag is checked then ALL line items are taxed using tax selected for Applicable_Tax__c field (of course only if the item is taxable).</inlineHelpText>
        <label>Override Tax For All Line Items?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Tax_Applicable_On__c</fullName>
        <label>Unit Tax Applicable On</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Sublet</fullName>
                </value>
                <value>
                    <fullName>Fees</fullName>
                </value>
                <value>
                    <fullName>Warranty products</fullName>
                </value>
                <value>
                    <fullName>Other products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Deal Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DealUnitOptionTaxedSelectionBatch.cls
/**
 * Author: Nidhi Sharma
 * Since: March 15, 2023
 * Name: DealUnitOptionTaxedSelectionBatch
 * Description: Batch for Populating Unit_Tax_Applicable_On__c fields on deal items
**/
global without sharing class DealUnitOptionTaxedSelectionBatch extends PostInstallScriptBaseBatch {

    global DealUnitOptionTaxedSelectionBatch() {
        this.scriptName = 'executeDealUnitOptionTaxedSelectionBatch()';
    }
    
    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id, Override_Tax_For_All_Line_Items__c FROM Deal_Item__c WHERE Unit_Tax_Applicable_On__c = null';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> dealItems) {
        for(Deal_Item__c dealItemRec : (List<Deal_Item__c>) dealItems) {
			if(dealItemRec.Override_Tax_For_All_Line_Items__c) {
                dealItemRec.Unit_Tax_Applicable_On__c = DealUtil.UNIT_TAX_APPLICABLE_ALL;
            } else {
                dealItemRec.Unit_Tax_Applicable_On__c = DealUtil.UNIT_TAX_APPLICABLE_DEFAULT;
            }
		}
        DealItemTriggerHelper.isForceStopTrigger = true;
        DMLUtility.updateSobjectList('Deal_Item__c', dealItems);
        DealItemTriggerHelper.isForceStopTrigger = false;
    }
    
    global override void finishScript(Database.BatchableContext bc) {}
}