src/objects/Deal__c.object
<CustomObject>
    <description>Unit Deal on Customer Order</description>
    <fields>
        <fullName>Available_For_DP360_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available For DP360 Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DP360_Lead_Id__c</fullName>
        <label>DP360 Lead Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of deal</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quotation</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DP360SyncFlagService.cls
/**
 * Author: Tarun Khandelwal
 * Since: Nov 07, 2020
 * Name: DP360SyncFlagService
 * Description: Service class for setting/resetting sync flag value for DP360 Integration
**/
public without sharing class DP360SyncFlagService {
    
    public static void manageDealSyncFlag(List<Deal__c> newList, Map<Id, Deal__c> oldMap) {
        for(Deal__c dealRec : newList) {
            if(dealRec.DP360_Lead_Id__c != null && dealRec.Status__c != oldMap.get(dealRec.Id).Status__c && dealRec.Status__c == 'Invoiced') {
                dealRec.Available_For_DP360_Sync__c = true;
            }
        }
    }
}