src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Hours__c</fullName>
        <label>Estimated Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start DateTime</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Scheduling__c.object
<CustomObject>
    <description>Ticket - 12652</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Schedulings</relationshipLabel>
        <relationshipName>Event_Schedulings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event Scheduling</label>
    <nameField>
        <displayFormat>ESCH-{00000000}</displayFormat>
        <label>Event Scheduling Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Schedulings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventSchedulingTriggerHelperTest.cls
@isTest
private class EventSchedulingTriggerHelperTest {
    
    static testMethod void eventSchedulingTest() {
        TestDataFactory.createShopSettings('Monday');
        TestDataFactory.createShopSettings('Tuesday');
        TestDataFactory.createShopSettings('Wednesday');
        TestDataFactory.createShopSettings('Thursday');
        TestDataFactory.createShopSettings('Friday');
        TestDataFactory.createShopSettings('Saturday');
        TestDataFactory.createShopSettings('Sunday');
        
        Event__c eventRec = new Event__c();
        eventRec.Estimated_Hours__c = 1;
        insert eventRec;
        
        Event_Scheduling__c schedulingRec = new Event_Scheduling__c(Event__c = eventRec.Id);
        schedulingRec.Start_Date_Time__c = DateTime.newInstance(2020, 01, 28, 8, 0, 0);
        schedulingRec.End_Date_Time__c = schedulingRec.Start_Date_Time__c.addHours(1);
        schedulingRec.Hours__c = 1;
        insert schedulingRec;
        
        eventRec = [Select Id, Start_DateTime__c from Event__c where Id =: eventRec.Id];
        system.assertEquals(schedulingRec.Start_Date_Time__c, eventRec.Start_DateTime__c);
        
        schedulingRec.Start_Date_Time__c = schedulingRec.End_Date_Time__c;
        schedulingRec.End_Date_Time__c = schedulingRec.Start_Date_Time__c.addHours(1);
        update schedulingRec;
        
        eventRec = [Select Id, Start_DateTime__c from Event__c where Id =: eventRec.Id];
        system.assertEquals(schedulingRec.Start_Date_Time__c, eventRec.Start_DateTime__c);
        
        delete schedulingRec;
        
        Event__c afterDeleteEventRec = [Select Id, Start_DateTime__c from Event__c where Id =: eventRec.Id];
        system.assertEquals(eventRec.Start_DateTime__c, afterDeleteEventRec.Start_DateTime__c);
    }
}