src/objects/FTP_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FTP_Password__c</fullName>
        <label>FTP Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTP_URL__c</fullName>
        <label>FTP URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTP_Username__c</fullName>
        <label>FTP Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FTPS_Connection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FTPS Connection?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Directory_Path__c</fullName>
        <description>Directory Path of the server where file needs to be send.</description>
        <inlineHelpText>Directory Path of the server where file needs to be send.</inlineHelpText>
        <label>Directory Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port__c</fullName>
        <description>Port number using which connection will established.</description>
        <inlineHelpText>Port number using which connection will established.</inlineHelpText>
        <label>Port</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFTP_Server__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the server is SFTP type or not.</description>
        <inlineHelpText>Flag to indicate the server is SFTP type or not.</inlineHelpText>
        <label>SFTP Server?</label>
        <type>Checkbox</type>
    </fields>
    <label>FTP Config</label>
</CustomObject>

src/objects/GE_File_Column_Override_Info__c.object
<CustomObject>
    <description>Contains information related to overriding any of the column value from its actual value.</description>
    <fields>
        <fullName>Actual_Column_Value__c</fullName>
        <description>Contains actual column value from the BP database</description>
        <inlineHelpText>Contains actual column value from the BP database</inlineHelpText>
        <label>Actual Column Value</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GE_File_Detail__c</fullName>
        <description>Parent object GE_File_Detail__c</description>
        <label>GE File Detail</label>
        <referenceTo>GE_File_Detail__c</referenceTo>
        <relationshipLabel>GE File Columns Override Info</relationshipLabel>
        <relationshipName>GE_File_Columns_Override_Info</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override_Column_Value__c</fullName>
        <description>Contains column value to be shown in export file for the defined actual value</description>
        <inlineHelpText>Contains column value to be shown in export file for the defined actual value</inlineHelpText>
        <label>Override Column Value</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>GE File Column Override Info</label>
    <nameField>
        <displayFormat>FCO-{00000000}</displayFormat>
        <label>GE File Column Override Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GE File Columns Override Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GE_File_Config__c.object
<CustomObject>
    <description>Generic export file config which contains config details of each different file to export</description>
    <fields>
        <fullName>Delimiter__c</fullName>
        <description>Symbol of file separator used for separating different column values in file</description>
        <inlineHelpText>Symbol of file separator used for separating different column values in file</inlineHelpText>
        <label>Delimiter</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Content_Type__c</fullName>
        <description>Different file content types like (csv, txt)</description>
        <inlineHelpText>Different file content types like (csv, txt)</inlineHelpText>
        <label>File Content Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>csv</fullName>
                </value>
                <value>
                    <fullName>txt</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <description>Name of the file to be exported</description>
        <inlineHelpText>Name of the file to be exported</inlineHelpText>
        <label>File Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Separator__c</fullName>
        <description>Text value of the file separator used for separating different column values in file</description>
        <inlineHelpText>Text value of the file separator used for separating different column values in file</inlineHelpText>
        <label>File Separator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>comma</fullName>
                </value>
                <value>
                    <fullName>pipe</fullName>
                </value>
                <value>
                    <fullName>semi-column</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>space</fullName>
                </value>
                <value>
                    <fullName>tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_Column_Header__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to indicate if column header should to be included in file export or not. Default value is true.</description>
        <inlineHelpText>Flag to indicate if column header should to be included in file export or not. Default value is true.</inlineHelpText>
        <label>Include Column Header?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Images__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if images should to be included in file export or not</description>
        <inlineHelpText>Flag to indicate if images should to be included in file export or not</inlineHelpText>
        <label>Include Images?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_Timestamp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if timestamp should be included in file name or not. Default value is false</description>
        <inlineHelpText>Flag to indicate if timestamp should be included in file name or not. Default value is false</inlineHelpText>
        <label>Include Timestamp?</label>
        <type>Checkbox</type>
    </fields>
    <label>GE File Config</label>
    <nameField>
        <displayFormat>FC-{00000000}</displayFormat>
        <label>GE File Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GE File Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GE_File_Detail__c.object
<CustomObject>
    <description>Generic File Details contains the information related to each column to be created in the export file</description>
    <fields>
        <fullName>Data_Type__c</fullName>
        <description>Field data type. Ex Text, Date</description>
        <inlineHelpText>Field data type. Ex Text, Date</inlineHelpText>
        <label>Data Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date/Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default_Value__c</fullName>
        <description>Hardcoded value for all records. If this field is having value then field API name will be ignored.</description>
        <inlineHelpText>Hardcoded value for all records. If this field is having value then field API name will be ignored.</inlineHelpText>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <description>Related field API name. If in case we can not create formula field for some data (like long text area field) then use this to provided &quot;/&quot; separated Field API Names in the order of Field_API1/Field_API2 if Field_API1 is blank and so on.</description>
        <inlineHelpText>Related field API name. If in case we can not create formula field for some data (like long text area field) then use this to provided &quot;/&quot; separated Field API Names in the order of Field_API1/Field_API2 if Field_API1 is blank and so on.</inlineHelpText>
        <label>Field API Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>File_Column_Label__c</fullName>
        <description>Column header value to be shown in exported file</description>
        <inlineHelpText>Column header value to be shown in exported file</inlineHelpText>
        <label>File Column Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GE_File_Config__c</fullName>
        <description>Parent File Config</description>
        <inlineHelpText>Parent File Config</inlineHelpText>
        <label>GE File Config</label>
        <referenceTo>GE_File_Config__c</referenceTo>
        <relationshipLabel>GE File Details</relationshipLabel>
        <relationshipName>GE_File_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Represents the column number value for the export file</description>
        <inlineHelpText>Represents the column number value for the export file</inlineHelpText>
        <label>Order Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Object_API_Name__c</fullName>
        <description>Represents the Object API name if we need to include information from some other object in export file. For ex Business_Profile__c</description>
        <inlineHelpText>Represents the Object API name if we need to include information from some other object in export file. For ex Business_Profile__c</inlineHelpText>
        <label>Other Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GE File Detail</label>
    <nameField>
        <displayFormat>FD-{00000000}</displayFormat>
        <label>GE File Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GE File Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFTP_Server__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SFTP Server</label>
</CustomObject>

src/classes/SOQLToFileWrapper.cls
public with sharing class SOQLToFileWrapper {
    public String soql;
    public String host;
    public Decimal port;
    public String username;
    public String password;
    public String filepath;
    public Boolean allowUnauthorized;
    public Boolean secure;
    public Boolean includeColumnHeader;
    public Boolean includeImages;
    public String imageSoql;
    public Map<String, String> apiNameToSoql;
    public csvFormatOption csvFormatOptions;

    public SOQLToFileWrapper(String exportType, GE_File_Config__c fileConfigRec, FTP_Config__c ftpConfigRec, Map<String, List<GE_File_Column_Override_Info__c>> fileDetailToColOverrideInfoListMap, Map<String, List<String>> otherObjAPINameToFieldAPINameListMap) {
        this.soql = BPUtility.getEncodedString(BPUtility.addNamespaceToQuery(GenericExportUtil.createQueryForDataToExport(fileConfigRec, exportType, null), Constants.NAMESPACE));
        this.host = String.isNotBlank(ftpConfigRec.FTP_URL__c) ? ftpConfigRec.FTP_URL__c : '';
        this.port = ftpConfigRec.Port__c != null ? ftpConfigRec.Port__c : 0;
        this.username = ftpConfigRec.FTP_Username__c;
        this.password = ftpConfigRec.FTP_Password__c;
        String fileName = fileConfigRec.Include_Timestamp__c ? GenericExportUtil.getAttachmentNameWithTime(fileConfigRec.File_Name__c, Datetime.now()) : fileConfigRec.File_Name__c;
        String fileNameWithContantType = String.isNotBlank(fileConfigRec.File_Content_Type__c) ? (fileName).removeEnd('.' + fileConfigRec.File_Content_Type__c) + '.' + fileConfigRec.File_Content_Type__c : '';
        this.filepath = ftpConfigRec.Directory_Path__c + fileNameWithContantType;
        this.includeColumnHeader = fileConfigRec.Include_Column_Header__c;
        this.includeImages = fileConfigRec.Include_Images__c;
        if(fileConfigRec.Include_Images__c) {
            this.imageSoql = BPUtility.getEncodedString(BPUtility.addNamespaceToQuery(GenericExportUtil.createQueryToFetchImages(fileConfigRec, null), Constants.NAMESPACE));
        }

        this.apiNameToSoql = new Map<String, string>();    
        for(String objectAPIName: otherObjAPINameToFieldAPINameListMap.keySet()) {
            String query = 'SELECT ' + String.join(otherObjAPINameToFieldAPINameListMap.get(objectAPIName), ',') + ' FROM ' + objectAPIName + ' LIMIT 1';
            this.apiNameToSoql.put(objectAPIName, BPUtility.getEncodedString(BPUtility.addNamespaceToQuery(query, Constants.NAMESPACE)));
        }

        if(!ftpConfigRec.SFTP_Server__c) {
            this.allowUnauthorized = true;
            this.secure = false;
        }
        if(ftpConfigRec.FTPS_Connection__c) {
            this.secure = true;
        }
        this.csvFormatOptions = new csvFormatOption(fileConfigRec, fileDetailToColOverrideInfoListMap);        
    }

    public class csvFormatOption {
        public String delimiter;
        public String timeFormat;
        public String timeStandard;
        public Decimal timezone;
        public List<columnDetail> columnDetails;

        public csvFormatOption() {}

        public csvFormatOption(GE_File_Config__c fileConfigRec, Map<String, List<GE_File_Column_Override_Info__c>> fileDetailToColOverrideInfoListMap) {
            this.timeFormat = 'YYYY-DD-MM';
            this.timeStandard = 'UTC';
            this.timezone = Decimal.valueOf(UserInfo.getTimeZone().getDisplayName().substringBefore(')').substringAfter('(GMT').replace(':','.')); 
            this.delimiter = GenericExportUtil.fileSeparatorToFileSeparatorSymbolMap.containsKey(fileConfigRec.File_Separator__c) ? 
                                                GenericExportUtil.fileSeparatorToFileSeparatorSymbolMap.get(fileConfigRec.File_Separator__c) : 
                                                (fileConfigRec.File_Separator__c.equalsIgnoreCase('other') ? fileConfigRec.Delimiter__c : fileConfigRec.File_Separator__c);
            
            this.columnDetails = new List<columnDetail>();
            List<GE_File_Column_Override_Info__c> colOverrideInfoList;
            for(GE_File_Detail__c columnDetailRec : fileConfigRec.GE_File_Details__r) {
                colOverrideInfoList = fileDetailToColOverrideInfoListMap.containsKey(columnDetailRec.Id) ? fileDetailToColOverrideInfoListMap.get(columnDetailRec.Id) : new List<GE_File_Column_Override_Info__c>();
                this.columnDetails.add(new columnDetail(columnDetailRec, colOverrideInfoList));
            }
        }
    }

    public class columnDetail {
        public String dataType;
        public String fieldAPIName;
        public String fileColumnLabel;
        public Integer orderNumber;
        public String defaultValue;
        public String otherObjectAPIName;
        public Map<String, String> columnOverrideInfo;

        public columnDetail() {}

        public columnDetail(GE_File_Detail__c columnDetailRec, List<GE_File_Column_Override_Info__c> colOverrideInfoList) {
            this.fileColumnLabel = columnDetailRec.File_Column_Label__c;
            this.fieldAPIName = columnDetailRec.Field_API_Name__c; 
            this.orderNumber = Integer.valueOf(columnDetailRec.Order_Number__c);
            this.dataType = columnDetailRec.Data_Type__c.equalsIgnoreCase('Date/Time') ? 'DateTime' : columnDetailRec.Data_Type__c;
            this.defaultValue = columnDetailRec.Default_Value__c != null ? columnDetailRec.Default_Value__c : '';
            this.otherObjectAPIName = columnDetailRec.Other_Object_API_Name__c != null ? columnDetailRec.Other_Object_API_Name__c : '';
            this.columnOverrideInfo = new Map<String, String>();
            for(GE_File_Column_Override_Info__c columnOverrideInfoRec : colOverrideInfoList) {
                this.columnOverrideInfo.put(columnOverrideInfoRec.Actual_Column_Value__c, columnOverrideInfoRec.Override_Column_Value__c);
            }
        }
    }
}