src/objects/Fusion_Benchmarking__c.object
<CustomObject>
    <fields>
        <fullName>Average_Technician_Prime_Labor_Cost__c</fullName>
        <label>Average Technician Prime Labor Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_No_Administration_Other__c</fullName>
        <label>Employee No. Administration &amp; Other</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_No_Parts__c</fullName>
        <label>Employee No. Parts</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_No_Sales__c</fullName>
        <label>Employee No. Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_No_Service_Non_Technical__c</fullName>
        <label>Employee No. Service Non-Technical</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee_No_Service_Technical__c</fullName>
        <label>Employee No. Service Technical</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Insurance_Contracts_Written__c</fullName>
        <label>No: Insurance Contracts Written</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Sales_People__c</fullName>
        <label>No. Sales People</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Working_Days__c</fullName>
        <label>No. of Working Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working_days_in_Period__c</fullName>
        <label>Working days in Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Fusion Benchmarking</label>
    <nameField>
        <displayFormat>FBN-{00000000}</displayFormat>
        <label>Fusion Benchmarking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusion Benchmarking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fusion_Report_Line_Item__c.object
<CustomObject>
    <description>FUSION BENCHMARKING LINE ITEM DETAILS used for reporting</description>
    <fields>
        <fullName>HDNet_Account__c</fullName>
        <description>Account Name</description>
        <label>HDNet Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Value__c</fullName>
        <label>Monthly Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Value__c</fullName>
        <label>Yearly Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Fusion Report Line Item</label>
    <nameField>
        <displayFormat>FLI-{00000000}</displayFormat>
        <label>Fusion Report Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusion Report Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FusionReportCtrl.cls
/**
 * Author: Tarun Khandelwal
 * Since: August 23, 2018
 * Name: FusionReportCtrl
 * Description: Ctrl class for Fusion Report Page
**/
public without sharing class FusionReportCtrl {
    
    public List<Fusion_Report_Line_Item__c> fusionLineItemList {get; set;}
    public Map<Integer, Decimal> lineItemNoToMonthValueMap {get; set;}
    public Map<Integer, Decimal> lineItemNoToYearValueMap {get; set;}
	public String csvString {get; set;}
	
    public FusionReportCtrl() {
        lineItemNoToMonthValueMap = new Map<Integer, Decimal>();
        lineItemNoToYearValueMap = new Map<Integer, Decimal>();
        populateFusionLineItemData();
        populateUserEnterData();
        populateOtherData();
        populateCSVData();
    }
    
    private void populateCSVData() {
    	csvString = 'HDNet Accounts,Monthly,YTD\n';
    	for(Fusion_Report_Line_Item__c fusionLineItemRec : fusionLineItemList) {
    		csvString += fusionLineItemRec.HDNet_Account__c + ',' + lineItemNoToMonthValueMap.get(Integer.valueOf(fusionLineItemRec.Order_Number__c)) + ',' +
    				lineItemNoToYearValueMap.get(Integer.valueOf(fusionLineItemRec.Order_Number__c)) +'\n';
    	}
    }
    
    private void populateFusionLineItemData() {
        fusionLineItemList = FusionSOQLUtil.getFusionLienItem(new Map<String, String>());
    }
    
    private void populateUserEnterData() {
        List<Fusion_Benchmarking__c> fusionBenchMarkingList = FusionSOQLUtil.getFusionBenchmarkingDetail(new Map<String, String>());
        if(fusionBenchMarkingList.size() > 0) {
            for(Integer orderNumber : lineItemNumberToFieldAPINameMap.keySet()) {
                lineItemNoToMonthValueMap.put(orderNumber, Decimal.valueOf(String.valueOf(fusionBenchMarkingList[0].get(lineItemNumberToFieldAPINameMap.get(orderNumber)))));
                lineItemNoToYearValueMap.put(orderNumber, Decimal.valueOf(String.valueOf(fusionBenchMarkingList[0].get(lineItemNumberToFieldAPINameMap.get(orderNumber)))));
            }
        }
    }
    
    private void populateOtherData() {
        for(Fusion_Report_Line_Item__c fusionReportLineItemRec : fusionLineItemList) {
            if(!lineItemNumberToFieldAPINameMap.containsKey(Integer.valueOf(fusionReportLineItemRec.Order_Number__c))) {
                lineItemNoToMonthValueMap.put(Integer.valueOf(fusionReportLineItemRec.Order_Number__c), 
                        (fusionReportLineItemRec.Monthly_Value__c != null) ? fusionReportLineItemRec.Monthly_Value__c : 0);
                lineItemNoToYearValueMap.put(Integer.valueOf(fusionReportLineItemRec.Order_Number__c), 
                    (fusionReportLineItemRec.Yearly_Value__c != null) ? fusionReportLineItemRec.Yearly_Value__c : 0 );
            }
        }
    }
    
    private Map<Integer, String> lineItemNumberToFieldAPINameMap = new Map<Integer, String>{
        5 => 'Working_days_in_Period__c',
        6 => 'Employee_No_Sales__c',
        7 => 'Employee_No_Service_Technical__c',
        8 => 'Employee_No_Service_Non_Technical__c',
        9 => 'Employee_No_Parts__c',
        10 => 'Employee_No_Administration_Other__c',
        37 => 'No_Sales_People__c',
        48 => 'No_Insurance_Contracts_Written__c',
        70 => 'No_of_Working_Days__c',
        78 => 'Average_Technician_Prime_Labor_Cost__c'
    };
}