src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <label>General Configurations</label>
</CustomObject>

src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <fields>
        <fullName>Accounting_Enabled__c</fullName>
        <formula>IF(
	Integration_Name__c == &apos;Xero&apos;,
	$Setup.General_Configurations__c.Enable_Xero_Accounting__c,
	IF(
		Integration_Name__c == &apos;QuickBooks Online&apos;,
		 $Setup.QuickBooks_Configurations__c.Enable_QuickBooks__c,
		Enabled__c
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accounting Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MergeAndPostToBRPQueueableTest.cls
@isTest
private without sharing class MergeAndPostToBRPQueueableTest {
    @testSetup
    private static void setupTestData() {
		TestDataFactory.disableFLSChecks();
   }

    @isTest
    private static void mergeAndPostToBRPQueueableMethodTest() {
        String exportType = 'None';

        Set<String> attIdList = new Set<String>();
        attIdList.add('Set1');
        attIdList.add('Set2');

        DateTime dateTimeValue = System.today();
        //MergeAndPostToBRPQueueable mergeObj = new MergeAndPostToBRPQueueable(exportType, attIdList, dateTimeValue);

        General_Configurations__c genConfig = TestDataFactory.createGeneralConfig(1);

        IFW_IntegrationConfig__c ifwConfig = TestDataFactory.createIFWConfigForIntegrationCheck();
        ifwConfig.Integration_Name__c = 'BRP';
        DMLUtility.updateSobjectList('IFW_IntegrationConfig__c', ifwConfig);

        Test.startTest();
        System.enqueueJob(new MergeAndPostToBRPQueueable(exportType, attIdList, dateTimeValue));
        List<IFW_IntegrationConfig__c> configList = [SELECT Username__c, Password__c FROM IFW_IntegrationConfig__c 
        		WHERE Accounting_Enabled__c = true AND Integration_Name__c = 'BRP'];
        System.assertEquals(1, configList.size());
        Test.stopTest();
    }
}