src/objects/General_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used in Blackpurl app</description>
    <fields>
        <fullName>Enable_Two_Way_Text__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Configuration setting to enable or disable SMS reply functionality</description>
        <inlineHelpText>Configuration setting to enable or disable SMS reply functionality</inlineHelpText>
        <label>Enable Two Way Text</label>
        <type>Checkbox</type>
    </fields>
    <label>General Configurations</label>
</CustomObject>

src/objects/Message_History__c.object
<CustomObject>
    <fields>
        <fullName>Formatted_Phone__c</fullName>
        <formula>IF(Phone__c != null, 
IF(Sent_To__c != null &amp;&amp; Sent_To__r.BillingCountry != null , 
IF(Sent_To__r.BillingCountry == &apos;Australia&apos;, 
CASE( LEN(Phone__c) , 
8 , MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 5, 4) , 
10 , IF(BEGINS(Phone__c, &apos;04&apos;) || BEGINS(Phone__c, &apos;05&apos;) , 
MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 5, 3)+ &quot; &quot; +MID(Phone__c, 8, 3), 
MID(Phone__c, 0, 2) + &quot; &quot; +MID(Phone__c, 3, 4)+ &quot; &quot; +MID(Phone__c, 7, 4)) 
, Phone__c ), 


CASE( LEN(Phone__c) , 10, &quot;(&quot; + MID(Phone__c, 0, 3) + &quot;) &quot; +MID(Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Phone__c, 7, 4) , Phone__c)) 
, 
CASE( LEN(Phone__c) , 8 , MID(Phone__c, 0, 4) + &quot; &quot; +MID(Phone__c, 4, 4) , 
10, &quot;(&quot; + MID(Phone__c, 0, 3) + &quot;) &quot; +MID(Phone__c, 4, 3) 
+ &quot;-&quot; +MID(Phone__c, 7, 4) , Phone__c)), 
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMS_Body__c</fullName>
        <label>SMS Body</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incoming_SMS_Time__c</fullName>
        <label>Incoming SMS Time</label>
        <type>DateTime</type>
    </fields>

    <label>Message History</label>
    <nameField>
        <displayFormat>MSG-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message_Read_By__c.object
<CustomObject>
    <fields>
        <fullName>Message_Status__c</fullName>
        <label>Message Status</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <referenceTo>Message_History__c</referenceTo>
        <relationshipLabel>Messages Read By</relationshipLabel>
        <relationshipName>Messages_Read_By</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Messages_Read_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message Read By</label>
    <nameField>
        <displayFormat>MRB-{00000000}</displayFormat>
        <label>Message Read By Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages Read By</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IncomingMessageCtrlTest.cls
/**
 * Author: Reena Singh
 * Since: Nov 25, 2020
 * Name: IncomingMessageCtrlTest
 * Description: Controller test Class of Incoming Message.
**/
@isTest
public without sharing class IncomingMessageCtrlTest {

    @testSetup
    private static void setup() {       
        TestDataFactory.disableFLSChecks();
        Account testCustomer = TestUtil.createCustomer(true, 'Test Customer', 'a.b@gmail.com', 'Jaipur', '987456123');
        Message_Read_By__c messageReadyBy = new Message_Read_By__c();
        Message_History__c messageHistory = new Message_History__c();
        messageHistory.Sent_To__c = testCustomer.Id;
        insert messageHistory;
        messageReadyBy.Message__c = messageHistory.Id;
        messageReadyBy.User__c = UserInfo.getUserId();
        messageReadyBy.Message_Status__c = 'Unread';
        insert messageReadyBy;

        General_Configurations__c generalConfig = General_Configurations__c.getOrgDefaults();
        generalConfig.Enable_Two_Way_Text__c = true;
        upsert generalConfig;
    }

    @isTest
    private static void getIncomingMessagesForCurrentUserTest() {
        IncomingMessageService.SortingWrapper sortingObj = new IncomingMessageService.SortingWrapper();
        sortingObj.NumberOfRecPerPage = 25;
        sortingObj.SortDirForTimeRec = 'DESC';
        Test.startTest();
        IncomingMessageCtrl controller = new IncomingMessageCtrl();
        String unReadMsg = BPUtility.getDecodedString(IncomingMessageCtrl.getIncomingMessagesForCurrentUser(BPUtility.getEncodedString(System.JSON.serialize(sortingObj))));
        System.assertNotEquals(null, unReadMsg);
        Test.stopTest();
    }

    @isTest
    private static void getIncomingReadMessagesForCurrentUserTest() {
        IncomingMessageService.SortingWrapper sortingObj = new IncomingMessageService.SortingWrapper();
        sortingObj.NumberOfRecPerPage = 25;
        sortingObj.SortDirForTimeRec = 'DESC';
        List<Message_Read_By__c> messageReadyByList = [SELECT Id, Message_Status__c, Message__r.SMS_Body__c, Message__r.Sent_To__r.Name, Message__r.Incoming_SMS_Time__c, Message__r.Formatted_Phone__c FROM Message_Read_By__c where Message__r.Sent_To__c != null AND Message_Status__c = 'Unread'];
        system.assertEquals(messageReadyByList.size(), 1);
        messageReadyByList[0].Message_Status__c = 'Read';
        update messageReadyByList[0];
        Test.startTest();
        String readMsg = BPUtility.getDecodedString(IncomingMessageCtrl.getIncomingMessagesForCurrentUser(BPUtility.getEncodedString(System.JSON.serialize(sortingObj))));
        System.assertNotEquals(null, readMsg);
        Test.stopTest();
    }

    @isTest
    private static void toggleMessageReadStatusTest() {
        List<Message_Read_By__c> messageReadByList = [Select Id, Message_Status__c from Message_Read_By__c ];
        Test.startTest();
        String result = BPUtility.getDecodedString(IncomingMessageCtrl.toggleMessageReadStatus(BPUtility.getEncodedString(messageReadByList[0].Id)));
        System.assertEquals('Success', result);
        Test.stopTest();
    }

    @isTest
    private static void markAllAsReadTest() {
        List<Message_Read_By__c> messageReadByList = [Select Id, Message_Status__c from Message_Read_By__c where Message_Status__c = 'Unread'];
        system.assertEquals(messageReadByList.size(), 1);
        system.assertEquals(messageReadByList[0].Message_Status__c, 'Unread');
        Test.startTest();
        String result = BPUtility.getDecodedString(IncomingMessageCtrl.markAllAsRead());
        system.assertEquals('Success',result);
    	Test.stopTest();
    }

    @isTest
    private static void getUnreadMessageCountTest() {
        List<Message_Read_By__c> messageReadByList = [SELECT Id, Message_Status__c FROM Message_Read_By__c WHERE Message_Status__c = 'Unread' AND User__c =: UserInfo.getUserId()];
        system.assertEquals(messageReadByList.size() > 0, true);
        Test.startTest();
        System.assertEquals(1, IncomingMessageCtrl.getUnreadMessageCount());
    	Test.stopTest();
    }

    @isTest
    private static void getUnreadMessageCountForZeroTest() {
        General_Configurations__c generalConfig = General_Configurations__c.getOrgDefaults();
        generalConfig.Enable_Two_Way_Text__c = false;
        upsert generalConfig;
        Test.startTest();
        System.assertEquals(0, IncomingMessageCtrl.getUnreadMessageCount());
    	Test.stopTest();
    }

}