src/objects/Hours_Logged__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Paused_Date_Time__c</fullName>
        <description>The time when the session was paused.</description>
        <inlineHelpText>The time when the session was paused.</inlineHelpText>
        <label>Paused Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Paused_Hours__c</fullName>
        <description>Accumulated paused hours for the clocking session.</description>
        <inlineHelpText>Accumulated paused hours for the clocking session.</inlineHelpText>
        <label>Paused Hours</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Order_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Order Header</label>
        <referenceTo>Service_Order_Header__c</referenceTo>
        <relationshipLabel>Hours Logged</relationshipLabel>
        <relationshipName>Hours_Logged</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician</label>
        <referenceTo>Technician__c</referenceTo>
        <relationshipLabel>Hours Logged</relationshipLabel>
        <relationshipName>Hours_Logged</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hours Logged</label>
    <nameField>
        <displayFormat>HN-{00000000}</displayFormat>
        <label>Hours Logged Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hours Logged</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payroll_Time__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician</label>
        <referenceTo>Technician__c</referenceTo>
        <relationshipLabel>Payroll Times</relationshipLabel>
        <relationshipName>Payroll_Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payroll Time</label>
    <nameField>
        <displayFormat>PT-{00000000}</displayFormat>
        <label>Payroll Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payroll Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Technician__c.object
<CustomObject>
    <label>Technician</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Technician Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PayrollAndJobClockingAutoClockOffBatch.cls
/** 
* Author: Richa Mittal
* Since: Oct 11, 2023
* Name: PayrollAndJobClockingAutoClockOffBatch 
* Description: Batch Apex class to clock will automatically clock out any payroll or job clocking entries which are still active.
**/
global without sharing class PayrollAndJobClockingAutoClockOffBatch implements Database.Batchable<sobject>, Schedulable {
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new PayrollAndJobClockingAutoClockOffBatch(), 100);
    }

    global Iterable<sObject> start(Database.BatchableContext bc) {
        List<sObject> sObjList = new List<sObject>();
        sObjList.addAll([SELECT Id, Start_Date_Time__c, Service_Order_Header__c, Technician__c, Paused_Date_Time__c, Paused_Hours__c, End_Date_Time__c 
                            FROM Hours_Logged__c WHERE Start_Date_Time__c != null AND End_Date_Time__c = null]);
        sObjList.addAll([SELECT Id FROM Payroll_Time__c WHERE Start_Date__c != null AND End_Date__c = null]);
        return sObjList;
    }
      
    global void execute(Database.batchableContext bc, List<sObject> sObjList) {
        List<Hours_Logged__c> hoursLoggedList = new List<Hours_Logged__c>();
        List<Payroll_Time__c> payrollList = new List<Payroll_Time__c>();
        for(sObject sObjRec: sObjList) {
            String objectName = (Id.valueOf(sObjRec.Id)).getSObjectType().getDescribe().getName();
            if(objectName == Constants.NAMESPACE + 'Hours_Logged__c') {
                hoursLoggedList.add((Hours_Logged__c)sObjRec);
            } else if(objectName == Constants.NAMESPACE + 'Payroll_Time__c') {
                DateTime clockOffDtTime = DateTime.newInstance(System.now().year(), System.now().month(), System.now().day(), 
                                                                System.now().hour(), System.now().minute(), 0);
                sObjRec.put('End_Date__c', clockOffDtTime);
                payrollList.add((Payroll_Time__c)sObjRec);
            }
        }
        if(!hoursLoggedList.isEmpty()) {
            TechnicianService.setHoursLoggedDataWhenClcokedOff(null, null, hoursLoggedList);
        }
        DMLUtility.updateSobjectList('Payroll_Time__c', payrollList);
    }
      
    global void finish(Database.batchableContext bc) {
        syncHoursLoggedToAccounting();
    }

    private void syncHoursLoggedToAccounting() {
        if(GeneralConfiguration.isTechnicianHoursCostingEnabled() && String.isNotBlank(IntegrationServiceFactory.getActiveAccountingIntegrationName())) {
            // Sync to QB/Xero
            AccountingScriptUtil.syncHoursLogged(25, 60);
        }
    }
}