src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WebService_Log__c.object
<CustomObject>
    <description>used to store response codes including success and error</description>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>WebService Logs</relationshipLabel>
        <relationshipName>WebService_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WebService Log</label>
    <nameField>
        <label>WebService Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebService Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WebServiceLogTriggerHelper.cls
/**
 * Author: Nikhil Kumar Srivastava
 * Since: May 07, 2019
 * Name: WebServiceLogTriggerHelper
 * Description: Helper Class to execute operation on WebServiceLog
**/
public without sharing class WebServiceLogTriggerHelper {
	
	public static void afterInsert(List<WebService_Log__c> newList) {
		notifySupportTeamOnFirstAccountingFailure(newList);
	} 
	
	public static void notifySupportTeamOnFirstAccountingFailure(List<WebService_Log__c> newList){
		if(isErrorLogExists(newList)) {
			checkForFirstXeroErrorOfDay();
		} 
	}
	
	private static Boolean isErrorLogExists(List<WebService_Log__c> newList) {
		Boolean isErrorLogExist = false;
		for(WebService_Log__c webLogRec : newList) {
			if((webLogRec.Response_Code__c != '200' && webLogRec.Response_Code__c != '201') && webLogRec.Status__c != 'OK'&& 
			     !webLogRec.Name.startsWithIgnoreCase('xero')) {
				isErrorLogExist = true;
				break;
			}
		}
		return isErrorLogExist;
	}

	private static void checkForFirstXeroErrorOfDay() {
		String activeAccountingIntegrationName = IntegrationServiceFactory.getActiveAccountingIntegrationName();
		
		if(AccessControl.ifObjectFieldIsAccessible('WebService_Log__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
		List<WebService_Log__c> logRecordList = [SELECT Name, CreatedDate, Endpoint__c, IFW_IntegrationConfig__c, Status__c, Entity_Name__c, 
							IFW_IntegrationConfig__r.Integration_Name__c, Apex_Class__c FROM WebService_Log__c 
							WHERE CreatedDate = TODAY AND Response_Code__c != '200' AND Status__c != 'OK' LIMIT 2];
		if(logRecordList.size() == 1 && logRecordList[0].IFW_IntegrationConfig__r.Integration_Name__c != null && 
				logRecordList[0].IFW_IntegrationConfig__r.Integration_Name__c.equalsIgnoreCase(activeAccountingIntegrationName)) {
			IntegrationFailureNotificationService.notifySupportTeamForAccountingFirstFailure(logRecordList, activeAccountingIntegrationName);
		}
	}
}