src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <fields>
        <fullName>Accounting_Enabled__c</fullName>
        <formula>IF(
	Integration_Name__c == &apos;Xero&apos;,
	$Setup.General_Configurations__c.Enable_Xero_Accounting__c,
	IF(
		Integration_Name__c == &apos;QuickBooks Online&apos;,
		 $Setup.QuickBooks_Configurations__c.Enable_QuickBooks__c,
		Enabled__c
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accounting Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auth_Scheme__c</fullName>
        <label>Auth Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bearer_Token__c</fullName>
        <label>Bearer Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certifcate_Password__c</fullName>
        <label>Certifcate Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <label>Certificate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Id__c</fullName>
        <label>Company Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Key__c</fullName>
        <description>It will contains the public key of the integration.</description>
        <inlineHelpText>It will contains the public key of the integration.</inlineHelpText>
        <label>Public Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Timeout value in Ms</description>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Token_Expiry__c</fullName>
        <description>Token lifetime in seconds</description>
        <label>Token Expiry</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Token_Type__c</fullName>
        <label>Token Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>URL of the resource you will access</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Item</fullName>
                </value>
                <value>
                    <fullName>Journal Entry</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Organisation</fullName>
                </value>
				<value>
                    <fullName>Tax Rate</fullName>
                </value>
                <value>
                    <fullName>GetPartLocator</fullName>
                </value>
				<value>
                    <fullName>GetVehicleSpecification</fullName>
                </value>
                <value>
                    <fullName>GetDealer</fullName>
                </value>
                <value>
                    <fullName>Honda Part Inventory</fullName>
                </value>
                <value>
                    <fullName>Honda All Vendor Invoices</fullName>
                </value>
                <value>
                    <fullName>Honda Vendor Invoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartsInvoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartInventory</fullName>
                </value>
                <value>
                    <fullName>BRPRepairOrder</fullName>
                </value>
                <value>
                    <fullName>BRPRetailDeliveryReporting</fullName>
                </value>
                <value>
                    <fullName>Upsert Product</fullName>
                </value>
                <value>
                    <fullName>Payment Terminal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HTTP_Method__c</fullName>
        <label>HTTP Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Override parent Timeout if set</description>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuickBooks_Configurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations used for Integration</description>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Id__c</fullName>
        <label>Company Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Configurations</label>
</CustomObject>

src/objects/WebService_Log__c.object
<CustomObject>
    <description>used to store response codes including success and error</description>
    <fields>
        <fullName>CalloutStartTime__c</fullName>
        <label>Callout Start Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Callout_End_Time__c</fullName>
        <label>Callout End Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>WebService Logs</relationshipLabel>
        <relationshipName>WebService_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Description__c</fullName>
        <description>used to store response descriptions for end user reference</description>
        <label>Response Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WebService Log</label>
    <nameField>
        <label>WebService Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebService Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BaseIntegration.cls
public without sharing abstract class BaseIntegration {
    
    public static List<WebService_Log__c> webServiceLogs;
  	public static Integer DEFAULT_TIMEOUT = 20000;
  	
    public static String performCallout(Id childId, String body, List<CustomHttpHeaderWrapper> headerList) {
        return performCallout(childId, body, headerList, new Map<String, String>());
    }
    
    public static String performCallout(Id childId, String body, List<CustomHttpHeaderWrapper> headerList, Map<String,String> parameters) {
        IFW_IntegrationConfigItem__c child = getChild(childId);
	    IFW_IntegrationConfig__c parent = getParent(child.IFW_IntegrationConfig__c);
	    if(IFW_IntegrationConfigItem__c.Id == null) {
	        throw new applicationException ('Child not found');
	    }
	    HttpResponse res = performCallout(parent, child, body, headerList, parameters);
	    if(webServiceLogs.size() > 0) {
            DMLUtility.insertSobjectList('WebService_Log__c', webServiceLogs);
	    }
	    return res.getBody();
    }
    
    public static HttpResponse performCallout(IFW_IntegrationConfig__c parent, IFW_IntegrationConfigItem__c child, String body, 
                                                            List<CustomHttpHeaderWrapper> headerList) {
        return performCallout(parent, child, body, headerList, new Map<String, String>(), null);
    }
    
    public static HttpResponse performCallout(IFW_IntegrationConfig__c parent, IFW_IntegrationConfigItem__c child, String body, 
                                                            List<CustomHttpHeaderWrapper> headerList, String entityName) {
        return performCallout(parent, child, body, headerList, new Map<String, String>(), entityName);
    }
    
    
    public static HttpResponse performCallout(IFW_IntegrationConfig__c parent, IFW_IntegrationConfigItem__c child, String body, 
                                                List<CustomHttpHeaderWrapper> headerList, Map<String, String> parameters) {
        return performCallout(parent, child, body, headerList, parameters, null);                                                  
    }
                                                
    public static HttpResponse performCallout(IFW_IntegrationConfig__c parent, IFW_IntegrationConfigItem__c child, String body, 
                                                List<CustomHttpHeaderWrapper> headerList, Map<String, String> parameters, String entityName) {
        system.debug('Request Body'+ body);
        WebService_Log__c wsLog = new WebService_Log__c();
        wsLog.CalloutStartTime__c = double.valueOf(DateTime.now().GetTime());
        wsLog.IFW_IntegrationConfig__c = parent.Id;
        wsLog.Name = parent.Integration_Name__c + ' ' + String.valueOf(Datetime.now());
        
        HttpResponse res = new HttpResponse();
        if(parent.Auth_Scheme__c == 'Basic') {
            res = BasicAuthUtility.performCallout(parent, child, body, headerList, parameters);
            
            system.debug('=== before token expire res in BaseIntegration === ' + res.getBody() + '  ' + res.getStatusCode());
            
            // this is to refresh the BRP access token because BRP uses this acces token in basic API request
            if(parent.Integration_Name__c == BRPUtility.BRP && (res.getStatusCode() == 401 || res.getStatus() == 'Unauthorized')) {
            	res = BRPAuthorizationService.refreshBRPAccessTokenAndPerformCallout(parent, child, body, headerList, parameters);
            }
            system.debug('=== res in BaseIntegration === ' + res.getBody() + '  ' + res.getStatusCode());
        
        } else if(parent.Auth_Scheme__c == 'Basic with Token') {
            res = BasicAuthUtility.performBasicWithTokenCallout(parent, child, body, headerList, parameters);
        
        } else if(parent.Auth_Scheme__c == 'OAuth1.0') {
            res = OAuthUtility.executeOauth1Callout(child.HTTP_Method__c, body, parent.Consumer_Key__c, child.Endpoint_URL__c, 
                                                      parent.Certificate_Name__c, parameters);
        
        } else if(parent.Auth_Scheme__c == 'OAuth2.0') {
        	String accessToken = parent.Access_Token__c;
        	Integer timeout = parent.timeout__c != null ? Integer.valueOf(parent.timeout__c) : DEFAULT_TIMEOUT;
        	String tenantId = QuickBooks_Configurations__c.getOrgDefaults().Company_Id__c;
        	
        	res = OAuthUtility.executeOauth2Callout(child.HTTP_Method__c, body, accessToken, tenantId, child.Endpoint_URL__c, parameters, timeout, headerList);
            
            if(res.getStatusCode() == 401 || res.getBody().contains('TokenExpired') || res.getBody().contains('TokenInvalidSignature')) {
                if(parent.Integration_Name__c == BRPUtility.BRP_DMS_OAUTH2) {
                    accessToken = BRPAuthorizationService.refreshAccessTokenForBRPDMS(new List<IFW_IntegrationConfig__c>{parent});
                } else {
                    accessToken = refreshAccessToken(parent);
                }
                res = OAuthUtility.executeOauth2Callout(child.HTTP_Method__c, body, accessToken, tenantId, child.Endpoint_URL__c, parameters, timeout, headerList);
            }
        	system.debug('=== res in BaseIntegration === ' + res.getBody() + '  ' + res.getStatusCode());
        } else {
            throw new applicationException ('Unsupported Auth Scheme: '+parent.Auth_Scheme__c);
        }
        
        wsLog.Callout_End_Time__c = Double.valueOf(DateTime.now().getTime());
        wsLog.Request_Body__c = body != null ? body.abbreviate(32768): null;
        wslog.Response_Code__c = String.valueOf(res.getStatusCode());
        if(res.getStatusCode() != 200) {
            Integer resBodyLength = res.getBody().length();
            wsLog.Response_Body__c = resBodyLength > 32768 ?  (res.getBody()).subString(resBodyLength - 32768,  resBodyLength) : res.getBody();
        } else {
        	wsLog.Response_Body__c = res.getBody().abbreviate(32768);
        }
        wslog.Status__c = res.getStatus();
        wsLog.endpoint__c = child.endpoint_URL__c;
        if(parameters != null) {
           wsLog.endpoint__c = BaseIntegration.addURLParamsToEndPoint(child.endpoint_URL__c, parameters);
        }
        wsLog.endpoint__c = wsLog.endpoint__c != null ? wsLog.endpoint__c.abbreviate(255): null;
        wsLog.Entity_Name__c = entityName;
        
        if(wsLog.Response_Code__c != '200') {
            wslog.Response_Description__c = res.getBody().abbreviate(255);
        }
        if(webServiceLogs != null) {
            webServiceLogs.add(wsLog);
        } else {
        	webServiceLogs = new List<WebService_Log__c>{wsLog};
        }
        return res;
    }
    
    public static IFW_IntegrationConfigItem__c getChild(Id childId) {
        return [SELECT IFW_IntegrationConfig__c, Endpoint_URL__c, HTTP_Method__c, Timeout__c FROM IFW_IntegrationConfigItem__c WHERE Id =: childId];
    }
    
    public static List<IFW_IntegrationConfigItem__c> getChild(Map<String, String> fieldNameToFieldValueMap) {
        String query = 'SELECT IFW_IntegrationConfig__c, Endpoint_URL__c, HTTP_Method__c, Timeout__c FROM IFW_IntegrationConfigItem__c ';
        Boolean isWhereClauseAdded = false;
        for(String fieldName : fieldNameToFieldValueMap.keySet()) {
            if(!isWhereClauseAdded) {
                query += ' WHERE ' + fieldName + ' = \'' + fieldNameToFieldValueMap.get(fieldName) + '\'';
                isWhereClauseAdded = true;
            } else {
                query += ' AND ' + fieldName + ' = \'' + fieldNameToFieldValueMap.get(fieldName) + '\'';  
            }
        }
        return Database.query(query);
    }
    
    public static IFW_IntegrationConfig__c getParent(Id parentId) {
        return [SELECT Access_Token__c, Auth_Scheme__c, Bearer_Token__c, Certificate_Name__c, Certifcate_Password__c, Consumer_Key__c,
                  Consumer_Secret__c, Enabled__c, Integration_Name__c, Grant_Type__c, Password__c, Username__c, Refresh_Token__c, Timeout__c,
                  Token_Expiry__c, Token_Type__c, Client_Id__c, Client_Secret__c, Company_Id__c FROM IFW_IntegrationConfig__c WHERE Id =: parentId];
    }
    
    public static List<IFW_IntegrationConfig__c> getParentByName(String integrationName) {
        return [SELECT Access_Token__c, Auth_Scheme__c, Bearer_Token__c, Certificate_Name__c, Certifcate_Password__c, Consumer_Key__c, Accounting_Enabled__c, 
                  Consumer_Secret__c, Enabled__c, Integration_Name__c, Grant_Type__c, Password__c, Username__c, Refresh_Token__c, Timeout__c,
                  Token_Expiry__c, Token_Type__c, Client_Id__c, Client_Secret__c, Public_Key__c FROM IFW_IntegrationConfig__c WHERE Integration_Name__c =: integrationName AND Enabled__c = true];
    }
    
    public static String addURLParamsToEndPoint(String endPoint, Map<String, String> paramsMap) {
        String urlParamString = '';
        for(String param : paramsMap.keySet()) {
            urlParamString += (param + '=' + paramsMap.get(param)) + '&';
        }
        if(String.isNotBlank(endpoint) && paramsMap.size() > 0) {
            endpoint += '?' + urlParamString.subString(0, urlParamString.length() - 1);
        }
        return endpoint;
    }
    
    public static String refreshAccessToken(IFW_IntegrationConfig__c parent) {
		String encodedString = EncodingUtil.base64Encode(Blob.valueOf(parent.Client_Id__c+':'+parent.Client_Secret__c));
		String endPoint = '';
		if(parent.Integration_Name__c == 'Xero') {
			endPoint = 'https://identity.xero.com/connect/token';
		}
		
		String requestBody = 'grant_type=refresh_token&refresh_token='+parent.Refresh_Token__c;
		system.debug('endpoint********'+endPoint);
		HttpRequest httpReq = new HttpRequest();
		HttpResponse httpRes = new HttpResponse();
		Http http = new Http();
		httpReq.setMethod('POST');
		httpReq.setEndPoint(endPoint);
		httpReq.setHeader('Authorization', 'Basic '+encodedString);
		httpReq.setHeader('Content-Type', 'application/x-www-form-urlencoded');
		httpReq.setHeader('Accept', 'application/json');
		httpReq.setBody(requestBody);
		try {
			httpRes = http.send(httpReq);
			if(httpRes.getStatusCode() == 200) {
 				Map<String, Object> response_Map = (Map<String, Object>)JSON.deserializeUntyped(httpRes.getBody());
 				parent.Access_Token__c = (String)response_Map.get('access_token');
			    parent.Refresh_Token__c = (String)response_Map.get('refresh_token');
 				return (String)response_Map.get('access_token');
			} else {
				throw new BlackpurlException(httpRes.getBody());
			}
		} catch(System.Exception e) {
			throw new BlackpurlException(e.getMessage());
	 	}
 	}
	
	public static Id getIFWConfigItemByEntityName(String entityName, String methodType, String integrationName) {
        if(AccessControl.ifObjectIsAccessible('IFW_IntegrationConfigItem__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); } 
        List<IFW_IntegrationConfigItem__c> configItemList = 
                [SELECT Id from IFW_IntegrationConfigItem__c WHERE Entity_Name__c =: entityName AND HTTP_Method__c =: methodType
                    AND IFW_IntegrationConfig__r.Integration_Name__c =: integrationName];
        Id returnId;
        if(configItemList.size() > 0) {
            returnId = configItemList[0].Id;
        }
        return returnId;
    }
    
    public class applicationException extends Exception {}
    
}