src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <fields>
        <fullName>Access_Token_Secret__c</fullName>
        <label>Access Token Secret</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Accounting_Enabled__c</fullName>
        <formula>IF(
	Integration_Name__c == &apos;Xero&apos;,
	$Setup.General_Configurations__c.Enable_Xero_Accounting__c,
	IF(
		Integration_Name__c == &apos;QuickBooks Online&apos;,
		 $Setup.QuickBooks_Configurations__c.Enable_QuickBooks__c,
		Enabled__c
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accounting Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auth_Scheme__c</fullName>
        <label>Auth Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bearer_Token__c</fullName>
        <label>Bearer Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certifcate_Password__c</fullName>
        <label>Certifcate Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <label>Certificate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Id__c</fullName>
        <label>Company Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Consumer_Secret__c</fullName>
        <label>Consumer Secret</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grant_Type__c</fullName>
        <label>Grant Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <label>Integration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token__c</fullName>
        <label>Refresh Token</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Timeout value in Ms</description>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Token_Expiry__c</fullName>
        <description>Token lifetime in seconds</description>
        <label>Token Expiry</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Token_Type__c</fullName>
        <label>Token Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Id_Long__c</fullName>
        <label>Client Id(Long)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Client_Secret_Long__c</fullName>
        <label>Client Secret(Long)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>URL of the resource you will access</description>
        <label>Endpoint URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Action__c</fullName>
        <label>Entity Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Entity_Name__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Item</fullName>
                </value>
                <value>
                    <fullName>Journal Entry</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Organisation</fullName>
                </value>
				<value>
                    <fullName>Tax Rate</fullName>
                </value>
                <value>
                    <fullName>GetPartLocator</fullName>
                </value>
				<value>
                    <fullName>GetVehicleSpecification</fullName>
                </value>
                <value>
                    <fullName>GetDealer</fullName>
                </value>
                <value>
                    <fullName>Honda Part Inventory</fullName>
                </value>
                <value>
                    <fullName>Honda All Vendor Invoices</fullName>
                </value>
                <value>
                    <fullName>Honda Vendor Invoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartsInvoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartInventory</fullName>
                </value>
                <value>
                    <fullName>BRPRepairOrder</fullName>
                </value>
                <value>
                    <fullName>BRPRetailDeliveryReporting</fullName>
                </value>
                <value>
                    <fullName>Upsert Product</fullName>
                </value>
                <value>
                    <fullName>Payment Terminal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HTTP_Method__c</fullName>
        <label>HTTP Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <description>Override parent Timeout if set</description>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IFW_SOQLUtil.cls
public without sharing class IFW_SOQLUtil {
    
    public static List<IFW_IntegrationConfig__c> getIntegrationConfig(Map<String, Object> fieldAPINameToFieldValueMap) {
        String query = 'SELECT Access_Token__c, Auth_Scheme__c, Bearer_Token__c, Certificate_Name__c, Certifcate_Password__c, Consumer_Key__c, ' +
                  'Consumer_Secret__c, Accounting_Enabled__c, Integration_Name__c, Grant_Type__c, Password__c, Username__c, Refresh_Token__c, Timeout__c, ' +
                  'Token_Expiry__c, Token_Type__c, Integration_Type__c, Client_Id__c, Client_Secret__c, Company_Id__c, Client_Secret_Long__c, Client_Id_Long__c FROM IFW_IntegrationConfig__c ';
        query += getWhereClause(fieldAPINameToFieldValueMap);
        if(!AccessControl.ifObjectFieldIsAccessible('IFW_IntegrationConfig__c')) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query);
    }
    
    public static List<IFW_IntegrationConfigItem__c> getIntegrationConfigItem(Map<String, Object> fieldAPINameToFieldValueMap) {
        String query = 'SELECT IFW_IntegrationConfig__c, Endpoint_URL__c, HTTP_Method__c, Timeout__c FROM IFW_IntegrationConfigItem__c ';
        query += getWhereClause(fieldAPINameToFieldValueMap);
        if(!AccessControl.ifObjectFieldIsAccessible('IFW_IntegrationConfigItem__c')) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query);
    }
    
    public static List<IFW_IntegrationConfig__c> getIntegrationConfigWithItems(Map<String, Object> fieldAPINameToFieldValueMap) {
        String query = 'SELECT Access_Token__c, Auth_Scheme__c, Bearer_Token__c, Certificate_Name__c, Certifcate_Password__c, Consumer_Key__c, ' +
                  'Consumer_Secret__c, Accounting_Enabled__c, Integration_Name__c, Grant_Type__c, Password__c, Username__c, Refresh_Token__c, Timeout__c, ' +
                  'Token_Expiry__c, Token_Type__c, Integration_Type__c, Client_Id__c, Client_Secret__c, Company_Id__c, Client_Id_Long__c, Client_Secret_Long__c, ' +
                  '(SELECT IFW_IntegrationConfig__c, Endpoint_URL__c, HTTP_Method__c, Timeout__c, Entity_Name__c FROM IFW_IntegrationConfigItems__r) ' + 
                  ' FROM IFW_IntegrationConfig__c ';
        query += getWhereClause(fieldAPINameToFieldValueMap);
        if(!AccessControl.ifObjectFieldIsAccessible('IFW_IntegrationConfig__c')) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        return Database.query(query);
    }

    public static List<IFW_IntegrationConfig__c> getIntegrationConfigWithItems(String integrationName, Map<String, String> integrationEntityNameToActionMap) {
        return getIntegrationConfigWithItems(integrationName, integrationEntityNameToActionMap, true);
    }

    public static List<IFW_IntegrationConfig__c> getIntegrationConfigWithItems(String integrationName, Map<String, String> integrationEntityNameToActionMap, Boolean isFilterXeroAccEnabled) {
    	if(String.isBlank(integrationName)) {
    		throw new BlackpurlException('No active integration');
    	}
    	String query = 'SELECT Client_Id__c, Client_Secret__c, Access_Token__c, Access_Token_Secret__c, Auth_Scheme__c, Bearer_Token__c, Certificate_Name__c, Certifcate_Password__c, ' +
    	    'Consumer_Key__c, Consumer_Secret__c, Enabled__c, Integration_Name__c, Grant_Type__c, Password__c, ' +
			'Username__c, Refresh_Token__c, Timeout__c, Token_Expiry__c, Client_Id_Long__c, Client_Secret_Long__c, Token_Type__c, ' +
    					'(SELECT IFW_IntegrationConfig__c, Endpoint_URL__c, HTTP_Method__c, Timeout__c, Entity_Name__c FROM IFW_IntegrationConfigItems__r ';
    	if(integrationEntityNameToActionMap != null && integrationEntityNameToActionMap.size() > 0) {
    		query += 'WHERE ';
    		for(String xeroEntityName : integrationEntityNameToActionMap.keySet()) {
    			if(integrationEntityNameToActionMap.get(xeroEntityName) == null) {
    				query += '(Entity_Name__c = \'' + xeroEntityName + '\' AND (Entity_Action__c = null)) OR ';
    			} else {
    				query += '(Entity_Name__c = \'' + xeroEntityName + '\' AND (Entity_Action__c includes (\'' + integrationEntityNameToActionMap.get(xeroEntityName) + '\'))) OR ';
    			}
    		}
    		query = query.subString(0, query.length() - 4);
    	} else if(integrationName == QBUtil.QUICKBOOKS_ONLINE) { // considering for QB if integrationEntityNameToActionMap is having no value then we need to query IFW item with HTTP method GET
			query += 'WHERE HTTP_Method__c = \'GET\'';
		}
    	
    	query += ') FROM IFW_IntegrationConfig__c WHERE Integration_Name__c =: integrationName ';
		if(integrationName == XeroUtility.XERO) {
			query += (isFilterXeroAccEnabled ? ' AND Accounting_Enabled__c = true ' : ' AND Enabled__c = true ');
		} else if (integrationName == QBUtil.QUICKBOOKS_ONLINE) {
			query += ' AND Enabled__c = true '; // need to discuss for QB trasactions query do we need to use Accounting_Enabled__c = true ??
		}
    	return Database.query(query);													
    }

    public static String getWhereClause(Map<String, Object> fieldsMap) {
        String whereClause = '';
        for(String fieldName : fieldsMap.keySet()) {
            whereClause += ((whereClause.length() == 0) ? 'WHERE ' : 'AND ') + getConditionBasedOnDataType(fieldName, fieldsMap.get(fieldName));
        }
        return whereClause;
    }
    
    private static String getConditionBasedOnDataType(String fieldName, Object fieldValue) {
        String condition;
        if(fieldValue == null || fieldValue instanceOf BOOLEAN) {
            condition = fieldName + ' = ' + fieldValue + ' ';
        } else if(fieldValue instanceOf STRING || fieldValue instanceOf ID) {
            condition = fieldName + ' = \'' + fieldValue + '\' ';
        }
        return condition;
    }
}