src/objects/IFW_IntegrationConfig__c.object
<CustomObject>
    <description>Stores Integration Configuration for Specific Integration to a Dealer Org</description>
    <fields>
        <fullName>Auth_Scheme__c</fullName>
        <label>Auth Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <label>Certificate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Key__c</fullName>
        <label>Consumer Key</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IFW_IntegrationConfig</label>
    <nameField>
        <displayFormat>INTCONFIG-{00000}</displayFormat>
        <label>IFW_IntegrationConfig Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IFW_IntegrationConfigItem__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Item</fullName>
                </value>
                <value>
                    <fullName>Journal Entry</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Organisation</fullName>
                </value>
				<value>
                    <fullName>Tax Rate</fullName>
                </value>
                <value>
                    <fullName>GetPartLocator</fullName>
                </value>
				<value>
                    <fullName>GetVehicleSpecification</fullName>
                </value>
                <value>
                    <fullName>GetDealer</fullName>
                </value>
                <value>
                    <fullName>Honda Part Inventory</fullName>
                </value>
                <value>
                    <fullName>Honda All Vendor Invoices</fullName>
                </value>
                <value>
                    <fullName>Honda Vendor Invoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartsInvoice</fullName>
                </value>
                <value>
                    <fullName>BRPPartInventory</fullName>
                </value>
                <value>
                    <fullName>BRPRepairOrder</fullName>
                </value>
                <value>
                    <fullName>BRPRetailDeliveryReporting</fullName>
                </value>
                <value>
                    <fullName>Upsert Product</fullName>
                </value>
                <value>
                    <fullName>Payment Terminal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IFW_IntegrationConfig__c</fullName>
        <label>IFW_IntegrationConfig</label>
        <referenceTo>IFW_IntegrationConfig__c</referenceTo>
        <relationshipLabel>IFW_IntegrationConfigItems</relationshipLabel>
        <relationshipName>IFW_IntegrationConfigItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IFW_IntegrationConfigItem</label>
    <nameField>
        <displayFormat>INTITEM-{00000}</displayFormat>
        <label>IFW_IntegrationConfigItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IFW_IntegrationConfigItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BaseIntegrationTest.cls
@isTest
private class BaseIntegrationTest {
    
    private static list<customHttpHeaderWrapper> generateHeaderList(){
        customHttpHeaderWrapper header = new customHttpHeaderWrapper('Content-Type', 'applications/json');
        return new List<customHttpHeaderWrapper>{header};
    }
    
    static testmethod void basicAuthTest(){
        IFW_IntegrationConfig__c parent = TestUtil.sampleIFWConfigForXero();
        parent.Username__c = 'test@test.com';
        parent.Password__c = 'password';
        parent.Auth_Scheme__c = 'Basic';
        insert parent;

        IFW_IntegrationConfigItem__c child = TestUtil.createIFWConfigItemForXero('Journal Entry' , parent.Id);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IntegrationMockHttpResponseGenerator());
        BaseIntegration.performCallout(parent, child, '{}', generateHeaderList());
        Test.stopTest();
        system.assertEquals(child.Entity_Name__c, 'Journal Entry');
    }
    
    static testmethod void oAuth1Test(){
        
        IFW_IntegrationConfig__c parent = TestUtil.sampleIFWConfigForXero();
        parent.Consumer_Key__c = 'AHSKJHGHJGSHJGS';
        parent.Certificate_Name__c = 'XeroCertificate';
        parent.Auth_Scheme__c = 'OAuth1.0';
        parent.Integration_Name__c = 'Test';
        insert parent;

        IFW_IntegrationConfigItem__c child = TestUtil.createIFWConfigItemForXero('Journal Entry' , parent.Id);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IntegrationMockHttpResponseGenerator());
        BaseIntegration.performCallout(parent,child, '{}', generateHeaderList());
        Test.stopTest();
        system.assertEquals(child.Entity_Name__c, 'Journal Entry');
                  
    }

}