src/objects/Leave__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician</label>
        <referenceTo>Technician__c</referenceTo>
        <relationshipLabel>Leaves</relationshipLabel>
        <relationshipName>Leaves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </fields>
    <label>Leave</label>
    <nameField>
        <label>Leave Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Technician__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Labour_Cost_Per_Hour__c</fullName>
        <label>Labour Cost Per Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIN__c</fullName>
        <label>PIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technician_Name__c</fullName>
        <label>Technician Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Working_Days__c</fullName>
        <label>Working Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Technician</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Technician Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddEditTechnicianScheduleService.cls
public class AddEditTechnicianScheduleService {

    public static TechnicianDetailWrapper getTechnicianById(String technicianRecId) {
    	if(AccessControl.ifObjectFieldIsAccessible('Technician__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<Technician__c> technicianRecList = SOQLUtil.getTechnicianListByFieldName(new Map<String, String>{'Id' => technicianRecId});
        TechnicianDetailWrapper technicianDetailObj;
        if(technicianRecList.size() > 0) {
        	technicianDetailObj = new TechnicianDetailWrapper(technicianRecList[0]);
        }
        return technicianDetailObj;
    }
    
    public static void saveTechnicianDetail(String technicianDetailJSON) {
    	if(AccessControl.ifObjectFieldIsCreateable('Technician__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_CREATEABLE); }
        if(AccessControl.ifObjectFieldIsUpdateable('Technician__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_UPDATEABLE); }
        TechnicianDetailWrapper technicianDetailObj = (TechnicianDetailWrapper)System.JSON.deserialize(technicianDetailJSON, TechnicianDetailWrapper.class);
        Technician__c technicianRec = setTechnicianFields(technicianDetailObj);
        DMLUtility.upsertSobjectList('Technician__c', technicianRec);
    }
    
    private static Technician__c setTechnicianFields(TechnicianDetailWrapper technicianDetailObj) {
    	Technician__c technicianRec = new Technician__c(Id = technicianDetailObj.Id);
    	technicianRec.Type__c = (technicianDetailObj.IsTechnician != null && technicianDetailObj.IsTechnician) ? Constants.TECHNICIAN : null;
    	
		if(!technicianDetailObj.IsLicensedUser) {
    		technicianRec.First_Name__c = technicianDetailObj.FirstName;
	        technicianRec.Last_Name__c = technicianDetailObj.LastName;
	        technicianRec.Technician_Name__c = technicianRec.First_Name__c + ' ' + technicianRec.Last_Name__c;
    	}
    	
        if(technicianDetailObj.LabourCostPerHour != null && technicianDetailObj.LabourCostPerHour < 0) {
        	throw new BlackpurlException('Labor cost should be greater than or equal to 0.');
        }
        if(String.isNotBlank(technicianDetailObj.PIN) && (technicianDetailObj.PIN).trim().length() > 10 ) {
        	throw new BlackpurlException('Technician PIN should not be greater than 10 characters');
        }
    	if(technicianDetailObj.IsTechnician != null && technicianDetailObj.IsTechnician) {
    		technicianRec.Type__c = Constants.TECHNICIAN;
    		technicianRec.Role__c = technicianDetailObj.Role;
    		technicianRec.Labour_Cost_Per_Hour__c = technicianDetailObj.LabourCostPerHour;
        	technicianRec.Working_Days__c = technicianDetailObj.WorkingDays;
    	} else {
    		technicianRec.Type__c = null;
    	}
        technicianRec.PIN__c = technicianDetailobj.PIN;
        return technicianRec;
    }
    
    public static List<LeaveWrapper> getTechnicianLeavesByTechnicianId(String technicianRecId) {
    	if(AccessControl.ifObjectFieldIsAccessible('Leave__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_ACCESSIBLE); }
        List<Leave__c> leaveList = SOQLUtil.getTechnicianLeavesByTechnicianId(new Set<String>{technicianRecId});
        List<LeaveWrapper> leaveObjList = new List<LeaveWrapper>();
    	for(Leave__c leaveRec : leaveList) {
    		leaveObjList.add(new LeaveWrapper(leaveRec));
    	}
        return leaveObjList;
    }
    
    public static LeaveWrapper saveLeaveDetail(String leaveJSON) {
        LeaveWrapper leaveDetailObj = (LeaveWrapper)System.JSON.deserialize(leaveJSON, LeaveWrapper.class);
    	Leave__c leaveRec = new Leave__c(Id = leaveDetailObj.Id);
    	leaveRec.Name = leaveDetailObj.Type;
    	leaveRec.Technician__c = leaveDetailObj.TechnicianId;
    	leaveRec.From__c = DateTimeUtility.getConvertedDateTime(leaveDetailObj.FromDate, leaveDetailObj.FromTime);
    	leaveRec.To__c = DateTimeUtility.getConvertedDateTime(leaveDetailObj.ToDate, leaveDetailObj.ToTime);
    
        DMLUtility.upsertSobjectList('Leave__c', leaveRec);
        return new LeaveWrapper(leaveRec);
    }
    
    public static void deleteLeave(String leaveId) {
    	if(AccessControl.ifObjectIsDeletable('Leave__c') == false) { throw new BlackPurlException(Constants.OBJIECT_NOT_DELETABLE); }
        delete new Leave__c(Id = leaveId);
    }
}