src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LocationWrapper.cls
/**
 * Author: Tarun Khandelwal
 * Since: Aug 26, 2019 
 * Name: LocationWrapper
 * Description: Used to handle all JSON related work of Location
**/
public without sharing class LocationWrapper {
    
    public String Id;
    public String Name;
    public Boolean IsActive;
    public DateTime CreatedDate;
    
    public LocationWrapper(Location__c locationRec) {
        this.Id = locationRec.Id;
        this.Name = locationRec.Name__c;
        this.IsActive = locationRec.Active__c;
        this.CreatedDate = locationRec.CreatedDate;
    }

    public class PaginatedLocation {
        public String SortBy;
        public Boolean Reverse;
        public String LocationSearchStr;
        public Integer StartIndex;
        public Integer RecordCount;
    }
    
    public static List<String> getLocationFieldList() {
        return new List<String>{ 'Id', 
                                'Name__c',
                                'Active__c',
                                'CreatedDate'
                        };
    }
}