src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <label>Integration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>QuickBooks Online</fullName>
                </value>
                <value>
                    <fullName>QB</fullName>
                </value>
                <value>
                    <fullName>MYOB</fullName>
                </value>
                <value>
                    <fullName>SOM</fullName>
                </value>
                <value>
                    <fullName>XERO</fullName>
                </value>
                <value>
                    <fullName>Part Count</fullName>
                </value>
                <value>
                    <fullName>HONDA</fullName>
                </value>
                <value>
                    <fullName>Automated Price File</fullName>
                </value>
                <value>
                    <fullName>FTP</fullName>
                </value>
                <value>
                    <fullName>Generic Export</fullName>
                </value>
                <value>
                    <fullName>Re-Open Deal</fullName>
                </value>
                <value>
                    <fullName>Re-Open Invoice</fullName>
                </value>
                <value>
                    <fullName>Shopify</fullName>
                </value>
                <value>
	                <fullName>Preferred Payment</fullName>
	            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Info__c</fullName>
        <label>Log Info</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method_Params__c</fullName>
        <label>Method Params</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message_History__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sent_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sent By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMS_Body__c</fullName>
        <label>SMS Body</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>

    <label>Message History</label>
    <nameField>
        <displayFormat>MSG-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SMSTextToSpecificNumberScheduler.cls
/**
* Author : Manoj Sharma
* Since : May 24, 2023
* Name : SMSTextToSpecificNumberScheduler
* Description : Scheduler class to send sms on specific number.
**/
global without sharing class SMSTextToSpecificNumberScheduler implements Schedulable  {
    public static String phoneNumber = '17192294983';
    global void execute(SchedulableContext sc) {
       if(!KenectService.isKenectEnable() && GeneralConfiguration.isSMSPhoneNumberConfigured()) sendSMSToNumber();
    }

    @future (callout=true)
    global static void sendSMSToNumber() {
        List<Log__c> logListToInsert = new List<Log__c>();
        try {
            String messageText = 'Hi, This is the monthly testing message from the Blackpurl.';
            String response = SendMessage.sendUsingPlivo(phoneNumber, messageText);
            if(response == 'Success') {
                Message_History__c msgRec = new Message_History__c();
                msgRec.Sent_By__c = UserInfo.getUserId();
                msgRec.Phone__c = phoneNumber;
                msgRec.SMS_Body__c = messageText;
                DMLUtility.insertSobjectList('Message_History__c', msgRec);
            } else {
                logListToInsert.add(new Log__c(Integration_Type__c = 'Plivo', Log_Info__c = response,
                                Method_Params__c = 'Phone Number ' + phoneNumber, Method__c = 'sendSMSToNumber()', 
                                Apex_Class__c = 'SMSTextToSpecificNumberScheduler', Type__c = 'Error'));
            }
        } catch (Exception e) {
            logListToInsert.add(new Log__c(Integration_Type__c = 'Plivo', Log_Info__c = e.getMessage(),
	        				Method_Params__c = 'Phone Number ' + phoneNumber, Method__c = 'sendSMSToNumber()', 
							Apex_Class__c = 'SMSTextToSpecificNumberScheduler', Type__c = 'Error'));
        }
        DMLUtility.insertSobjectList('Log__c', logListToInsert);
    }
}