src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Part</description>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PO_Type__c.object
<CustomObject>
    <label>Purchase Order Type</label>
    <nameField>
        <displayFormat>POT-{0000000}</displayFormat>
        <label>PO Type Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Receiving_Group__c.object
<CustomObject>
    <fields>
        <fullName>Ignore_Current_Cost_Update__c</fullName>
	    <defaultValue>false</defaultValue>
	    <description>In order to ignore part cost update when user actions learn more button and make changes in current VRG cost update setting from true to false on modal, we turn this flag ON considering that while finalizing receiving we will ignore this group from updating part cost.</description>
	    <inlineHelpText>To ignore part current cost update while finalizing vendor receiving.</inlineHelpText>
	    <label>Ignore Current Cost Update</label>
	    <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Order_As_Individual_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Order As Individual Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Vendor Receiving Group Parts</relationshipLabel>
        <relationshipName>Vendor_Receiving_Group_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Update_Reviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To track if user changed cost update setting or not.</description>
        <inlineHelpText>To track if user changed cost update setting or not.</inlineHelpText>
        <label>Cost Update Reviewed</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Receiving Group</label>
    <nameField>
        <displayFormat>VG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Receiving Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VRGCurrentCostSettingWrapper.cls
/**
 * Author: Nidhi Sharma
 * Since: September 14, 2022
 * Name: VRGCurrentCostSettingWrapper
 * Description: VRG current cost setting wrapper class
**/
public class VRGCurrentCostSettingWrapper {
    public String VRGId;
    public String ItemDesc;
    public Boolean IsUpdateCurrentCost;

    public VRGCurrentCostSettingWrapper(Vendor_Receiving_Group__c vrGroup, PO_Type__c vendorDefaultPOType) {
        if(vrGroup != null && vrGroup.Part__c != null) {
            this.VRGId = vrGroup.Id;
            this.ItemDesc = vrGroup.Part__r.Part_Number__c + ' - ' + vrGroup.Part__r.Description__c + 
                            (vrGroup.Is_Order_As_Individual_Item__c ? ' (Ordered as individual items)' : '');
            if(vrGroup.Cost_Update_Reviewed__c) {
                this.IsUpdateCurrentCost = !vrGroup.Ignore_Current_Cost_Update__c;
            } else {
                this.IsUpdateCurrentCost = VendorOrderReceivingService.getCurrentCostUpdateSetting(vrGroup, vendorDefaultPOType);
            }
        }
    }
}