src/objects/Part__c.object
<CustomObject>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part_FIFO_Bucket__c.object
<CustomObject>
    <fields>
        <fullName>Average_Cost_When_Created__c</fullName>
        <label>Average Cost When Created</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_FIFO_Bucket__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is FIFO Bucket</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part FIFO Buckets</relationshipLabel>
        <relationshipName>Part_FIFO_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_In_Stock_When_Created__c</fullName>
        <label>Qty In Stock When Created</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Qty_In__c</fullName>
        <label>Qty In</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Part FIFO Bucket</label>
    <nameField>
        <displayFormat>PBN-{00000000}</displayFormat>
        <label>Part FIFO Bucket  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part FIFO Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SetQtyAndAvgCostOnFIFOBktAndLIBatch.cls
/**
 * Author: Nidhi Sharma
 * Since: Sept 12, 2018
 * Name: SetQtyAndAvgCostOnFIFOBktAndLIBatch
 * Description: Batch for Populating fields on part and vendor
 * This is calling from queueable to avaoid Too many DML rows: 10001 - #18892
**/
global without sharing class SetQtyAndAvgCostOnFIFOBktAndLIBatch implements Database.Batchable<sobject> {
	
	private Set<String> recordIds;
	global Boolean isTriggerDisabled = false;
	global SetQtyAndAvgCostOnFIFOBktAndLIBatch() {}

	global SetQtyAndAvgCostOnFIFOBktAndLIBatch(Set<String> recordIdSet) {
	    recordIds = recordIdSet;
	}

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String partStrQuery = 'SELECT Id FROM Part__c';
        if(recordIds != null && recordIds.size() > 0) {
            partStrQuery += ' Where Id IN: recordIds';
        }
        partStrQuery += ' Order By CreatedDate ASC';
	    return Database.getQueryLocator(partStrQuery);
	}
	
    global void execute(Database.batchableContext bc, List<sObject> scope) {
        List<Part__c> partList = [SELECT Id, (Select Id, CreatedDate, Cost__c, Qty_In__c, Qty_In_Stock_When_Created__c, Average_Cost_When_Created__c FROM Part_FIFO_Buckets__r WHERE Is_FIFO_Bucket__c = true Order By CreatedDate ASC) FROM Part__c WHERE Id IN :scope];
    	FIFOTransaction.updatePartFIFODetails(partList);
    }
    
    global void finish(Database.batchableContext bc) {}
}