src/objects/Part__c.object
<CustomObject>
    <fields>
        <fullName>Is_Superseded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Superseded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Part_ID__c</fullName>
        <description>Merge of Part Number and Vendor Code</description>
        <formula>Part_Number__c  &amp; Vendor_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Merge of Part Number and Vendor Code</inlineHelpText>
        <label>Part ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Superseded_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Superseded To</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Parts (Superseded To)</relationshipLabel>
        <relationshipName>Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Part</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Part_Alternates__c.object
<CustomObject>
    <fields>
        <fullName>Alternate_Part_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Alternate Part ID</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part Alternates (Alternate Part ID)</relationshipLabel>
        <relationshipName>Part_Alternates1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Part ID</label>
        <referenceTo>Part__c</referenceTo>
        <relationshipLabel>Part Alternates</relationshipLabel>
        <relationshipName>Part_Alternates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relation__c</fullName>
        <label>Relation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Replaces</fullName>
                </value>
                <value>
                    <fullName>Replaced By</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Part Alternates</label>
    <nameField>
        <displayFormat>PAN-{0000000}</displayFormat>
        <label>Part Alternates Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Alternates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateSupersessionFieldsOnPartBatch.cls
/** 
* Author: Richa Mittal
* Since: Dec 12, 2019
* Name: UpdateSupersessionFieldsOnPartBatch 
* Description: Batch class to update Supersession Fields on Part record
**/
global without sharing class UpdateSupersessionFieldsOnPartBatch implements Database.Batchable<sobject> {
	
    global Database.QueryLocator start(Database.BatchableContext bc) {
    	BPScriptUtility.disbaleTrigger('PartTrigger');
        String strQuery = 'SELECT Alternate_Part_ID__c, Relation__c, Part_ID__c ' + 
        					'FROM Part_Alternates__c WHERE Relation__c = \'Replaced By\'';
        return Database.getQueryLocator(strQuery);
    }
    
    global void execute(Database.batchableContext bc, List<Part_Alternates__c> partAlternatesList) {
        List<Part__c> partListToUpdate = new List<Part__c>();
        for(Part_Alternates__c partAlternateRec: partAlternatesList) {
        	partListToUpdate.add(new Part__c(Id = partAlternateRec.Part_ID__c, Is_Superseded__c = true, Superseded_To__c = partAlternateRec.Alternate_Part_ID__c));
        }
        if(partListToUpdate.size() > 0) {
    		update partListToUpdate;
    	}
    }
    
    global void finish(Database.batchableContext bc) {
    	BPScriptUtility.enableTrigger('PartTrigger');
    }
}