src/objects/Price_Level__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Markup__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount-Markup</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Labour_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Labour Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Part_Price_Base__c</fullName>
        <label>Part Price Base</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Average Cost</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>MSRP</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Price Level</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PriceLevelTest.cls
@isTest
private class PriceLevelTest {
	@testSetup
    private static void setupTestData() {
		TestDataFactory.disableFLSChecks();
   }
	static testMethod void testPriceLevel() {
		
		String priceLevelName = 'Default Price Level';
		TestUtil.createPriceLevel(true, priceLevelName, 'MSRP', 10 , true, true);
		
		Price_Level__c defaultPriceLevel = [Select Id, Name__c, Default__c, Description__c, Part_Price_Base__c, Discount_Markup__c, Labour_Rate__c, Active__c from Price_Level__c Where name__c=:priceLevelName Limit 1];
		PriceLevel priceLevelObj = new PriceLevel(defaultPriceLevel);
		
		System.assertEquals(priceLevelName, defaultPriceLevel.name__c);
		System.assertEquals(true, defaultPriceLevel.Default__c);
	}
	
	static testMethod void testFieldsList() {
		
		List<String> fieldsList = PriceLevel.fieldsList();
		
		System.assertNotEquals(null, fieldsList);
		System.assertEquals(8, fieldsList.size());
	}
}