src/objects/Return_VO_Header__c.object
<CustomObject>
    <fields>
        <fullName>Credits_Pending__c</fullName>
        <description>Total pre-tax cost of all of the line items that have not been credited.</description>
        <inlineHelpText>Total pre-tax cost of all of the line items that have not been credited.</inlineHelpText>
        <label>Credits Pending</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>        
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Credited</fullName>
                </value>
                <value>
                    <fullName>Partially Credited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubTotal__c</fullName>
        <label>SubTotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Return VO Header</label>
    <nameField>
        <displayFormat>RTN-{00000000}</displayFormat>
        <label>Return VO Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return VO Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Return_VO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <formula>IF(TEXT(Return_CR_Line_Item__r.Return_CR_Header__r.Status__c) == &apos;Credited&apos;, &apos;Credited&apos;, &apos;Pending&apos;)</formula>
        <label>Credit Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Cost__c</fullName>
        <label>Item Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Return_Qty__c</fullName>
        <label>Return Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Return_VO_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Return VO Header</label>
        <referenceTo>Return_VO_Header__c</referenceTo>
        <relationshipLabel>Return VO Line Items</relationshipLabel>
        <relationshipName>Return_VO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Return VO Line Item</label>
    <nameField>
        <displayFormat>RVOLI-{00000000}</displayFormat>
        <label>Return VO Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return VO Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateCreditsPendingOnRVOBatch.cls
global without sharing class PopulateCreditsPendingOnRVOBatch extends PostInstallScriptBaseBatch {

    global PopulateCreditsPendingOnRVOBatch() {
        this.scriptName = 'executePopulateCreditsPendingOnRVOBatch()';
    }

    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'Select Id from Return_VO_Header__c where Credits_Pending__c = null';
        return Database.getQueryLocator(strQuery); 
    }

    global override void executeScript(Database.BatchableContext bc, List<SObject> rvoList) {
        List<Return_VO_Header__c> rvoWithLIList = [SELECT SubTotal__c, Status__c, (SELECT Item_Cost__c, Return_Qty__c FROM Return_VO_Line_Items__r WHERE Credit_Status__c = 'Pending') FROM Return_VO_Header__c WHERE Id IN :rvoList];
        for(Return_VO_Header__c rvoHeaderRec: rvoWithLIList) {
            if(rvoHeaderRec.Status__c == 'Approved') {
                rvoHeaderRec.Credits_Pending__c = rvoHeaderRec.SubTotal__c;
            } else if(rvoHeaderRec.Status__c == 'Partially Credited') {
                rvoHeaderRec.Credits_Pending__c = 0;
                for(Return_VO_Line_Item__c rvoliRec: rvoHeaderRec.Return_VO_Line_Items__r) {
                    rvoHeaderRec.Credits_Pending__c += ((rvoliRec.Item_Cost__c != null ? rvoliRec.Item_Cost__c : 0) * (rvoliRec.Return_Qty__c != null ? rvoliRec.Return_Qty__c : 0));
                }
            } else {
                rvoHeaderRec.Credits_Pending__c = 0;
            }
        }
        ReturnVOHeaderTriggerHelper.isForceStopTrigger = true;
        DMLUtility.updateSobjectList('Return_VO_Header__c', rvoWithLIList);
        ReturnVOHeaderTriggerHelper.isForceStopTrigger = false;
    }
    
    global override void finishScript(Database.BatchableContext bc) {}
}