src/objects/Service_Order_Header__c.object
<CustomObject>
    <description>Object used to handle service related section on Customer order header</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>Unique name field</description>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SO_Status__c</fullName>
        <formula>SO_Status_Ref__r.Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SO Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SO_Status_Ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SO Status Ref</label>
        <referenceTo>SO_Status__c</referenceTo>
        <relationshipLabel>Service Order Headers (SO Status Ref)</relationshipLabel>
        <relationshipName>Service_Order_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Status__c</fullName>
        <label>Work Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New job</fullName>
                </value>
                <value>
                    <fullName>Estimate</fullName>
                </value>
                <value>
                    <fullName>Triage required</fullName>
                </value>
                <value>
                    <fullName>Triage done</fullName>
                </value>
                <value>
                    <fullName>Customer to ok</fullName>
                </value>
                <value>
                    <fullName>Customer approved</fullName>
                </value>
                <value>
                    <fullName>Ready to start</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Wait for parts</fullName>
                </value>
                <value>
                    <fullName>PartMgr review</fullName>
                </value>
                <value>
                    <fullName>ServMgr review</fullName>
                </value>
                <value>
                    <fullName>Job complete</fullName>
                </value>
                <value>
                    <fullName>Ready to invoice</fullName>
                </value>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Order Header</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order Header Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SO_Status__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SO Status</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>SO Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SO Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceJobStatusUpdateBatch.cls
/** Author: Nidhi Sharma
 * Since: Oct 10, 2023
 * Name: ServiceJobStatusUpdateBatch
 * Description: 
**/
global without sharing class ServiceJobStatusUpdateBatch extends PostInstallScriptBaseBatch {

    global ServiceJobStatusUpdateBatch() {
        this.scriptName = 'executeServiceJobStatusUpdateBatch()';
    }
    
    global override Database.QueryLocator startScript(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id, Work_Status__c FROM Service_Order_Header__c WHERE Work_Status__c != null AND SO_Status_Ref__c = null';
        return Database.getQueryLocator(strQuery);
    }
    
    global override void executeScript(Database.BatchableContext bc, List<SObject> soList) {
        Map<String, Id> soStatusNameToIdMap = getSOStatusNameToIdMap(); 
        for(Service_Order_Header__c soRec : (List<Service_Order_Header__c>)soList) {
            if(UpdateServiceJobStatusBatch.oldSOStatusToNewStatusMap.containsKey(soRec.Work_Status__c)) {
                soRec.Work_Status__c = UpdateServiceJobStatusBatch.oldSOStatusToNewStatusMap.get(soRec.Work_Status__c);
            }
            soRec.SO_Status_Ref__c = soStatusNameToIdMap.get(soRec.Work_Status__c.toLowerCase());
        }
        SOTriggerHelper.isForceStopTrigger = true;
        DMLUtility.updateSobjectList('Service_Order_Header__c', soList);
        SOTriggerHelper.isForceStopTrigger = false;
    }
    
    global override void finishScript(Database.BatchableContext bc) {}

    private static Map<String, Id> getSOStatusNameToIdMap() {
        Map<String, Id> statusNameToIdMap = new Map<String, Id>();
        for(SO_Status__c soStatusRec : [Select Id, Name__c FROM SO_Status__c ORDER BY Order_No__c]) {
            statusNameToIdMap.put(soStatusRec.Name__c.toLowerCase(), soStatusRec.Id);
        }
        return statusNameToIdMap;
    }
}