src/objects/SO_Status__c.object
<CustomObject>
    <fields>
        <fullName>Background_Color__c</fullName>
        <label>Background Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Clock_ON_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Clock ON Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text_Color__c</fullName>
        <label>Text Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SO Status</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>SO Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SO Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceJobStatusWrapper.cls
/**
 * Author: Nidhi Sharma
 * Since: Nov. 30, 2022
 * Name: ServiceJobStatusWrapper
**/
public without sharing class ServiceJobStatusWrapper {
	
    public String Id;
    public String Name;
    public String ShortName;
    public Boolean IsActive;
    public Boolean IsRequired;
    public Integer OrderNo;
    public String TextColor;
    public String BgColor;
    public Boolean IsTechClockJobStatus;

    public ServiceJobStatusWrapper(SO_Status__c soStatusRec) {
        if(soStatusRec != null) {
            Id = soStatusRec.Id;
            Name = soStatusRec.Name__c;
            ShortName = soStatusRec.Short_Name__c;
            IsActive = soStatusRec.Is_Active__c;
            IsRequired = soStatusRec.Is_Required__c;
            OrderNo = soStatusRec.Order_No__c != null ? Integer.valueOf(soStatusRec.Order_No__c) : 10;
            TextColor = soStatusRec.Text_Color__c;
            BgColor = soStatusRec.Background_Color__c;
            IsTechClockJobStatus = soStatusRec.Is_Active__c && soStatusRec.Default_Clock_ON_Status__c;
        }
    }
}