src/objects/Summary_Log__c.object
<CustomObject>
    <fields>
        <fullName>Failed_Record_Count__c</fullName>
        <label>Failed Record Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inserted_Record_Count__c</fullName>
        <label>Inserted Record Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Updated_Record_Count__c</fullName>
        <label>Updated Record Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Master</label>
        <referenceTo>Vendor_Master__c</referenceTo>
        <relationshipLabel>Summary Logs</relationshipLabel>
        <relationshipName>Summary_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Summary Log</label>
    <nameField>
        <displayFormat>SL-{00000000}</displayFormat>
        <label>Summary Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Master__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Vendor_Master_Identifier__c</fullName>
        <label>Partner Vendor Master Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_File_Import_Status__c</fullName>
        <label>Price File Import Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued for import</fullName>
                </value>
                <value>
                    <fullName>Import in progress</fullName>
                </value>
                <value>
                    <fullName>Failed to import</fullName>
                </value>
                <value>
                    <fullName>Review import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Blackpurl_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Blackpurl Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Masters</relationshipLabel>
        <relationshipName>Vendor_Masters</relationshipName>
        <type>Lookup</type>
	</fields>
    <label>Vendor Master</label>
    <nameField>
        <displayFormat>VM-{00000000}</displayFormat>
        <label>Vendor Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APF_FinishImportRestService.cls
@RestResource(urlMapping = '/apf/finishImport/*')
global without sharing class APF_FinishImportRestService {
    
    @HttpPost
    global static String doPost() {
        RequestWrapper requestObj = (RequestWrapper)JSON.deserialize(RestContext.request.requestBody.toString(), RequestWrapper.class);
        finishImport(requestObj);
        return 'Price file import has been completed successfully. Inserted parts: ' + requestObj.createdParts + ', Updated parts: ' + requestObj.updatedParts + ', Failed parts: ' + requestObj.failedParts;
    }

    private static void finishImport(APF_FinishImportRestService.RequestWrapper requestObj) {
        if(String.isNotBlank(requestObj.vendorMasterId)) {
            for(Vendor_Master__c vendorMasterRec : [SELECT Blackpurl_Vendor__c, Partner_Vendor_Master_Identifier__c, (Select Id FROM Summary_Logs__r WHERE Id =: requestObj.requestId) FROM Vendor_Master__c WHERE Id = :requestObj.vendorMasterId]) {
                requestObj.createdParts = requestObj.createdParts != null ? requestObj.createdParts : 0;
                requestObj.updatedParts = requestObj.updatedParts != null ? requestObj.updatedParts : 0;
                requestObj.failedParts = requestObj.failedParts != null ? requestObj.failedParts : 0;
                if(!vendorMasterRec.Summary_Logs__r.isEmpty()) {
                    vendorMasterRec.Summary_Logs__r[0].Inserted_Record_Count__c = requestObj.createdParts;
                    vendorMasterRec.Summary_Logs__r[0].Updated_Record_Count__c = requestObj.updatedParts;
                    vendorMasterRec.Summary_Logs__r[0].Failed_Record_Count__c = requestObj.failedParts;
                    DMLUtility.updateSobjectList('Summary_Log__c', vendorMasterRec.Summary_Logs__r[0]);
                }
                vendorMasterRec.Price_File_Import_Status__c = (requestObj.failedParts > 0 ? 'Failed to import' : 'Review import');
                DMLUtility.updateSobjectList('Vendor_Master__c', vendorMasterRec);

                if(!Test.isRunningTest()) {
                    ActivityHistory.createActivityHistory('Price File Import', 'Vendor', vendorMasterRec.Blackpurl_Vendor__c, 'Vendor', vendorMasterRec.Blackpurl_Vendor__c, null);
                }
                AutomatedPriceFileService.updateVendorMasterSubscriberPartnerOrg(new Set<String>{vendorMasterRec.Partner_Vendor_Master_Identifier__c}, vendorMasterRec.Id);
                ImportSupersessionPart_Batch batchObj = new ImportSupersessionPart_Batch(null, 200);
            }
        } else {
            throw new BlackpurlException('Vendor Master Id is required.');
        }
    }
    
    global class RequestWrapper {
        public String vendorMasterId;
        public String requestId;
        public Integer createdParts;
        public Integer updatedParts;
        public Integer failedParts;
    }
}