src/objects/Sync_Error_Log__c.object
<CustomObject>
    <description>Object to store data for any sync failure caused while sending data to third party like Elastic Search.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sync Error Log</label>
    <nameField>
        <displayFormat>SELog-{00000000}</displayFormat>
        <label>Sync Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SyncErrorLogTriggerTest.cls
@isTest
private class SyncErrorLogTriggerTest {
    
    @testSetup
    private static void setupTestData() {
		TestDataFactory.disableFLSChecks();

        Sync_Error_Log__c ser = new Sync_Error_Log__c();
        ser.Error_Message__c = 'Test Error Message';
        insert ser;
    }

    private static testMethod void myUnitTest() {
        List<Sync_Error_Log__c> serList = [SELECT Id FROM Sync_Error_Log__c];
        System.assertEquals(1, serList.size());
        
        Sync_Error_Log__c ser = serList[0];
        ser.Error_Message__c = 'Test Error Message Updated';
        update ser;
        
        ser = [SELECT Id, Error_Message__c FROM Sync_Error_Log__c WHERE Id = :ser.Id];
        System.assertEquals('Test Error Message Updated', ser.Error_Message__c);
    }
}