src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Model_Description__c</fullName>
        <label>Model Description (Depricated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>unit model description</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Model_Description__c</fullName>
        <label>Sub Model Description (Deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Unit sub model description</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateModelSubModelDescBatch.cls
/**
 * Author: Tarun Khandelwal
 * Since: July 1, 2021
 * Name: PopulateModelSubModelDescBatch
 * Description: Batch for Populating Description field on Unit Model and Unit SubModel
**/ 
global without sharing class PopulateModelSubModelDescBatch implements Database.Batchable<sobject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        BPScriptUtility.disbaleTrigger('UnitModelTrigger');
        BPScriptUtility.disbaleTrigger('UnitSubModelTrigger');
        return Database.getQueryLocator('SELECT Model_Description__c FROM Unit_Model__c');
    }
    
    public void execute(Database.batchableContext bc, List<Unit_Model__c> unitModelList) {
        updateModelDescription(unitModelList);
        
        Set<Id> unitModelIdSet = getModelIdSet(unitModelList);
        updateSubModelDescription(unitModelIdSet); 
    }
    
    private void updateModelDescription(List<Unit_Model__c> unitModelList) {
        List<Unit_Model__c> modelListToUpdate = new List<Unit_Model__c>();
        for(Unit_Model__c unitModel : unitModelList) {
            if(String.isNotBlank(unitModel.Model_Description__c)) {
                unitModel.Description__c = unitModel.Model_Description__c;
                modelListToUpdate.add(unitModel);
            }
        }
        if(modelListToUpdate.size() > 0) {
            DMLUtility.updateSobjectList('Unit_Model__c', modelListToUpdate);
        }
    }
    
    private void updateSubModelDescription(Set<Id> unitModelIdSet) {
        List<Unit_Sub_Model__c> unitSubModelListToUpdate = new List<Unit_Sub_Model__c>();
        for(Unit_Sub_Model__c unitSubModel : [SELECT Sub_Model_Description__c FROM Unit_Sub_Model__c WHERE Unit_Model__c IN: unitModelIdSet]) {
            if(String.isNotBlank(unitSubModel.Sub_Model_Description__c)) {
                unitSubModel.Description__c = unitSubModel.Sub_Model_Description__c;
                unitSubModelListToUpdate.add(unitSubModel);
            }
        }
        if(unitSubModelListToUpdate.size() > 0) {
            DMLUtility.updateSobjectList('Unit_Sub_Model__c', unitSubModelListToUpdate);
        }
    }
    
    private Set<Id> getModelIdSet(List<Unit_Model__c> unitModelList) {
        Set<Id> unitModelIdSet = new Set<Id>();
        for(Unit_Model__c unitModel : unitModelList) {
            unitModelIdSet.add(unitModel.Id);
        }
        return unitModelIdSet;
    }
    
    public void finish(Database.batchableContext bc) {
        BPScriptUtility.enableTrigger('UnitModelTrigger');
        BPScriptUtility.enableTrigger('UnitSubModelTrigger');
    }
}