src/objects/Unit_Make__c.object
<CustomObject>
    <label>Unit Make</label>
    <nameField>
        <label>Make</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Makes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit_Model__c.object
<CustomObject>
    <fields>
        <fullName>Model_Description__c</fullName>
        <label>Model Description (Depricated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Make__c</fullName>
        <label>Unit Make</label>
        <referenceTo>Unit_Make__c</referenceTo>
        <relationshipLabel>Unit Models</relationshipLabel>
        <relationshipName>Unit_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>unit model description</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Model</label>
    <nameField>
        <displayFormat>UM-{0000000}</displayFormat>
        <label>Unit Model Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unit_Sub_Model__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Model_Description__c</fullName>
        <label>Sub Model Description (Deprecated)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Model</label>
        <referenceTo>Unit_Model__c</referenceTo>
        <relationshipLabel>Unit Sub Models</relationshipLabel>
        <relationshipName>Unit_Sub_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Unit sub model description</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Unit Sub Model</label>
    <nameField>
        <displayFormat>USM-{0000000}</displayFormat>
        <label>Unit Sub Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Sub Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PopulateModelSubModelDescBatchTest.cls
@isTest
public without sharing class PopulateModelSubModelDescBatchTest {
    
    @TestSetup
    static void createSampleData(){
        Unit_Make__c unitMake = TestDataFactory.createUnitMake('Test Unit Make', 'Te1', true);

        Unit_Model__c unitModel = TestDataFactory.createUnitModel('Test Unit Model', 'Te1', true, unitMake.Id);
        unitModel.Model_Description__c = 'Model description';
        update unitModel;

        Unit_Sub_Model__c unitSubModel = TestDataFactory.createSubModel(unitModel);
        unitSubModel.Sub_Model_Description__c = 'Sub-Model description';
        update unitSubModel;
    }

    @isTest
    public static void PopulateModelSubModelDescBatch_test() {
        Test.startTest();
        Database.executeBatch(new PopulateModelSubModelDescBatch());
        Test.stopTest();
        Unit_Sub_Model__c unitSubModelRec = [SELECT Description__c, Unit_Model__r.Description__c FROM Unit_Sub_Model__c LIMIT 1];
        System.assertEquals(unitSubModelRec.Description__c, 'Sub-Model description');
        System.assertEquals(unitSubModelRec.Unit_Model__r.Description__c, 'Model description');
    }
}